### ISSUE TITLE
Привязка бота хомяка идет к устройству, а не к телеграм аккаунту?

### ISSUE THREAD

**Issue by bd100b** [shamhi/HamsterKombatBot#100]
Я правильно понимаю что привязка бота хомяка идет к устройству, а не к телеграм аккаунту? Потому что я пробовал зайти со второго аккаунта с того же устройства, а мне показывает бананс предыдущего аккаунт?

**Comment by Kanorto** [comment]
Крч он скорее всего на один цифровой след только одного игрока дает. Это сделано чтобы несколько людей в одной квартире могли сразу майнить. Попробуйте использовать другое устройство или приложение, должно работать

**Comment by AlexKrutoy** [comment]
Привязка к клиенту ТГ и телефону, для использования твинков я использую клонирование телеграмм путем приложения из Гугл маркета

**Comment by shamhi** [comment]
> Я правильно понимаю что привязка бота хомяка идет к устройству, а не к телеграм аккаунту?

нет, бот привязывается только к аккаунту

> Потому что я пробовал зайти со второго аккаунта с того же устройства, а мне показывает бананс предыдущего аккаунт?

обнови страницу
