### ISSUE TITLE
Ничего не происходит

### ISSUE THREAD

**Issue by oligator77** [shamhi/HamsterKombatBot#104]
Что я делаю не так?

![Снимок](https://github.com/shamhi/HamsterKombatBot/assets/170873129/8137d106-1c6a-43c8-9554-ff345b65c683)

**Comment by mrranger** [comment]
Если банально прочитать ошибку не можешь, то наверное лучше не стоит использовать

**Comment by oligator77** [comment]
> Если банально прочитать ошибку не можешь, то наверное лучше не стоит использовать

api все написал

**Comment by mrranger** [comment]
Проблема в том как ты установил python

**Comment by mrranger** [comment]
Даже банально за гуглить ошибку не можешь

![image](https://github.com/shamhi/HamsterKombatBot/assets/13420378/c9ad32d5-ec30-4490-be12-8d52fe2997af)

**Comment by ilyaking** [comment]
у друга была такая ошибка, я ему сказал удалить пайтон и скачать из магазина винды 3.11

**Comment by oligator77** [comment]
Спасибо, извиняюсь за тупость

**Comment by ilyaking** [comment]
щас кстати бот не работает вроде

**Comment by oligator77** [comment]
У меня вроде работает, только как только я его запускаю аккаунт сразу банят

**Comment by shamhi** [comment]
> У меня вроде работает, только как только я его запускаю аккаунт сразу банят

проблема не в боте, а в аккаунте
