### ISSUE TITLE
Ерорки 500

### ISSUE THREAD

**Issue by AlexKrutoy** [shamhi/HamsterKombatBot#105]
![изображение](https://github.com/shamhi/HamsterKombatBot/assets/65369825/32cda277-224e-4811-a1bb-b53cb1ae28c7)
Что это и как данное фиксить?
Лишь бот работал сам по себе, решил глянуть а тут такое

**Comment by XxHLeB** [comment]
> ![изображение](https://github.com/shamhi/HamsterKombatBot/assets/65369825/32cda277-224e-4811-a1bb-b53cb1ae28c7)
> 
> Что это и как данное фиксить?
> 
> Лишь бот работал сам по себе, решил глянуть а тут такое

Все ок просто подожди и перезапусти бота, вчера так же было, походу у них бот сейчас тупит

**Comment by tancyit3** [comment]
> > ![изображение](https://private-user-images.githubusercontent.com/65369825/333888181-32cda277-224e-4811-a1bb-b53cb1ae28c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzU5ODcsIm5iZiI6MTcxNjczNTY4NywicGF0aCI6Ii82NTM2OTgyNS8zMzM4ODgxODEtMzJjZGEyNzctMjI0ZS00ODExLWExYmItYjUzY2IxYWUyOGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE1MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNzkxMTNlYTZiZTcxZGRjMjg1NmJlNWFhODk3Y2RmZmZlNDNjMDE2NGM0Y2NkYjRlNWJjNGQxODBmYjhjYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4AtDlga9l3RXYYkK47Hujf_Oq7H-yRMoZ2eCUg0SMXc)
> > Что это и как данное фиксить?
> > Лишь бот работал сам по себе, решил глянуть а тут такое
> 
> Все ок просто подожди и перезапусти бота, вчера так же было, походу у них бот сейчас тупит
> 
> Типо если ошибка 5ХХ обычно все проблемы на стороне сервера а не у пользователя

с телефона заходит  - всё ок, с ПК так же вылазитт ошибка 500
 возможно снова они какую то обнову выкатили и выдает ошибку 500

**Comment by AlexKrutoy** [comment]
Ну, видимо реально обновление, я уж думал всё, капец

С телефона да, заходит. А через бота 500

**Comment by XxHLeB** [comment]
> > > ![изображение](https://private-user-images.githubusercontent.com/65369825/333888181-32cda277-224e-4811-a1bb-b53cb1ae28c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzU5ODcsIm5iZiI6MTcxNjczNTY4NywicGF0aCI6Ii82NTM2OTgyNS8zMzM4ODgxODEtMzJjZGEyNzctMjI0ZS00ODExLWExYmItYjUzY2IxYWUyOGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE1MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNzkxMTNlYTZiZTcxZGRjMjg1NmJlNWFhODk3Y2RmZmZlNDNjMDE2NGM0Y2NkYjRlNWJjNGQxODBmYjhjYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4AtDlga9l3RXYYkK47Hujf_Oq7H-yRMoZ2eCUg0SMXc)
> 
> > > Что это и как данное фиксить?
> 
> > > Лишь бот работал сам по себе, решил глянуть а тут такое
> 
> > 
> 
> > Все ок просто подожди и перезапусти бота, вчера так же было, походу у них бот сейчас тупит
> 
> > 
> 
> > Типо если ошибка 5ХХ обычно все проблемы на стороне сервера а не у пользователя
> 
> 
> 
> с телефона заходит  - всё ок, с ПК так же вылазитт ошибка 500
> 
>  возможно снова они какую то обнову выкатили и выдает ошибку 500
> 
> 

Так говорю вчера так же было, даже в закрытых тут осталось от меня, я себе код поменял на пол часа в сон отправляю и потом он еще раз пробует

**Comment by ButCheR-PRO** [comment]
> > > > ![изображение](https://private-user-images.githubusercontent.com/65369825/333888181-32cda277-224e-4811-a1bb-b53cb1ae28c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzU5ODcsIm5iZiI6MTcxNjczNTY4NywicGF0aCI6Ii82NTM2OTgyNS8zMzM4ODgxODEtMzJjZGEyNzctMjI0ZS00ODExLWExYmItYjUzY2IxYWUyOGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE1MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNzkxMTNlYTZiZTcxZGRjMjg1NmJlNWFhODk3Y2RmZmZlNDNjMDE2NGM0Y2NkYjRlNWJjNGQxODBmYjhjYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4AtDlga9l3RXYYkK47Hujf_Oq7H-yRMoZ2eCUg0SMXc)
> > 
> > 
> > > > Что это и как данное фиксить?
> > 
> > 
> > > > Лишь бот работал сам по себе, решил глянуть а тут такое
> > 
> > 
> > > 
> > 
> > 
> > > Все ок просто подожди и перезапусти бота, вчера так же было, походу у них бот сейчас тупит
> > 
> > 
> > > 
> > 
> > 
> > > Типо если ошибка 5ХХ обычно все проблемы на стороне сервера а не у пользователя
> > 
> > 
> > с телефона заходит  - всё ок, с ПК так же вылазитт ошибка 500
> > возможно снова они какую то обнову выкатили и выдает ошибку 500
> 
> Так говорю вчера так же было, даже в закрытых тут осталось от меня, я себе код поменял на пол часа в сон отправляю и потом он еще раз пробует

В файле .env поставил SLEEP_BY_MIN_ENERGY=1800
верно?

**Comment by XxHLeB** [comment]
> > > > > ![изображение](https://private-user-images.githubusercontent.com/65369825/333888181-32cda277-224e-4811-a1bb-b53cb1ae28c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MzU5ODcsIm5iZiI6MTcxNjczNTY4NywicGF0aCI6Ii82NTM2OTgyNS8zMzM4ODgxODEtMzJjZGEyNzctMjI0ZS00ODExLWExYmItYjUzY2IxYWUyOGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE1MDEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyNzkxMTNlYTZiZTcxZGRjMjg1NmJlNWFhODk3Y2RmZmZlNDNjMDE2NGM0Y2NkYjRlNWJjNGQxODBmYjhjYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4AtDlga9l3RXYYkK47Hujf_Oq7H-yRMoZ2eCUg0SMXc)
> 
> > > 
> 
> > > 
> 
> > > > > Что это и как данное фиксить?
> 
> > > 
> 
> > > 
> 
> > > > > Лишь бот работал сам по себе, решил глянуть а тут такое
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Все ок просто подожди и перезапусти бота, вчера так же было, походу у них бот сейчас тупит
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Типо если ошибка 5ХХ обычно все проблемы на стороне сервера а не у пользователя
> 
> > > 
> 
> > > 
> 
> > > с телефона заходит  - всё ок, с ПК так же вылазитт ошибка 500
> 
> > > возможно снова они какую то обнову выкатили и выдает ошибку 500
> 
> > 
> 
> > Так говорю вчера так же было, даже в закрытых тут осталось от меня, я себе код поменял на пол часа в сон отправляю и потом он еще раз пробует
> 
> 
> 
> В файле .env поставил SLEEP_BY_MIN_ENERGY=1800
> 
> верно? 

Нет, так как бот не работает щас, в чем смысл на минимальную энергию ставить?

**Comment by AlexKrutoy** [comment]
папка/bot/core/tapper.py

строки: 93-108
на 108:
await asyncio.sleep(delay=3)

цифру 3 меняешь на столько секунд, сколько нужно ждать после данной ошибки
