### ISSUE TITLE
Error 106 - как фикстить?

### ISSUE THREAD

**Issue by f1reberg** [shamhi/HamsterKombatBot#106]
https://imgur.com/a/XKbYCZ5
Что делать?

**Comment by ilyaking** [comment]
ждать

**Comment by f1reberg** [comment]
> ждать

в смысле ждать? у всех так типо?

**Comment by babasuck** [comment]
> > ждать
> 
> в смысле ждать? у всех так типо?

да

**Comment by ButCheR-PRO** [comment]
Ой, у меня тоже самое. А я и тему создал, а пока создавал вы тоже создали

**Comment by ilyaking** [comment]
> Ой, у меня тоже самое. А я и тему создал, а пока создавал вы тоже создали
угу

**Comment by ButCheR-PRO** [comment]
Дубликат https://github.com/shamhi/HamsterKombatBot/issues/189
