### ISSUE TITLE
106 Unknown error while getting Access Token: 500 Internal Server Error

### ISSUE THREAD

**Issue by ButCheR-PRO** [shamhi/HamsterKombatBot#107]
Пару дней работало отлично, а сейчас вдруг перестало работать, начало ошибки выбивать. Я уже и через INSTALL.bat обновил и скачал новую версию бота, заново настроил и заново сессию создал, но результат тот же. А с телефона в игру заходит нормально.
![image](https://github.com/shamhi/HamsterKombatBot/assets/23020594/72997221-2d4a-4a00-8d06-735db42d66be)

**Comment by VadFonker-cyber** [comment]
Такой же прикол, резко дропнулся бот, чет странно

**Comment by darhanger** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/22445395/a5500592-82de-4a59-805b-89c0bfcee167)

**Comment by Mephelist** [comment]
![Screenshot_20240526_230827_Termius](https://github.com/shamhi/HamsterKombatBot/assets/135533738/0a8b0c56-f313-4f0f-9799-f9d68065bdca)
У всех это

**Comment by tonysxn** [comment]
+1

**Comment by xKumorio** [comment]
+

**Comment by ic23** [comment]
Я конечно ни разу разработчик подобных ботов, и не знаю как внутри устроены Mini Apps и Telegram API и API HamsterKombat.
Но по ошибке могу сказать, что они ввели некую проверку, которая видит что компьютер это или нет.
Смею предположить, что это по заголовкам считывается, либо по приложению сессии, через которое авторизация проходила (не факт, не знаю передаётся ли такая информация)

**Comment by XxHLeB** [comment]
> Я конечно ни разу разработчик подобных ботов, и не знаю как внутри устроены Mini Apps и Telegram API и API HamsterKombat.
> 
> Но по ошибке могу сказать, что они ввели некую проверку, которая видит что компьютер это или нет.
> 
> Смею предположить, что это по заголовкам считывается, либо по приложению сессии, через которое авторизация проходила (не факт, не знаю передаётся ли такая информация)

Вряд ли, тут есть скрипт на fingerprint, а игра и до этого с пк не пускало надо в ссылке кое что поменять, вчера было так же но, прошло быстрее сейчас чет долго оно

**Comment by ButCheR-PRO** [comment]
Неужели разработчики игры начали борьбу с ботами и кликерами?)

**Comment by KOTBCTAKAHE** [comment]
тоже самое, может заметили подозрительную активность на айпи адресе? пробовали включать на компе впн?

**Comment by XxHLeB** [comment]
> тоже самое, может заметили подозрительную активность на айпи адресе? пробовали включать на компе впн?

У меня всегда на прокси были сейчас попробовал запустить без прокси 1 акк и ошибка, я думаю они сейчас что-то меняют ибо скоро задания для аирдропа итд

**Comment by KOTBCTAKAHE** [comment]
> > тоже самое, может заметили подозрительную активность на айпи адресе? пробовали включать на компе впн?
> 
> У меня всегда на прокси были сейчас попробовал запустить без прокси 1 акк и ошибка, я думаю они сейчас что-то меняют ибо скоро задания для аирдропа итд

пипец, надеюсь это хоть как-то пофиксят =)

**Comment by XxHLeB** [comment]
> > > тоже самое, может заметили подозрительную активность на айпи адресе? пробовали включать на компе впн?
> 
> > 
> 
> > У меня всегда на прокси были сейчас попробовал запустить без прокси 1 акк и ошибка, я думаю они сейчас что-то меняют ибо скоро задания для аирдропа итд
> 
> 
> 
> пипец, надеюсь это хоть как-то пофиксят =)

![image](https://github.com/shamhi/HamsterKombatBot/assets/54667358/36c93be1-56ef-4583-87af-f036669e23ab)у них веб версия не грузит(она и не должна но багом можно было) а сейчас пишет ошибка miniapps

**Comment by KOTBCTAKAHE** [comment]
> > > > тоже самое, может заметили подозрительную активность на айпи адресе? пробовали включать на компе впн?
> > 
> > 
> > > 
> > 
> > 
> > > У меня всегда на прокси были сейчас попробовал запустить без прокси 1 акк и ошибка, я думаю они сейчас что-то меняют ибо скоро задания для аирдропа итд
> > 
> > 
> > пипец, надеюсь это хоть как-то пофиксят =)
> 
> ![image](https://private-user-images.githubusercontent.com/54667358/333897049-36c93be1-56ef-4583-87af-f036669e23ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDM4NDksIm5iZiI6MTcxNjc0MzU0OSwicGF0aCI6Ii81NDY2NzM1OC8zMzM4OTcwNDktMzZjOTNiZTEtNTZlZi00NTgzLTg3YWYtZjAzNjY2OWUyM2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE3MTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YzdjNjg1ZTU0YWUzOWVjOWYzNGQwZGQwM2YzNzE0ZThhMWEzN2E0N2IyNTcyZGZlNTM0OWY0OTA2MGI3OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LHHPIO_6MqSFNTowrlE5lZI1Do9UpGaYV-UxSPQEu3E)у них веб версия не грузит(она и не должна но багом можно было) а сейчас пишет ошибка miniapps

не подскажите, что за баг?

**Comment by XxHLeB** [comment]
> > у них веб версия не грузит(она и не должна но багом можно было) а сейчас пишет ошибка miniapps
> 
> 
> 
> У знакомых и с телефона не пускает, видимо сервера авторизации легли
> 
> 

Если sync порой бывает, а так вчера у меня половина аккаунтов тупила, сегодня ок было но теперь снова бац и все, все акки один держался еще пол часа и то отлител уже

**Comment by XxHLeB** [comment]
> > Если sync порой бывает, а так вчера у меня половина аккаунтов тупила, сегодня ок было но теперь снова бац и все, все акки один держался еще пол часа и то отлител уже
> 
> 
> 
> Не sync, а именно Unable to login
> 
> 

Тогда да, у них траблы, и хорошо ибо ферму не закроют

**Comment by XxHLeB** [comment]
Если тебе с телефона, то надо сильно поиграться и желательно джейл (если айфон), с пк гайд в гитхабе есть

**Comment by KOTBCTAKAHE** [comment]
> Если тебе с телефона, то надо сильно поиграться и желательно джейл (если айфон), с пк гайд в гитхабе есть

у меня рут

**Comment by XxHLeB** [comment]
> > > > > тоже самое, может заметили подозрительную активность на айпи адресе? пробовали включать на компе впн?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > У меня всегда на прокси были сейчас попробовал запустить без прокси 1 акк и ошибка, я думаю они сейчас что-то меняют ибо скоро задания для аирдропа итд
> 
> > > 
> 
> > > 
> 
> > > пипец, надеюсь это хоть как-то пофиксят =)
> 
> > 
> 
> > ![image](https://private-user-images.githubusercontent.com/54667358/333897049-36c93be1-56ef-4583-87af-f036669e23ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NDM4NDksIm5iZiI6MTcxNjc0MzU0OSwicGF0aCI6Ii81NDY2NzM1OC8zMzM4OTcwNDktMzZjOTNiZTEtNTZlZi00NTgzLTg3YWYtZjAzNjY2OWUyM2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE3MTIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YzdjNjg1ZTU0YWUzOWVjOWYzNGQwZGQwM2YzNzE0ZThhMWEzN2E0N2IyNTcyZGZlNTM0OWY0OTA2MGI3OWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LHHPIO_6MqSFNTowrlE5lZI1Do9UpGaYV-UxSPQEu3E)у них веб версия не грузит(она и не должна но багом можно было) а сейчас пишет ошибка miniapps
> 
> 
> 
> не подскажите, что за баг?

Ответил, правда не ответ чуть выше почитай

**Comment by KOTBCTAKAHE** [comment]
> Если тебе с телефона, то надо сильно поиграться и желательно джейл (если айфон), с пк гайд в гитхабе есть

благодарю. на андроиде сделал (можно без рута) с помощью Kivi Browser

**Comment by XxHLeB** [comment]
> > Если тебе с телефона, то надо сильно поиграться и желательно джейл (если айфон), с пк гайд в гитхабе есть
> 
> 
> 
> благодарю. на андроиде сделал (можно без рута) с помощью Kivi Browser

Это да, просто на айфоне блок ядра, все браузера они внутри все равно сафари, только в этом году разрешат другие, вот и приходится джейлом

**Comment by XxHLeB** [comment]
> > Если тебе с телефона, то надо сильно поиграться и желательно джейл (если айфон), с пк гайд в гитхабе есть
> 
> 
> 
> благодарю. на андроиде сделал (можно без рута) с помощью Kivi Browser

Кстати, загрузило? Просто я проверил http запросы мне выдает 404 на api.hamster

**Comment by KOTBCTAKAHE** [comment]
> > > Если тебе с телефона, то надо сильно поиграться и желательно джейл (если айфон), с пк гайд в гитхабе есть
> > 
> > 
> > благодарю. на андроиде сделал (можно без рута) с помощью Kivi Browser
> 
> Кстати, загрузило? Просто я проверил http запросы мне выдает 404 на api.hamster

нет, unable to auth. но потом, как я переустановил этот скрипт на расширение хром, он вообще задетектил что я с браузера захожу. но думаю это я в чем то ошибся.

**Comment by XxHLeB** [comment]
> > > > Если тебе с телефона, то надо сильно поиграться и желательно джейл (если айфон), с пк гайд в гитхабе есть
> 
> > > 
> 
> > > 
> 
> > > благодарю. на андроиде сделал (можно без рута) с помощью Kivi Browser
> 
> > 
> 
> > Кстати, загрузило? Просто я проверил http запросы мне выдает 404 на api.hamster
> 
> 
> 
> нет, unable to login. но потом, как я переустановил этот скрипт на расширение хром, он вообще задетектил что я с браузера захожу. но думаю это я в чем то ошибся. 

Он с браузера и не пустит, хз знал ли, но есть автокликер на жс который через консоль разработчика на сайт вставляется и все, он кликает, там надо в ссылке поменять пару символов и он грузит не как веб версия и тогда запустит (но сейчас ошибка эта)

**Comment by shamhi** [comment]
у меня ни разу не было такой ошибки, все работает четко
я не знаю, почему у вас

**Comment by XxHLeB** [comment]
> у меня ни разу не было такой ошибки, все работает четко
> 
> я не знаю, почему у вас

Та не, это моментами когда у них нагрузки, проблема не в боте, я просто добавил тест на ошибку 500, если это она то он спит пол часа и дальше пробует, просто это не на всех аккаунтах только пару аккаунтов у меня из 25 16 сейчас тупили, но уже все работают

**Comment by XxHLeB** [comment]
> > у меня ни разу не было такой ошибки, все работает четко
> > 
> > я не знаю, почему у вас
> 
> Та не, это моментами когда у них нагрузки, проблема не в боте, я просто добавил тест на ошибку 500, если это она то он спит пол часа и дальше пробует, просто это не на всех аккаунтах только пару аккаунтов у меня из 25 16 сейчас тупили, но уже все работают 

Там игроки в ру чате хамстера писали эту же ошибку хоть они честно играли

**Comment by KOTBCTAKAHE** [comment]
ребят, заработало

**Comment by XxHLeB** [comment]
> ребят, заработало

Да знаю я подключил параллельно что бы мне аккаунты отписали в группу, когда ошибка прошла
