### ISSUE TITLE
OverflowError: int too big to convert из-за Python 3.12

### ISSUE THREAD

**Issue by softer777** [shamhi/HamsterKombatBot#108]
![image](https://github.com/shamhi/HamsterKombatBot/assets/165616740/3852e004-9c12-4c80-87c8-a2409d9d84d4)

**Comment by AlexKrutoy** [comment]
качай питон 3.10 или 3.11, у тебя стоит 3.12

**Comment by ButCheR-PRO** [comment]
Скачай [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Установи, и потом запусти INSTALL.bat
