### ISSUE TITLE
422

### ISSUE THREAD

**Issue by softer777** [shamhi/HamsterKombatBot#109]
![image](https://github.com/shamhi/HamsterKombatBot/assets/165616740/5b50ce9f-0ea6-4282-b988-ab20dd9430a6)

**Comment by Mephelist** [comment]
Сессию телеграма новую сделай (мб закрыл) у тебя даже в ошибке написано

**Comment by darhanger** [comment]
> Сессию телеграма новую сделай (мб закрыл) у тебя даже в ошибке написано

Дело не в сессии, или какой-то глюк с прилогой или борьба с ботом. Лутанул такую же ошибку
![image](https://github.com/shamhi/HamsterKombatBot/assets/22445395/ee0a1e59-1ed4-47ce-a7ab-801c5821619b)

**Comment by XxHLeB** [comment]
> > Сессию телеграма новую сделай (мб закрыл) у тебя даже в ошибке написано
> 
> 
> 
> Дело не в сессии, или какой-то глюк с прилогой или борьба с ботом. Лутанул такую же ошибку
> 
> ![image](https://github.com/shamhi/HamsterKombatBot/assets/22445395/ee0a1e59-1ed4-47ce-a7ab-801c5821619b)
> 
> 
> 
> 

У тебя другая, это они что-то мутят вчера было так же но пол часа где-то

**Comment by XxHLeB** [comment]
> ![image](https://github.com/shamhi/HamsterKombatBot/assets/165616740/5b50ce9f-0ea6-4282-b988-ab20dd9430a6)
> 
> 

Попробуй скачать новую версию этого фармбота, если ты качал его еще давно

**Comment by ButCheR-PRO** [comment]
Дубликат https://github.com/shamhi/HamsterKombatBot/issues/4
