### ISSUE TITLE
bug on buy_upgrade and others

### ISSUE THREAD

**Issue by FrontendDevBehruz** [shamhi/HamsterKombatBot#11]
![photo_2024-04-25_13-37-01](https://github.com/shamhi/HamsterKombatBot/assets/166024611/740a9f02-5e04-4f2d-a4a3-db2f404b7eaa)

**Comment by FrontendDevBehruz** [comment]
bug

**Comment by mfaizfauzann** [comment]
just increase the damage to level 10, and the capacity of up to 5000 is more than enough. If this has been achieved, reset the .env and change True to False to turn off the upgrade function

**Comment by shamhi** [comment]
do you choose exchange?

**Comment by shamhi** [comment]
set AUTO_UPGRADE=False in .env
