### ISSUE TITLE
500

### ISSUE THREAD

**Issue by glofflive** [shamhi/HamsterKombatBot#110]
![image](https://github.com/shamhi/HamsterKombatBot/assets/74303868/164c3243-d295-4c70-85f5-233ecfb23e62)

**Comment by PSHacks** [comment]
+1 Same here..

**Comment by general12345** [comment]
+

**Comment by voutuk** [comment]
I also have this problem

**Comment by youngbloodes** [comment]
same

**Comment by c5bomba** [comment]
+

**Comment by glorySyntax** [comment]
Такая же ошибка

**Comment by darhanger** [comment]
Я думаю что просто сверка идет что не с телефона или что. Такой некий фикс) Что бы на ботах не фармили

**Comment by ButCheR-PRO** [comment]
Dupe https://github.com/shamhi/HamsterKombatBot/issues/189
