### ISSUE TITLE
[Error] 106 Unknown error while getting Access Token: 500, message=Internal Server Error

### ISSUE THREAD

**Issue by Yarik-Walker** [shamhi/HamsterKombatBot#111]

**Comment by Yarik-Walker** [comment]
![photo_2024-05-26_20-40-19](https://github.com/shamhi/HamsterKombatBot/assets/80649368/5b00d683-0ab3-4e3f-9554-ddd773a2bb37)

**Comment by n3vermnd** [comment]
какая операционка?

**Comment by ButCheR-PRO** [comment]
Дубликат https://github.com/shamhi/HamsterKombatBot/issues/189
