### ISSUE TITLE
неужели у меня одного такая проблема?

### ISSUE THREAD

**Issue by yacody** [shamhi/HamsterKombatBot#113]
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/b3e2b6ae-278a-4a3a-9762-f8d46ec3447e)

**Comment by tancyit3** [comment]
![изображение](https://github.com/shamhi/HamsterKombatBot/assets/136000100/2882670a-a43c-4064-8031-17a804c553b5)
у тебя тут стоит 2015 секунд значит, поставь 200

**Comment by yacody** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/136000100/333904381-2882670a-a43c-4064-8031-17a804c553b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3NTE4NTIsIm5iZiI6MTcxNjc1MTU1MiwicGF0aCI6Ii8xMzYwMDAxMDAvMzMzOTA0MzgxLTI4ODI2NzBhLWE0M2MtNDA2NC04MDMxLTE3YTgwNGM1NTNiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNlQxOTI1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02M2NlMjlmMWE2MzM5NTQ5MWRkNjg1MjU1ZWZmMWI4NTZjZGExMWQxYTRlYzIzOGUzODZiNGUxYmYyZjI5ODk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iO4grwwN0itNFRw6AAbZhI2smd0FpiYg2IZ27osWRUQ) у тебя тут стоит 2015 секунд значит, поставь 200
> 
> bot/config/config.py SLEEP_BY_MIN_ENERGY: int = 200
> 
> или же в env просто ты поставил, он у тебя берет оттуда.а не по умолчанию 200

так мне и надо 2015. проблема в том, что у него один заряд энергия норм идет, потом перезарядка и после нее бот ничего не кликает! Спустя 2015 он просто собирает пассивный доход и снова уходит в ребут на 2015 секунд

**Comment by yacody** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/cfacaa21-1bc1-40d3-ac90-7fec627e56b9)
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/d2263a5d-bc6b-4343-a3a9-080a227a47bd)

**Comment by ButCheR-PRO** [comment]
В файле .env:
```
MIN_AVAILABLE_ENERGY=100
SLEEP_BY_MIN_ENERGY=[1800,2400]
RANDOM_TAPS_COUNT=[50,200]
SLEEP_BETWEEN_TAP=[10,25]
```
