### ISSUE TITLE
Это нормально что он так медленно кликает?

### ISSUE THREAD

**Issue by CramPusy** [shamhi/HamsterKombatBot#116]
![image](https://github.com/shamhi/HamsterKombatBot/assets/170892000/94c30d80-ecf2-4c3b-8d59-b54c3224c4cd)

**Comment by XxHLeB** [comment]
Так поставить в конфиге меньше диапазон рандома, он тут работает по очереди то есть прокликал проверил улучшения, подождал перед улучшением 5 сек, улучшил и подождал 1 сек, а после уходит в сон на время из конфига, и так по кругу

**Comment by XxHLeB** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/54667358/1a27e9b6-7799-4b97-b4d1-92f3422e3610)

**Comment by yacody** [comment]
> ![image](https://private-user-images.githubusercontent.com/54667358/333924671-1c562c59-35e4-4805-90bc-0410e9e7704b.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3OTU1NTksIm5iZiI6MTcxNjc5NTI1OSwicGF0aCI6Ii81NDY2NzM1OC8zMzM5MjQ2NzEtMWM1NjJjNTktMzVlNC00ODA1LTkwYmMtMDQxMGU5ZTc3MDRiLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QwNzM0MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYzY1MTE5OGExNGZiZmMxZGE5OGRlNTk0MDBiMTk1ZTNhYWQzMmQyMjNkNzZjMWEyZWVhNzljZTM2MjUzYjNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2S9jHH0MXSozdee3DefTO_GLt6M6cjJnKU8jCSnznJ0)

ты чушь написал. Это баг у него, у меня такой же. у него бот не кликает, а просто ждёт по 200 секунд, ничего не кликая, тупо собирая пассивный заработок

**Comment by tancyit3** [comment]
Всё советы выше - не советы. Потому что они даже не посмотрели твой скриншот

У тебя нормально кликает, не медленно. У тебя пассивный долход 3465 в час
Тапы - это не основной заработок в игре, он ничего почти не приносит. Основное - это пассивный доход

**Comment by tancyit3** [comment]
> > Всё советы выше - не советы. Потому что они даже не посмотрели твой скриншот
> > У тебя нормально кликает, не медленно. У тебя пассивный долход 3465 в час Тапы - это не основной заработок в игре, он ничего почти не приносит. Основное - это пассивный доход
> 
> при чем тут неосновной заработок? речь о том, что в игре баг с тапами. Даже если основной фарм в пасиве это не отменяет того факта, что клики не кликаются

а где он не тапает? он тапает рандомное кол-во раз (RANDOM_TAPS_COUNT=[50,200]) и забирает пассивный заработок
у него даже на скриншое видно это - Successful tapped
и когда заходишь в игру после этого, то у тебя на балансе минимальное количество энергии

**Comment by XxHLeB** [comment]
> > Всё советы выше - не советы. Потому что они даже не посмотрели твой скриншот
> 
> > 
> 
> > У тебя нормально кликает, не медленно. У тебя пассивный долход 3465 в час Тапы - это не основной заработок в игре, он ничего почти не приносит. Основное - это пассивный доход
> 
> 
> 
> при чем тут неосновной заработок? речь о том, что в игре баг с тапами. Даже если основной фарм в пасиве это не отменяет того факта, что клики не кликаются 

Хз что там у тебя, я если поставлю минимальное количество кликов 1 и рандомно 9к-10к у меня каждый раз пишет что энергии ноль и идет в сон

И ты вообще знаешь как клики на сервер отправляются?
