### ISSUE TITLE
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required

### ISSUE THREAD

**Issue by gitbcat** [shamhi/HamsterKombatBot#117]
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required
Hi there, I tried all these proxy formats with a user password but it's not working. Please help. Thank you.
type://user:pass@ip:port
type://user:pass:ip:port
type://ip:port:user:pass
type://ip:port@user:pass
type://ip:port

http://157.20.62.134:35270:abcde:xmH566
http://157.20.62.134:35270@abcde:xmH566
http://abcde:xmH566:157.20.62.134:35270
http://abcde:xmH566@157.20.62.134:35270

**Comment by Pasha4056** [comment]
Keep only your proxy, delete everything else from the file

**Comment by gitbcat** [comment]
<img width="669" alt="2024-05-27_14-36-24" src="https://github.com/shamhi/HamsterKombatBot/assets/122675925/001a263d-eea7-43bd-9f1f-c12732db8eec">
Thank you, but not working too

**Comment by ClassicEddy46** [comment]
Like this should work in case of http imo (without http and with @ as a separator) - at least I have proxies this way in the .txt file.
157.20.62.134:35270@abcde:xmH566
Othwerise could be that proxy is not active/dead/needs new credentials

> <img alt="2024-05-27_14-36-24" width="669" src="https://private-user-images.githubusercontent.com/122675925/334009858-001a263d-eea7-43bd-9f1f-c12732db8eec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MDEyNDcsIm5iZiI6MTcxNjgwMDk0NywicGF0aCI6Ii8xMjI2NzU5MjUvMzM0MDA5ODU4LTAwMWEyNjNkLWVlYTctNDNiZC05ZjFmLWMxMjczMmRiOGVlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyN1QwOTA5MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mODFlMDM4YjczNTY3YjQ2ZmUyNjE0NzJkMTg0ODVjMWEyZTczZjVmZjZiNDI2ZTJhMTg0NjExNWZlY2M5YWZiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dq9NSRc3us4Ai6opuJn75dW1CMyaxpHlGXplaLK9foE">
> Thank you, but not working too

**Comment by b0chk0v** [comment]
> Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required Hi there, I tried all these proxy formats with a user password but it's not working. Please help. Thank you. type://user:pass@ip:port type://user:pass:ip:port type://ip:port:user:pass type://ip:port@user:pass type://ip:port
> 
> http://157.20.62.134:35270:abcde:xmH566 http://157.20.62.134:35270@abcde:xmH566 http://abcde:xmH566:157.20.62.134:35270 http://abcde:xmH566@157.20.62.134:35270

do you fix it? i have same problem with blum soft

**Comment by gitbcat** [comment]
> > Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required Hi there, I tried all these proxy formats with a user password but it's not working. Please help. Thank you. type://user:pass@ip:port type://user:pass:ip:port type://ip:port:user:pass type://ip:port@user:pass type://ip:port
> > http://157.20.62.134:35270:abcde:xmH566 http://157.20.62.134:35270@abcde:xmH566 http://abcde:xmH566:157.20.62.134:35270 http://abcde:xmH566@157.20.62.134:35270
> 
> do you fix it? i have same problem with blum soft

not yet, still sticking with proxy http://

**Comment by ButCheR-PRO** [comment]
1) Log in to this telegram account from any device;
2) Close all sessions with the Pyrogram header
3) Recreate the session inside your bot (instead of a token, use a phone number in international format)
4) Disable proxy or use SOCKS5 instead of HTTP
5) Synchronize the system time on your computer

**Comment by sadeqeslahi** [comment]
I have error 407
Unable to connect due to network issues: Socket error: 407: Proxy Authentication Required
