### ISSUE TITLE
[Ошибка] BadMsgNotification: [16] The msg_id is too low, the client time has to be synchronized

### ISSUE THREAD

**Issue by levisq955** [shamhi/HamsterKombatBot#118]
Помогите ошибка : BadMsgNotification: [16] The msg_id is too low, the client time has to be synchr
![Безымянный](https://github.com/shamhi/HamsterKombatBot/assets/170915890/eb25773f-226f-4b16-9ccd-605374377bcd)

**Comment by Zainds** [comment]
Столкнулся с такой же ошибкой: решилось синхронизацией времени.
![изображение_2024-06-03_173051479](https://github.com/shamhi/HamsterKombatBot/assets/56344333/0534a157-fa41-4765-af47-2a9a7037b616)
