### ISSUE TITLE
[ПРЕДЛОЖЕНИЕ] Добавить в конфиг лимит на мин. кол-во денег на балансе

### ISSUE THREAD

**Issue by ButCheR-PRO** [shamhi/HamsterKombatBot#119]
Идея в том, чтоб в конфиг .env добавить новый параметр типа:
MIN_AVAILABLE_MONEY = 1000000
То есть, когда параметр AUTO_UPGRADE = True, оно может потратить все деньги на балансе до нуля, и когда будет новая комбо-акция, где надо покупать карточки, у тебя просто может не хватать денег для покупки карточки. Поэтому нужно чтобы на балансе всегда была неприкосновенная сумма денег на такого рода расходы. А всё что больше этой суммы, пусть бот расходует на автоулучшение.

**Comment by tancyit3** [comment]
> Идея в том, чтоб в конфиг .env добавить новый параметр типа: MIN_AVAILABLE_MONEY = 1000000 То есть, когда параметр AUTO_UPGRADE = True, оно может потратить все деньги на балансе до нуля, и когда будет новая комбо-акция, где надо покупать карточки, у тебя просто может не хватать денег для покупки карточки. Поэтому нужно чтобы на балансе всегда была неприкосновенная сумма денег на такого рода расходы. А всё что больше этой суммы, пусть бот расходует на автоулучшение.

Идея хорошая
Правда я сутки попользовался автоапгрейдом и понял, что руками лучше улучшать. Условно часов 12 работает кликер, останавливаешь, улучшаешь ЧТО НУЖНО И ЧТО ВЫГОДНО, и дальше запускаешь

**Comment by ButCheR-PRO** [comment]
> > Идея в том, чтоб в конфиг .env добавить новый параметр типа: MIN_AVAILABLE_MONEY = 1000000 То есть, когда параметр AUTO_UPGRADE = True, оно может потратить все деньги на балансе до нуля, и когда будет новая комбо-акция, где надо покупать карточки, у тебя просто может не хватать денег для покупки карточки. Поэтому нужно чтобы на балансе всегда была неприкосновенная сумма денег на такого рода расходы. А всё что больше этой суммы, пусть бот расходует на автоулучшение.
> 
> Идея хорошая Правда я сутки попользовался автоапгрейдом и понял, что руками лучше улучшать. Условно часов 12 работает кликер, останавливаешь, улучшаешь ЧТО НУЖНО И ЧТО ВЫГОДНО, и дальше запускаешь

Так он уже улучшает те карточки, которые самые выгодные по профиту. Ну а в конце уже все остальные.

**Comment by h3sq** [comment]
> > > Идея в том, чтоб в конфиг .env добавить новый параметр типа: MIN_AVAILABLE_MONEY = 1000000 То есть, когда параметр AUTO_UPGRADE = True, оно может потратить все деньги на балансе до нуля, и когда будет новая комбо-акция, где надо покупать карточки, у тебя просто может не хватать денег для покупки карточки. Поэтому нужно чтобы на балансе всегда была неприкосновенная сумма денег на такого рода расходы. А всё что больше этой суммы, пусть бот расходует на автоулучшение.
> 
> > 
> 
> > Идея хорошая Правда я сутки попользовался автоапгрейдом и понял, что руками лучше улучшать. Условно часов 12 работает кликер, останавливаешь, улучшаешь ЧТО НУЖНО И ЧТО ВЫГОДНО, и дальше запускаешь
> 
> 
> 
> Так он уже улучшает те карточки, которые самые выгодные по профиту. Ну а в конце уже все остальные.  Просто карточки в разделе Special устанавливают таймер перед следующей покупкой. Прокачал один раз и ждешь по 2 часа пока можно будет еще раз прокачать, не всегда есть время заходить проверять таймер. А так поставил и оно само как таймер кончился, улучшает. 

Абсолютно согласен, но суть как раз в той идеи про которую человек выше написал про минимальный баланс. Дневное комбо - я на ночь всегда оставляю без апгрейда чтобы в 15:00 зайти и апгрейдеуть комбо

**Comment by XxHLeB** [comment]
Идея прикольная я уже добавил к себе, будет улучшать от 5млн, типо 5 млн будет считаться за 0, потом буду параллельно увеличивать минималку

**Comment by ButCheR-PRO** [comment]
> Идея прикольная я уже добавил к себе, будет улучшать от 5млн, типо 5 млн будет считаться за 0, потом буду параллельно увеличивать минималку

А куда добавил? Поделись кодом :)

**Comment by PSHacks** [comment]
В **config.py**:

> BALANCE_TO_SAVE: int = 50000

В **.env**:

> BALANCE_TO_SAVE=ВАША_ЦИФРА

В **tapper.py** (строка **402**):
Это:

> if balance > price and level <= settings.MAX_LEVEL:

Заменяем на это:

> tempBalance = balance - settings.BALANCE_TO_SAVE
> if tempBalance > price and level <= settings.MAX_LEVEL:


Попробуйте, по идее должно работать, пока нет возможности проверить к сожалению.

**Comment by Kanorto** [comment]
Ну так оно есть лол...

чт, 30 мая 2024 г., 13:31 PSHacks ***@***.***>:

**Comment by ButCheR-PRO** [comment]
Всем спасибо, проблема с минимальным балансом решена. Вот готовое решение: https://github.com/shamhi/HamsterKombatBot/issues/134#issuecomment-2140811851

**Comment by ButCheR-PRO** [comment]
Всем спасибо, проблема с минимальным балансом решена. Вот готовое решение: https://github.com/shamhi/HamsterKombatBot/issues/134#issuecomment-2140811851

**Comment by ButCheR-PRO** [comment]
Всем спасибо, проблема с минимальным балансом решена. Вот готовое решение: https://github.com/shamhi/HamsterKombatBot/issues/134#issuecomment-2140811851
