### ISSUE TITLE
Как выключить автоматический сбор кода морзе и ежедневного бонуса?

### ISSUE THREAD

**Issue by FBtarget** [shamhi/HamsterKombatBot#1190]

**Comment by KOTBCTAKAHE** [comment]
#1108 dupe

**Comment by FBtarget** [comment]
Апи комбо поменял на неверное значение и все работает, можно закрывать

**Comment by KOTBCTAKAHE** [comment]
> Апи комбо поменял на неверное значение и все работает, можно закрывать

не совсем понял. вы про меня? у апи верное значение.

**Comment by FBtarget** [comment]
> > Апи комбо поменял на неверное значение и все работает, можно закрывать
> 
> не совсем понял. вы про меня? у апи верное значение.

Нет, я написал выше решение
Мне нужно остаться в первых лигах, чтобы занять топ. Для этого нужно было отключить сбор шифра и ежедневного бонуса
