### ISSUE TITLE
[BAN] 106 Unknown error during Authorization: Telegram says: (401 USER_DEACTIVATED_BAN)

### ISSUE THREAD

**Issue by oligator77** [shamhi/HamsterKombatBot#121]
![image](https://github.com/shamhi/HamsterKombatBot/assets/170873129/c5c9e237-7b27-4872-85f3-e33d69027a90)
аккаунт не авторег
с прокси тоже банит

**Comment by bd100b** [comment]
это забанили номер или доступ к боту?

**Comment by mrranger** [comment]
Бред

**Comment by ButCheR-PRO** [comment]
А какие настройки в конфиге .env у тебя были, что могли привести к бану? Можешь конфиг скинуть свой?

**Comment by oligator77** [comment]
> А какие настройки в конфиге .env у тебя были, что могли привести к бану? Можешь конфиг скинуть свой?

![JPEG](https://github.com/shamhi/HamsterKombatBot/assets/170873129/8e28daa9-ff96-442e-8f36-fe5589d7dfdf)

расширение только нужно переписать (.env не дает загрузить)

**Comment by oligator77** [comment]
> это забанили номер или доступ к боту?

аккаунт

**Comment by 19temp** [comment]
@oligator77 Покажи конфиг .env интересно какие настройки привели к бану

**Comment by bd100b** [comment]
> > это забанили номер или доступ к боту
> 
> номер

а страна номера и устройства с которого запускал одинаковые?

**Comment by ButCheR-PRO** [comment]
> @oligator77 Покажи конфиг .env интересно какие настройки привели к бану

в сообщении выше он прикрепил конфиг, только переименовал его в .jpg. Вот его настройки:
```
MIN_AVAILABLE_ENERGY=100
SLEEP_BY_MIN_ENERGY=80

ADD_TAPS_ON_TURBO=2500

AUTO_UPGRADE=True
MAX_LEVEL=20

APPLY_DAILY_ENERGY=True
APPLY_DAILY_TURBO=True

RANDOM_TAPS_COUNT=[50,200]
SLEEP_BETWEEN_TAP=[10,25]
USE_PROXY_FROM_FILE=False
```

**Comment by oligator77** [comment]
> > > это забанили номер или доступ к боту
> > 
> > 
> > номер
> 
> а страна номера и устройства с которого запускал одинаковые?

Да

**Comment by shamhi** [comment]
> аккаунт не авторег

покупной или свой?

**Comment by oligator77** [comment]
> > аккаунт не авторег
> 
> покупной или свой?

Номер покупной.
Но с этого же сайта купил номер недавно для другого бота и все живёт уже неделю

**Comment by AutumnQR** [comment]
Это стандартная проблема авторизации с паблик APP HASH/APP ID, + в авторизации не указываются, условные, device_info, device_model, и т.д. Был не большой опыт работы с фермой телеграмм аккаунтов, как правило, они жили дольше, если эти данные указывать.. Ну и да, конечно же, еще могут быть проблемы с покупаемыми номерами на сервисах, факторов оооочень много, и определить какой именно выдал бан - практически невозможно

```
    session = Client(
        name=session_name,
        api_id=API_ID,
        api_hash=API_HASH,
        workdir="sessions/"
    )
```
