### ISSUE TITLE
bot for BLUM 

### ISSUE THREAD

**Issue by lonya** [shamhi/HamsterKombatBot#124]
If you can please make a bot for BLUM (@BlumCryptoBot), a top project with a larger audience and a grant from Binance

**Comment by ButCheR-PRO** [comment]
Тоже ищу бота на Blum но пока никто не сделал.

**Comment by shamhi** [comment]
https://sh4mh1.t.me

**Comment by Pasha4056** [comment]
Бот на блум какими функциями обладает?

**Comment by shamhi** [comment]
> Бот на блум какими функциями обладает?

обычный клейм, дружеский клейм, drop игра
а еще, съэмулированы все запросы, что кидает сама игра, чтобы не палить бота
