### ISSUE TITLE
Бесконечные ошибки + Миксует прокси

### ISSUE THREAD

**Issue by Strogazs** [shamhi/HamsterKombatBot#127]
![image](https://github.com/shamhi/HamsterKombatBot/assets/100476931/00a1e505-d631-40a7-8666-2f6f8ddfc362)

Это первая проблема. Она возникает не только на одном аккаунте, а вообще на всех. 

Вторая проблема заключается в том, что при нескольких аккаунтов и прокси. Прокси миксует между аккаунтами. И получается при перезапуске прокси постоянно сменяются. Это стало заметно когда я более 3х аккаунтов подключал

**Comment by Strogazs** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/100476931/30db950d-630b-4dcc-94e9-5d8e2be19f0f)

**Comment by Strogazs** [comment]
Как понял прокси можно как-то привязать к сессии. Но как я так и не разобрался. Жду помощи комьюнити

**Comment by shamhi** [comment]
> Это первая проблема. Она возникает не только на одном аккаунте, а вообще на всех.

версия бота последняя?

**Comment by shamhi** [comment]
> Как понял прокси можно как-то привязать к сессии

нет, в боте не предусмотрена возможность привязать определенный прокси к аккаунту

**Comment by Strogazs** [comment]
Стоит ли параллельно на одном аккаунте запускать три бота? 
- Хамстер
- МемеФи
- Ескоин
Если одновременно на одних прокси один аккаунт будет работать. Или лучше разделять

**Comment by dropclient** [comment]
> Стоит ли параллельно на одном аккаунте запускать три бота?
> 
> * Хамстер
> * МемеФи
> * Ескоин
>   Если одновременно на одних прокси один аккаунт будет работать. Или лучше разделять
Можно.
