### ISSUE TITLE
[Ошибка] Error: unable to sync

### ISSUE THREAD

**Issue by Karero26** [shamhi/HamsterKombatBot#128]
Вырубаю  софт, пытаюсь  зайти  в телефоне(чтоб  собрать комбо) и ничего не происходит, думаю кто-то сталкивался

**Comment by bd100b** [comment]
надо подождать, у меня где то через час снова заходит

**Comment by ButCheR-PRO** [comment]
Я тоже раньше спокойно играл на телефоне даже когда бот фармит на компе. А сегодня весь ден зайти не могу. Попробую выключить бота полностью и войти через час-два.

**Comment by NLegal** [comment]
у меня вот что работает: 
тормозим бота...
свайп на канал, удаление, очищаем историю...
заходим обратно в канал, запускаем

**Comment by NLegal** [comment]
сегодня и кликер начал кидать:

Unknown error while getting Profile Data: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/sync') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...

**Comment by ButCheR-PRO** [comment]
> сегодня и кликер начал кидать:

Такое бывает когда хомячьи сервера лежат. Обычно наблюдается после 1%:00 по МСК, когда обновляется комбо и все ринулись заходить в игру, создав нагрузку типа ДДОС атаки. Со временем проходит. А вот после того как закрыл бота, ещё минут 40-50 нельзя войти на телефоне, потому что выбивает ошибку unable to sync. Но через час спокойно заходит. Другого решения пока не найдено, остаётся просто ждать.
