### ISSUE TITLE
Через docker не запускается

### ISSUE THREAD

**Issue by Makhkets** [shamhi/HamsterKombatBot#129]
![image](https://github.com/shamhi/HamsterKombatBot/assets/89061583/74787be5-b375-482d-ba5c-c0f50bd1c75e)

**Comment by hahatulk** [comment]
> ![image](https://private-user-images.githubusercontent.com/89061583/334549332-74787be5-b375-482d-ba5c-c0f50bd1c75e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyNTY0MjMsIm5iZiI6MTcxNzI1NjEyMywicGF0aCI6Ii84OTA2MTU4My8zMzQ1NDkzMzItNzQ3ODdiZTUtYjM3NS00ODJkLWJhNWMtYzBmNTBiZDFjNzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDE1MzUyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNzE1OTYxMTZiN2YxMmI2YWM1N2YzMWIyYTNiZTAwNzBmZGYzYjkzZWM4ZDAwOTE0M2FiMmM5MzYwODE4MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.onYehUFJDGXcdPjM2aSvOqGuoxaxDFRc0U6mcsRSuHs)

как решил?

**Comment by ic23** [comment]
@hahatulk https://github.com/shamhi/HamsterKombatBot/issues/155#issuecomment-2144337479
