### ISSUE TITLE
Предложение. Добавить нотификацию на email если бот остановился из за ошибок

### ISSUE THREAD

**Issue by bd100b** [shamhi/HamsterKombatBot#130]
Возможно ли добавить нотификацию на email в случае если бот остановился из-за ошибок чтобы каждый раз не проверять консоль? Например вылезла ошибка 400 или еще какая то и на почту пришло уведомление

**Comment by shamhi** [comment]
легче в тг писать, но думаю это пригодится одному тебе )

**Comment by bd100b** [comment]
> легче в тг писать, но думаю это пригодится одному тебе )

или да, можно в тг. Так даже лучше

**Comment by Strogazs** [comment]
Полностью поддерживаю предложение. В телеграмм было бы супер

**Comment by mesteruh** [comment]
через supervisor делайте в чём проблема

**Comment by ButCheR-PRO** [comment]
Рациональное предложение. Одобряю.

**Comment by ButCheR-PRO** [comment]
Продолжение:
1. https://github.com/shamhi/HamsterKombatBot/issues/289
