### ISSUE TITLE
Предложение. Добавить рандомность к SLEEP_BY_MIN_ENERGY

### ISSUE THREAD

**Issue by bd100b** [shamhi/HamsterKombatBot#131]
Хорошо бы добавить рандомность к SLEEP_BY_MIN_ENERGY. Потому что так можно отследить что бот начинает тапать через один и тот же промежуток времени.

**Comment by ButCheR-PRO** [comment]
Уже добавили. В конфиге .env надо прописать:
`SLEEP_BY_MIN_ENERGY=[1800,2400]`
