### ISSUE TITLE
BadMsgNotification: [17] The msg_id is too high, the client time has to be synchronized.

### ISSUE THREAD

**Issue by Rofl1234** [shamhi/HamsterKombatBot#132]
![Снимок экрана (44)](https://github.com/shamhi/HamsterKombatBot/assets/171097650/181c23c0-45bb-49b8-a430-c74937cd9005)
Гайс, что сделал не так. Помогите пожалуйста, полный 0 в программировании. Версия Python 3.10.0 Пробовал с 3.11.0 и разными API телеграма. Одна и таже ошибка как на скрине.

**Comment by Maryoux** [comment]
Try to renew the code, `git clone https://github.com/shamhi/HamsterKombatBot.git` again manually or use `git pull`. The code is working fine on me

**Comment by Rofl1234** [comment]
не помогло

**Comment by Maryoux** [comment]
did you try it renew by git clone? by defaut it won't be happen.

**Comment by shamhi** [comment]
системное время синхронизировано?

**Comment by Rofl1234** [comment]
Воу, реальное системное время отставало, сейчас все заработало. Спасибо огромное!
