### ISSUE TITLE
[Предложениe] Добавить поддержку минимального баланса 

### ISSUE THREAD

**Issue by GoldenBroPro** [shamhi/HamsterKombatBot#134]
Сделать параметр в конфиге, чтобы можно было выставить минимальный баланс, который не будет тратиться. Основная цель этого баланса это покупка комбо, на автопокупке иногда не хватает времени, чтобы бот прошелся по всем предметам.

**Comment by xKumorio** [comment]
+

**Comment by ButCheR-PRO** [comment]
Я же уже создал такую тему с предложением: https://github.com/shamhi/HamsterKombatBot/issues/119

**Comment by PSHacks** [comment]
В **config.py**:

> BALANCE_TO_SAVE: int = 50000

В **.env**:

> BALANCE_TO_SAVE=ВАША_ЦИФРА

В **tapper.py** (строка **402**):
Это:

> if balance > price and level <= settings.MAX_LEVEL:

Заменяем на это:

> tempBalance = balance - settings.BALANCE_TO_SAVE
> if tempBalance > price and level <= settings.MAX_LEVEL:


Попробуйте, по идее должно работать, пока нет возможности проверить к сожалению.

**Comment by ButCheR-PRO** [comment]
> В **config.py**:
> 
> > BALANCE_TO_SAVE: int = 50000
> 
> В **.env**:
> 
> > BALANCE_TO_SAVE=ВАША_ЦИФРА
> 
> В **tapper.py** (строка **402**): Это:
> 
> > if balance > price and level <= settings.MAX_LEVEL:
> 
> Заменяем на это:
> 
> > tempBalance = balance - settings.BALANCE_TO_SAVE
> > if tempBalance > price and level <= settings.MAX_LEVEL:
> 
> Попробуйте, по идее должно работать, пока нет возможности проверить к сожалению.

К сожалению не работает. Ошибок никаких нет, но и тратит всё до нуля, хотя я поставил 500 000 ограничение  BALANCE_TO_SAVE

**Comment by PSHacks** [comment]
> > В **config.py**:
> > > BALANCE_TO_SAVE: int = 50000
> > 
> > 
> > В **.env**:
> > > BALANCE_TO_SAVE=ВАША_ЦИФРА
> > 
> > 
> > В **tapper.py** (строка **402**): Это:
> > > if balance > price and level <= settings.MAX_LEVEL:
> > 
> > 
> > Заменяем на это:
> > > tempBalance = balance - settings.BALANCE_TO_SAVE
> > > if tempBalance > price and level <= settings.MAX_LEVEL:
> > 
> > 
> > Попробуйте, по идее должно работать, пока нет возможности проверить к сожалению.
> 
> К сожалению не работает или работает неправильно. Ошибок никаких нет, но и тратит всё ниже лимита, хотя я поставил 50000 ограничение BALANCE_TO_SAVE. Возможно что перед апгрейдом на балансе было например 51к, а карточка стоит 40к, оно видит что денег хватает, покупает карточку за 40к и остается на балансе 11к, тогда оно больше не апгрейдит, пока не наберется минимум 50к. То есть нужно сделать проверку на минимальный баланс с учетом цены покупки апгрейда? Может быть так:
> 
> ```
> tempBalance = balance - price
> if tempBalance > settings.BALANCE_TO_SAVE and level <= settings.MAX_LEVEL:
> ```

По логике так и устроено, то есть:

> временный баланс = текущий - резерв (например если баланс 200к то временный будет 150к)

И проверка:

> если временный больше чем цена то ..

Сейчас потестирую.

**Comment by ButCheR-PRO** [comment]
> > В **config.py**:
> > > BALANCE_TO_SAVE: int = 50000
> > 
> > 
> > В **.env**:
> > > BALANCE_TO_SAVE=ВАША_ЦИФРА
> > 
> > 
> > В **tapper.py** (строка **402**): Это:
> > > if balance > price and level <= settings.MAX_LEVEL:
> > 
> > 
> > Заменяем на это:
> > > tempBalance = balance - settings.BALANCE_TO_SAVE
> > > if tempBalance > price and level <= settings.MAX_LEVEL:
> > 
> > 
> > Попробуйте, по идее должно работать, пока нет возможности проверить к сожалению.
> 
> К сожалению не работает или работает неправильно. Ошибок никаких нет, но и тратит всё ниже лимита, хотя я поставил 50000 ограничение BALANCE_TO_SAVE. Возможно что перед апгрейдом на балансе было например 51к, а карточка стоит 40к, оно видит что денег хватает, покупает карточку за 40к и остается на балансе 11к, тогда оно больше не апгрейдит, пока не наберется минимум 50к. То есть нужно сделать проверку на минимальный баланс с учетом цены покупки апгрейда? Может быть так:
> 
> ```
> tempBalance = balance - price
> if tempBalance > settings.BALANCE_TO_SAVE and level <= settings.MAX_LEVEL:
> ```

Похоже что моё исправление теперь работает как надо. 
Вносим коррективы в код bot/core/tapper.py (у меня 395 строка):
`if balance > price and level <= settings.MAX_LEVEL:`
заменить на:
```
tempBalance = balance - price
if tempBalance > settings.BALANCE_TO_SAVE and level <= settings.MAX_LEVEL:
```
а в bot/config/config.py например после 16 сроки добавим:
`    BALANCE_TO_SAVE: int = 5000`
и в файле  .env добавим:
`BALANCE_TO_SAVE=ВАШЕ_ЧИСЛО`

Не забываем удалять папки __pycache__ после изменений в коде, перед запуском бота.

**Comment by PSHacks** [comment]
> > > В **config.py**:
> > > > BALANCE_TO_SAVE: int = 50000
> > > 
> > > 
> > > В **.env**:
> > > > BALANCE_TO_SAVE=ВАША_ЦИФРА
> > > 
> > > 
> > > В **tapper.py** (строка **402**): Это:
> > > > if balance > price and level <= settings.MAX_LEVEL:
> > > 
> > > 
> > > Заменяем на это:
> > > > tempBalance = balance - settings.BALANCE_TO_SAVE
> > > > if tempBalance > price and level <= settings.MAX_LEVEL:
> > > 
> > > 
> > > Попробуйте, по идее должно работать, пока нет возможности проверить к сожалению.
> > 
> > 
> > К сожалению не работает или работает неправильно. Ошибок никаких нет, но и тратит всё ниже лимита, хотя я поставил 50000 ограничение BALANCE_TO_SAVE. Возможно что перед апгрейдом на балансе было например 51к, а карточка стоит 40к, оно видит что денег хватает, покупает карточку за 40к и остается на балансе 11к, тогда оно больше не апгрейдит, пока не наберется минимум 50к. То есть нужно сделать проверку на минимальный баланс с учетом цены покупки апгрейда? Может быть так:
> > ```
> > tempBalance = balance - price
> > if tempBalance > settings.BALANCE_TO_SAVE and level <= settings.MAX_LEVEL:
> > ```
> 
> Похоже что моё исправление теперь работает как надо. Вносим коррективы в код bot/core/tapper.py (у меня 395 строка): `if balance > price and level <= settings.MAX_LEVEL:` заменить на:
> 
> ```
> tempBalance = balance - price
> if tempBalance > settings.BALANCE_TO_SAVE and level <= settings.MAX_LEVEL:
> ```
> 
> а в bot/config/config.py например после 16 сроки добавим: ` BALANCE_TO_SAVE: int = 5000` и в файле .env добавим: `BALANCE_TO_SAVE=ВАШЕ_ЧИСЛО`
> 
> Не забываем удалять папки **pycache** после изменений в коде, перед запуском бота.

Командная работа? (^_^)

**Comment by ButCheR-PRO** [comment]
Я там пофиксил немного работу очереди (queue). Теперь работает как часы! 
Вот финальный вариант:

Вносим коррективы в код bot/core/tapper.py (у меня 395 строка):
`if balance > price and level <= settings.MAX_LEVEL:`
заменить на:
```
tempBalance = balance - settings.BALANCE_TO_SAVE
if tempBalance > price and level <= settings.MAX_LEVEL:
```
и чуть ниже (у меня на 402 строке):
`if balance > upgrade[3] and upgrade[2] <= settings.MAX_LEVEL:`
заменяем на:
```
                                tempBalance = balance - settings.BALANCE_TO_SAVE
                                if tempBalance > upgrade[3] and upgrade[2] <= settings.MAX_LEVEL:
```
и ещё сделал отображение баланса после каждого апгрейда. На 413 строке заменяем:
`f"Earn every hour: <y>{earn_on_hour}</y> (<g>+{upgrade[4]}</g>)")`
на:
`f"Balance: <c>{balance}</c> | Earn every hour: <y>{earn_on_hour}</y> (<g>+{upgrade[4]}</g>)")`

а в bot/config/config.py например после 16 сроки добавим:
`    BALANCE_TO_SAVE: int = 5000`
и в файле  .env добавим:
`BALANCE_TO_SAVE=ВАШЕ_ЧИСЛО`

Не забываем удалять папки __pycache__ после изменений в коде, перед запуском бота.

**Comment by Kit0077** [comment]
> Я там пофиксил немного работу очереди (queue). Теперь работает как часы! Вот финальный вариант:
> 
> Вносим коррективы в код bot/core/tapper.py (у меня 395 строка): `if balance > price and level <= settings.MAX_LEVEL:` заменить на:
> 
> ```
> tempBalance = balance - settings.BALANCE_TO_SAVE
> if tempBalance > price and level <= settings.MAX_LEVEL:
> ```
> 
> и чуть ниже (у меня на 402 строке): `if balance > upgrade[3] and upgrade[2] <= settings.MAX_LEVEL:` заменяем на:
> 
> ```
>                                 tempBalance = balance - settings.BALANCE_TO_SAVE
>                                 if tempBalance > upgrade[3] and upgrade[2] <= settings.MAX_LEVEL:
> ```
> 
> и ещё сделал отображение баланса после каждого апгрейда. На 413 строке заменяем: `f"Earn every hour: <y>{earn_on_hour}</y> (<g>+{upgrade[4]}</g>)")` на: `f"Balance: <c>{balance}</c> | Earn every hour: <y>{earn_on_hour}</y> (<g>+{upgrade[4]}</g>)")`
> 
> а в bot/config/config.py например после 16 сроки добавим: ` BALANCE_TO_SAVE: int = 5000` и в файле .env добавим: `BALANCE_TO_SAVE=ВАШЕ_ЧИСЛО`
> 
> Не забываем удалять папки **pycache** после изменений в коде, перед запуском бота.

Бро, приветствую! Можешь, пожалуйста, скинуть свои отредактированные файлы из core и config. Я сделал все по твоей инструкции, но ловлю кучу ошибок, не запускается бот

**Comment by ButCheR-PRO** [comment]
> Бро, приветствую! Можешь, пожалуйста, скинуть свои отредактированные файлы из core и config. Я сделал все по твоей инструкции, но ловлю кучу ошибок, не запускается бот

Может не соблюдал отступы перед кодом? Там это важно сохранять отступы как в оригинале.

**Comment by Kit0077** [comment]
> > Бро, приветствую! Можешь, пожалуйста, скинуть свои отредактированные файлы из core и config. Я сделал все по твоей инструкции, но ловлю кучу ошибок, не запускается бот
> 
> Может не соблюдал отступы перед кодом? Там это важно сохранять отступы как в оригинале. А что за ошибки?

Кстати, отступы горят синими полосками, я вроде редактирую на сколько понимаю правила построения кода, но я в этом тупой. IDE стоит ScTi, подсвечивает, но хз почему мои правки не помогают

**Comment by Kit0077** [comment]
> [bot.zip](https://github.com/user-attachments/files/15513615/bot.zip) Вот прикрепил архив с изменёнными файлами. Ну а в .env строчку `BALANCE_TO_SAVE=ВАШЕ_ЧИСЛО` добавите самостоятельно

Большое спасибо, попробую запустить сегодня

**Comment by ButCheR-PRO** [comment]
> Кстати, отступы горят синими полосками, я вроде редактирую на сколько понимаю правила построения кода, но я в этом тупой. IDE стоит ScTi, подсвечивает, но хз почему мои правки не помогают

А, я в обычном блокноте весь код пишу :)

**Comment by JayNKey** [comment]
красавчики )
