### ISSUE TITLE
Помогите дураку который не прогер и не может установить даже бота

### ISSUE THREAD

**Issue by Sqweezz** [shamhi/HamsterKombatBot#136]
Не знаю как правильно вставлять API надо, но так не работает, вставляю без всяких команд

![image](https://github.com/shamhi/HamsterKombatBot/assets/171202036/6da9c221-51b8-4f43-96d8-494e74246f34)

Что нужно сделать чтобы заработало?

**Comment by join1337** [comment]
для криворуких есть файл install.bat в корне запускаешь открываешь .env настраиваешь и start.bat

**Comment by Strogazs** [comment]
Могу помочь если совсем тяжело. @strogazs телега

**Comment by DamAlyuk** [comment]
Версию питона установи 3.11.*

**Comment by DDstar1** [comment]
This is really great, will be the best if it works well on a VPS too

What do you guys think?

**Comment by ButCheR-PRO** [comment]
## Предварительные условия
Прежде чем начать, убедитесь, что у вас установлено следующее:
- [Python](https://www.python.org/downloads/release/python-3109/) версии 3.10.9 

Чтобы установить библиотеки в Windows, запустите INSTALL.bat.

## Получение API ключей
1. Перейдите на сайт [my.telegram.org](https://my.telegram.org) и войдите в систему, используя свой номер телефона.
2. Выберите **"API development tools"** и заполните форму для регистрации нового приложения.
3. Запишите `API_ID` и `API_HASH` в файле `.env`, предоставленные после регистрации вашего приложения.
В .env обязательно должны указать ваши API_ID и API_HASH , остальное берется по умолчанию.

 Для запуска бота используйте `START.bat` (или в консоли: `python main.py`).
# 1 - Создает сессию (ввести номер телефона и код который придёт в личное сообщение Telegram)
# 2 - Запускает кликер
