### ISSUE TITLE
Не работает авторизация через токен bot - Unknown error while getting Access token 422: Unprocessable Entity

### ISSUE THREAD

**Issue by globalskye** [shamhi/HamsterKombatBot#137]
Unknown error while getting Access token 422: Unprocessable Entity

**Comment by globalskye** [comment]
https://i.imgur.com/9FAjcsq.png

**Comment by ButCheR-PRO** [comment]
Не путай API_HASH и токен бота. Где ты берешь токен бота? 
Как вариант, вместо токена вводи номер телефона к которому привязан Телеграм аккаунт, туда придёт код, этот код вставляй в бота и всё будет работать.
