### ISSUE TITLE
Не подключается при создании сессии. Unable to connect due to network issues: Connection timed out

### ISSUE THREAD

**Issue by Skampf1** [shamhi/HamsterKombatBot#140]
Unable to connect due to network issues: Connection timed out
Что делать в такой ситуации?

**Comment by ButCheR-PRO** [comment]
Попробуй в .env параметр:
`USE_PROXY_FROM_FILE=False`
Так же, попробуй использовать VPN или прокси. Либо наоборот отключить их. Могут быть проблемы с настройками прокси как тут: https://github.com/shamhi/HamsterKombatBot/issues/117
