### ISSUE TITLE
Насущные проблемки

### ISSUE THREAD

**Issue by VintaGist** [shamhi/HamsterKombatBot#141]
Спасибо за софт, все работает. Немного подправил чтоб выводило остаток после покупок и не тратило до определенного остатка денег. Реально актуальные моменты.
Еще добавил сумму покупки и разделители для тысяч при выводе.

`Successfully upgraded shit_coins with price 5,000 to 1 lvl | Earn every hour: 20,375 (+590) | Money left 2,886,798`  -так легче воспринимается

Но еще есть проблемка, для новых акков покупка чего-то вроде `joe_rogan_podcast` за лям монеток с доходом (+0) считаю нецелесообразным. Для старых акков под вопросом, конечно. 

Как считаете?

**Comment by ButCheR-PRO** [comment]
> Спасибо за софт, все работает. Немного подправил чтоб выводило остаток после покупок и не тратило до определенного остатка денег. Реально актуальные моменты. Еще добавил сумму покупки и разделители для тысяч при выводе.
> 
> `Successfully upgraded shit_coins with price 5,000 to 1 lvl | Earn every hour: 20,375 (+590) | Money left 2,886,798` -так легче воспринимается

А скинь код, как ты эти разделители на выводе прописывал.

**Comment by VintaGist** [comment]
> А скинь код, как ты эти разделители на выводе прописывал.

Вот здесь:
https://github.com/shamhi/HamsterKombatBot/blob/d7b218787ec5a04ef3341ca38cab491e8271a63f/bot/core/tapper.py#L410C41-L413C110

Код:
```
logger.success(
    f"{self.session_name} | "
    f"Successfully upgraded <e>{upgrade[0]}</e> to <m>{upgrade[2]}</m> lvl | "
    f"Earn every hour: <y>{earn_on_hour}</y> (<g>+{upgrade[4]}</g>)")
```
Замени на 
```
logger.success( 
    f"{self.session_name} | " 
    f"Successfully upgraded <e>{upgrade[0]}</e> with price <r>{upgrade[3]:,}</r> to <m>{upgrade[2]}</m> lvl | "
    f"Earn every hour: <y>{earn_on_hour:,}</y> (<g>+{upgrade[4]}</g>) | "
    f"Money left <e>{balance:,}</e>")
```
Важно: соблюдать отступы от начала строки!

**Comment by ButCheR-PRO** [comment]
> Важно: соблюдать отступы от начала строки!

Спасибо! Я бы везде заменил {earn_on_hour} и {balance} на {earn_on_hour:,} и {balance:,}

**Comment by ButCheR-PRO** [comment]
> Но еще есть проблемка, для новых акков покупка чего-то вроде `joe_rogan_podcast` за лям монеток с доходом (+0) считаю нецелесообразным. Для старых акков под вопросом, конечно.

Предлагаю немного модернизировать логику покупки карточек: https://github.com/shamhi/HamsterKombatBot/issues/142#issuecomment-2143381837
