### ISSUE TITLE
[Ошибка] Error while getting Access Token: SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by dokznx** [shamhi/HamsterKombatBot#143]
error while getting Access Token: Cannot connect to host api.hamsterkombat.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')] | Response text: ...

Помогите пожалуйста. Как решить проблему с сертификатом? Видел, были такие проблемы, но решения не увидел. Заранее спасибо!

**Comment by dokznx** [comment]
Сам отвечу на вопрос. Может кому пригодится.
Мне помогла установка данного сертификата с сайта Amazon
https://www.amazontrust.com/repository/AmazonRootCA1.cer

А помог мне chatgpt этим ответом:
 
Add Amazon Root CA 1 to your local certificate store:

Download the Amazon Root CA 1 certificate from the Amazon Trust Services repository.
Install it in your operating system's certificate store or the certificate store used by your application.
Ensure Intermediate Certificates are Available:

Make sure the intermediate certificates (like Amazon RSA 2048 M02) are available either in the certificate store or provided by the server during the handshake.

Надеюсь пригодится.

**Comment by ZakezMine** [comment]
в файле core/tapper.py строку async with aiohttp.ClientSession(headers=headers, connector=proxy_conn) as http_client:
заменить на async with aiohttp.ClientSession(headers=headers, connector=aiohttp.TCPConnector(verify_ssl=False)) as http_client:

**Comment by vitaliiich** [comment]
> в файле core/tapper.py строку async with aiohttp.ClientSession(headers=headers, connector=proxy_conn) as http_client: заменить на async with aiohttp.ClientSession(headers=headers, connector=aiohttp.TCPConnector(verify_ssl=False)) as http_client:

тогда каждая сессия будет запущена без прокси ( = акки в бан)

**Comment by Mahnazmohammadii** [comment]
my .eve vonfig 
![Uploading .env file config .png…]()

**Comment by MsaMadman** [comment]
> > в файле core/tapper.py строку async with aiohttp.ClientSession(headers=headers, connector=proxy_conn) as http_client: заменить на async with aiohttp.ClientSession(headers=headers, connector=aiohttp.TCPConnector(verify_ssl=False)) as http_client:
> 
> тогда каждая сессия будет запущена без прокси ( = акки в бан)

Так как правильно делать? Покупать платный прокси на каждый аккаунт?

**Comment by hardwin1014** [comment]
> Сам отвечу на вопрос。 Может кому пригодится。 亚马逊 https://www.amazontrust.com/repository/AmazonRootCA1.cer-----------谷歌翻译----------我自己来回答这个问题。也许这对某人有用。从亚马逊安装这个证书对我很有帮助。
> 
> 一个例子是 chatgpt этим ответом:-----------谷歌翻译------------ chatgpt 帮助我找到了这个答案：
> 
> 将 Amazon Root CA 1 添加到您的本地证书存储：-----------谷歌翻译----------将 Amazon Root CA 1 添加到您的本地证书存储：
> 
> 从 Amazon Trust Services 存储库下载 Amazon Root CA 1 证书。 将其安装在操作系统的证书存储区或应用程序使用的证书存储区中。 确保中级证书可用：-----------谷歌翻译----------从 Amazon Trust Services 存储库下载 Amazon Root CA 1 证书。将其安装在操作系统的证书存储或应用程序中使用的存储证书中。确保中级可用证书：
> 
> 确保中间证书（如 Amazon RSA 2048 M02）在证书存储中可用或在握手期间由服务器提供。-----------谷歌翻译----------确保中间证书（例如 Amazon RSA 2048 M02）在存储证书中可用或由服务器在握手期间提供。

I have this certificate in my system
