### ISSUE TITLE
[Error] error: unable to sync, while opening the bot

### ISSUE THREAD

**Issue by Mikeyounger** [shamhi/HamsterKombatBot#147]
hi i got this error when on my phone request error : unable to sync even i turned off the script whats the problem

**Comment by 0xlimon** [comment]
same

**Comment by mesteruh** [comment]
i have same issue. try later

**Comment by Mikeyounger** [comment]
> same

Guys it still happens to me, what we gonna do?

**Comment by 0xlimon** [comment]
> > same
> 
> Guys it still happens to me, what we gonna do?

I don't know bro, I have this problem too. None of the accounts will be opened

**Comment by Mikeyounger** [comment]
> > > same
> > 
> > 
> > Guys it still happens to me, what we gonna do?
> 
> I don't know bro, I have this problem too. None of the accounts will be opened

even those that not running with this script ?

**Comment by ButCheR-PRO** [comment]
When the script is running, do not launch the game on your phone. After turning off the script, wait 30 minutes before entering the game from your phone. For me this error disappears when I log in 40-60 minutes after closing the script.
