### ISSUE TITLE
Возможно ли добавить неснижаемый остаток на балансе?

### ISSUE THREAD

**Issue by l1v0n1** [shamhi/HamsterKombatBot#149]
Ну вот допустим сейчас у меня на балансе 10 млн и он его держит, ниже не спускается. Если баланс я сам снижу вручную покупая карты он идёт в накопление

**Comment by XPacL** [comment]
https://github.com/shamhi/HamsterKombatBot/issues/142.  Вот эту тему почитай, там ребята вообще логику переписали, добавили в том числе и возможность задать неснижаемый остаток.

**Comment by NLegal** [comment]
закрываем... работает...
