### ISSUE TITLE
[Предложение] Оптимальная покупка combo-карточек

### ISSUE THREAD

**Issue by EugeneMartein** [shamhi/HamsterKombatBot#1498]
Можно сделать так, чтобы combo-карточки покупались только в том случае, если их цена не превышает трети суточной прибыли.
То есть текущую прибыль умножаем на 24, прибавляем к ней награду 5 000 000, и если сумма цен трёх combo-карточек не превышает получаемой суммы дневной прибыли вместе с наградой, то не покупаем эти карточки, потому что уходим в минус.

**Comment by wannaD1E** [comment]
ну так это прописать элементарно в условиях, врятли это нужно массам

**Comment by EugeneMartein** [comment]
В каких уславиях ты это прописываешь?

**Comment by wannaD1E** [comment]
if common_price < earn_on_hour * 24 and balance > common_price and is_combo_accessible:

> В каких условиях ты это прописываешь? В файле `tapper.py` ? Это условие редактировать? `if common_price < settings.MAX_COMBO_PRICE and balance > common_price and is_combo_accessible:`

                                if common_price < earn_on_hour * 24 and balance > common_price and is_combo_accessible:

Да, вот твоё условие.

**Comment by EugeneMartein** [comment]
> > В каких условиях ты это прописываешь? В файле `tapper.py` ? Это условие редактировать? `if common_price < settings.MAX_COMBO_PRICE and balance > common_price and is_combo_accessible:`
> 
> ```
>                             if common_price < earn_on_hour * 24 and balance > common_price and is_combo_accessible:
> ```
> 
> Да, вот твоё условие.

Спасибо, исправил, прибавил к нему ещё 5млн, чтобы с учётом выгоды от покупки считало.
