### ISSUE TITLE
'available_energy'

### ISSUE THREAD

**Issue by liluglymane666** [shamhi/HamsterKombatBot#15]
![image](https://github.com/shamhi/HamsterKombatBot/assets/57453873/83c92b62-54f9-46c6-a491-52353686f446)
обновил репо и тут вернулась старая проблема

**Comment by shamhi** [comment]
кажись я понял в чем проблема
у тебя системное время правильное?

**Comment by liluglymane666** [comment]
> кажись я понял в чем проблема у тебя системное время правильное?

да,в тот раз его это помогло.в этот раз синхронизировал и ничего.но cпустя час ошибок стало намного меньше

**Comment by avtosubaru25** [comment]
вот еще програмка можно поставить автоматом обновление времени   https://www.timesynctool.com/      мин 15 поставил меньше ошибок

**Comment by avtosubaru25** [comment]
> кажись я понял в чем проблема у тебя системное время правильное?

Саш привет я тебе в телегу написал  если несложно помоги моя телега  https://t.me/alligatorCCCP

**Comment by c5bomba** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/108828167/bb7e2865-83da-4565-a178-a6ecc11eef99)

Have same problem, tried time sync with 15min interval but didnt helped..
now i am not able to log in on phone too.

**Comment by Fess23** [comment]
have same problem Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
