### ISSUE TITLE
[Ошибка] ModuleNotFoundError: No module named loguru

### ISSUE THREAD

**Issue by PivnoyPyps** [shamhi/HamsterKombatBot#150]
Ниче не пон, подскажите друзья
![Снимок](https://github.com/shamhi/HamsterKombatBot/assets/171507960/a7bc2086-be19-40ad-894d-47db9587e24f)

**Comment by mesteruh** [comment]
pip install loguru

**Comment by ButCheR-PRO** [comment]
Обычно достаточно запустить INSTALL.bat, он установит все модули из списка requirements.txt
И там есть в том числе: 
`loguru==0.7.2`
Ну можно и просто в консоли 
`pip install loguru`

**Comment by KOTBCTAKAHE** [comment]
Проблема решена, закройте issue.

**Comment by treyne** [comment]
Результат выполнения pip install loguru 
![Снимок](https://github.com/user-attachments/assets/ef5e0ea1-861e-4ce3-83a0-763f3368da78)

При запуске скрипта
![Снимок2](https://github.com/user-attachments/assets/ea45bb8f-2f9a-442f-a3a3-e3a38553de05)
