### ISSUE TITLE
вылезает ошибка на скачивание pip install -r requirements.txt

### ISSUE THREAD

**Issue by UNLUCKYxx** [shamhi/HamsterKombatBot#151]
![2024-06-02 09 30 20](https://github.com/shamhi/HamsterKombatBot/assets/171423760/ecee030b-c978-4a2f-8e99-57f83528d1bb)

**Comment by mesteruh** [comment]
Нужно установить Microsoft VIsual C++ 14 написано же

**Comment by UNLUCKYxx** [comment]
уже разобрался, спасибо
