### ISSUE TITLE
Request Error, Unable to sync | Ошибка запроса, невозможно синхронизировать

### ISSUE THREAD

**Issue by tektungg** [shamhi/HamsterKombatBot#1515]
So guys, i've run the bot and works well. But after i ran the bot, i can't access the app on my phone with saying "Request error. Unable to sync". Any help?

Итак, ребята, я запустил бота и он работает хорошо. Но после запуска бота я не могу получить доступ к приложению на телефоне с сообщением "Ошибка запроса. Невозможно синхронизировать". Кто-нибудь может помочь?
![image](https://github.com/shamhi/HamsterKombatBot/assets/128006927/e7637dc1-9842-4177-9cdf-2a8b6c35a6ec)

**Comment by shamhi** [comment]
это нормально, не нужно заходить в игру при включенном боте
останови бота и зайди через 10-20 мин

**Comment by tektungg** [comment]
Я подождал 30 минут, но все еще получил эту ошибку, думаю, я проверю еще раз завтра. спасибо за ответ!

**Comment by ahrorbeksoft** [comment]
for me, when this happens, i just restart the script and start the bot on my phone at the same time and i keep resetting the bot until it successfully lunches
