### ISSUE TITLE
ERROR | 30 - Unknown error while getting Combo Cards

### ISSUE THREAD

**Issue by loganleito** [shamhi/HamsterKombatBot#1524]
ERROR | 30 - Unknown error while getting Combo Cards: Cannot connect to host api21.datavibe.top:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')] | Response text: ...

This has been going on for several days now.

**Comment by KOTBCTAKAHE** [comment]
try to update

**Comment by LOQQQQ** [comment]
do you fix it ?

**Comment by loganleito** [comment]
It didn't work out anyway.
![Снимок](https://github.com/user-attachments/assets/9f4674e9-3d9f-43d0-baf0-89df0dff4678)

**Comment by loganleito** [comment]
Мне помогло:
`pip install --trusted-host api21.datavibe.top:443 requests`
