### ISSUE TITLE
[Ошибка] 492 Unknown error: list index out of range. в чём может быть причина? 

### ISSUE THREAD

**Issue by DeeArt63** [shamhi/HamsterKombatBot#153]
Пересоздал сессию и вылезла ошибка, подскажите в чём может быть причина? 
![image](https://github.com/shamhi/HamsterKombatBot/assets/171515301/34c1c79b-8701-43c0-9c76-d6da3147d8d4)

**Comment by DeeArt63** [comment]
Все ок. Нашёл ошибки в стройках!

**Comment by Azamir69** [comment]
> Все ок. Нашёл ошибки в стройках файла .env! Нужно настраивать как описано в файле README.md. Там были изменения в параметрах.

какие именно ? можешь скинуть как ты заполнил env файл плз

**Comment by ButCheR-PRO** [comment]
> какие именно ? можешь скинуть как ты заполнил env файл плз

```
API_ID=21236859
API_HASH=9ab1affd113a4188606fa01v4x8cdc8b

MIN_AVAILABLE_ENERGY=100
SLEEP_BY_MIN_ENERGY=[1800,2400]

ADD_TAPS_ON_TURBO=2500

AUTO_UPGRADE=True
MAX_LEVEL=20
BALANCE_TO_SAVE=5000000
UPGRADES_COUNT=10

APPLY_DAILY_ENERGY=True
APPLY_DAILY_TURBO=True

RANDOM_TAPS_COUNT=[50,200]
SLEEP_BETWEEN_TAP=[10,25]
USE_PROXY_FROM_FILE=False
```
