### ISSUE TITLE
[Ошибка] BOOST_MAX_LEVEL Boost BoostFullAvailableTaps cannot be increased above level 6

### ISSUE THREAD

**Issue by KiraSokolov** [shamhi/HamsterKombatBot#156]
Иногда вылетает такая ошибка

ERROR    | 221 - first | Unknown error while Apply BoostFullAvailableTaps Boost: 400, message='Bad Request', url=URL('https://api.hamsterkombat.io/clicker/buy-boost') | Response text: {"error_code":"BOOST_MAX_LEVEL","error_message":"Boost BoostFullAvailableTaps cannot be increased above level 6. Cooldown Tue Ju...

**Comment by ButCheR-PRO** [comment]
https://github.com/shamhi/HamsterKombatBot/issues/168
