### ISSUE TITLE
Unknown error: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by Stelfelics** [shamhi/HamsterKombatBot#1574]
![image](https://github.com/user-attachments/assets/87b294b5-72eb-4603-a136-c208febcd15e)

**Comment by Stelfelics** [comment]
Without a proxy, everything worked for just a couple of days.

Без прокси, буквально пару дней всё работало.

**Comment by IveNeSGaming** [comment]
hey, I don't see the same message. Unknown error: 'NoneType' object has no attribute 'replace', why is this happening? Will the program be updated?
