### ISSUE TITLE
[Вопрос] Как работает логика авто-покупки? 

### ISSUE THREAD

**Issue by AntonLodygin** [shamhi/HamsterKombatBot#160]
по какому принципу работает авто-покупка карточек? покупаются рандомные карточки или с наибольшей выгодой?

**Comment by NLegal** [comment]
Автоматическая покупка карточек в том контексте, который вы описываете, осуществляется не случайно, а с учетом наибольшей выгоды. Система оценивает каждую доступную карточку на основе ее потенциальной прибыли в час (profitPerHourDelta) и стоимости (price). Алгоритм рассчитывает "значимость" каждой карточки как отношение прибыли к стоимости, и приоритет отдается тем, которые предлагают большую отдачу по сравнению с их ценой.

Подход заключается в том, чтобы оценить, какие улучшения максимально повышают пассивный доход с минимальными затратами, что позволяет эффективно управлять ресурсами пользователя. Система учитывает текущий баланс и не тратит все средства, сохраняя определенный процент в качестве резерва. Это гарантирует, что у пользователя всегда будет достаточно средств для покупки наиболее значимых улучшений.

Если конечно все по образцу.

**Comment by Yorksik** [comment]
Пока не уверен что все работает действительно так как вы описали. У меня бот покупает совсем не выгодные карточки.
Условно говоря, бот купит за 100к карточку вместо того чтобы дождаться пока не будет на счету больше денег и купить более выгодную, скажем, за 5кк.

пока предполагаю что алгоритм такой :
бот выбирает только из тех карточек, на которые хватает денег.
если не хватает денег, бот ждет след запуска.
опять выбирает из тех на которые хватает денег.
оказывается что хватает денег на 2 самые дешевые. 
из этих двух выбирает самую прибыльную и качает ее.
и так далее.

получается бот качает самую дешевую карту.
у меня так одну карту до 20 ур докачал.

как то так. 

Спасибо тому кто подтвердит или опровергнет это

**Comment by ButCheR-PRO** [comment]
Всё верно, пока работает именно так. Логику автопокупки мы усовершенствовали и дискуссировали на эту тему здесь: https://github.com/shamhi/HamsterKombatBot/issues/142

**Comment by Yorksik** [comment]
> Всё верно, пока работает именно так. Логику автопокупки мы усовершенствовали и дискуссировали на эту тему здесь: #142

Но ведь экономичиски это не целесообразно, не так ли.? (возможно я не понимаю чего то)
Ведь как только становиться достаточно монет купить самую дешевую карту, бот это делает, тратит все деньги и все по кругу.

сори если не офтоплю

**Comment by si4man** [comment]
> > Всё верно, пока работает именно так. Логику автопокупки мы усовершенствовали и дискуссировали на эту тему здесь: #142
> 
> Но ведь экономичиски это не целесообразно, не так ли.? (возможно я не понимаю чего то) Ведь как только становиться достаточно монет купить самую дешевую карту, бот это делает, тратит все деньги и все по кругу.
> 
> Почему бы не ждать пока накопятся монеты для с самой быстрой окупаемостью?
> 
> сори если не офтоплю

сейчас работает система приоритетов у карточек, оно старается тратить меньше при этом покупая эффективные карточки рассчитывая эту эффективность по рассчитывается по отношению прибыли к цене, да и даже после апгрейда какой-то баланс всё равно будет оставаться т.к. оно не тратит всё

**Comment by ButCheR-PRO** [comment]
Продолжение будет здесь:
1. https://github.com/shamhi/HamsterKombatBot/issues/142
