### ISSUE TITLE
ошибка при запуске 

### ISSUE THREAD

**Issue by sdlazxc** [shamhi/HamsterKombatBot#1625]
когда запускаю START.bat появляеться такая ошибка 
![image](https://github.com/user-attachments/assets/f0e2b0d6-2f1b-4abf-a779-7523a62370a9)
подскажите пожалуйста как пофиксить? при нажатии любой кнопки окно закрываеться

**Comment by WeendVidente777** [comment]
попробуй pip install loguru

**Comment by molotov95** [comment]
У меня тоже самое, хотя данная библиотека установлена

**Comment by sdlazxc** [comment]
> попробуй pip install loguru

![image](https://github.com/user-attachments/assets/0885c6f4-53c1-4190-af4c-cfc54352715b)
установлен, несколько раз переустанавливал его
