### ISSUE TITLE
Cannot connect to host hamsterkombatgame.io

### ISSUE THREAD

**Issue by sultanlive** [shamhi/HamsterKombatBot#1630]
### Error logs:

`Unknown error while getting Nuxt Builds: Cannot connect to host hamsterkombatgame.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')] | Response text: ...`

`Unknown error while getting Access Token: Cannot connect to host api.hamsterkombatgame.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')] | Response text: ...`

`Unknown error while getting Nuxt Builds: Cannot connect to host hamsterkombatgame.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')] | Response text: ...`

I don't use a proxy. ENV is correct. System: MacOS Sonoma.

**Comment by shamhi** [comment]
#143
