### ISSUE TITLE
when starting START.bat crashes such an error

### ISSUE THREAD

**Issue by sdlazxc** [shamhi/HamsterKombatBot#1635]
![Снимок экрана 2024-07-22 134113](https://github.com/user-attachments/assets/a38363cd-d9ca-4ba1-a374-4c0f23418f6c)

Please help me fix it

**Comment by DenisSalnikoff** [comment]
Скорее всего дело в папке "Рабочий стол". Размести репозиторий просто на диске с:\, Например в c:\reps
