### ISSUE TITLE
слип рандомный

### ISSUE THREAD

**Issue by yacody** [shamhi/HamsterKombatBot#164]
ну и почему он мне слип дает на 2800 когда в конфиге 2523

**Comment by yacody** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/613438bc-84f3-46f7-8256-d7a332b1c3bf)

**Comment by yacody** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/8ae8d9b0-4425-45e7-86f0-8256fae665a7)

**Comment by gg-script** [comment]
так и задумано

**Comment by shamhi** [comment]
я изменил логику слипа, теперь при достижении минимального баланса, разрывает коннект и спит (по дефолту рандом от 1800 до 2400) по указанному в .env времени [n1,n2]
далее, создается новый коннект

это сделано для эмуляции человеческой активности
