### ISSUE TITLE
[Ошибка] TypeError: unsupported operand type(s) for: type and type. На macOS Выдает ошибку даже не запустившись

### ISSUE THREAD

**Issue by Vadoc1337** [shamhi/HamsterKombatBot#165]
<img width="837" alt="image" src="https://github.com/shamhi/HamsterKombatBot/assets/121457828/e67a209d-1a98-40f2-a294-5cbb4e9d3c4a">

TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by NLegal** [comment]
seems you are trying to use proxy, check proxy settings:

bot/core/proxies.txt

**Comment by micromagicman** [comment]
@Vadoc1337, а python3 --version что пишет?

**Comment by shamhi** [comment]
используй версию 3.10 или 3.11

**Comment by Vadoc1337** [comment]
<img width="495" alt="image" src="https://github.com/shamhi/HamsterKombatBot/assets/121457828/ae38196e-4def-46f1-8743-f2fefaa1082a">

**Comment by Vadoc1337** [comment]
В итоге скачал новую версию бота и старые ошибки ушли, появились другие) но там уже есть отдельный тред))
