### ISSUE TITLE
[Ошибка] ModuleNotFoundError: No module named pyrogram, Помогите глупцу!

### ISSUE THREAD

**Issue by f9xik** [shamhi/HamsterKombatBot#166]
Что не так и что надо сделать желательно для чайников

![Снимок экрана 2024-06-04 105339](https://github.com/shamhi/HamsterKombatBot/assets/81516333/fd69795f-fe65-4b17-92db-0e9b59d04088)

**Comment by BloodyKatana47** [comment]
`
python -m venv .venv && source .venv/bin/activate && pip install -r requirements.txt && python main.py
`

**Comment by f9xik** [comment]
пробовал не помогает

**Comment by Jokekkka** [comment]
Pip install pyrogram

**Comment by ButCheR-PRO** [comment]
Вообще достаточно запустить INSTALL.bat и оно само установить нужные модули и библиотеки из файла requirements.txt. Там кстати прописан:
`Pyrogram==2.0.106`
Можно и вручную 
`pip install Pyrogram`
