### ISSUE TITLE
[Вопрос] Как в боте работать с TDATA аккаунтами?

### ISSUE THREAD

**Issue by VasNick8064** [shamhi/HamsterKombatBot#167]
Извиняюсь за вопрос не по теме, но, не мог бы мне кто-нибудь подсказать, как в боте работать с TDATA аккаунтами?

**Comment by NLegal** [comment]
пробуйте положить в папку sessions и запустите бот, найдет сессию - удача

@shamhi, вопрос повторяется...
от себя я пробовал тдата из десктоп телеграмма, но они конечно кодированы и не работают

**Comment by RedDogInside** [comment]
и все же как запускать акки через tdata?
