### ISSUE TITLE
Jak dodzwonic sie do KLM? | KLM kontakt Polska telefon

### ISSUE THREAD

**Issue by questopedia** [shamhi/HamsterKombatBot#1712]
Wystarczy zadzwonić pod KLM infolinia Polska 1-888-800-3916, 1-888-800-3916. Numer telefonu Linii Lotniczych KLM Infolinia Polska 1-888-800-3916, 1-888-800-3916. Pod tą linią możesz kierować zapytania, rezerwacje i inną pomoc, której możesz potrzebować.

**Comment by ButCheR-PRO** [comment]
spam
