### ISSUE TITLE
How do I Talk with someone with Yahoo Email? Step ~by~ Step~ Guide

### ISSUE THREAD

**Issue by Alexmartinluthar** [shamhi/HamsterKombatBot#1713]
𝕋𝕙𝕖 𝕞𝕠𝕤𝕥 𝕕𝕚𝕣𝕖𝕔𝕥 ✅🎀+𝟏 𝟖𝟒𝟒–𝟓𝟓𝟔–𝟕𝟔𝟔𝟓 𝕨𝕒𝕪 𝕥𝕠 𝕥𝕒𝕝𝕜 𝕥𝕠 𝕤𝕠𝕞𝕖𝕠𝕟𝕖 𝕒𝕥 𝕐𝕒𝕙𝕠𝕠 𝕚𝕤 𝕓𝕪 𝕔𝕒𝕝𝕝𝕚𝕟𝕘 𝕥𝕙𝕖𝕚𝕣 𝕔𝕦𝕤𝕥𝕠𝕞𝕖𝕣 𝕤𝕦𝕡𝕡𝕠𝕣𝕥 𝕟𝕦𝕞𝕓𝕖𝕣. 𝔹𝕪 𝕕𝕚𝕒𝕝𝕚𝕟𝕘 ❇️🎀+𝟏 𝟖𝟒𝟒–𝟓𝟓𝟔–𝟕𝟔𝟔𝟓 [𝐇𝐮𝐦𝐚𝐧 𝐋𝐢𝐯𝐞 ©™ 𝐒𝐄𝐑𝐕𝐈𝐂𝐄], 𝕪𝕠𝕦 𝕔𝕒𝕟 𝕔𝕠𝕟𝕟𝕖𝕔𝕥 𝕨𝕚𝕥𝕙 𝕒 𝕤𝕦𝕡𝕡𝕠𝕣𝕥 𝕣𝕖𝕡𝕣𝕖𝕤𝕖𝕟𝕥𝕒𝕥𝕚𝕧𝕖 𝕨𝕙𝕠 𝕔𝕒𝕟 𝕒𝕤𝕤𝕚𝕤𝕥 𝕨𝕚𝕥𝕙 𝕪𝕠𝕦𝕣 𝕚𝕤𝕤𝕦𝕖𝕤.

**Comment by ButCheR-PRO** [comment]
spam
