### ISSUE TITLE
Ошибка при получении ключа minigame

### ISSUE THREAD

**Issue by kirajok** [shamhi/HamsterKombatBot#1714]
![image](https://github.com/user-attachments/assets/73f828c8-ea81-4ef0-b963-22adafe3b4ba)
Устанавливал проект на чистую, переустановил но сейчас игра в кд, позже посмотрю

**Comment by kirajok** [comment]
Попробовал еще раз такая же ошибка

**Comment by kirajok** [comment]
Ещё раз переустановил, пробовал уже после перерыва на ночь - та же ошибка

**Comment by crispan2** [comment]
Пофиксил?
