### ISSUE TITLE
[Ошибка] 500 - Internal Server Error. Что за ошибка и как ее исправить?

### ISSUE THREAD

**Issue by UNLUCKYxx** [shamhi/HamsterKombatBot#172]
![image](https://github.com/shamhi/HamsterKombatBot/assets/171423760/4802caa6-a983-4482-a541-03419145eb15)

**Comment by XPacL** [comment]
Это возможно хомяк лежит сейчас. При покупке карточек тоже ошибка. В телеге жалуются что приложение начало глючить у многих

**Comment by dinrise** [comment]
Судя по сайту downdetector, интернет у половины европы лег

**Comment by XPacL** [comment]
ChatGPT тоже лежит. Ждём новостей

**Comment by XPacL** [comment]
Хомяк воскрес. Проблема ушла
