### ISSUE TITLE
Error Extra inputs are not permitted

### ISSUE THREAD

**Issue by viperblck** [shamhi/HamsterKombatBot#1729]
I download latest version and now I get this error after lanching:

pydantic_core._pydantic_core.ValidationError: 1 validation error for Settings
apply_daily_turbo
  Extra inputs are not permitted [type=extra_forbidden, input_value='True', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/extra_forbidden

How to solve?

**Comment by Openyoueyes** [comment]
I have the same problem

**Comment by ButCheR-PRO** [comment]
Same
