### ISSUE TITLE
[Question] How can i intercept telegram webapps requests

### ISSUE THREAD

**Issue by iPurya** [shamhi/HamsterKombatBot#174]
Hi dear,
can i ask you how did you mitm telegram webapp ?
how can i intercept telegram webapps requests using burpsuite for example ?

Привет, дорогой,
могу я спросить, как вы перехватили трафик веб-приложения Telegram?
как я могу перехватывать запросы веб-приложений Telegram с помощью BurpSuite, например?

**Comment by ITProjectDmitry** [comment]
@iPurya Привет. Почитал твой вопрос  и задумался. мне кажется что ни как.  по моим ощущениям все кто используют данный "скрипт" стали жертвами.  я не исключаю тот факт что пользователи данного "скрипта-помощника" стали жертвами своих аккаунтов. себя я из этого списка не исключаю)))  ну так вопрос к автору?  что будет дальше? надо наплевать на авторов идей и не только. надо задуматься над безопасностью наших данных.   Всем Добра!

**Comment by ITProjectDmitry** [comment]
люблю гит!

**Comment by ExtbhiteEAS** [comment]
> все кто используют данный "скрипт" стали жертвами. я не исключаю тот факт что пользователи данного "скрипта-помощника" стали жертвами своих аккаунтов. себя я из этого списка не исключаю)))

В каком смысле стали "жертвами"? Если речь про аккаунты, то аккаунт никто не украдёт, тем более это всё делалось на pyrogram да и с сессией аккаунта баловаться может только сам владелец аккаунта.

**Comment by ButCheR-PRO** [comment]
> все кто используют данный "скрипт" стали жертвами

Глупости говоришь, Дмитрий. Чекни код, какие библиотеки и запросы используются и всё поймёшь. В чём заключается жертвенность? И что здесь небезопасного? Приведи пример небезопасного кода.
