### ISSUE TITLE
option 2 no answer

### ISSUE THREAD

**Issue by GiuseppeRazzetto** [shamhi/HamsterKombatBot#175]
because when I choose option 2 the bot stays stuck and does not show any error

![imagen_2024-06-04_201150223](https://github.com/shamhi/HamsterKombatBot/assets/156551088/076f5fba-bd81-42cb-8718-89238fb2055d)

**Comment by shamhi** [comment]
synchronize your system time

**Comment by GiuseppeRazzetto** [comment]
thanks
