### ISSUE TITLE
[Ошибки] Версия Python и настройки в .env - Помогите разобраться

### ISSUE THREAD

**Issue by Flanor2** [shamhi/HamsterKombatBot#176]
Не понимаю что от меня требует. Питон 3.11, инсталл тыкал, в файле всё указал
![image](https://github.com/shamhi/HamsterKombatBot/assets/171763048/99d79cc3-e1c2-48eb-b5c5-41294714085b)

**Comment by Flanor2** [comment]
Поставил 3.10 инсталл начал адекватно работать,но при запуске стар появилось это![image](https://github.com/shamhi/HamsterKombatBot/assets/171763048/71b86de3-0b20-4f5e-97b6-60faba21b1ac)

**Comment by XPacL** [comment]
.env правильно настрой

**Comment by ButCheR-PRO** [comment]
В .env пропиши например: 
```
SLEEP_BY_MIN_ENERGY=[1800,2400]
RANDOM_TAPS_COUNT=[10,50]
SLEEP_BETWEEN_TAP=[10,25]
```

**Comment by Flanor2** [comment]
> В .env пропиши например: 
> 
> ```
> 
> SLEEP_BY_MIN_ENERGY=[1800,2400]
> 
> RANDOM_TAPS_COUNT=[50,200]
> 
> SLEEP_BETWEEN_TAP=[10,25]
> 
> ```
> 
> Ну и лучше использовать python-3.10.9 [https://www.python.org/downloads/release/python-3109/](url)

Дело было в версии питона, разобрался. Сябки
