### ISSUE TITLE
[Вопрос] После последних коммитов упало количество заработка от тапов

### ISSUE THREAD

**Issue by gg-script** [shamhi/HamsterKombatBot#179]
### Описание
После последних коммитов (начиная с Change connection logic) и далее очень сильно упал заработок от тапов (до этого за итерацию было 165000), а сейчас 10000.

### ENV
`API_ID=
API_HASH=

MIN_AVAILABLE_ENERGY=150
SLEEP_BY_MIN_ENERGY=[500,1350]

ADD_TAPS_ON_TURBO=3000

AUTO_UPGRADE=True
MAX_LEVEL=20

BALANCE_TO_SAVE=1
UPGRADES_COUNT=7

APPLY_DAILY_ENERGY=True
APPLY_DAILY_TURBO=True

RANDOM_TAPS_COUNT=[150, 600]
SLEEP_BETWEEN_TAP=[1, 10]
USE_PROXY_FROM_FILE=False`

**Comment by ButCheR-PRO** [comment]
Попробуй поставить
```
SLEEP_BY_MIN_ENERGY=[1800,2400]
RANDOM_TAPS_COUNT=[50,200]
SLEEP_BETWEEN_TAP=[10,25]
```

**Comment by gg-script** [comment]
Привет! Благодарю, попробую.

**Comment by ButCheR-PRO** [comment]
Похожая ситуация? https://github.com/shamhi/HamsterKombatBot/issues/116

**Comment by gg-script** [comment]
да, твой конфиг не помогает
