### ISSUE TITLE
Unknown error while buying Upgrade: 400, message='Bad Request'

### ISSUE THREAD

**Issue by tkmynrg** [shamhi/HamsterKombatBot#18]
2024-05-06 07:00:49 | ERROR   | Unknown error while buying Upgrade: 400, message='Bad Request', url=URL('https://api.hamsterkombat.io/clicker/buy-upgrade')

**Comment by LifeViwer** [comment]
+1
api url change? Need fix pliss
![image](https://github.com/shamhi/HamsterKombatBot/assets/36803375/7f423045-444b-4acd-be6e-644a98616dc7)

**Comment by Ridanil** [comment]
it's error occures when "bot" bought all available perks and goes to the "special" tab -> "sold cards" and tries to buy them

**Comment by Ridanil** [comment]
решено добавлением в конфиг - **IGNORED_UPGRADES: list[str] = ['save_hamsters_from_drowning']**
и в tapper строка 306 - if balance > price and level <= settings.MAX_LEVEL **and upgrade_id not in settings.IGNORED_UPGRADES:**

**Comment by DamAlyuk** [comment]
Добавляем в bot/config/config.py 
IGNORED_UPGRADES: list[str] = ['save_hamsters_from_drowning']
Добавляем в not/.env в конце
IGNORED_UPGRADES=
Добавляем в bot/core/tapper.py то что написано в комментарии выше
Запускаем!
