### ISSUE TITLE
 Unknown error: list index out of range

### ISSUE THREAD

**Issue by Daniilvergiles** [shamhi/HamsterKombatBot#180]
![Снимок экрана (1)](https://github.com/shamhi/HamsterKombatBot/assets/171806741/f28059f1-5770-43f0-b823-69e033f9ec89)
Как исправить

**Comment by Daniilvergiles** [comment]
![Снимок экрана (3)](https://github.com/shamhi/HamsterKombatBot/assets/171806741/1a63ef19-33cf-44b0-a009-372940f781cc)

**Comment by Daniilvergiles** [comment]
ок

**Comment by ButCheR-PRO** [comment]
Дубликат https://github.com/shamhi/HamsterKombatBot/issues/153

**Comment by Azamir69** [comment]
> Ха, API не обязательно было палить всем))) Настрой .env согласно ридми, в квадратных скобках должно быть два числа через запятую

какие ?

**Comment by ButCheR-PRO** [comment]
> SLEEP_BY_MIN_ENERGY=[400]

Тут ошибка. Поставь:
`SLEEP_BY_MIN_ENERGY=[1800,2400]`
