### ISSUE TITLE
Unknown error: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by xdxdxdxdxdxxdxd** [shamhi/HamsterKombatBot#181]
2024-06-05 15:26:32 | ERROR    | 500 - п | Unknown error: 'NoneType' object has no attribute 'close'
2024-06-05 15:26:35 | ERROR    | 295 - п | Unknown error while Tapping: Session is closed | Response text: ...
![1](https://github.com/shamhi/HamsterKombatBot/assets/120827285/78ab384c-2bda-4468-87c9-653f97a2e44a)

**Comment by ATAMAH161** [comment]
> 2024-06-05 15:26:32 | ERROR | 500 - п | Unknown error: 'NoneType' object has no attribute 'close' 2024-06-05 15:26:35 | ERROR | 295 - п | Unknown error while Tapping: Session is closed | Response text: ... ![1](https://private-user-images.githubusercontent.com/120827285/336835544-78ab384c-2bda-4468-87c9-653f97a2e44a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc1OTE0OTEsIm5iZiI6MTcxNzU5MTE5MSwicGF0aCI6Ii8xMjA4MjcyODUvMzM2ODM1NTQ0LTc4YWIzODRjLTJiZGEtNDQ2OC04N2M5LTY1M2Y5N2EyZTQ0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNVQxMjM5NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWNkZmNkM2I0M2NiOWY5NTkwYjA2OGU4MmY2YmMwNDU5MGE5OWFmZjA2MDcyZGQ2Zjg0MjlhM2M4YzVlZmU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TYpqP_-iIJ3pOTy0nTtKyufmZzHB9xNoow0hPHnpofI)

Такая же тема

**Comment by gg-script** [comment]
fixed in https://github.com/shamhi/HamsterKombatBot/commit/36afff8bbd2feb2262956b37f4709096b578911b
