### ISSUE TITLE
Unknown error while Tapping: 500, message='Internal Server Error'

### ISSUE THREAD

**Issue by Hoochizoid** [shamhi/HamsterKombatBot#184]
> 2024-06-05 22:07:24 | INFO     | 510 - Sleep 24s
> 2024-06-05 22:07:50 | ERROR    | 295 - Home | Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...
> 2024-06-05 22:07:55 | ERROR    | 295 - Home | Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...
> 2024-06-05 22:08:00 | ERROR    | 295 - Home | Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...
> 2024-06-05 22:08:05 | ERROR    | 295 - Home | Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...
> 2024-06-05 22:08:10 | ERROR    | 295 - Home | Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...
> 2024-06-05 22:08:15 | ERROR    | 295 - Home | Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...
> 2024-06-05 22:08:19 | SUCCESS  | 399 - Home | Successful tapped! | Balance: 2,759,333 (+11,333) | Total: 51,982,333

Такое поведение скрипта норма или все-таки в чем то проблема? :)

**Comment by Vadoc1337** [comment]
<img width="559" alt="image" src="https://github.com/shamhi/HamsterKombatBot/assets/121457828/36a38b72-23b5-476c-8272-41c11a4830ae">
У меня вот так, но он какое-то время работает(мб час мб меньше, все апает кликает, несмотря на ошибки, потом отваливается :)

**Comment by shamhi** [comment]
видишь, initDataRaw: null, значит проблема с сессией

**Comment by Hoochizoid** [comment]
> видишь, initDataRaw: null, значит проблема с сессией

предполагаю, на телефоне хомяк тоде был запущен... на данный момент вроде работает стабильно, но иногда вот такая ошибка все таки проскакивает: 2024-06-05 22:54:32 | ERROR    | 221 - Home | Unknown error while Apply BoostFullAvailableTaps Boost: 400, message='Bad Request', url=URL('https://api.hamsterkombat.io/clicker/buy-boost') | Response text: {"error_code":"BOOST_COOLDOWN","error_message":"Boost BoostFullAvailableTaps on cooldown 3491 seconds"}...

**Comment by Vadoc1337** [comment]
> видишь, initDataRaw: null, значит проблема с сессией

я кажется понял в чем трабл, я добавил новую сессию, но не удалил старые, вот ошибки и лезут

**Comment by Vadoc1337** [comment]
> > 2024-06-05 22:07:24 | INFO     | 510 - Sleep 24s
> > 2024-06-05 22:07:50 | ERROR    | 295 - Home | Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...
> > 2024-06-05 22:07:55 | ERROR    | 295 - Home | Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...
> > 2024-06-05 22:08:00 | ERROR    | 295 - Home | Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...
> > 2024-06-05 22:08:05 | ERROR    | 295 - Home | Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...
> > 2024-06-05 22:08:10 | ERROR    | 295 - Home | Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...
> > 2024-06-05 22:08:15 | ERROR    | 295 - Home | Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_...
> > 2024-06-05 22:08:19 | SUCCESS  | 399 - Home | Successful tapped! | Balance: 2,759,333 (+11,333) | Total: 51,982,333
> 
> Такое поведение скрипта норма или все-таки в чем то проблема? :)

теперь тоже вначале выскакивает 😂. Но вроде все равно покупает там все как надо, так что можно сказать что работает ботецкий, автору респект😁

**Comment by ButCheR-PRO** [comment]
ТАк же эти ошибки могут быть связаны: https://github.com/shamhi/HamsterKombatBot/issues/189
