### ISSUE TITLE
Ошибки при создание сессии

### ISSUE THREAD

**Issue by DeeArt63** [shamhi/HamsterKombatBot#185]
Обновил бота начал заново устанавливать сессию, стал выдавать такую ошибку. С чем может быть проблема? 
![image](https://github.com/shamhi/HamsterKombatBot/assets/171515301/4c049272-6ded-4aa2-9d76-12c71980fce3)

**Comment by Scientianor** [comment]
Сейчас перебои с ботом, поэтому ошибки. Запусти, когда свободно будет открываться бот в самом телеграм

**Comment by shamhi** [comment]
нет, проблема на твоей стороне, синхронизируй системное время

**Comment by Scientianor** [comment]
> нет, проблема на твоей стороне, синхронизируй системное время

Это из-за багов. Сейчас хомяк на все запросы 500 возвращает, в том числе синхронизацию. У меня мои самописные полетели из-за этого

**Comment by shamhi** [comment]
> > нет, проблема на твоей стороне, синхронизируй системное время
> 
> Это из-за багов. Сейчас хомяк на все запросы 500 возвращает, в том числе синхронизацию. У меня мои самописные полетели из-за этого

при создании сессии хамстер не имеет никакого отношения, так что не говори того, чего не знаешь

**Comment by Scientianor** [comment]
> > > нет, проблема на твоей стороне, синхронизируй системное время
> > 
> > 
> > Это из-за багов. Сейчас хомяк на все запросы 500 возвращает, в том числе синхронизацию. У меня мои самописные полетели из-за этого
> 
> при создании сессии, хамстер не имеет никакого отношения, так что не говори того, чего не знаешь

Ну да, не в хомяке дело 🤡 
![IMG_6694](https://github.com/shamhi/HamsterKombatBot/assets/130798806/ca8310f8-07ae-4ec0-b6c0-2dd473dfa68f)

**Comment by DeeArt63** [comment]
Всем спасибо! Да синхронизация времени помогла. По какой-то причине сбилось время на ПК.

**Comment by shmelrad** [comment]
> Ну да, не в хомяке дело

чел, какое отношение имеет вход в тг и хомяк? зачем бубнить про то, в чем не разбираешься
