### ISSUE TITLE
Ошибка при создании сессии

### ISSUE THREAD

**Issue by DeeArt63** [shamhi/HamsterKombatBot#186]
После переустановки на новую версию бота, выходят ошибки при создании токена! В чём может быть проблема?
![image](https://github.com/shamhi/HamsterKombatBot/assets/171515301/ec54e891-c70d-48f7-a736-7332b55c3845)

**Comment by VasNick8064** [comment]
Синхронизируй время

**Comment by ButCheR-PRO** [comment]
Дубликат. Проблема уже решена здесь: https://github.com/shamhi/HamsterKombatBot/issues/185
