### ISSUE TITLE
Unknown error while Tapping: 503, message='Service Unavailable: Back-end server is at capacity'

### ISSUE THREAD

**Issue by NLegal** [shamhi/HamsterKombatBot#187]
Unknown error while Tapping: 503, message='Service Unavailable: Back-end server is at capacity', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: ...

s_wait? :)

**Comment by ButCheR-PRO** [comment]
Эти ошибки связаны: https://github.com/shamhi/HamsterKombatBot/issues/189
