### ISSUE TITLE
Есть ли способ сделать так, чтобы пользователи ботов могли использовать только функцию автоматического обновления?

### ISSUE THREAD

**Issue by AyPewAre** [shamhi/HamsterKombatBot#188]
Я использую этого бота уже несколько часов, но функция автообновления не работает, могу ли я использовать этого бота только для автообновления?

**Comment by ButCheR-PRO** [comment]
Обновления чего?

**Comment by Malg1nov** [comment]
> Обновления чего? Не понял, что нужно обновить? И что конкретно не работает и какие ошибки пишет?

Подскажите как бота обновить на новую версию ?? скачиваю снова архив, запускаю все равно пишет что нужно обновить на последнюю версию.
