### ISSUE TITLE
106 - Unknown error while getting Access Token: 500, message='Internal Server Error'

### ISSUE THREAD

**Issue by faizahmaddae** [shamhi/HamsterKombatBot#189]
Unknown error while getting Access Token: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/auth/auth-by-telegram-webapp') | Response text: Couchbase error! Method=query(q=
      select auth_user.* from auth_user
      where telegramUserId = $telegramUserId
      limi...

**Comment by gg-script** [comment]
также

**Comment by F0RQU1N** [comment]
same

**Comment by AnhAnhii** [comment]
Same

**Comment by Arsiprog** [comment]
2024-06-06 06:06:53 | ERROR    | 106 - hello | Unknown error while getting Access Token: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/auth/auth-by-telegram-webapp') | Response text: Couchbase error! Method=query(q=
      select auth_user.* from auth_user
      where telegramUserId = $telegramUserId
      limi...

**Comment by Flanor2** [comment]
Same

**Comment by NLegal** [comment]
dup: https://github.com/shamhi/HamsterKombatBot/issues/190

**Comment by ExtbhiteEAS** [comment]
> dup: #190

That's not dupe, the number of this issue is #189, look better when you see some of "duplicate".

**Comment by XPacL** [comment]
Разрабы хомяка пытаются побрить нас?

**Comment by glorySyntax** [comment]
> Разрабы хомяка пытаются побрить нас?

Походу

**Comment by glorySyntax** [comment]
Да не, родившихся в СНГ они точно не побреют)

**Comment by XPacL** [comment]
В телеге пишут что многие и с телефона зайти не могут. Хомяк опять лёг в общем. Ждём.

**Comment by sonnguyenHT** [comment]
the 500 status code it's seem the problem is on side of hamsterkombat or the query is not available with the code right now anymore

**Comment by farcray57** [comment]
на телефоне вообще пишет "Unable to login. Please, reload mini app"

**Comment by Hoochizoid** [comment]
такая же беда

**Comment by DeeArt63** [comment]
Тоже перестал работать похоже веб версия накрылась тазом(

**Comment by goncharovnr** [comment]
same

**Comment by A-platinum** [comment]
Same

**Comment by Typ3DHard** [comment]
Надейтесь, что просто проблема на стороне хоста сайта и всё. Не думаю, что веб версия будет закрыта

**Comment by ButCheR-PRO** [comment]
Ну у меня тоже сегодня с утра, с телефона заходит нормально. А через скрипт ошибка.

**Comment by Typ3DHard** [comment]
![Screenshot_2024-06-06-12-34-56-47_948cd9899890cbd5c2798760b2b95377.jpg](https://github.com/shamhi/HamsterKombatBot/assets/88327933/a362bf83-d8bb-40d9-9ba6-368f7e12f169)

Ребят, забейте
Я уверен там тех обслуживание идёт жёское. Думаю к вечеру всё опять работать начнёт. Затяните пояса

**Comment by A-platinum** [comment]
Эта картинка с тех работами у рефералов с ночи, проблем с ботом тогда еще не было

**Comment by themiralay** [comment]
Same issue for me

**Comment by Desamod** [comment]
Кто-нибудь проверял на новых аккаунтах, пускает ли сейчас в хомяка?

**Comment by ButCheR-PRO** [comment]
> Кто-нибудь проверял на новых аккаунтах, пускает ли сейчас в хомяка?

У меня на всех старых аккаунтах нормально входит с мбоилки в хомяка. Но скрипт не работает.

**Comment by UltiGamer5G** [comment]
same

**Comment by Mik-chan** [comment]
> У меня на всех старых аккаунтах нормально входит с телефона в хомяка. Но скрипт не работает.

Это потому что токен сохраняется в клиенте между заходами. Если под чистую переустановить клиент телеграма, а потом попытаться зайти в хомяка, он попытается вызвать этот злосчастный метод, что приведет к этой самой ошибке. У меня, например, по этой причине до сих пор работает веб версия, однако, прекращает работать, если вручную пойти и очистить localStorage браузера. Я думаю, это косяк на стороне авторов хомяка, и они его починят, как только заметят, что новые игроки не могут больше зайти. Надо просто ждать.

**Comment by zolotarevinc** [comment]
такая же дичь, кто знает как фиксить

**Comment by zolotarevinc** [comment]
Пофиксили вроде у меня заработало

**Comment by A-platinum** [comment]
С такой ошибкой кто-то сталкивался?
2024-06-06 11:34:56 | ERROR    | 295 - Polina Fedorovna | Unknown error while Tapping: Session is closed | Response text: ...

**Comment by lolyinseo** [comment]
> > У меня на всех старых аккаунтах нормально входит с телефона в хомяка. Но скрипт не работает.
> 
> Это потому что токен сохраняется в клиенте между заходами. Если под чистую переустановить клиент телеграма, а потом попытаться зайти в хомяка, он попытается вызвать этот злосчастный метод, что приведет к этой самой ошибке. У меня, например, по этой причине до сих пор работает веб версия, однако, прекращает работать, если вручную пойти и очистить localStorage браузера. Я думаю, это косяк на стороне авторов хомяка, и они его починят, как только заметят, что новые игроки не могут больше зайти. Надо просто ждать.

Тк тут каждый раз при запуске или при time() - access_token_created_time >= 3600 оно пытается получить новый токен. Зачем? Для чего? Получить бан? Делать это нужно ТОЛЬКО если токен истек. В форках это уже переписали и ушли далеко дальше и хранят токены, тут нет (дичь). Форки работают. В форках уже и задания дневные реализуют(подгружаются с веба соот json), и настройки сессии в json хранят, а не в sqlite. Как же не охота самому писать ))

**Comment by Mik-chan** [comment]
> Тк тут каждый раз при запуске или при time() - access_token_created_time >= 3600 оно пытается получить новый токен. Зачем? Для чего? Получить бан? Делать это нужно ТОЛЬКО если токен истек. В форках это уже переписали и ушли далеко дальше и хранят токены, тут нет (дичь). Форки работают. В форках уже и задания дневные реализуют(подгружаются с веба соот json), и настройки сессии в json хранят, а не в sqlite. Как же не охота самому писать ))

Я не понимаю, какие ко мне тут претензии, но ладно

**Comment by zuevav** [comment]
Завелся бот, значит на серверах проблемы были.

**Comment by lolyinseo** [comment]
> > Тк тут каждый раз при запуске или при time() - access_token_created_time >= 3600 оно пытается получить новый токен. Зачем? Для чего? Получить бан? Делать это нужно ТОЛЬКО если токен истек. В форках это уже переписали и ушли далеко дальше и хранят токены, тут нет (дичь). Форки работают. В форках уже и задания дневные реализуют(подгружаются с веба соот json), и настройки сессии в json хранят, а не в sqlite. Как же не охота самому писать ))
> 
> Я не понимаю, какие ко мне тут претензии, но ладно

никаких, мысли вслух
рекомендую обратить внимание на https://github.com/AnisovAleksey/HamsterKombatBot

**Comment by ButCheR-PRO** [comment]
> > > Тк тут каждый раз при запуске или при time() - access_token_created_time >= 3600 оно пытается получить новый токен. Зачем? Для чего? Получить бан? Делать это нужно ТОЛЬКО если токен истек. В форках это уже переписали и ушли далеко дальше и хранят токены, тут нет (дичь). Форки работают. В форках уже и задания дневные реализуют(подгружаются с веба соот json), и настройки сессии в json хранят, а не в sqlite. Как же не охота самому писать ))
> > 
> > 
> > Я не понимаю, какие ко мне тут претензии, но ладно
> 
> никаких, мысли вслух рекомендую обратить внимание на https://github.com/AnisovAleksey/HamsterKombatBot

Это ты к @shamhi хотел обратиться?

**Comment by IDMaxPower** [comment]
> никаких, мысли вслух рекомендую обратить внимание на https://github.com/AnisovAleksey/HamsterKombatBot
Не знаю, пробовал поставить этот форк, в итоге не дает зайти даже в тг аккаунт, выдает ошибку что не задал имя, хотя имя сессии указываю

**Comment by CleFerMy** [comment]
Сейчас всё работает, гуд

**Comment by ButCheR-PRO** [comment]
Как обычно, проблема с 106 - Unknown error while getting Access Token: 500, message='Internal Server Error'
решилась сама по себе. Нужно было просто подождать. Это на стороне сервера игры.

**Comment by ButCheR-PRO** [comment]
В данный момент снова наблюдаются те же ошибки, но это из-за наплыва людей которые кинулись заходить и собирать комбо. Ждём.

**Comment by ExtbhiteEAS** [comment]
> > В данный момент снова наблюдаются те же ошибки, но это из-за наплыва людей которые кинулись заходить и собирать комбо. Ждём.
> 
> Шеф, а подскажи где token или tg auth достать?

Случаем, не этим форком пользуешься? https://github.com/AnisovAleksey/HamsterKombatBot
Я и сам не знаю, но тут лучше видимо у автора форка спрашивать.

**Comment by n1tr0g3n4ik** [comment]
> лол, это серверная ошибка коуч дб, а не какая-та клиентская (forbidden) есть еще 503 ошибки 'Service Unavailable: Back-end server is at capacity'
> 
> я куда более уверен, что их сервера под высокой нагрузкой и они вовсе не выдерживают, тк спустя какое-то время аккаунты снова в строю

 Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
 
 такое еще появилось)

**Comment by Sanek63** [comment]
> > лол, это серверная ошибка коуч дб, а не какая-та клиентская (forbidden) есть еще 503 ошибки 'Service Unavailable: Back-end server is at capacity'
> > я куда более уверен, что их сервера под высокой нагрузкой и они вовсе не выдерживают, тк спустя какое-то время аккаунты снова в строю
> 
> Unknown error: cannot access local variable 'available_energy' where it is not associated with a value
> 
> такое еще появилось) но это возможно из-за того что к их серверу подключиться не может

ну да, частенько я наблюдаю нестабильное поведение, а потом все возвращается в норму)
надеюсь, не побреют нас xD

**Comment by Rofl1234** [comment]
Всех приветствую. У вас заработал софт?

**Comment by A-platinum** [comment]
> Всех приветствую. У вас заработал софт?

С горем по полам, из 15 сессий 1-2 простреливают

**Comment by Rofl1234** [comment]
Боюсь как бы не забанили мой аккаунт. На аккаунте на котором крутил через софт вылазит ошибка Unable to login. Please reolad mini app. На рефералах на которых ничего не крутил ошибка Unable to sync

**Comment by XPacL** [comment]
> Боюсь как бы не забанили мой аккаунт. На аккаунте на котором крутил через софт вылазит ошибка Unable to login. Please reolad mini app. На рефералах на которых ничего не крутил ошибка Unable to sync

Не бойся, у многих даже кто не пользуется софтом такие проблемы. Это сервер хомяка устал.

**Comment by Rofl1234** [comment]
Всем еще раз привет. Никак не могу войти в хомяка уже третий день после фикса серверов. Софт заходит в хомяка и собирает прибыль, но с телефона никак не могу зайти, Request error. Пробовал завершать все сессии в тг, пытался с компа заходить, с разных устройств, но ничего не помогает. Сталкивался кто с такой проблемой?

**Comment by shamhi** [comment]
> Всем еще раз привет. Никак не могу войти в хомяка уже третий день после фикса серверов. Софт заходит в хомяка и собирает прибыль, но с телефона никак не могу зайти, Request error. Пробовал завершать все сессии в тг, пытался с компа заходить, с разных устройств, но ничего не помогает. Сталкивался кто с такой проблемой?

VPN пробовал?

**Comment by Rofl1234** [comment]
не помог

**Comment by Rofl1234** [comment]
с разными впнами попробовал все равно не получается зайти

**Comment by Sanek63** [comment]
> Всем еще раз привет. Никак не могу войти в хомяка уже третий день после фикса серверов. Софт заходит в хомяка и собирает прибыль, но с телефона никак не могу зайти, Request error. Пробовал завершать все сессии в тг, пытался с компа заходить, с разных устройств, но ничего не помогает. Сталкивался кто с такой проблемой?

что пишет ошибка Request Error, пиши больше конкретики. Если ошибка "SyncError", то выруби бота и подожди 5 минут, прежде чем заходить. Если, другая ошибка, то напиши ее в чат. Мы не ванги чтобы предсказать твою ошибку, почему не заходит

**Comment by Sanek63** [comment]
и смысла в впн-ах нету, используй обычный прокси, он дешевле и надежнее в текущем случае.
Или ты от кого-то шифруешь трафик что-ли? Тебе надо поменять IP и локацию, прокси спокойно выполняет свою задачу в этом плане

**Comment by Rofl1234** [comment]
![IMG_5509](https://github.com/shamhi/HamsterKombatBot/assets/171097650/945fb406-5628-49a3-94dd-d77d407ae096)

**Comment by nvquangil** [comment]
(venv) D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main>python main.py
Traceback (most recent call last):
  File "D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main\bot\utils\__init__.py", line 8, in <module>
    if not os.path.exists(path='sessions'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments

No run

**Comment by Sanek63** [comment]
> (venv) D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main>python main.py Traceback (most recent call last): File "D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main\main.py", line 4, in from bot.utils.launcher import process File "D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main\bot\utils__init__.py", line 8, in if not os.path.exists(path='sessions'): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: nt._path_exists() takes no keyword arguments
> 
> No run

у тебя же ясно написано, что функция не принимает именованные аргументы. Ты документацию к программе читал, прежде чем запускать программу???

<img width="542" alt="Снимок экрана 2024-06-23 в 16 11 02" src="https://github.com/shamhi/HamsterKombatBot/assets/46131081/aef32788-13e0-4082-9963-73d33772524c">

**Comment by Sanek63** [comment]
> (venv) D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main>python main.py Traceback (most recent call last): File "D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main\main.py", line 4, in from bot.utils.launcher import process File "D:\GMP\tele\HamsterKombatBot-main\HamsterKombatBot-main\bot\utils__init__.py", line 8, in if not os.path.exists(path='sessions'): ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: nt._path_exists() takes no keyword arguments
> 
> No run

ты даже ничего не сказал, с какой версии питона запускаешь. Мы тут как тебе поможем, если ты не в контексте проблемы все описал?

**Comment by nvquangil** [comment]
I user Python 3.12
