### ISSUE TITLE
 Unknown error while getting Access Token: 500, message='Internal Server Error'

### ISSUE THREAD

**Issue by yourbee03** [shamhi/HamsterKombatBot#190]
Unknown error while getting Access Token: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/auth/auth-by-telegram-webapp') | Response text: Couchbase error! Method=query(q=
      select auth_user.* from auth_user
      where telegramUserId = $telegramUserId
      limi...

**Comment by NLegal** [comment]
same... any idea?

**Comment by yourbee03** [comment]
> same... any idea?

im tryng to re-install but still same

**Comment by XPacL** [comment]
Хомяк перестал работать через API? Что делать братцы?

**Comment by BlackZsh** [comment]
me too   plz deal soon. tks

**Comment by MGTV01** [comment]
> خطای ناشناخته هنگام دریافت رمز دسترسی: 500، message='خطای سرور داخلی'، url=URL(' https://api.hamsterkombat.io/auth/auth-by-telegram-webapp ') | متن پاسخ: خطای Couchbase! Method=query(q= auth_user.* را از auth_user انتخاب کنید که telegramUserId = $telegramUserId limi...

How to fix this error??

**Comment by ButCheR-PRO** [comment]
dupe https://github.com/shamhi/HamsterKombatBot/issues/189
