### ISSUE TITLE
New ISSUE! PLEASE CHECK THIS OUT! NEED HEELP

### ISSUE THREAD

**Issue by akhi305** [shamhi/HamsterKombatBot#191]
![2024-06-06_07-37-29](https://github.com/shamhi/HamsterKombatBot/assets/18718154/5353cd81-d325-4d2b-9ab5-20dce97423cc)

**Comment by XPacL** [comment]
Dupe https://github.com/shamhi/HamsterKombatBot/issues/189

**Comment by A-platinum** [comment]
The same problem after last update tapper.py

**Comment by ButCheR-PRO** [comment]
Dupe https://github.com/shamhi/HamsterKombatBot/issues/189
