### ISSUE TITLE
[Request] New feature: MAX_UPGRADE_PRICE - upgrading card only under limit price

### ISSUE THREAD

**Issue by ZeroParadoxHome** [shamhi/HamsterKombatBot#192]
Hello sir, can you add a variable for upgrading card only under X price?

for example UPGRADE_CARD_UNDER: 1000000

In that case script only upgrade cards under 1 million coins.

Or even Overwrite_Upgrade_Level: True/False for ignoring the max level upgrade for cards under 1 million

**Comment by ButCheR-PRO** [comment]
Personally, I also added:
| **MAX_UPGRADE_PRICE* | Maximum purchase price for an upgrade _(eg 1000000)_ |
If, for example, you set MAX_LEVEL=20, then cards from the Specials section will be very expensive starting from lvl 12, and cards from the Markets section even at lvl 16 cost less than 500k, so if you want to first improve all inexpensive cards to level 20, spending on each no more than 1M, for example, you can manually limit it in the config with the MAX_UPGRADE_PRICE parameter. If you don't want to limit, set the value 99999999 for example :)

in bot/config/config.py, for example, after 16 deadlines we will add:
`    MAX_UPGRADE_PRICE: int = 10000000`

Let's add just one line to the code bot/core/tapper.py (I have line 445):

```
                                            and profit > 0
                                            and price <= settings.MAX_UPGRADE_PRICE
                                            and price < max_price_limit):
```
and in the .env file add:
`MAX_UPGRADE_PRICE=1000000`

Ideally, add this to .env-example and add a description of this parameter to README.md.

**Comment by ZeroParadoxHome** [comment]
Wow that explanation and guidance was awesome!
I am going to try it out

By the way, I am facing this problem since few hours ago
Do you have any idea?

![image](https://github.com/shamhi/HamsterKombatBot/assets/77263046/aafeb61f-cb4d-48ef-be4d-7e25d4ade6ca)

**Comment by ZeroParadoxHome** [comment]
Alright, thanks for your answers🫡
