### ISSUE TITLE
i've got baned i guess

### ISSUE THREAD

**Issue by Mikeyounger** [shamhi/HamsterKombatBot#193]
Unknown error while getting Access Token: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/auth/auth-by-telegram-webapp') | Response text: Couchbase error! Method=query(q=
      select auth_user.* from auth_user
      where telegramUserId = $telegramUserId
      limi...

**Comment by ButCheR-PRO** [comment]
Dupe https://github.com/shamhi/HamsterKombatBot/issues/189
