### ISSUE TITLE
Traceback error: validation error for Settings SLEEP_BY_MIN_ENERGY, input should be a valid list

### ISSUE THREAD

**Issue by Rofl1234** [shamhi/HamsterKombatBot#194]
Софт работал как часы, но сегодня перестал запускаться, была какая-то ошибка, связанная с сессией. Решил переустановить софт, теперь вылазит следующее (на скрине). Как фиксить?
![Снимок экрана (60)](https://github.com/shamhi/HamsterKombatBot/assets/171097650/cf8313d4-b7c2-4cf7-a15a-b1ffb64ff491)

**Comment by ButCheR-PRO** [comment]
Настрой правильно .env конфиг согласно описанию из README.md

**Comment by Rofl1234** [comment]
все сделал, просто в ранних версиях SLEEP_BY_MIN_ENERGY по-другому указывался, не заметил. Теперь это вылазит
![Снимок экрана (62)](https://github.com/shamhi/HamsterKombatBot/assets/171097650/1c5fa3d0-b412-4f44-8ddf-a9f6adcc9bb9)

**Comment by ButCheR-PRO** [comment]
> Теперь это вылазит

Ну эта проблема у всех сегодня https://github.com/shamhi/HamsterKombatBot/issues/189

**Comment by Rofl1234** [comment]
Ждать фикса?

**Comment by ButCheR-PRO** [comment]
> Ждать фикса?

Может со временем само пофиксится. Такое раньше бывало.
