### ISSUE TITLE
[Предложение] Хранение сессий access_token в в json

### ISSUE THREAD

**Issue by lolyinseo** [shamhi/HamsterKombatBot#195]
` time() - access_token_created_time >= 3600 `

1. Нужно обрабатывать ответ о истечении сессии. Так делать не нужно. Обновление токена с такой периодичностью нет у юзера, это 100% привет бан
2.  access_token нужно хранить в json для каждого профиля, как все остальные настройки, а не в едином env (текстовом!!) файле.
3. Форки уже далеко ушли и реализую ежедневные задания кот удалённо подгр из json

**Comment by ButCheR-PRO** [comment]
> 3\. Форки уже далеко ушли и реализую ежедневные задания кот удалённо подгр из json

Форки, я так понимаю всё те же  https://github.com/AnisovAleksey/HamsterKombatBot

**Comment by Mik-chan** [comment]
Вставлю свои 5 монет, но json это тоже текстовый файл :^)

**Comment by lolyinseo** [comment]
> Вставлю свои 5 монет, но json это тоже текстовый файл :^)

ну вы поняли )
я старый, больной человек ) я когда вижу хранение в неформатированном виде, мне плохо становится
логично же иметь default.json который при создании профиля копируется в папку профиля в profile.json, всегда можно зайти поправить для конкретного профиля что нужно

**Comment by Mik-chan** [comment]
.env это стандратный формат хранения переменных окружения для python, nodejs, bash и тд, плюс не такой уж он и неформатированный. Формат это:
```env
KEY=VALUE
```
, где `VALUE` - это строковое значение.
Но с тем, что было бы удобно иметь отдельную конфигурацию для каждого профиля, я соглашусь.

**Comment by lolyinseo** [comment]
> Но с тем, что было бы удобно иметь отдельную конфигурацию для каждого профиля, я соглашусь.

Питонистам виднее. 
Я глянул, тут похоже фингерпринт у всех один и UA один на всех с

` 'maxTouchPoints': 1,`
и
` 'screenResolution': {
                'value': [
                    800,
                    440,
                ],`

что-то я сомневаюсь, что android webview такое отдаёт )) похоже они сняты с десктопа или эмулятора.
уже сразу можно всех в бан с такой авторизацией

**Comment by shamhi** [comment]
> > Но с тем, что было бы удобно иметь отдельную конфигурацию для каждого профиля, я соглашусь.
> 
> Питонистам виднее. Я глянул, тут похоже фингерпринт у всех один и UA один на всех
> 
> `'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36',`
> 
> ` 'maxTouchPoints': 1,` и ` 'screenResolution': { 'value': [ 800, 440, ],`
> 
> что-то я сомневаюсь, что android webview такое отдаёт )) похоже они сняты с десктопа или эмулятора. уже сразу можно всех в бан с такой авторизацией
> 
> fingeprint.json должен генерится свой для каждого профиля и валидный

то есть дать возможность пользователю поставить свой личный fingerprint?

**Comment by GravelFire** [comment]
А что если генерировать headers и fingerprint для каждой вилки?
И привязать это всё к этой вилке условно в json или SQL Database
А потом дёргать, туда же можно и access_token засунуть.

**Comment by lolyinseo** [comment]
> А что если генерировать headers и fingerprint для каждой вилки? headers условно засовывать в json(Потому что ну там нечему меняться) Наш отпечаток сделать более рандомным, там много параметров как выше Расширение экрана('screenResolution'), заряд батареи('battery') и тп А потом дёргать, туда же можно и access_token засунуть, проверять каждый раз на его жизнь и в случаи чего обновлять.

именно, фингерпринт и ua должен быть для каждого юзера(сессии) свой и хранится, что бы он был во всех запросах один. Ну и я молчу, что он тут вообще не валидный, а рандом. При проверке все улетим в бан

**Comment by lolyinseo** [comment]
> > > Но с тем, что было бы удобно иметь отдельную конфигурацию для каждого профиля, я соглашусь.
> > 
> > 
> > Питонистам виднее. Я глянул, тут похоже фингерпринт у всех один и UA один на всех
> > `'User-Agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Mobile Safari/537.36',`
> > ` 'maxTouchPoints': 1,` и ` 'screenResolution': { 'value': [ 800, 440, ],`
> > что-то я сомневаюсь, что android webview такое отдаёт )) похоже они сняты с десктопа или эмулятора. уже сразу можно всех в бан с такой авторизацией
> > fingeprint.json должен генерится свой для каждого профиля и валидный
> 
> то есть дать возможность пользователю поставить свой личный fingerprint?

именно, и не только. те к примеру profile.json должен содержать свой
1. User-Agent, sec-ch-ua (он у вас не валидный)
2. Фингерпринт (он у вас не валидный)
3. все настройки(не нужно общих, для каждого профиля свои), auth key, И ГЛАВНОЕ access token, не нужно его постоянно получать новый
4. проксю, что бы для каждого профиля можно указать свою
