### ISSUE TITLE
295 - Unknown error while Tapping: Session is closed | Response text: ...

### ISSUE THREAD

**Issue by A-platinum** [shamhi/HamsterKombatBot#196]
https://i.imgur.com/GUO9zE8.png

**Comment by ButCheR-PRO** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/23020594/b5f56071-643d-4b60-846d-598fbc18639e)
Очевидно что сессия была закрыта. Попробуй перезапустить докер-контейнер ( docker compose restart).
Я предполагаю, что в таких случаях в некоторых средах (например, Docker) лучше полностью выйти из бота, чтобы Docker автоматически запустил его снова, и ошибка исчезла.

Похожая ошибка: https://github.com/shamhi/HamsterKombatBot/issues/58

**Comment by A-platinum** [comment]
Ошибка остается, также добавилась другая ошибка
<img width="2048" alt="Снимок экрана 2024-06-06 в 13 18 06" src="https://github.com/shamhi/HamsterKombatBot/assets/171882059/1fbd453b-7ba9-4773-9d6d-076682b74a1b">
связанная с "int" object is nor subscriptable
