### ISSUE TITLE
Account deletion after executing the script / Удаление аккаунта после выполнения скрипта

### ISSUE THREAD

**Issue by Mahnazmohammadii** [shamhi/HamsterKombatBot#197]
Hello good time 
I ran the script on a Linux server, first I created a crate sassion using option 1
After that, I ran the robot using option 2
After two minutes, my Telegram account was deleted and my phone number was blocked for Telegram 
tip ? I used the old api id and api hash that I used before for NatCoin
Can you advise what is the reason? Isn't there a tutorial video?  Please help me

ru languache : 

Привет, доброго времени 
Я запустил скрипт на сервере Linux, сначала создал crate sassion, используя вариант 1.
После этого я запустил робота, используя вариант 2.
Через две минуты моя учетная запись Telegram была удалена, а мой номер телефона заблокирован для Telegram. 
кончик ? Я использовал старый идентификатор API и хэш API, которые я использовал раньше для NatCoin.
Можете подсказать в чем причина? Нет ли обучающего видео?  пожалуйста, помогите мне

**Comment by ButCheR-PRO** [comment]
Предварительные условия
Скачайте и установите: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)

Затем синхронизируйте на компьютере системное время.

Получение API ключей
1. Перейдите на сайт [my.telegram.org](https://my.telegram.org) и войдите в систему, используя свой номер телефона.
2. Выберите "API development tools" и заполните форму для регистрации нового приложения.
3. Запишите API_ID и API_HASH в файле .env, предоставленные после регистрации вашего приложения.

Скачать последнюю версию бота [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) и распакуйте.
Потом запустить INSTALL.bat. 
Затем настроить конфиг .env согласно документации в README.md
После этого нужно создать сессию через START.bat выбрав пункт 1. 
И только потом запускать настроенный кликер через START.bat выбрав пункт 2.

**Comment by A-platinum** [comment]
> Предварительные условия Скачайте и установите: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
> 
> Затем синхронизируйте на компьютере системное время.
> 
> Получение API ключей
> 
> 1. Перейдите на сайт [my.telegram.org](https://my.telegram.org) и войдите в систему, используя свой номер телефона.
> 2. Выберите "API development tools" и заполните форму для регистрации нового приложения.
> 3. Запишите API_ID и API_HASH в файле .env, предоставленные после регистрации вашего приложения.
> 
> Скачать последнюю версию бота [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) и распакуйте. Потом запустить INSTALL.bat. Затем настроить конфиг .env согласно документации в README.md После этого нужно создать сессию через START.bat выбрав пункт 1. И только потом запускать настроенный кликер через START.bat выбрав пункт 2.

Install bat и Start bat безсмысленны, так как у него Linux

**Comment by Mahnazmohammadii** [comment]
Я прошу прощения 
Я аккаунт, создавший этот запрос
И я перепостил ошибку твоей цитаты
Мой дорогой друг, я не понял 
Можете ли вы вести меня дальше?
Нужно ли нам создавать новый API для каждого номера телеграммы?
Нужна ли синхронизация часов сервера?
Должен ли я использовать версию Python, которую вы прислали?
Нужно ли нам вносить другие изменения в файл .en
v, кроме api hsh — api id?
Меня не волнует количество кликов, я просто хочу, чтобы бот оставался онлайн, чтобы его внутренний майнер не отключался после трехчасового отсутствия в сети. 
Так что количество нажатий мне не важно и я выбираю самый низкий режим
Спасибо за дополнительные рекомендации

**Comment by ButCheR-PRO** [comment]
> Я прошу прощения Я аккаунт, создавший этот запрос И я перепостил ошибку твоей цитаты Мой дорогой друг, я не понял Можете ли вы вести меня дальше? Нужно ли нам создавать новый API для каждого номера телеграммы? Нужна ли синхронизация часов сервера? Должен ли я использовать версию Python, которую вы прислали? Нужно ли нам вносить другие изменения в файл .en v, кроме api hsh — api id? Меня не волнует количество кликов, я просто хочу, чтобы бот оставался онлайн, чтобы его внутренний майнер не отключался после трехчасового отсутствия в сети. Так что количество нажатий мне не важно и я выбираю самый низкий режим Спасибо за дополнительные рекомендации
API_ID и API_HASH можно использовать одинаковый для нескольких аккаунтов Telegram. 
Синхронизация часов обязательна, иначе будут ошибки.
В .env внесите стандартные параметры:
```
API_ID=ВАШ_ID
API_HASH=ВАШ_ХЭШ

MIN_AVAILABLE_ENERGY=100
SLEEP_BY_MIN_ENERGY=[1800,2400]

ADD_TAPS_ON_TURBO=2500

AUTO_UPGRADE=True
MAX_LEVEL=15
BALANCE_TO_SAVE=5000000
UPGRADES_COUNT=10

APPLY_DAILY_ENERGY=True
APPLY_DAILY_TURBO=True

RANDOM_TAPS_COUNT=[50,200]
SLEEP_BETWEEN_TAP=[10,25]
USE_PROXY_FROM_FILE=False
```
Можете настраивать по своему усмотрению, но согласно документации в README.md.

**Comment by Mahnazmohammadii** [comment]
I am very grateful for your guidance, my dear friend 
But I have one question
What do you think was the reason for deleting my user account and blocking my phone number?

Я очень благодарен за ваше руководство, мой дорогой друг 
Но у меня есть один вопрос
Как вы думаете, что послужило причиной удаления моей учетной записи и блокировки моего номера телефона?

**Comment by iamhaghighi** [comment]
I do not know the answer to your question.
But if you want the internal tank of the robot not to be filled every three hours, you can use Telegram Web so that the robot is always online.

**Comment by iamhaghighi** [comment]
> Я прошу прощения Я аккаунт, создавший этот запрос И я перепостил ошибку твоей цитаты Мой дорогой друг, я не понял Можете ли вы вести меня дальше? Нужно ли нам создавать новый API для каждого номера телеграммы? Нужна ли синхронизация часов сервера? Должен ли я использовать версию Python, которую вы прислали? Нужно ли нам вносить другие изменения в файл .en v, кроме api hsh — api id? Меня не волнует количество кликов, я просто хочу, чтобы бот оставался онлайн, чтобы его внутренний майнер не отключался после трехчасового отсутствия в сети. Так что количество нажатий мне не важно и я выбираю самый низкий режим Спасибо за дополнительные рекомендации

I do not know the answer to your question.
But if you want the internal tank of the robot not to be filled every three hours, you can use Telegram Web so that the robot is always online.

**Comment by Mahnazmohammadii** [comment]
This is a good idea, but in Telegram, the desktop robot would not start and it says that you need to scan the qr with your phone

can explain more ?

**Comment by iamhaghighi** [comment]
> > > Я прошу прощения Я аккаунт, создавший этот запрос И я перепостил ошибку твоей цитаты Мой дорогой друг, я не понял Можете ли вы вести меня дальше? Нужно ли нам создавать новый API для каждого номера телеграммы? Нужна ли синхронизация часов сервера? Должен ли я использовать версию Python, которую вы прислали? Нужно ли нам вносить другие изменения в файл .en v, кроме api hsh — api id? Меня не волнует количество кликов, я просто хочу, чтобы бот оставался онлайн, чтобы его внутренний майнер не отключался после трехчасового отсутствия в сети. Так что количество нажатий мне не важно и я выбираю самый низкий режим Спасибо за дополнительные рекомендации
> > 
> > 
> > I do not know the answer to your question. But if you want the internal tank of the robot not to be filled every three hours, you can use Telegram Web so that the robot is always online.
> 
> This is a good idea, but in Telegram, the desktop robot would not start and it says that you need to scan the qr with your phone
> 
> can explain more ?

https://github.com/mudachyo/Hamster-Kombat

**Comment by Mahnazmohammadii** [comment]
> > > > Я прошу прощения Я аккаунт, создавший этот запрос И я перепостил ошибку твоей цитаты Мой дорогой друг, я не понял Можете ли вы вести меня дальше? Нужно ли нам создавать новый API для каждого номера телеграммы? Нужна ли синхронизация часов сервера? Должен ли я использовать версию Python, которую вы прислали? Нужно ли нам вносить другие изменения в файл .en v, кроме api hsh — api id? Меня не волнует количество кликов, я просто хочу, чтобы бот оставался онлайн, чтобы его внутренний майнер не отключался после трехчасового отсутствия в сети. Так что количество нажатий мне не важно и я выбираю самый низкий режим Спасибо за дополнительные рекомендации
> > > 
> > > 
> > > I do not know the answer to your question. But if you want the internal tank of the robot not to be filled every three hours, you can use Telegram Web so that the robot is always online.
> > 
> > 
> > This is a good idea, but in Telegram, the desktop robot would not start and it says that you need to scan the qr with your phone
> > can explain more ?
> 
> you can use this repo. https://github.com/mudachyo/Hamster-Kombat

Isn't there a risk of banning the account of a diagnosis as a robot? 
I lost over 1 billion Natcoin tokens because I used a script

**Comment by iamhaghighi** [comment]
> > > > > Я прошу прощения Я аккаунт, создавший этот запрос И я перепостил ошибку твоей цитаты Мой дорогой друг, я не понял Можете ли вы вести меня дальше? Нужно ли нам создавать новый API для каждого номера телеграммы? Нужна ли синхронизация часов сервера? Должен ли я использовать версию Python, которую вы прислали? Нужно ли нам вносить другие изменения в файл .en v, кроме api hsh — api id? Меня не волнует количество кликов, я просто хочу, чтобы бот оставался онлайн, чтобы его внутренний майнер не отключался после трехчасового отсутствия в сети. Так что количество нажатий мне не важно и я выбираю самый низкий режим Спасибо за дополнительные рекомендации
> > > > 
> > > > 
> > > > I do not know the answer to your question. But if you want the internal tank of the robot not to be filled every three hours, you can use Telegram Web so that the robot is always online.
> > > 
> > > 
> > > This is a good idea, but in Telegram, the desktop robot would not start and it says that you need to scan the qr with your phone
> > > can explain more ?
> > 
> > 
> > you can use this repo. https://github.com/mudachyo/Hamster-Kombat
> 
> Isn't there a risk of banning the account of a diagnosis as a robot? I lost over 1 billion Natcoin tokens because I used a script

I do not know about this. ashamed

**Comment by XPacL** [comment]
Риски, что ты при дропе не получишь ничего есть всегда. Если хочешь без риска, то используй руки и смартфон

**Comment by Mahnazmohammadii** [comment]
> > Я прошу прощения Я аккаунт، создавший этот سوال و я я перепостил ошибку твой цитаты My dorogoй друг، آیا نمی توانید این را بنویسید؟ Нужно ли нам ایجادть جدید API для каждого номера телеграммы؟ Нужна ли синхронизация часов سرور? Должен ли я использовать версию پایتون، которую вы прислали؟ Нужно ли нам вносить другие изменения в файл .en v, crome api hsh — api id? من نمی خواهم همه چیز را بگذارم. Так что количество нажатий мне не اهمیت и я выбираю самый низкий режим Спасибо за дополнительные اصلاح
> 
> API_ID و API_HASH می‌توانید از تلگرام استفاده کنید. Синхронизация часов обязательна, иначе будут ошибки. در .env وارد کنید استانداردهای پارامتر:
> 
> ```
> API_ID=ВАШ_ID
> API_HASH=ВАШ_ХЭШ
> 
> MIN_AVAILABLE_ENERGY=100
> SLEEP_BY_MIN_ENERGY=[1800,2400]
> 
> ADD_TAPS_ON_TURBO=2500
> 
> AUTO_UPGRADE=True
> MAX_LEVEL=20
> BALANCE_TO_SAVE=1000000
> UPGRADES_COUNT=10
> 
> APPLY_DAILY_ENERGY=True
> APPLY_DAILY_TURBO=True
> 
> RANDOM_TAPS_COUNT=[50,200]
> SLEEP_BETWEEN_TAP=[10,25]
> USE_PROXY_FROM_FILE=False
> ```
> 
> در README.md می توانید به اسناد خود دسترسی پیدا کنید.

#202  please read this i lost 250 milion ha,ster :)
