### ISSUE TITLE
Request daily combo feature

### ISSUE THREAD

**Issue by ZeroParadoxHome** [shamhi/HamsterKombatBot#199]
Would you please add the ability to bot in order to get daily combo bonus?
Because due to so many people playing the app won't load on my mobile but the script can perform
I think this repo already added this feature but its not working for some reason
https://github.com/AnisovAleksey/HamsterKombatBot
Thanks

**Comment by ZeroParadoxHome** [comment]
Also I have a suggestion that but only get daily combo cards on each session if the price of upgrading card are less than that bonus, So it would be logical to upgrade them

**Comment by ButCheR-PRO** [comment]
Dupe https://github.com/shamhi/HamsterKombatBot/issues/102
