### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Towmasmd** [shamhi/HamsterKombatBot#200]
Iam face this problem when l run main.py
> 22024-06-06 17:23:33 | ERROR    | 106 - towmas | Unknown error while getting Access Token: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/auth/auth-by-telegram-webapp') | Response text: Couchbase error! Method=query(q=
      select auth_user.* from auth_user      where telegramUserId = $telegramUserId
      limi...

**Comment by Blasthacker** [comment]
oh bro I understand you, same problem

**Comment by Kostya2077** [comment]
+ 1

**Comment by ButCheR-PRO** [comment]
Dupe https://github.com/shamhi/HamsterKombatBot/issues/189

**Comment by Towmasmd** [comment]
I don't understand the solution to the problem!!!!
