### ISSUE TITLE
Unknown error: local variable 'available_energy' referenced before assignment

### ISSUE THREAD

**Issue by A-platinum** [shamhi/HamsterKombatBot#204]
<img width="2048" alt="Снимок экрана 2024-06-06 в 18 08 10" src="https://github.com/shamhi/HamsterKombatBot/assets/171882059/845301b2-be3b-4502-af53-9a78b18fcb96">

**Comment by kxnkxv** [comment]
Тоже самое

**Comment by ButCheR-PRO** [comment]
Сейчас наблоюдаются проблемы с серверами. Надо подождать пока можно будет нормально зайти в игру и запускать бота.

**Comment by KOTBCTAKAHE** [comment]
Solved: It was a problem with the hamster servers.
