### ISSUE TITLE
Robot update

### ISSUE THREAD

**Issue by MGTV01** [shamhi/HamsterKombatBot#206]
Hello. The robot is amazing. There is only one thing. How to update the robot so that our meetings and information remain intact? If there is a way, show me...

**Comment by ButCheR-PRO** [comment]
What information exactly bothers you? Your data remains intact.

**Comment by MGTV01** [comment]
> What information exactly bothers you? Your data remains intact.

Well, with what command should I update the robot?

**Comment by ButCheR-PRO** [comment]
Download and install: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)

Then synchronize the system time on your computer.

Obtaining API keys
1. Go to the website [my.telegram.org](https://my.telegram.org) and log in using your phone number.
2. Select "API development tools" and fill out the form to register a new application.
3. Record the API_ID and API_HASH in the .env file provided after registering your application.

Download the latest version of the bot [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) and unpack it.
Then run INSTALL.bat.
Then configure the .env config according to the documentation in README.md
After this, you need to create a session via START.bat by selecting option 1.
And only then launch the configured clicker through START.bat by selecting point 2.

**Comment by MGTV01** [comment]
> Download and install: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
> 
> Then synchronize the system time on your computer.
> 
> Obtaining API keys
> 
> 1. Go to the website [my.telegram.org](https://my.telegram.org) and log in using your phone number.
> 2. Select "API development tools" and fill out the form to register a new application.
> 3. Record the API_ID and API_HASH in the .env file provided after registering your application.
> 
> Download the latest version of the bot [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) and unpack it. Then run INSTALL.bat. Then configure the .env config according to the documentation in README.md After this, you need to create a session via START.bat by selecting option 1. And only then launch the configured clicker through START.bat by selecting point 2.

Thank you. Are there robots for monorix or topcoin or bunnyapp or dotcoin and other robots that we can extract and mine more easily?

**Comment by ButCheR-PRO** [comment]
> Are there robots for monorix or topcoin or bunnyapp or dotcoin and other robots that we can extract and mine more easily?

You can see all projects in the Shamhi repository https://github.com/shamhi?tab=repositories
Or by searching for the desired bot throughout GitHub.
