### ISSUE TITLE
No module named 'loguru' Хотя он установлен.

### ISSUE THREAD

**Issue by treyne** [shamhi/HamsterKombatBot#2090]
Результат выполнения pip install loguru 
![Снимок](https://github.com/user-attachments/assets/ef5e0ea1-861e-4ce3-83a0-763f3368da78)

При запуске скрипта
![Снимок2](https://github.com/user-attachments/assets/ea45bb8f-2f9a-442f-a3a3-e3a38553de05)

**Comment by socloseeee** [comment]
Так его надо в venv установить
Перед тем как pip install loguru, надо активировать виртуальную среду через venv\Scripts\activate

**Comment by treyne** [comment]
Да, это помогло, но ведь скрипт автоматической установки должен был сам его установить. 
![Uploading Снимок3.PNG…]()

**Comment by Stelfelics** [comment]
> Да, это помогло, но ведь скрипт автоматической установки должен был сам его установить. ![Снимок3](https://private-user-images.githubusercontent.com/8302610/352819770-79f452a0-93aa-4408-a00f-0aa151affb75.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzgyNjQsIm5iZiI6MTcyMjE3Nzk2NCwicGF0aCI6Ii84MzAyNjEwLzM1MjgxOTc3MC03OWY0NTJhMC05M2FhLTQ0MDgtYTAwZi0wYWExNTFhZmZiNzUuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjhUMTQ0NjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTlmMGI3Yjk0NzZkOGNiYWI4ZmUxYzM3YWNiZGFkMzBlODA2ODIyODk1YzdiYThiMzIwYmUzMzk0NWU5ODFmZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xmrVAMfvWTQl8J0khXQITLAVWoYduCzSUGD0up91oe4)
> 
> Установил ещё таким образом pyrogram call venv\Scripts\activate pip install pyrogram
> 
> Теперь ругается на tgcrypto Microsoft C++ Build Tools установлен, но это не дало никаких результатов ![Снимок5](https://private-user-images.githubusercontent.com/8302610/352824912-c5999dbc-6673-4cb5-bafb-faec72dc7817.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzgyNjQsIm5iZiI6MTcyMjE3Nzk2NCwicGF0aCI6Ii84MzAyNjEwLzM1MjgyNDkxMi1jNTk5OWRiYy02NjczLTRjYjUtYmFmYi1mYWVjNzJkYzc4MTcuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjhUMTQ0NjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzY1NzMyNDQ5MjI0Y2YxMTU4ZjhjYzlmZTIwMjQ0ZjRhNDE4MTQ0MTQ3ZTRhMmE2ZWZmZmZhMDliZDVjMDcwZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dKat9tzMwbydFQTxs4MnEeIGmt0wIAaLhtpEfJFKK9k)

бро.. 
```
@echo off
title HamsterCombat

if not exist venv (
    echo Creating virtual environment...
    py -m venv venv
)

echo Activating virtual environment...
call venv\Scripts\activate

if not exist venv\Lib\site-packages\installed (
    if exist requirements.txt (
		echo installing wheel for faster installing
		pip install wheel
        echo Installing dependencies...
        pip install -r requirements.txt
        echo. > venv\Lib\site-packages\installed
    ) else (
        echo requirements.txt not found, skipping dependency installation.
    )
) else (
    echo Dependencies already installed, skipping installation.
)

if not exist .env (
	echo Copying configuration file
	copy .env-example .env
) else (
	echo Skipping .env copying
)

echo Starting the bot...
py main.py

echo done
echo PLEASE EDIT .ENV FILE
pause
```

**Comment by treyne** [comment]
> 
> бро..
> 
> ```
> @echo off
> title HamsterCombat
> 
> if not exist venv (
>     echo Creating virtual environment...
>     py -m venv venv
> )
> 
> echo Activating virtual environment...
> call venv\Scripts\activate
> 
> if not exist venv\Lib\site-packages\installed (
>     if exist requirements.txt (
> 		echo installing wheel for faster installing
> 		pip install wheel
>         echo Installing dependencies...
>         pip install -r requirements.txt
>         echo. > venv\Lib\site-packages\installed
>     ) else (
>         echo requirements.txt not found, skipping dependency installation.
>     )
> ) else (
>     echo Dependencies already installed, skipping installation.
> )
> 
> if not exist .env (
> 	echo Copying configuration file
> 	copy .env-example .env
> ) else (
> 	echo Skipping .env copying
> )
> 
> echo Starting the bot...
> py main.py
> 
> echo done
> echo PLEASE EDIT .ENV FILE
> pause
> ```
Оно выполнилось но опять застряло на tgcrypto

**Comment by Stelfelics** [comment]
> > бро..
> > ```
> > @echo off
> > title HamsterCombat
> > 
> > if not exist venv (
> >     echo Creating virtual environment...
> >     py -m venv venv
> > )
> > 
> > echo Activating virtual environment...
> > call venv\Scripts\activate
> > 
> > if not exist venv\Lib\site-packages\installed (
> >     if exist requirements.txt (
> > 		echo installing wheel for faster installing
> > 		pip install wheel
> >         echo Installing dependencies...
> >         pip install -r requirements.txt
> >         echo. > venv\Lib\site-packages\installed
> >     ) else (
> >         echo requirements.txt not found, skipping dependency installation.
> >     )
> > ) else (
> >     echo Dependencies already installed, skipping installation.
> > )
> > 
> > if not exist .env (
> > 	echo Copying configuration file
> > 	copy .env-example .env
> > ) else (
> > 	echo Skipping .env copying
> > )
> > 
> > echo Starting the bot...
> > py main.py
> > 
> > echo done
> > echo PLEASE EDIT .ENV FILE
> > pause
> > ```
> 
> Оно выполнилось но опять застряло на tgcrypto ![Снимок6](https://private-user-images.githubusercontent.com/8302610/352834809-01a70369-48af-46f0-8e6d-1e6e4db9a6d1.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNzg5NTMsIm5iZiI6MTcyMjE3ODY1MywicGF0aCI6Ii84MzAyNjEwLzM1MjgzNDgwOS0wMWE3MDM2OS00OGFmLTQ2ZjAtOGU2ZC0xZTZlNGRiOWE2ZDEuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjhUMTQ1NzMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDNjMDUxNzRiZWRiZGEyMWQ0MDM1MjM2YTgwOGU5NzMzYWUzMTE0YTU4NTVlZGE0NTg3ZWZhZjc1M2Q4MTVhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZMZULvaFyodSB83AR-SodtWlL07X-udtURBdd3SVE-g)

а ты удалил папку venv перед запуском батника?

**Comment by Stelfelics** [comment]
> > бро..
> > ```
> > @echo off
> > title HamsterCombat
> > 
> > if not exist venv (
> >     echo Creating virtual environment...
> >     py -m venv venv
> > )
> > 
> > echo Activating virtual environment...
> > call venv\Scripts\activate
> > 
> > if not exist venv\Lib\site-packages\installed (
> >     if exist requirements.txt (
> > 		echo installing wheel for faster installing
> > 		pip install wheel
> >         echo Installing dependencies...
> >         pip install -r requirements.txt
> >         echo. > venv\Lib\site-packages\installed
> >     ) else (
> >         echo requirements.txt not found, skipping dependency installation.
> >     )
> > ) else (
> >     echo Dependencies already installed, skipping installation.
> > )
> > 
> > if not exist .env (
> > 	echo Copying configuration file
> > 	copy .env-example .env
> > ) else (
> > 	echo Skipping .env copying
> > )
> > 
> > echo Starting the bot...
> > py main.py
> > 
> > echo done
> > echo PLEASE EDIT .ENV FILE
> > pause
> > ```
> 
> Оно выполнилось но опять застряло на tgcrypto ![Снимок6](https://private-user-images.githubusercontent.com/8302610/352834809-01a70369-48af-46f0-8e6d-1e6e4db9a6d1.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxODA1MDcsIm5iZiI6MTcyMjE4MDIwNywicGF0aCI6Ii84MzAyNjEwLzM1MjgzNDgwOS0wMWE3MDM2OS00OGFmLTQ2ZjAtOGU2ZC0xZTZlNGRiOWE2ZDEuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjhUMTUyMzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWYwMDcxZDdjZTQ4YzhkYjRiODMzMDE5NjMxZjk5MDMwYjgxYWU0ZWYyZjVmY2M1MDVlOTg3YjQ3Y2YzNzY0ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.F4A9iHNZCBqHGr3nPIga0NI0vSkStv7ow2bjnEIdDXg)

а у тебя python какой версии? вижу 312.. не уж то 3.12?? надо 3.10 или 3.11..

**Comment by Stelfelics** [comment]
> > бро..
> > ```
> > @echo off
> > title HamsterCombat
> > 
> > if not exist venv (
> >     echo Creating virtual environment...
> >     py -m venv venv
> > )
> > 
> > echo Activating virtual environment...
> > call venv\Scripts\activate
> > 
> > if not exist venv\Lib\site-packages\installed (
> >     if exist requirements.txt (
> > 		echo installing wheel for faster installing
> > 		pip install wheel
> >         echo Installing dependencies...
> >         pip install -r requirements.txt
> >         echo. > venv\Lib\site-packages\installed
> >     ) else (
> >         echo requirements.txt not found, skipping dependency installation.
> >     )
> > ) else (
> >     echo Dependencies already installed, skipping installation.
> > )
> > 
> > if not exist .env (
> > 	echo Copying configuration file
> > 	copy .env-example .env
> > ) else (
> > 	echo Skipping .env copying
> > )
> > 
> > echo Starting the bot...
> > py main.py
> > 
> > echo done
> > echo PLEASE EDIT .ENV FILE
> > pause
> > ```
> 
> Оно выполнилось но опять застряло на tgcrypto ![Снимок6](https://private-user-images.githubusercontent.com/8302610/352834809-01a70369-48af-46f0-8e6d-1e6e4db9a6d1.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxODA4NDQsIm5iZiI6MTcyMjE4MDU0NCwicGF0aCI6Ii84MzAyNjEwLzM1MjgzNDgwOS0wMWE3MDM2OS00OGFmLTQ2ZjAtOGU2ZC0xZTZlNGRiOWE2ZDEuUE5HP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjhUMTUyOTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODVmYTIyMTgwZDhkMTBhMDljZTQ1N2NiYzU0Nzc2ZDYxY2MyYjE1MmJmNmI1M2NmMjBkNDg2ZGRlMWY3NzBkNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LG3VuSB82DHf65HwBqZCgkee4A0siytUPp1NJxC3_6Q)

и ещё что я заметил, так это странная работа любого бота, если запускать его от имени администратора.. попробуй запустить установщик в обычном режиме

**Comment by treyne** [comment]
Установил Python 3.10. удалил папку env. не помогло

**Comment by Stelfelics** [comment]
> Установил Python 3.10. удалил папку env. не помогло

попробуй 3.11

**Comment by WeendVidente777** [comment]
Обожаю питон (нет). Юзайте нодЖс. Сорри за комментарий, но наболело. Ненавижу питон.

**Comment by treyne** [comment]
Так и не смог установить скрипт. Написал нужный функционал с помощью кода который нашёл тут.
