### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Fairmont77** [shamhi/HamsterKombatBot#2091]
Hi, I want to write a bot for OKX Racer, but I don't understand where to get the game api, can you tell me?

**Comment by socloseeee** [comment]
There are some examples of usage HamsterKombatAPI:

https://github.com/shamhi/HamsterKombatBot/tree/main/bot/api

**Comment by Fairmont77** [comment]
> There are some examples of usage HamsterKombatAPI:
> 
> https://github.com/shamhi/HamsterKombatBot/tree/main/bot/api

I see, but where get API for OKX Racer, MemeFi?... With DevTools?

**Comment by yoyoallf** [comment]
> curl -X POST 'https://api.gamepromo.io/promo/login-client' \ -H 'Content-Type:application/json; charset=utf-8' \ -H 'Host:api.gamepromo.io' \ -d '{"appToken":"d28721be-fd2d-4b45-869e-9f253b554e50","clientId": "{сгенерируйте свой}", "clientOrigin":"deviceid"}'
> 
> clientId '{timestamp}-{19 рандомных чисел}' напр. 1722170090396-7788705357781847528
> 
> curl -X POST 'https://api.gamepromo.io/promo/register-event' \ -H 'Authorization:Bearer {token - предыдущий запрос}' \ -H 'Content-Type:application/json; charset=utf-8' \ -H 'Host:api.gamepromo.io' \ -d '{"promoId": "43e35910-c168-4634-ad4f-52fd764a843f", "eventId": "{random uuid}", "eventOrigin": "undefined"}'
> 
> закидываем события (разные uuid) пока не получим hasCode: true. На забываем про задержки, иначе too many attempts
> 
> получаем код: curl -X POST 'https://api.gamepromo.io/promo/create-code' \ -H 'Authorization:Bearer {token - предыдущий запрос}' \ -H 'Content-Type:application/json; charset=utf-8' \ -H 'Host:api.gamepromo.io' \ -d '{"promoId": "43e35910-c168-4634-ad4f-52fd764a843f"}'

**Comment by WeendVidente777** [comment]
> > There are some examples of usage HamsterKombatAPI:
> > https://github.com/shamhi/HamsterKombatBot/tree/main/bot/api
> 
> I see, but where get API for OKX Racer, MemeFi?... With DevTools?

yep. For web apps - devtools in your browser. For other apps - emulator + wireshark. 
Perform action
get request
copy 
paste in code, in your format
...
PROFIT

**Comment by Abidbdwork** [comment]
> > There are some examples of usage HamsterKombatAPI:
> > https://github.com/shamhi/HamsterKombatBot/tree/main/bot/api
> 
> I see, but where get API for OKX Racer, MemeFi?... With DevTools?

You can use android emulator, and use any packet capture tool to read telegram app. And then open and bot you will see the API enpoints
