### ISSUE TITLE
[Предложение] Мини-Игры

### ISSUE THREAD

**Issue by KOTBCTAKAHE** [shamhi/HamsterKombatBot#2092]
Как насчет того, чтобы добавить автоматического активации кода, в мини игре «Bike Ride 3D»
Знаю, что вряд-ли получится, ну, а в друг)

**Comment by KOTBCTAKAHE** [comment]
Там наверное надо будет отслеживать API запросы игры.

**Comment by iskizreal** [comment]
Уже в дев ветке

**Comment by KOTBCTAKAHE** [comment]
> Уже в дев ветке

Пардон, не заметил. Не перестаю удивляться от автора.
