### ISSUE TITLE
4 Keys from bike games

### ISSUE THREAD

**Issue by hardim26** [shamhi/HamsterKombatBot#2095]
В ветке про бритье ребята вроде раскопали как можно получать ключи. Есть ли в планах автоматизировать процесс получения и вставки этих ключей. В игру играть не вариант вообще :) https://github.com/shamhi/HamsterKombatBot/issues/1918

**Comment by socloseeee** [comment]
С утра было в dev ветке, теперь в main. Просто обновите до текущего состояния
