### ISSUE TITLE
Unknown error while getting Access Token: 500

### ISSUE THREAD

**Issue by wrntic** [shamhi/HamsterKombatBot#210]
Целый день вылазит такая ошибка, хотя в прошлые дни все было хорошо. С телефона в игру заходит спокойно

> Unknown error while getting Access Token: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/auth/auth-by-telegram-webapp') | Response text: Couchbase error! Method=upsert(id=Айпи, data={"ip":"Айпи"}) Collection=default._default.ip_info Error=AmbiguousTimeoutError: ambiguous timeout...

**Comment by Mik-chan** [comment]
С телефона заходит по причине, что клиент кеширует токен, а этот бот его запрашивает почти для каждого клика по новой

**Comment by XPacL** [comment]
Висят сервера хомы други мои. Ждите

**Comment by ahrorbeksoft** [comment]
> С телефона заходит по причине, что клиент кеширует токен, а этот бот его запрашивает почти для каждого клика по новой

okay, if u insist:

**Comment by ButCheR-PRO** [comment]
Дубликат https://github.com/shamhi/HamsterKombatBot/issues/189
