### ISSUE TITLE
Daily combo неправильные карточки

### ISSUE THREAD

**Issue by AlexSeley** [shamhi/HamsterKombatBot#2131]
Походу ссылка _https://api21.datavibe.top/api/GetCombo_ перестала работать и в ответ отправляет только карточки которые были 29 июля. У вас также?

**Comment by dinrise** [comment]
Он в целом карточки перестал апгрейдить

**Comment by newtoneweb** [comment]
я для себя добавил возможность самому создавать файл с комбо  combo_cards.json в tapper.py 128 строка
при этом не нарушая нормальную работу скрипта
...
`combo_cards = await get_combo_cards(http_client=http_client)
cards = combo_cards['combo']
date = combo_cards['date']

try:
    with open('combo_cards.json', 'r') as file:
        combo_local = json.load(file)
        cards_local = combo_local['combo']
        date_local = combo_local['date']

    if date_local > date:
        date = date_local
        cards = cards_local
except FileNotFoundError:
    logger.warning(
        f"{self.session_name} | Local combo_cards.json not found. Using server data.")`

**Comment by ButCheR-PRO** [comment]
@KOTBCTAKAHE обновляет api
1. https://github.com/shamhi/HamsterKombatBot/issues/225#issuecomment-2155370580

**Comment by KOTBCTAKAHE** [comment]
> Походу ссылка _https://api21.datavibe.top/api/GetCombo_ перестала работать и в ответ отправляет только карточки которые были 29 июля. У вас также?

Я извиняюсь, работы у меня много, комбо я уже обновил.

**Comment by KOTBCTAKAHE** [comment]
мой публичный репозиторий: https://github.com/KOTBCTAKAHE/hamster-kombo-server/ там вы можете смотреть когда комбо было обновлено.

**Comment by KOTBCTAKAHE** [comment]
мой публичный репозиторий: https://github.com/KOTBCTAKAHE/hamster-kombo-server/ там вы можете смотреть когда комбо было обновлено.

**Comment by KOTBCTAKAHE** [comment]
Стараюсь ежедневно обновлять свое комбо.
