### ISSUE TITLE
Unknown error while getting Access Token: 500,

### ISSUE THREAD

**Issue by afdulfauzan** [shamhi/HamsterKombatBot#214]
Unknown error while getting Access Token: 500,
 message='Internal Server Error', url=URL('http
s://api.hamsterkombat.io/auth/auth-by-telegram-
webapp') | Response text: Couchbase error! Meth
od=upsert(id=212.83.46.XXX, data={"ip":"212.83.
46.XXX"}) Collection=default._default.ip_info E
rror=AmbiguousTimeoutError: ambiguous timeout..

**Comment by afdulfauzan** [comment]
Unknown error while Tapping: 500, message='Int
ernal Server Error', url=URL('https://api.hamst
erkombat.io/clicker/tap') | Response text: Couc
hbase error upsertUser! Error=AmbiguousTimeoutE
rror: ambiguous timeout Bucket=default Scope=ha
mster_prod Collection=clicker_tg_user Data

**Comment by afdulfauzan** [comment]
`Unknown error while Tapping: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/tap') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_tg_user`

**Comment by ButCheR-PRO** [comment]
Dupe https://github.com/shamhi/HamsterKombatBot/issues/189
