### ISSUE TITLE
[Предложения] В связи с обновлением, я так понимаю просмотр видосов и другая активность, будет вознаграждатся

### ISSUE THREAD

**Issue by dmitryGolikov** [shamhi/HamsterKombatBot#2148]
Просмотр видосиков думаю реализуем через api, там правда ожидание через час, но разрабы в апи стали отдавать время до проверки. Кто нить уже делал? поделитесь с комюнити.

**Comment by yoyoallf** [comment]
я с телефона теперь не могу этот ютуб вообще смотреть)) тупо не грузится) есть вроде какой то костыль, чтоб обойти, но мне лень)

**Comment by dmitryGolikov** [comment]
I know, I try it as soon, of course my be some one done it and share))

**Comment by dmitryGolikov** [comment]
Thanks, its realy easy, not need wait 1h. check-task and get reward.
