### ISSUE TITLE
Появились новые achievement

### ISSUE THREAD

**Issue by treyne** [shamhi/HamsterKombatBot#2149]
![Screenshot_2024-08-02-14-55-50-731_ir ilmili telegraph](https://github.com/user-attachments/assets/6e251216-8a0e-4833-9aa2-a63b206dbf84)
Сегодня вечерком поковыряю хомяка. Может найду как эти achievement получить. Ребятки присоединяйтесь к обсуждению.

**Comment by andrei010084** [comment]
Как их можно получить, если он берет информацию с сервера по всем активностям аккаунта и отображает её в таблице

**Comment by Bonch72** [comment]
Где вы это нашли? только что зашел ничего подобного нет.

**Comment by yoyoallf** [comment]
> Как их можно получить, если он берет информацию с сервера по всем активностям аккаунта и отображает её в таблице

Ну вот он и хочет узнать, за какие действия есть награды

**Comment by shamhi** [comment]
> Сегодня вечерком поковыряю хомяка. Может найду как эти achievement получить. Ребятки присоединяйтесь к обсуждению.

![image](https://github.com/user-attachments/assets/fb568bfc-5ef2-436d-b69d-5b10540de53d)

**Comment by yoyoallf** [comment]
> > Сегодня вечерком поковыряю хомяка. Может найду как эти achievement получить. Ребятки присоединяйтесь к обсуждению.
> 
> ![image](https://private-user-images.githubusercontent.com/148555284/354655378-fb568bfc-5ef2-436d-b69d-5b10540de53d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2MTYwODgsIm5iZiI6MTcyMjYxNTc4OCwicGF0aCI6Ii8xNDg1NTUyODQvMzU0NjU1Mzc4LWZiNTY4YmZjLTVlZjItNDM2ZC1iNjlkLTViMTA1NDBkZTUzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwMlQxNjIzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTc5MjY2ZTIzODQyMDU0ZWNhMmI2NTk3OGVhNGI3NzE2ZTU1NDUyM2YyMGJiZTA2ZTczMTQ4MTg1Y2RjNTRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lf7GoK-DFyZm84mGAV2iEWowCPdi5UOGyUwZQZauHwg)

Можно будет намутить, чтоб при определенных условиях, например, заданных в конфике (например, "выполнять достижения - True)  бот автоматически обновлял 25 карт самых дешевых и т.п.?

**Comment by DenisSalnikoff** [comment]
Автопокупку скинов бы добавить. А то не все телефоны всегда под рукой.
