### ISSUE TITLE
Upgrade Api Response 500

### ISSUE THREAD

**Issue by themiralay** [shamhi/HamsterKombatBot#215]
Unknown error while buying Upgrade: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/clicker/buy-upgrade') | Response text: Couchbase error upsertUser! Error=AmbiguousTimeoutError: ambiguous timeout Bucket=default Scope=hamster_prod Collection=clicker_tg_user Data={
        "id": "xxxx",
        "totalCoins": 2285275.6412666794,
        "balanceCoins": 1366527.6412666803,
        "level": 5,
        "avail...

**Comment by iamhaghighi** [comment]
same .

**Comment by ButCheR-PRO** [comment]
Dupe https://github.com/shamhi/HamsterKombatBot/issues/189
