### ISSUE TITLE
Traceback" Validation error for Settings SLEEP_BY_MIN_ENERGY. Input should be a valid list

### ISSUE THREAD

**Issue by ATAMAH161** [shamhi/HamsterKombatBot#216]
![IMG_1647](https://github.com/shamhi/HamsterKombatBot/assets/170763572/19a1baf3-3f5b-46e1-87af-484620fc8c23)

почему-то ошибка возникает еще когда requirements устанавливаешь, pip последней версии не ставит.

**Comment by iiust** [comment]
the same after the update

**Comment by ButCheR-PRO** [comment]
Дубликат https://github.com/shamhi/HamsterKombatBot/issues/194 
Дубликат 2 https://github.com/shamhi/HamsterKombatBot/issues/171
Дубликат 3 https://github.com/shamhi/HamsterKombatBot/issues/162
