### ISSUE TITLE
[Question] Hosting for the bot, which one would you use?

### ISSUE THREAD

**Issue by GiuseppeRazzetto** [shamhi/HamsterKombatBot#217]
hosting for the bot, does anyone know???

**Comment by borcrypto** [comment]
i use digital ocean

**Comment by mrranger** [comment]
Home server, pterodactyl

**Comment by ButCheR-PRO** [comment]
https://github.com/shamhi/HamsterKombatBot/issues/208

**Comment by ButCheR-PRO** [comment]
See this:
1. https://github.com/shamhi/HamsterKombatBot/issues/208
2. https://github.com/shamhi/HamsterKombatBot/pull/219

**Comment by DineshValor** [comment]
> Do you know how to use Termux for bots?

Did you find it or u can try mine (yesterday I made a fork for termux runnable).

**Comment by vheske** [comment]
> > Do you know how to use Termux for bots?
> 
> Did you find it or u can try mine (yesterday I made a fork for termux runnable).

Please share your fork with me

**Comment by DineshValor** [comment]
> > > Do you know how to use Termux for bots?
> > 
> > 
> > Did you find it or u can try mine (yesterday I made a fork for termux runnable).
> 
> Please share your fork with me

https://github.com/DineshValor/HamsterValor

**Comment by DineshValor** [comment]
Render.com & Koyeb.com
