### ISSUE TITLE
код на

### ISSUE THREAD

**Issue by treyne** [shamhi/HamsterKombatBot#2173]
код на
[1.zip](https://github.com/user-attachments/files/16405252/1.zip)
 python

_Originally posted by @trakds in https://github.com/shamhi/HamsterKombatBot/issues/1918#issuecomment-2254652673_
            Подскажите пожалуйста как перехватывали запросы в приложении. Я попробовал через Fiddler, установил сертификат на телефон и на комп. Единственное что смог перехватить запросы из браузера, приложения отказываются работать.

**Comment by Stelfelics** [comment]
я обнаружил способ как открыть тапалку через браузер и отслеживать запросы на сервак без сторонних прог (через браузер всё таки привычнее и как-то удобнее):
(заходишь в тг с браузера ПК -> заходишь в бота -> ПКМ по любому месту в тапалке -> код элемента -> ищешь iframe тэг и копируешь ссылку из src) копируешь ссылку тапалки с iframe, ищешь там tgWebAppPlatform и меняешь его параметр с weba на android, копируешь теперь уже обновлённую ссылку и вставляешь её снова в адресную строку. Проверил: хомяка, 1win, memefi, worm slap.. думаю и остальные заработают так. Надеюсь помог)

**Comment by treyne** [comment]
> я обнаружил способ как открыть тапалку через браузер и отслеживать запросы на сервак без сторонних прог (через браузер всё таки привычнее и как-то удобнее): (заходишь в тг с браузера ПК -> заходишь в бота -> ПКМ по любому месту в тапалке -> код элемента -> ищешь iframe тэг и копируешь ссылку из src) копируешь ссылку тапалки с iframe, ищешь там tgWebAppPlatform и меняешь его параметр с weba на android, копируешь теперь уже обновлённую ссылку и вставляешь её снова в адресную строку. Проверил: хомяка, 1win, memefi, worm slap.. думаю и остальные заработают так. Надеюсь помог)

Хомяка я давно вскрыл, мне интересно как перехватить запросы со сторонних приложений.

**Comment by Stelfelics** [comment]
> > я обнаружил способ как открыть тапалку через браузер и отслеживать запросы на сервак без сторонних прог (через браузер всё таки привычнее и как-то удобнее): (заходишь в тг с браузера ПК -> заходишь в бота -> ПКМ по любому месту в тапалке -> код элемента -> ищешь iframe тэг и копируешь ссылку из src) копируешь ссылку тапалки с iframe, ищешь там tgWebAppPlatform и меняешь его параметр с weba на android, копируешь теперь уже обновлённую ссылку и вставляешь её снова в адресную строку. Проверил: хомяка, 1win, memefi, worm slap.. думаю и остальные заработают так. Надеюсь помог)
> 
> Хомяка я давно вскрыл, мне интересно как перехватить запросы со сторонних приложений.

со сторонних это мини игры, в которых бот собирает ключи?

**Comment by treyne** [comment]
> > > я обнаружил способ как открыть тапалку через браузер и отслеживать запросы на сервак без сторонних прог (через браузер всё таки привычнее и как-то удобнее): (заходишь в тг с браузера ПК -> заходишь в бота -> ПКМ по любому месту в тапалке -> код элемента -> ищешь iframe тэг и копируешь ссылку из src) копируешь ссылку тапалки с iframe, ищешь там tgWebAppPlatform и меняешь его параметр с weba на android, копируешь теперь уже обновлённую ссылку и вставляешь её снова в адресную строку. Проверил: хомяка, 1win, memefi, worm slap.. думаю и остальные заработают так. Надеюсь помог)
> > 
> > 
> > Хомяка я давно вскрыл, мне интересно как перехватить запросы со сторонних приложений.
> 
> со сторонних это мини игры, в которых бот собирает ключи?

Как вариант, например whoosh или KFC и подобные

**Comment by Stelfelics** [comment]
> > > > я обнаружил способ как открыть тапалку через браузер и отслеживать запросы на сервак без сторонних прог (через браузер всё таки привычнее и как-то удобнее): (заходишь в тг с браузера ПК -> заходишь в бота -> ПКМ по любому месту в тапалке -> код элемента -> ищешь iframe тэг и копируешь ссылку из src) копируешь ссылку тапалки с iframe, ищешь там tgWebAppPlatform и меняешь его параметр с weba на android, копируешь теперь уже обновлённую ссылку и вставляешь её снова в адресную строку. Проверил: хомяка, 1win, memefi, worm slap.. думаю и остальные заработают так. Надеюсь помог)
> > > 
> > > 
> > > Хомяка я давно вскрыл, мне интересно как перехватить запросы со сторонних приложений.
> > 
> > 
> > со сторонних это мини игры, в которых бот собирает ключи?
> 
> Как вариант, например whoosh или KFC и подобные

попробуй приложение Reqable на андроид, а то у меня руки никак не доходят
