### ISSUE TITLE
Проблема с прокачкой у нулевых аккаунтов

### ISSUE THREAD

**Issue by si4man** [shamhi/HamsterKombatBot#221]
Добавил в бота несколько новых пустых аккаунтов без улучшений, бот на них только тапает. Если вручную купить любое улучшение, тогда бот начинает уже покупать разные карточки.

баланс на аккаунте есть но т.к. нет никаких карточек он без прокачки просто идёт отдыхать
![image](https://github.com/shamhi/HamsterKombatBot/assets/22753861/b1f7012a-31eb-41f7-8671-bf1b36d04b00)

**Comment by lolyinseo** [comment]
Есть такое

**Comment by ButCheR-PRO** [comment]
На аккаунт надо хотя бы раз зайти и хоть что-то купить. Это для безопасноти вашего же аккаунта. Не ленитесь.

**Comment by si4man** [comment]
> На аккаунт надо хотя бы раз зайти и хоть что-то купить. Это для безопасноти вашего же аккаунта. Не ленитесь.

Я первым делом всегда захожу на аккаунт сам, просто думал что возможно это баг, в любом случае спасибо за ответ
