### ISSUE TITLE
API To get current combo cards

### ISSUE THREAD

**Issue by l0v3m0n3y** [shamhi/HamsterKombatBot#2210]
Solved this problem with the help of 
data=requests.post("https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list",json={}).json()["data"]["dailyComboCards"]
for i in data:
i=i["card_name"]
It works well

**Comment by aozbebit** [comment]
In which file and on which line should we add this?


> Solved this problem with the help of data=requests.post("[https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list",json={}).json()["data"]["dailyComboCards"]](https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list%22,json=%7B%7D).json()%5B%22data%22%5D%5B%22dailyComboCards%22%5D) for i in data: i=i["card_name"] It works well

**Comment by l0v3m0n3y** [comment]
> In which file and on which line should we add this?
> 
> > Solved this problem with the help of data=requests.post("[https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list",json={}).json()["data"]["dailyComboCards"]](https://hamstercombos.com/hamstercombos/public/api/hamster-kombat-card-list%22,json=%7B%7D).json()%5B%22data%22%5D%5B%22dailyComboCards%22%5D) for i in data: i=i["card_name"] It works well

This function gives the name of the combo cards. In my script I formatted it like this
![Screenshot_2024-08-15-20-25-58-332](https://github.com/user-attachments/assets/47afd414-ef24-4872-a861-6eb3a64f2656)
