### ISSUE TITLE
вопрос по поводу USE_RANDOM_MINI_GAME_KEY

### ISSUE THREAD

**Issue by SmILeTheMobster** [shamhi/HamsterKombatBot#2220]
стоит ли включать этот параметр или нет, не совсем понимаю на что он влияет
понятное дело что рандомный ключ, но рандомный вплане любой даже не подходящий будет пробовать или как?

**Comment by treyne** [comment]
Он будет подходить в любом случае, различается механизм генерации.
Файл HamsterKombatBot/bot/utils/scripts.py строка 93 
И строка 101
