### ISSUE TITLE
socket.send() raised exception.

### ISSUE THREAD

**Issue by pixelincorp** [shamhi/HamsterKombatBot#223]
![image](https://github.com/shamhi/HamsterKombatBot/assets/169544547/2a1bd0d2-6581-4912-b661-980c78915a51)

**Comment by avtosubaru25** [comment]
> ![image](https://private-user-images.githubusercontent.com/169544547/337629588-2a1bd0d2-6581-4912-b661-980c78915a51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjE5NjYsIm5iZiI6MTcxNzc2MTY2NiwicGF0aCI6Ii8xNjk1NDQ1NDcvMzM3NjI5NTg4LTJhMWJkMGQyLTY1ODEtNDkxMi1iNjYxLTk4MGM3ODkxNWE1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxMjAxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWFiN2E1N2I5OWRhZjdiZDNhMGRkMjUzYmVjNzcwY2VhNTgyNTk1OWRmZGFlYTMyYTZmOWVmZTViN2E1NjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QEyB3C3oo2w249prN_4ahpj_U8UuTH6cEyUPYd1AYZA)

а ты не выключай по идее он потом отдупляет и дальше начинает работать

**Comment by ButCheR-PRO** [comment]
Restarting the docker container (docker compose restart) simply fixes it!
I guess in such cases, in some environments (e.g. Docker) it's better to exit the bot completely so Docker will automatically start it again and the error is disappeared (this is a quick fix if handling all the errors correctly takes time to implement).

**Comment by pixelincorp** [comment]
> Перезапуск докер-контейнера ( `docker compose restart`) просто исправляет ситуацию! Я предполагаю, что в таких случаях в некоторых средах (например, Docker) лучше полностью выйти из бота, чтобы Docker автоматически запустил его снова, и ошибка исчезла (это быстрое исправление, если для правильной обработки всех ошибок требуется время).

CommandNotFoundException

**Comment by pixelincorp** [comment]
> > ![изображение](https://private-user-images.githubusercontent.com/169544547/337629588-2a1bd0d2-6581-4912-b661-980c78915a51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NjE5NjYsIm5iZiI6MTcxNzc2MTY2NiwicGF0aCI6Ii8xNjk1NDQ1NDcvMzM3NjI5NTg4LTJhMWJkMGQyLTY1ODEtNDkxMi1iNjYxLTk4MGM3ODkxNWE1MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxMjAxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWFiN2E1N2I5OWRhZjdiZDNhMGRkMjUzYmVjNzcwY2VhNTgyNTk1OWRmZGFlYTMyYTZmOWVmZTViN2E1NjI0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QEyB3C3oo2w249prN_4ahpj_U8UuTH6cEyUPYd1AYZA)
> 
> а ты не выключай по идее, он потом отдупляет и дальше начинает работать

час ждал

**Comment by avtosubaru25** [comment]
А версия пайтон у тебя какая , у меня 3.11 и все норм

пт, 7 июн. 2024 г., 18:06 pixelincorp ***@***.***>:

**Comment by GravelFire** [comment]
Создайте пж блеклист на покупку всякой фигни.
![Screenshot_32](https://github.com/shamhi/HamsterKombatBot/assets/37264286/ff9d779c-7500-406d-bd14-af212c06ec0f)
Это вообще рофл, можно хоть в мемы с хомяком выкладывать..

**Comment by shamhi** [comment]
> удалил vscode и python, переустановил, скачал заново скрипт, добавил новые id/hash. зависло на создании новой сессии, буду ждать... ![image](https://private-user-images.githubusercontent.com/169544547/337689359-34df6c97-77a3-4b24-9af4-9889141daaa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzI4ODQsIm5iZiI6MTcxNzc3MjU4NCwicGF0aCI6Ii8xNjk1NDQ1NDcvMzM3Njg5MzU5LTM0ZGY2Yzk3LTc3YTMtNGIyNC05YWY0LTk4ODkxNDFkYWFhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwN1QxNTAzMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NWZkZmQ4Y2RhMWZjMjRjY2E3MGRjYTFiZjE5NGM4YzhkNDg5ODUwZDQ3MDk2OTliNDQ1MWMwNzRmOTRlNzIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.p0DxysP-dN_mC163AhI_SPLaZHMEdtWxnOfvDg_1z5o)

синхронизируй системное время

**Comment by pixelincorp** [comment]
> синхронизируй системное время

ты гений, спасибо!
