### ISSUE TITLE
как-то оч много попыток для мини игры My Clone Army

### ISSUE THREAD

**Issue by SmILeTheMobster** [shamhi/HamsterKombatBot#2246]
![image](https://github.com/user-attachments/assets/cb7227f2-0122-498c-a6e4-3ca2dea4aeb6)

**Comment by Inquisitor007** [comment]
Нужно увеличить event_timeout

**Comment by ilya125625262** [comment]
> Нужно увеличить event_timeout

Подскажи пожалуйста, в каком файле и на что нужно поменять?

**Comment by SmILeTheMobster** [comment]
Я если не ошибаюсь, то с новой обновой таймауты для игр все в конфиге хранятся вне бота

**Comment by shamhi** [comment]
Исправлено
