### ISSUE TITLE
[Предложение] Добавить Комбо.

### ISSUE THREAD

**Issue by KOTBCTAKAHE** [shamhi/HamsterKombatBot#225]
Можем сделать чтобы, комбо бралось с сервера, который я верстану, я там буду писать айди комбо карт, и скрипт, должен смотреть, выгодно ли покупать это комбо, типо можно в минус уйти, если выгодно то оно берется. Я могу помочь с сервером, для того чтобы скрипт смотрел какие комбо карты. Просто если разработчик, будет вручную в репозиторий ставить json, с комбо, то он замучается, а так я буду сам на сервер это загружать. Как вам такое предложение?

**Comment by ButCheR-PRO** [comment]
Ещё и азбуку-морзе прикрутить, чтоб оно само тапало слова BTC, ETHEREUM и т.д.)

**Comment by KOTBCTAKAHE** [comment]
> Ещё и азбуку-морзе прикрутить, чтоб оно само тапало слова BTC, ETHEREUM и т.д. и собирало по 1кк

Да, было бы отлично

**Comment by shamhi** [comment]
> Ещё и азбуку-морзе прикрутить, чтоб оно само тапало слова BTC, ETHEREUM и т.д. и собирало по 1кк

так уже, вчера добавил

**Comment by KOTBCTAKAHE** [comment]
> > Ещё и азбуку-морзе прикрутить, чтоб оно само тапало слова BTC, ETHEREUM и т.д. и собирало по 1кк
> 
> так уже, вчера добавил

А, точно, сейчас увидел. Спасибо вам большое! А откуда скрипт узнает какой шифр на сегодняшний день?

**Comment by shamhi** [comment]
> > так уже, вчера добавил
> 
> Спасибо вам большое за вашу работу! У меня возник вопрос: каким образом скрипт узнает, какой шифр актуален на сегодняшний день?

в конфиге передается base64 строка, ее нужно декодировать

**Comment by KOTBCTAKAHE** [comment]
> в конфиге передается base64 строка, ее нужно декодировать

Спасибо вам большое за быстрый и подробный ответ!

Хотел бы предложить свою помощь: могу настроить  хост, где я буду ежедневно писать, какие комбо карты на сегодня (дату тоже писать буду) это будет некий json файл на сервере.

**Comment by shamhi** [comment]
> > в конфиге передается base64 строка, ее нужно декодировать
> 
> Спасибо вам большое за быстрый и подробный ответ!
> 
> Хотел бы предложить свою помощь: могу настроить хост, где я буду ежедневно писать, какие комбо карты на сегодня (дату тоже писать буду) это будет некий json файл на сервере.
> 
> Хост будет довольно надёжный.

разверни мелкую апишку, которая принимает 1 запрос на получение комбо карт

**Comment by KOTBCTAKAHE** [comment]
> > разверни мелкую апишку, которая принимает 1 запрос на получение комбо карт

GET
https://api21.datavibe.top/api/GetCombo

пойдет такое?

**Comment by shamhi** [comment]
> > > разверни мелкую апишку, которая принимает 1 запрос на получение комбо карт
> 
> GET https://api21.datavibe.top/api/GetCombo
> 
> пойдет такое?

{"combo":["qa_team","meme_coins","license_japan"],"date":"07-06-24"}

да, спасибо

**Comment by KOTBCTAKAHE** [comment]
> да, спасибо

Вам спасибо!

**Comment by KOTBCTAKAHE** [comment]
Думаю, стоит закрыть этот диалог. Спасибо автору.
