### ISSUE TITLE
New Games

### ISSUE THREAD

**Issue by KOTBCTAKAHE** [shamhi/HamsterKombatBot#2253]
Mud Racing и Mow and Trim

**Comment by miladesign** [comment]
appToken is same as promoId
```
{
        "name": "Mow and Trim",
        "appToken": "ef319a80-949a-492e-8ee0-424fb5fc20a6",
        "promoId": "ef319a80-949a-492e-8ee0-424fb5fc20a6"
}
```
`TRIM-YNW-3Y8B-YGTA-1YX`

```
{
        "name": "Mud Racing",
        "appToken": "8814a785-97fb-4177-9193-ca4180ff9da8",
        "promoId": "8814a785-97fb-4177-9193-ca4180ff9da8",
}
```
`RACE-XMR-QPT5-YYRP-NLC`

**Comment by sxrryformyabuze** [comment]
Им уже реально пофиг, что делают promoId и appToken одинаковыми? :/

**Comment by Garrri** [comment]
> appToken is same as promoId
> 
> ```
> {
>         "name": "Mow and Trim",
>         "appToken": "ef319a80-949a-492e-8ee0-424fb5fc20a6",
>         "promoId": "ef319a80-949a-492e-8ee0-424fb5fc20a6"
> }
> ```
> 
> `TRIM-YNW-3Y8B-YGTA-1YX`
> 
> ```
> {
>         "name": "Mud Racing",
>         "appToken": "8814a785-97fb-4177-9193-ca4180ff9da8",
>         "promoId": "8814a785-97fb-4177-9193-ca4180ff9da8",
> }
> ```
> 
> `RACE-XMR-QPT5-YYRP-NLC`

Спасибо

**Comment by SilentMajor1ty** [comment]
> Им уже реально пофиг, что делают promoId и appToken одинаковыми? :/

А кому не похуй?

**Comment by KVDcorp** [comment]
Перерыл все файлы, куда это кидать?

**Comment by KOTBCTAKAHE** [comment]
> Перерыл все файлы, куда это кидать?

никуда

**Comment by mlcni** [comment]
> Им уже реально пофиг, что делают promoId и appToken одинаковыми? :/

Главное назначение тапалок: привлечь как можно людей к использованию Ton. А там уж за что будут розданы токены: за чесание пяткой за ухом, тапанье или ключи: не столь важно.

**Comment by shamhi** [comment]
> Перерыл все файлы, куда это кидать?

В оригинальной версии уже есть новые игры, теперь даже обновлять не нужно, мы сами добавим их [сюда](https://api21.datavibe.top/api/Games)

**Comment by kyt3** [comment]
Таймаут 31 по интуиции взят или есть какая-то инфа? Спрашиваю, потому что раньше люди JSON кидали с таймаутом, хоть я и не знаю это они от себя добавили или реально где-то нарыли))

**Comment by aboange** [comment]
Python ??
