### ISSUE TITLE
Неправильные комбо 23/08/2024

### ISSUE THREAD

**Issue by newtoneweb** [shamhi/HamsterKombatBot#2256]
ответ от https://api21.datavibe.top/api/GetCombo
`{
    "combo": [
        "margin_trading_x10",
        "sleeping_hamster",
        "negotiations_partners"
    ],
    "date": "23-08-24"
}`
там должен быть
"margin_trading_x50",

**Comment by KOTBCTAKAHE** [comment]
исправлено, скрипт неправильно ввел комбо. извиняюсь
