### ISSUE TITLE
Не покупает апргейды

### ISSUE THREAD

**Issue by 4erdenko** [shamhi/HamsterKombatBot#227]
Я вижу, что по дефолту всё должно покупаться.
Лимит BALANCE_TO_SAVE=20000000.
Но ничего не покупает.
И что такое "круг" ?

**Comment by 4erdenko** [comment]
Карточки, ничего не покупает.
Версия последняя.

**Comment by join1337** [comment]
> Карточки, ничего не покупает. Версия последняя.

скинь конфиг свой .env

**Comment by 4erdenko** [comment]
https://github.com/shamhi/HamsterKombatBot/issues/228#issuecomment-2155642921

Ну такое. Всё таки я бы поправил это.
