### ISSUE TITLE
Minigame Unknown error: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by snowline-dev** [shamhi/HamsterKombatBot#2277]
Minigame auto claim is no longer working. I got error: Unknown error: 'NoneType' object is not subscriptable

**Comment by cmeept** [comment]
Update the bot

**Comment by snowline-dev** [comment]
> Update the bot

already done this. nothing changed

**Comment by nikhilpatidar** [comment]
yes its not working
