### ISSUE TITLE
Новая игра и миниигра на ключ

### ISSUE THREAD

**Issue by cmeept** [shamhi/HamsterKombatBot#2279]
1) Вроде как добавили игру в API cafe dash но бот ее не играет .
2) После того как перенесли вчера игру puzzle game с миниигры в плайгроунд то игра не играет и не дает ключ .
Как решить ?

**Comment by cmeept** [comment]
API  починили . А мини игра на ключ ?

**Comment by pekatron9000** [comment]
> API починили . А мини игра на ключ ?

в другой теме человек выложил фикс мини игры на ключ вместе с автофармом hexa puzzle
https://github.com/shamhi/HamsterKombatBot/issues/2268#issuecomment-2315420451

**Comment by DineshValor** [comment]
@shamhi bro there are lot of ready requested and there solution, plz merge them, so everyone can access it.
