### ISSUE TITLE
Bug report: Auto-upgrade not working in tapper.py

### ISSUE THREAD

**Issue by kamranmt21** [shamhi/HamsterKombatBot#228]
Dear Programmer,

I'd like to report a bug in the **auto-upgrade** functionality within the bot.

### Steps to reproduce:
1. Started 'hamster kombat' on a new Telegram account without any upgrades.
2. Observed that **'profit per hour'** remained at 0, and the auto-upgrade feature wasn't working.
3. Manually performed an upgrade, which caused 'profit per hour' to increase above 0. Only then did auto-upgrade start functioning.

### Investigation:
I investigated the code and believe the issue lies in **bot/core/tapper.py** on line **484**. The condition `"price < max_price_limit"` seems to prevent **auto-upgrade** from working when **'profit per hour'** is 0.

### Proposed solution:
I propose adding an if-clause to check if **'profit per hour'** is not equal to 0 before evaluating the `"price < max_price_limit"` condition. This should allow auto-upgrade to function properly regardless of the initial **'profit per hour'** value.

Thank you for your time and consideration.

**Comment by si4man** [comment]
#221 
"You have to log into the account at least once and buy something. It's for the safety of your account. Don't be lazy."

**Comment by Mik-chan** [comment]
Probably related to my issue, which everyoe ignored for some reason: #209

**Comment by 4erdenko** [comment]
Same problem. Already buy 1 upgrade and 1 card, create new session - nothing.

**Comment by ButCheR-PRO** [comment]
Log into your account from your phone and buy several cards manually in the game.

**Comment by 4erdenko** [comment]
https://github.com/shamhi/HamsterKombatBot/commit/8f89f4b5a8a24a2d7dc16f1a0eed01bac80c4baf
