### ISSUE TITLE
API Telegram Error

### ISSUE THREAD

**Issue by Homavi88** [shamhi/HamsterKombatBot#2280]
Вопрос возможно не такой актуальный, но по какой то причине я не могу получить  api telegram ,  ввыдаёт ошибку - error
Гугл или Яндекс особо не помог решить проблему

есть ли возможно как то получить ключи чтобы запустить бот ?

**Comment by Boomkuze** [comment]
> Вопрос возможно не такой актуальный, но по какой то причине я не могу получить  api telegram ,  ввыдаёт ошибку - error Гугл или Яндекс особо не помог решить проблему
> 
> есть ли возможно как то получить ключи чтобы запустить бот ?

Ну камон в описании же всё есть.
https://my.telegram.org/

![image](https://github.com/user-attachments/assets/a2b6f7d7-68be-46f3-b938-da94f0dbed59)

**Comment by Homavi88** [comment]
> > Вопрос возможно не такой актуальный, но по какой то причине я не могу получить  api telegram ,  ввыдаёт ошибку - error Гугл или Яндекс особо не помог решить
> > есть ли возможно как то получить ключи чтобы запустить бот ?
> 
> Ну камон в описании же всё есть. https://my.telegram.org/
> 
> ![image](https://private-user-images.githubusercontent.com/111609736/362417115-a2b6f7d7-68be-46f3-b938-da94f0dbed59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MDMzMDEsIm5iZiI6MTcyNDkwMzAwMSwicGF0aCI6Ii8xMTE2MDk3MzYvMzYyNDE3MTE1LWEyYjZmN2Q3LTY4YmUtNDZmMy1iOTM4LWRhOTRmMGRiZWQ1OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwMzQzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjcwY2QzZTZlZDVjODNjOTc0NGRlNGY5MzUxYmUzZGNiZWYzNjMzOWFkNjgyODE3NDVlZDgwZjU5NjE0MjE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tZzV3wRooE-RWu0-OfDNE-mXw9wwSFHAVMOc0KsaXkU)

Проблема в том что я все заполняю но получаю просто ошибку Error без описания и все.

**Comment by d-kurchenko** [comment]
> Проблема в том что я все заполняю но получаю просто ошибку Error без описания и все. 

Попробуйте заполнить поле description, мне помогло. Еще читал что проблема может быть из за сети (возможно vpn)
