### ISSUE TITLE
2 новые игры Zoopolis и Gang Wars

### ISSUE THREAD

**Issue by krot12345** [shamhi/HamsterKombatBot#2288]

**Comment by Kartoshka2331** [comment]
"zoopolis": {
        "name": "Zoopolis",
        "app_token": "b2436c89-e0aa-4aed-8046-9b0515e1c46b",
        "promo_id": "b2436c89-e0aa-4aed-8046-9b0515e1c46b"
    },
    "gangs_wars": {
        "name": "Gangs Wars",
        "app_token": "b6de60a0-e030-48bb-a551-548372493523",
        "promo_id": "c7821fa7-6632-482c-9635-2bd5798585f9"
    }

**Comment by offramzes** [comment]
where to past this code?

**Comment by DineshValor** [comment]
> Where to paste this code?

Will soon updated on bot api, no need to update anything
