### ISSUE TITLE
Enter phone number or bot token...

### ISSUE THREAD

**Issue by AKTanara** [shamhi/HamsterKombatBot#2305]
I was trying to create a session not by phone number but by Bot Token!
I entered the Bearer authorization that got from browser and entered as bot token. Resulted in many many errors....
Obviously I'm doing it wrong. Can you please guide me to right direction please?
![image](https://github.com/user-attachments/assets/d83d2df2-df9d-4dca-b3a4-d1dce97fb321)

**Comment by tancyit3** [comment]
you need to log in using your phone number, otherwise your hamster won't work

**Comment by AKTanara** [comment]
Thanks
