### ISSUE TITLE
Игра Tiles выдает ошибку

### ISSUE THREAD

**Issue by cmeept** [shamhi/HamsterKombatBot#2307]
Запустил и вот что получилось . это последний обновленный бот 3.0
![image](https://github.com/user-attachments/assets/cc5fa3d7-678c-42ee-9e41-0e1642d60c2c)

**Comment by TheMeror** [comment]
![image](https://github.com/user-attachments/assets/1f523a61-c3bc-4a84-b3fa-5d4178c5afd1)
Скачать отсюда (Download ZIP)

**Comment by vciumak** [comment]
> Запустил и вот что получилось . это последний обновленный бот 3.0 ![image](https://private-user-images.githubusercontent.com/35558327/363413979-cc5fa3d7-678c-42ee-9e41-0e1642d60c2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDkyNDMsIm5iZiI6MTcyNTEwODk0MywicGF0aCI6Ii8zNTU1ODMyNy8zNjM0MTM5NzktY2M1ZmEzZDctNjc4Yy00MmVlLTllNDEtMGUxNjQyZDYwYzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEyNTU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyYzM1NTFiMjQyNjI4MDY4M2I3MmVhY2I5ZWE5MjdjYzJkMjEyY2RiMmNlMjliMmI4YzQ2MTQ2MTUzODIwZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ySkhEnaWEfoObLAscR8noDycBv_srsYZvffEV0aE05w)

Гы, а у меня несколько другое %)))

![Untitled](https://github.com/user-attachments/assets/ce93ed35-0c90-4bc1-a51b-1139eadd095b)

**Comment by vciumak** [comment]
> Запустил и вот что получилось . это последний обновленный бот 3.0 ![image](https://private-user-images.githubusercontent.com/35558327/363413979-cc5fa3d7-678c-42ee-9e41-0e1642d60c2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMTAwMTYsIm5iZiI6MTcyNTEwOTcxNiwicGF0aCI6Ii8zNTU1ODMyNy8zNjM0MTM5NzktY2M1ZmEzZDctNjc4Yy00MmVlLTllNDEtMGUxNjQyZDYwYzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEzMDgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyY2JjMmE5ODlmNDBlMGU1NTJmZjAxOWY1ZjNiZDgzNzI5MTlkYjc3ZmUwY2QxOTUzNjdlYWNlMjNkNDZmODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t0fGpFRsRP5jkSzXw3rQ0BONIAfUGx2tG4Zn2yOQEmU)

Вобщем, работает все, только сервер хомяка глючит.

![Untitled](https://github.com/user-attachments/assets/dd1848ec-255e-408a-bec3-c9912d90e583)

**Comment by vciumak** [comment]
> Запустил и вот что получилось . это последний обновленный бот 3.0 ![image](https://private-user-images.githubusercontent.com/35558327/363413979-cc5fa3d7-678c-42ee-9e41-0e1642d60c2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMTAyOTAsIm5iZiI6MTcyNTEwOTk5MCwicGF0aCI6Ii8zNTU1ODMyNy8zNjM0MTM5NzktY2M1ZmEzZDctNjc4Yy00MmVlLTllNDEtMGUxNjQyZDYwYzJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEzMTMxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNzBiZTU0NmZiMmYzOTZiZThlODMwMDU1ODUyMjg2Zjk5NDdmOTE2MDE2MDYzNzc3MmRkZmEzMThhNWM3NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GxLM1G0jXoXLoUZkW0Fq0OKhrybkHbHaLrT_rcYy5mk)

А, забыл главное добавит, - надо обновить скрипты бота. Шамхи обновы выкатил, буквально, вот, только что. как раз правил ошибки по мини-играм.

**Comment by cmeept** [comment]
> !
> Скачать отсюда (Download ZIP)
Сделай одолжение . Не пиши .

**Comment by cmeept** [comment]
> ![image](https://github.com/user-attachments/assets/1f523a61-c3bc-4a84-b3fa-5d4178c5afd1)
> Скачать отсюда (Download ZIP)
Сделай одолжение не пиши
