### ISSUE TITLE
Hexa Puzzle redeem problem

### ISSUE THREAD

**Issue by Fast0n** [shamhi/HamsterKombatBot#2311]
If the bot is running, the hexa puzzle mini game does not redeem the reward

![image](https://github.com/user-attachments/assets/b50fad9b-2185-47c0-ad64-3ce2f3cf24af)

**Comment by pmkod2** [comment]
> If the bot is running, the hexa puzzle mini game does not redeem the reward
> 
> ![image](https://private-user-images.githubusercontent.com/5260133/363445422-b50fad9b-2185-47c0-ad64-3ce2f3cf24af.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzY2NjEsIm5iZiI6MTcyNTE3NjM2MSwicGF0aCI6Ii81MjYwMTMzLzM2MzQ0NTQyMi1iNTBmYWQ5Yi0yMTg1LTQ3YzAtYWQ2NC0zY2UyZjNjZjI0YWYuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA3MzkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZDY1NmU2MTYyZDk3ZGZmZGQ2MWUzODZlNzY3OTQ3YmZkYmM4NDMxMTA4ZDE5Y2JhNzNiZjI3ODA4NzBhYWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0L4pXvF1IORNqk1S_p-v7MAeOKFledCYaZWPeCeDyT8)

Sorry for the possibly stupid question, but have you opened the bot window and are you monitoring the bot's actions? How did you do that?
