### ISSUE TITLE
proxies.txt

### ISSUE THREAD

**Issue by Defarion** [shamhi/HamsterKombatBot#2313]
Подскажите плз, как указать в файле прокси свой айпи/порт или чтобы другая сессия не использовала прокси?

К примеру я имею две сессии и чтобы одна использовала прокси, а вторая нет.

т.к. если указать просто одни прокси, то все сессии его будут использовать.

**Comment by shamhi** [comment]
Используй [профили](https://github.com/shamhi/HamsterKombatBot?tab=readme-ov-file)

**Comment by Defarion** [comment]
с профилями все понятно, не во всех играх есть профили (мемефи, тапсвап). Можно ли это как-то реализовать с помощью файла?
