### ISSUE TITLE
Mini game Tiles error

### ISSUE THREAD

**Issue by snowline-dev** [shamhi/HamsterKombatBot#2314]
Unknown error while Claim Mini Game: 400, message='Bad Request', url=URL('https://api.hamsterkombatgame.io/clicker/claim-daily-keys-minigame') | Response text: {"error_code":"DAILY_KEYS_MINI_GAME_NEGATIVE_POINTS","error_message":"MiniGame negative points"}...

**Comment by cmeept** [comment]
Did you install a new bot? Or did you update it? Like copy paste ?

**Comment by snowline-dev** [comment]
> Did you install a new bot? Or did you update it? Like copy paste ? In the env file, did you delete USE_RANDOM_MINI_GAME_KEY ?

thanks, I usually update using git pull. Forgot remove env variable. Now everything is OK.
