### ISSUE TITLE
New game Fluff Crusade

### ISSUE THREAD

**Issue by afillimonov** [shamhi/HamsterKombatBot#2331]
![Screenshot_2024-09-04-10-35-29-022-edit_org.telegram.messenger.jpg](https://github.com/user-attachments/assets/e3c8df8d-172c-4f2f-a7e8-1f85aad4c52d)

is it possible to automate?

**Comment by aboange** [comment]
appToken ?

**Comment by Garrri** [comment]
Приветствую, есть у кого промоид на новые игры?

**Comment by igorjok** [comment]
name: 'Tile Trio',
            appToken: 'e68b39d2-4880-4a31-b3aa-0393e7df10c7',
            promoId: 'e68b39d2-4880-4a31-b3aa-0393e7df10c7',

name: 'Fluff Crusade',
            appToken: '112887b0-a8af-4eb2-ac63-d82df78283d9',
            promoId: '112887b0-a8af-4eb2-ac63-d82df78283d9',

**Comment by Garrri** [comment]
> name: 'Tile Trio', appToken: 'e68b39d2-4880-4a31-b3aa-0393e7df10c7', promoId: 'e68b39d2-4880-4a31-b3aa-0393e7df10c7',
> 
> name: 'Fluff Crusade', appToken: '112887b0-a8af-4eb2-ac63-d82df78283d9', promoId: '112887b0-a8af-4eb2-ac63-d82df78283d9',

Спасибо огромное

**Comment by igorjok** [comment]
Fluff Crusade большие тайминги, у меня 120+ только отдает токены

**Comment by Alex22891** [comment]
Что вообще дает игра Fluff Crusade?

**Comment by Defarion** [comment]
> Что вообще дает игра Fluff Crusade?

монеты, чем больше доход в час, тем больше монет

**Comment by WeendVidente777** [comment]
при доходе в 8 лямов с копейками дает 14.5 лямов за код.

**Comment by WeendVidente777** [comment]
> > Fluff Crusade
> 
> 25с стандартный тайминг, отдает легко

после логина нужен длинный слип, у меня на 30 не сработало, а на 120 пошло. Зато после него сразу отдает.

**Comment by Hronojo** [comment]
Есть у кого хорошие генераторы которые сразу много генерируют ?

**Comment by argoarsiks** [comment]
ребята, у вас тайминга дерьма. У меня везде стоят по 20 секунд тайминги и все генерирует

**Comment by dukerok** [comment]
вот генерируете вы, генерируете, а никто и не заметил что url-ки то другие у запросов оригинальных

**Comment by snackshell** [comment]
app token ?

Stone Age
