### ISSUE TITLE
Error on Getting Access Tokens and Nuxt Builds | Ошибка при получении токенов доступа и сборок Nuxt

### ISSUE THREAD

**Issue by tektungg** [shamhi/HamsterKombatBot#2349]
I am getting error getting access token and nuxt builds since latest update like this:
![image](https://github.com/user-attachments/assets/6fdb0657-7f18-4ff2-9510-0b1c385d5ca1)

==============================================================

Я получаю ошибку при получении токена доступа и сборки nuxt после последнего обновления, как это:
![image](https://github.com/user-attachments/assets/e7481214-0c5b-490d-b5b5-5b2de69a7e7c)

**Comment by Color-maN** [comment]
Тоже самое на аккаунтах после подключения к ним прокси

**Comment by arthur469** [comment]
[Maybe a proxy issue ? See here, maybe it can help you (https://github.com/shamhi/HamsterKombatBot/issues/2373)
