### ISSUE TITLE
venv\Scripts\activate Системе не удается найти указанный путь.

### ISSUE THREAD

**Issue by pythonhk22** [shamhi/HamsterKombatBot#235]
При установке застреваю на пункте 2

\HamsterKombatBot>venv\Scripts\activate
Системе не удается найти указанный путь.

**Comment by ButCheR-PRO** [comment]
Если ты скачал архив и распаковал папку с ботом, установил библиотеке, а потом переименовал папку HamsterKombatBot-main в HamsterKombatBot, то тебе придётся заново выполнить установку. 

#Получение API ключей:
1. Перейдите на сайт [my.telegram.org](https://my.telegram.org) и войдите в систему, используя свой номер телефона.
2. Выберите "API development tools" и заполните форму для регистрации нового приложения.
3. Запишите API_ID и API_HASH в файле .env, предоставленные после регистрации вашего приложения.

#Установка:
Скачай и установи: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Затем синхронизируйте на компьютере системное время.
Скачай последнюю версию бота [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) и распакуй.
Потом запусти INSTALL.bat. 
Затем нужно настроить конфиг .env согласно документации в README.md
После этого нужно создать сессию через START.bat выбрав пункт 1. 
И только потом запускать настроенный кликер через START.bat выбрав пункт 2.

**Comment by pythonhk22** [comment]
Это я через Git пытался. Теперь создал виртуалку Win10, установил эту версию питона, распаковал и переименовал архив. Запустил install. 

Creating virtual environment...
Python Activating virtual environment...
Системе не удается найти указанный путь.
Installing dependencies...
"pip" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
Copying .env-example to .env...
Скопировано файлов:         1.
Please edit the .env file to add your API_ID and API_HASH.
Для продолжения нажмите любую клавишу . . .

**Comment by pythonhk22** [comment]
start тоже не может найти путь

**Comment by pythonhk22** [comment]
При попытке установки через git, в виртуалке пишет Pthon was not found but can be installed from Microsoft Store

**Comment by pythonhk22** [comment]
> Если ты скачал архив и распаковал папку с ботом, установил библиотеки, а потом переименовал папку HamsterKombatBot-main в HamsterKombatBot, то тебе придётся заново выполнить установку.
> 
> # Получение API ключей:
> 1. Перейдите на сайт [my.telegram.org](https://my.telegram.org) и войдите в систему, используя свой номер телефона.
> 2. Выберите "API development tools" и заполните форму для регистрации нового приложения.
> 3. Запишите API_ID и API_HASH в файле .env, предоставленные после регистрации вашего приложения.
> 
> # Установка:
> Скачай и установи: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/) Затем синхронизируйте на компьютере системное время. Скачай последнюю версию бота [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) и распакуй. Потом запусти INSTALL.bat. Затем нужно настроить конфиг .env согласно документации в README.md После этого нужно создать сессию через START.bat выбрав пункт 1. И только потом запускать настроенный кликер через START.bat выбрав пункт 2.

Activating virtual environment...
Системе не удается найти указанный путь.
Starting the bot...
Python Для продолжения нажмите любую клавишу . . .

**Comment by pythonhk22** [comment]
API_ID=********
API_HASH=*******************************

MIN_AVAILABLE_ENERGY=100
SLEEP_BY_MIN_ENERGY=5

ADD_TAPS_ON_TURBO= 5500

AUTO_UPGRADE=True
MAX_LEVEL=6

BALANCE_TO_SAVE=1000
UPGRADES_COUNT=10

APPLY_DAILY_ENERGY=True
APPLY_DAILY_TURBO=True

RANDOM_TAPS_COUNT=[20,190]
SLEEP_BETWEEN_TAP=[12,30]
USE_PROXY_FROM_FILE=False

**Comment by pythonhk22** [comment]
Оказалось что Питон надо в корень диска ставить
