### ISSUE TITLE
как отключить автокликер?

### ISSUE THREAD

**Issue by aleksei1951** [shamhi/HamsterKombatBot#236]
не нашёл такой возможности в настройках. очень нужна просто прокачка карточек. (+ риск бана из за использования автокликера немного напрягает)

**Comment by ButCheR-PRO** [comment]
Попробуй в .env:
`RANDOM_TAPS_COUNT=[0,0]`

**Comment by aleksei1951** [comment]
> А при использовании бота рисков нет?)

риск есть всегда, но если есть возможность его уменьшить, то почему бы и нет?

**Comment by aleksei1951** [comment]
> Попробуй в .env: `RANDOM_TAPS_COUNT=[0,0]`

не работает((

**Comment by stalker-run** [comment]
RANDOM_TAPS_COUNT=[1,2]
SLEEP_BETWEEN_TAP: list[int] = [5999, 6001]
1-2 тапа каждые 100 минут, потом апдейт карточек, не думаю что смертельно 1-2 клика.

**Comment by stalker-run** [comment]
> > Попробуй в .env: `RANDOM_TAPS_COUNT=[0,0]`
> 
> не работает((

RANDOM_TAPS_COUNT=[1,2]
SLEEP_BETWEEN_TAP: list[int] = [5999, 6001]
1-2 тапа каждые 100 минут, потом апдейт карточек, не думаю что смертельно 1-2 клика.

**Comment by ButCheR-PRO** [comment]
Чтобы полностью отьключить тапы:
```
RANDOM_TAPS_COUNT=[0,1]
APPLY_DAILY_ENERGY=False
APPLY_DAILY_TURBO=False
ADD_TAPS_ON_TURBO=0
```
