### ISSUE TITLE
🆕🆘⛔️📛After 1click in run clicker  my Telegram account was deleted / После 1 клика по кликеру «Запустить» моя учетная запись Telegram была удалена🆘

### ISSUE THREAD

**Issue by Mahnazmohammadii** [shamhi/HamsterKombatBot#237]
### RU LANG 

> Привет, я последовал вашим предыдущим рецептам и рекомендациям.
> Я также использовал учетную запись пользователя, созданную в 2018 году.
> Я установил часовой пояс сервера в Нидерланды, Амстердам, поскольку Telegram фильтруется в Иране, и подключаюсь к Telegram через VPN с тем же IP.
> Вариант 1 создал успешный сеанс
> После запуска кликера менее секунды мой аккаунт в Telegram был удален 
> Я установил значения env на самые низкие и лучшие из возможных.
> Логи бота прилагаю 
> Такой скриншот
> пожалуйста, помогите мне

### ENGLISH 
> Hi, I followed your previous recipes and recommendations
> I also used a user account created in 2018
> I set the time zone of the server to Netherlands, Amsterdam, because Telegram is filtered in Iran, and I connect to Telegram with the VPN of the same IP.
> Option 1 created a successful session
> After running the clicker for less than a second, my Telegram account was deleted 
> I set the env values ​​to the lowest and best possible

I have attached the bot logs 
> [log.txt](https://github.com/user-attachments/files/15749263/log.txt)

> Such a screenshot
![ban2](https://github.com/shamhi/HamsterKombatBot/assets/167020867/358c6b62-bffb-41d3-9692-c90d460c6733)

> Please help me
REFAER ANTHOR MY ISUSE 
#233 
#202 
PLASS READ REFRANCE MY ISUSE CRATED

**Comment by ButCheR-PRO** [comment]
Dupe https://github.com/shamhi/HamsterKombatBot/issues/237

**Comment by Mahnazmohammadii** [comment]
> The most interesting thing: the only country that gets banned is Iran. Only two issues has ban problem and both are from Iran.

I tried using real phone numbers in Germany and Indonesia, but I was blocked
Can you add one of my numbers on your server? for test

**Comment by Mahnazmohammadii** [comment]
> Dupe #237

Hello
Are you a this  script developer? Can you help me?
I didn't understand what you meant, you referred to my issue

**Comment by Mahnazmohammadii** [comment]
Dear WHy closed my issue?
Why say DUB?
Please help me
Really I need this

**Comment by Mahnazmohammadii** [comment]
> فریب [شماره 237](https://github.com/shamhi/HamsterKombatBot/issues/237)



> Dupe #237

Dear WHy closed my issue?
Why say DUB?
Please help me
Really I need this
