### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by TheMeror** [shamhi/HamsterKombatBot#2372]
ERROR    | 37 - Unknown error while getting Access Token: 503, message='Service Unavailable: Back-end server is at capacity', url=URL('https://api.hamsterkombatgame.io/auth/auth-by-telegram-webapp') | Response text: ...

**Comment by afillimonov** [comment]
> ERROR    | 37 - Unknown error while getting Access Token: 503, message='Service Unavailable: Back-end server is at capacity', url=URL('https://api.hamsterkombatgame.io/auth/auth-by-telegram-webapp') | Response text: ...

the problem is on the hamster's side, it should be fixed soon

**Comment by Fast0n** [comment]
Now it seems that the site is working you can close the issue

**Comment by afillimonov** [comment]
> Now it seems that the site is working you can close the issue

![IMG_20240908_230756_252.jpg](https://github.com/user-attachments/assets/0f930432-b502-493a-bb75-adb6595a033b)

not quite

**Comment by NamasteIndia** [comment]
It's fixed
