### ISSUE TITLE
its base on profit not coin balance pls add auto upgrade cards

### ISSUE THREAD

**Issue by Rollagit** [shamhi/HamsterKombatBot#238]

**Comment by Rollagit** [comment]
its base on profit not coin balance pls add auto upgrade cards

**Comment by Rollagit** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/151917730/4879158b-bc88-4a2e-bd61-b8c726b644c8)

any config need?
my account just clicking

**Comment by ButCheR-PRO** [comment]
Log into your account from your phone and buy several cards manually in the game.

**Comment by KOTBCTAKAHE** [comment]
If problem solved, close the issue

**Comment by 4erdenko** [comment]
> ![image](https://private-user-images.githubusercontent.com/151917730/337973502-4879158b-bc88-4a2e-bd61-b8c726b644c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxNzk2MjIsIm5iZiI6MTcxODE3OTMyMiwicGF0aCI6Ii8xNTE5MTc3MzAvMzM3OTczNTAyLTQ4NzkxNThiLWJjODgtNGEyZS1iZDYxLWI4YzcyNmI2NDRjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMlQwODAyMDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjE0ZmI1ZDc4YzQzOTIzZjE3ZDE3NGVlYzU2M2Q2ODBiNTc5ZGMxZjdhMWE0MWZhMmE3ZjZiYzkxOGQ0NjBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jCKUmK72JL4SD0ZHbLif5cR4kcF5LIXhuVTQNW6n8k8)
> 
> any config need? my account just clicking

[#](https://github.com/shamhi/HamsterKombatBot/commit/8f89f4b5a8a24a2d7dc16f1a0eed01bac80c4baf)
