### ISSUE TITLE
Карточка reddit

### ISSUE THREAD

**Issue by GriGriGG** [shamhi/HamsterKombatBot#239]
![image](https://github.com/shamhi/HamsterKombatBot/assets/23379012/390f425c-68cf-47e6-9fd2-447b06481230)

Ребята, я не могу найти карточку reddit в игре. Просто интересно, не может ли это быть какая-то фантомная карточка, которая прилипает как "чёрная метка"?

**Comment by getgitgood** [comment]
```{'id': 'reddit', 'name': 'Сoindesk', 'price': 159841, 'profitPerHour': 1803, 'condition'...```

**Comment by GriGriGG** [comment]
@getgitgood Как она выглядит? покажи скрин, пожалуйста

**Comment by getgitgood** [comment]
![Screenshot_2024-06-09-11-50-04-553_org.telegram.messenger-edit.jpg](https://github.com/shamhi/HamsterKombatBot/assets/106710399/b4651c1f-648e-45f8-933d-37d71c33dc4c)

**Comment by Machaeon** [comment]
Так же не смог найти hamster_drop. Может, стоит выводить как id, так и name?

**Comment by GriGriGG** [comment]
Сорян за панику @getgitgood и спасибо! Уж не думал что это одно и то же)
