### ISSUE TITLE
ACHTUNG!!! TURN OFF BOTS. Changed API endpoints.

### ISSUE THREAD

**Issue by AlexanderQueen** [shamhi/HamsterKombatBot#2391]
![image](https://github.com/user-attachments/assets/c79276ad-fc8f-4f37-9fe3-089e06be9442)

![image](https://github.com/user-attachments/assets/e470906b-1ea8-4b99-a43a-8b4db5680847)

**Comment by manasseh-zues** [comment]
is better you stop using the bot at this point in time in order not to get banned.

**Comment by manasseh-zues** [comment]
all these concerns raised but Shamhi isn't updating the API nor the other.

**Comment by AlexanderQueen** [comment]
> is better you stop using the bot at this point in time in order not to get banned.

Already.

**Comment by d10nn** [comment]
ключи получает ок, пазлы отключил пока что

**Comment by WeendVidente777** [comment]
Это была проблема на стороне хомяка, он в принципе не работал. Ендпоинты старые.

**Comment by d10nn** [comment]
> Это была проблема на стороне хомяка, он в принципе не работал. Ендпоинты старые.

т.е. пазлы можно включать?

**Comment by ivan52605** [comment]
Да можешь включить бота у меня ни 1 ошибки
