### ISSUE TITLE
Hi Bro

### ISSUE THREAD

**Issue by LifeViwer** [shamhi/HamsterKombatBot#24]
"Привет брат, подскажи, а логика покупки как работает, покупается самое выгодное, делится цена карточки относительно доходности и покупается самая выгодная по доходности и цене?"

"Hey brother, can you explain how the purchasing logic works? Is the most profitable one bought by dividing the card's price by its profitability, and then the one with the best price-to-profitability ratio is purchased?"

**Comment by LifeViwer** [comment]
Кажется, не увидели код.
Можете добавить функцию подсчёта выгодной карты?

Чтобы определить, какая карта будет более выгодной для приобретения с точки зрения увеличения прибыли, необходимо оценить соотношение стоимости карты к прибыли в данный момент. Чем меньше это отношение, тем выгоднее покупка. Это можно объяснить следующим образом:

Для первых карточек:
Стоимость увеличения прибыли
238390/1860≈128,28

Для второй карточки:
Стоимость увеличения прибыли
149846/1260≈118,92

Из этих расчетов видно, что вторая карточка имеет более низкую стоимость по величине прибыли (118,92) по сравнению с первой карточкой (128,28). Это означает, что вторая карточка более выгодна для приобретения с точки зрения увеличения прибыли, так как вы платите меньше за каждую единицу прибыли в час.






____________________



It seems they didn't see the code.
Can you add a function for counting advantageous cards?

To determine which card will be more profitable to purchase in terms of increasing profits, it is necessary to evaluate the ratio of the card's cost to profit at the moment. The lower this ratio, the more profitable the purchase. This can be explained as follows:

For the first cards:
The cost of increasing profits
238390/1860≈128.28

For the second card:
The cost of increasing profits
149846/1260≈118.92

From these calculations it is clear that the second card has a lower value in terms of profit (118.92) compared to the first card (128.28). This means that the second card is more profitable to purchase in terms of increasing profits, since you pay less per unit of profit per hour.

**Comment by shamhi** [comment]
Hi, it's good idea, do you can send pull request? I won't be able to add it until tomorrow.
