### ISSUE TITLE
Traceback TypeError: unsupported operand type(s) for: 'type' and 'type'

### ISSUE THREAD

**Issue by nimakhooye2** [shamhi/HamsterKombatBot#240]
What is error?
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "/root/HamsterKombatBot/bot/utils/__init__.py", line 2, in <module>
    from . import launcher
  File "/root/HamsterKombatBot/bot/utils/launcher.py", line 8, in <module>
    from better_proxy import Proxy
  File "/usr/local/lib/python3.8/dist-packages/better_proxy/__init__.py", line 1
, in <module>
    from .proxy import Proxy
  File "/usr/local/lib/python3.8/dist-packages/better_proxy/proxy.py", line 16,
in <module>
    def _load_lines(filepath: Path | str) -> list[str]:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by Mik-chan** [comment]
You're using version of Python too old. You need to install Python 3.10 or higher

**Comment by nimakhooye2** [comment]
> You're using version of Python too old. You need to install Python 3.10 or higher

I updated it and it still gives these errors

**Comment by ButCheR-PRO** [comment]
Dupe: https://github.com/shamhi/HamsterKombatBot/issues/165

# Installation:
Download and install: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Then synchronize the system time on your computer.
Download the latest version of the bot [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) and unpack it.
Then run INSTALL.bat.
Then you need to configure the .env config according to the documentation in README.md
After this, you need to create a session via START.bat by selecting option 1.
And only then launch the configured clicker through START.bat by selecting point 2.
