### ISSUE TITLE
Как через pm2 его запустить в фоновом режиме ?

### ISSUE THREAD

**Issue by Hamsssterc** [shamhi/HamsterKombatBot#2402]
Как через pm2 его запустить в фоновом режиме ?

**Comment by Yorksik** [comment]
запуская. через Tmux

**Comment by Hamsssterc** [comment]
Оказывается была инструкция, не сразу посмотрел [здесь](https://github.com/shamhi/HamsterKombatBot/blob/main/docs/LINUX-SERVIS-INSTALL.md)
