### ISSUE TITLE
VDS: как только закрываю консоль скрипт перестает работать

### ISSUE THREAD

**Issue by crispan2** [shamhi/HamsterKombatBot#241]
Парни, помогите пожалуйста. Запустил скрипт на дедике, все хорошо встало, как только закрываю консоль скрипт перестает работать, что с этим можно сделать?

**Comment by rezaj65** [comment]
server

**Comment by crispan2** [comment]
> server

Он и стоит на сервере(ubuntu). После выключения консоли сервера скрипт также выключается. Видел тут, предлагали создать сервис, но так не работает

**Comment by Dmitry-Golyshkin** [comment]
nohup ./your_script.sh & 
Таким образом, скрипт будет продолжать работать, когда вы закроете консоль.

**Comment by Pasha4056** [comment]
Сделал таким образом сервис, всё отлично работает:

[Unit]
Description=farmbot service

[Service]
Type=simple
WorkingDirectory=/root/HamsterKombatBot
ExecStart=/bin/bash -c "python3.11 -m venv farm; source farm/bin/activate; python3.11 main.py --action 2"
Restart=always
RestartSec=10
User=root

[Install]
WantedBy=multi-user.target

**Comment by Yorksik** [comment]
или tmux

**Comment by HoyT6yK** [comment]
Использую screen. Попробуй его.

**Comment by Dmitry-Golyshkin** [comment]
https://github.com/flaming-chameleon/tmux-short-guide

**Comment by dinrise** [comment]
> Использую screen. Попробуй его.

Самый шикарный способ) У меня куча ботов на скринах пашут, плюс впн там же крутятся
