### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by paaavann** [shamhi/HamsterKombatBot#2414]
![Screenshot 2024-09-18 162627](https://github.com/user-attachments/assets/6d101885-278b-4851-b0fe-af13019efc4c)

**Comment by mir-ashiq** [comment]
@paaavann write below code in bot/utils/__init__.py

```
from .logger import logger
from . import tg_channel_check
from . import tg_web_data
from . import launcher
from . import scripts
from . import default
from . import json_db
from . import proxy


import os

if not os.path.exists('sessions'):
    os.mkdir('sessions')
```

**Comment by paaavann** [comment]
that worked but
![image](https://github.com/user-attachments/assets/646295f4-fff0-4883-8de1-d949fc8cc34a)

**Comment by mir-ashiq** [comment]
@paaavann You haven't created session.
select 1 to create session, after completing all the steps run it again and select 2 to run the bot

**Comment by paaavann** [comment]
> @paaavann You haven't created session. select 1 to create session, after completing all the steps run it again and select 2 to run the bot

i dont have proxy

**Comment by paaavann** [comment]
Thanks started working

**Comment by paaavann** [comment]
But how do I customize how much to spend and all?

**Comment by mir-ashiq** [comment]
Edit .env file.
Don't use APPLY_PROMO_CODES if gives ban

**Comment by paaavann** [comment]
oh okay thanks a lot man
