### ISSUE TITLE
Please create the same bot for the game moonbix (binance)

### ISSUE THREAD

**Issue by Theslandybrain** [shamhi/HamsterKombatBot#2419]
прошу для кого актуально оставлять реакции

**Comment by WeNuLLApp** [comment]
Need make payload first😅

**Comment by lolyinseo** [comment]
нахер не нужно, тк вывод будет скорее всего только на аа бинанса

**Comment by slavon141** [comment]
Please, please please please 🙏🥺🥺🥺

**Comment by kics223w1** [comment]
```js
class MoonbixBot {
  sleep(time) {
    return new Promise((resolve) => setTimeout(resolve, time));
  }

  run() {
    setInterval(async () => {
      const buttonPlayGame = this.findButtonPlayGame();
      if (!buttonPlayGame) {
        return;
      }

      const event = new MouseEvent("click", {
        bubbles: true,
        cancelable: true,
        view: window,
      });
      buttonPlayGame.dispatchEvent(event);

      await this.sleep(1000);

      for (let i = 0; i < 50; i++) {
        await this.sleep(1000);
        this.simulateLeftClick();
      }

      this.findReturnButtonElementsAndClick();

      await this.sleep(1500);
    }, 1000);
  }

  findButtonPlayGame() {
    const button = document.querySelector("[class^='Game_entry__playBtn']");
    if (button && button.textContent.trim().toLowerCase() === "play game") {
      const style = window.getComputedStyle(button);
      if (style.marginTop === "40px") {
        return button;
      }
    }
    return null;
  }

  findReturnButtonElementsAndClick() {
    const svgs = document.getElementsByTagName("svg");
    for (let svg of svgs) {
      // Check if the SVG matches the specified structure
      if (
        svg.outerHTML ===
        '<svg class="bn-svg absolute top-4 start-4 w-6 h-6" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.999 11.999l7.071-7.072 1.768 1.768-4.055 4.055H21v2.5H7.785l4.053 4.053-1.768 1.768L3 12v-.001z" fill="currentColor"></path></svg>'
      ) {
        const event = new MouseEvent("click", {
          bubbles: true,
          cancelable: true,
          view: window,
        });
        svg.dispatchEvent(event);
      }
    }
  }

  autoMining() {}

  simulateLeftClick() {
    const canvas = document.querySelector("canvas");
    console.error("Canvas: ", canvas);
    if (canvas) {
      const event = new MouseEvent("mousedown", {
        bubbles: true,
        cancelable: true,
        view: window,
        button: 0, // 0 indicates the left mouse button
      });
      canvas.dispatchEvent(event);

      const clickEvent = new MouseEvent("mouseup", {
        bubbles: true,
        cancelable: true,
        view: window,
        button: 0, // 0 indicates the left mouse button
      });
      canvas.dispatchEvent(clickEvent);

      canvas.dispatchEvent(
        new MouseEvent("click", {
          bubbles: true,
          cancelable: true,
          view: window,
          button: 0, // 0 indicates the left mouse button
        })
      );
    }
  }
}

const moonBixBot = new MoonbixBot();
moonBixBot.run();
```

## How to use
1. Launch game
2. Right click -> Inspect element -> Change to Console View
3. Paste this code and click `Enter`

## Description
 - This code run permently, the process is clicking `Play Game` button -> Auto Mining -> click `Back` -> click `Play Game` button -> Repeat
 - This code is not clean, and not well written but it does the job 🚀 
 
## How to reach me
 - Ping me on [Telegram](https://t.me/caoviethuy123) if you want me write tool for you

**Comment by Theslandybrain** [comment]
> ```js
> class MoonbixBot {
>   sleep(time) {
>     return new Promise((resolve) => setTimeout(resolve, time));
>   }
> 
>   run() {
>     setInterval(async () => {
>       const buttonPlayGame = this.findButtonPlayGame();
>       if (!buttonPlayGame) {
>         return;
>       }
> 
>       const event = new MouseEvent("click", {
>         bubbles: true,
>         cancelable: true,
>         view: window,
>       });
>       buttonPlayGame.dispatchEvent(event);
> 
>       await this.sleep(1000);
> 
>       for (let i = 0; i < 50; i++) {
>         await this.sleep(1000);
>         this.simulateLeftClick();
>       }
> 
>       this.findReturnButtonElementsAndClick();
> 
>       await this.sleep(1500);
>     }, 1000);
>   }
> 
>   findButtonPlayGame() {
>     const button = document.querySelector("[class^='Game_entry__playBtn']");
>     if (button && button.textContent.trim().toLowerCase() === "play game") {
>       const style = window.getComputedStyle(button);
>       if (style.marginTop === "40px") {
>         return button;
>       }
>     }
>     return null;
>   }
> 
>   findReturnButtonElementsAndClick() {
>     const svgs = document.getElementsByTagName("svg");
>     for (let svg of svgs) {
>       // Check if the SVG matches the specified structure
>       if (
>         svg.outerHTML ===
>         '<svg class="bn-svg absolute top-4 start-4 w-6 h-6" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.999 11.999l7.071-7.072 1.768 1.768-4.055 4.055H21v2.5H7.785l4.053 4.053-1.768 1.768L3 12v-.001z" fill="currentColor"></path></svg>'
>       ) {
>         const event = new MouseEvent("click", {
>           bubbles: true,
>           cancelable: true,
>           view: window,
>         });
>         svg.dispatchEvent(event);
>       }
>     }
>   }
> 
>   autoMining() {}
> 
>   simulateLeftClick() {
>     const canvas = document.querySelector("canvas");
>     console.error("Canvas: ", canvas);
>     if (canvas) {
>       const event = new MouseEvent("mousedown", {
>         bubbles: true,
>         cancelable: true,
>         view: window,
>         button: 0, // 0 indicates the left mouse button
>       });
>       canvas.dispatchEvent(event);
> 
>       const clickEvent = new MouseEvent("mouseup", {
>         bubbles: true,
>         cancelable: true,
>         view: window,
>         button: 0, // 0 indicates the left mouse button
>       });
>       canvas.dispatchEvent(clickEvent);
> 
>       canvas.dispatchEvent(
>         new MouseEvent("click", {
>           bubbles: true,
>           cancelable: true,
>           view: window,
>           button: 0, // 0 indicates the left mouse button
>         })
>       );
>     }
>   }
> }
> 
> const moonBixBot = new MoonbixBot();
> moonBixBot.run();
> ```
> 
> ## Как использовать
> 1. Запустить игру
> 2. правый клик мыши -> Исследовать элемент -> Изменить на вид консоли.
> 3. Вставьте этот код и нажмите`Enter`
> 4. @slavon141  @lolyinseo  @WeNuLLApp
> 
> ## Описание
> * Этот код показывает результат непрерывно, процесс следующий: зарядка батареи `Play Game`-> Автоматический майнинг -> зарядка `Back`-> зарядка `Play Game`-> Повторить
> * Этот код написан не совсем чисто и не очень хорошо, но он выполняет свою работу 🚀
> 
> ## Как со мной связаться
> * Напишите мне в [Telegram,](https://t.me/caoviethuy123) если хотите, чтобы я написал для вас инструмент.

Blocked script execution in 'about:blank' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.

**Comment by kics223w1** [comment]
Well, I wrote this to use for my account. I didn't use your bot. 
Just came across this issue and thought I should share my code.

**Comment by Theslandybrain** [comment]
> Well, I wrote this to use for my account. I didn't use your bot. Just came across this issue and thought I should share my code.

Рow did you use it? it just doesn't work

**Comment by Theslandybrain** [comment]
> Well, I wrote this to use for my account. I didn't use your bot. Just came across this issue and thought I should share my code.

it's just returns undefined
![image](https://github.com/user-attachments/assets/de5ada97-aaff-4126-b4ba-f698fe2e64ea)

**Comment by kics223w1** [comment]
Open game, paste the code to the inspect view then click Enter.
That's it. It works well for me.
<img width="1731" alt="ảnh" src="https://github.com/user-attachments/assets/209d83cd-1f0d-4e56-8c05-7b7acb2fe5c1">

**Comment by Theslandybrain** [comment]
How to open this game via browser? I managed to do it only with the experimental functions of telegram desktop

**Comment by Theslandybrain** [comment]
> Open game, paste the code to the inspect view then click Enter. That's it. It works well for me. <img alt="ảnh" width="1731" src="https://private-user-images.githubusercontent.com/77295189/369640874-209d83cd-1f0d-4e56-8c05-7b7acb2fe5c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NDMzMjQsIm5iZiI6MTcyNjk0MzAyNCwicGF0aCI6Ii83NzI5NTE4OS8zNjk2NDA4NzQtMjA5ZDgzY2QtMWYwZC00ZTU2LThjMDUtN2I3YWNiMmZlNWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDE4MjM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhYjBmYzkwNDlhYjBkODk2OTVmZTdhYTE5Y2RhYTBmNDBlOTE0MzFkOGYzODBmM2U4ZTEwOGY4MDI2MGViY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dBEsfHNIr4DB-CN0CsWw2cgvmeqOguaRr4HBijdRT4w">

How to open this game via browser? I managed to do it only with the experimental functions of telegram desktop

**Comment by kics223w1** [comment]
I use telegram desktop too.
My friend send me the reference to launch the game.

![image](https://github.com/user-attachments/assets/465db480-d560-44d9-b102-c4fdd5bdb320)

**Comment by Theslandybrain** [comment]
> I use telegram desktop too. My friend send me the reference to launch the game.
> 
> ![image](https://private-user-images.githubusercontent.com/77295189/369641274-465db480-d560-44d9-b102-c4fdd5bdb320.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5NDQ4NTcsIm5iZiI6MTcyNjk0NDU1NywicGF0aCI6Ii83NzI5NTE4OS8zNjk2NDEyNzQtNDY1ZGI0ODAtZDU2MC00NGQ5LWIxMDItYzRmZGQ1YmRiMzIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIxVDE4NDkxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMDVmM2U2MGIwZjhkN2E4ZTMwNTNiMTcwNDJlNTNjYzE4YjYwNmNlY2RhNmRhYjg3ZjM1Mjk3OGQ2ZjkzMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8XgI-G5F7GiQN-AFjFnLcIknt7conjxY_k8bBvaGIu4)

![image](https://github.com/user-attachments/assets/0d67ada4-4c5c-44ec-8c90-18851b2c7d0f)

**Comment by Theslandybrain** [comment]
it just doesn't work in browser

**Comment by kics223w1** [comment]
It works well for me.

**Comment by Theslandybrain** [comment]
![image](https://github.com/user-attachments/assets/fbf1e9fa-73aa-4440-aa63-4396ba585e6a)
I fixed the launch via browser, but the script just doesn't work

**Comment by Theslandybrain** [comment]
i just change language to english, and it's worked! Thank you!

**Comment by kics223w1** [comment]
Great to hear that.
Yes it should be English because if it is Russian, the code will never find the Play Game button.

**Comment by slavon141** [comment]
> ```js
> class MoonbixBot {
>   sleep(time) {
>     return new Promise((resolve) => setTimeout(resolve, time));
>   }
> 
>   run() {
>     setInterval(async () => {
>       const buttonPlayGame = this.findButtonPlayGame();
>       if (!buttonPlayGame) {
>         return;
>       }
> 
>       const event = new MouseEvent("click", {
>         bubbles: true,
>         cancelable: true,
>         view: window,
>       });
>       buttonPlayGame.dispatchEvent(event);
> 
>       await this.sleep(1000);
> 
>       for (let i = 0; i < 50; i++) {
>         await this.sleep(1000);
>         this.simulateLeftClick();
>       }
> 
>       this.findReturnButtonElementsAndClick();
> 
>       await this.sleep(1500);
>     }, 1000);
>   }
> 
>   findButtonPlayGame() {
>     const button = document.querySelector("[class^='Game_entry__playBtn']");
>     if (button && button.textContent.trim().toLowerCase() === "play game") {
>       const style = window.getComputedStyle(button);
>       if (style.marginTop === "40px") {
>         return button;
>       }
>     }
>     return null;
>   }
> 
>   findReturnButtonElementsAndClick() {
>     const svgs = document.getElementsByTagName("svg");
>     for (let svg of svgs) {
>       // Check if the SVG matches the specified structure
>       if (
>         svg.outerHTML ===
>         '<svg class="bn-svg absolute top-4 start-4 w-6 h-6" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M2.999 11.999l7.071-7.072 1.768 1.768-4.055 4.055H21v2.5H7.785l4.053 4.053-1.768 1.768L3 12v-.001z" fill="currentColor"></path></svg>'
>       ) {
>         const event = new MouseEvent("click", {
>           bubbles: true,
>           cancelable: true,
>           view: window,
>         });
>         svg.dispatchEvent(event);
>       }
>     }
>   }
> 
>   autoMining() {}
> 
>   simulateLeftClick() {
>     const canvas = document.querySelector("canvas");
>     console.error("Canvas: ", canvas);
>     if (canvas) {
>       const event = new MouseEvent("mousedown", {
>         bubbles: true,
>         cancelable: true,
>         view: window,
>         button: 0, // 0 indicates the left mouse button
>       });
>       canvas.dispatchEvent(event);
> 
>       const clickEvent = new MouseEvent("mouseup", {
>         bubbles: true,
>         cancelable: true,
>         view: window,
>         button: 0, // 0 indicates the left mouse button
>       });
>       canvas.dispatchEvent(clickEvent);
> 
>       canvas.dispatchEvent(
>         new MouseEvent("click", {
>           bubbles: true,
>           cancelable: true,
>           view: window,
>           button: 0, // 0 indicates the left mouse button
>         })
>       );
>     }
>   }
> }
> 
> const moonBixBot = new MoonbixBot();
> moonBixBot.run();
> ```
> 
> ## How to use
> 1. Launch game
> 2. Right click -> Inspect element -> Change to Console View
> 3. Paste this code and click `Enter`
> 4. @slavon141  @lolyinseo  @WeNuLLApp
> 
> ## Description
> * This code run permently, the process is clicking `Play Game` button -> Auto Mining -> click `Back` -> click `Play Game` button -> Repeat
> * This code is not clean, and not well written but it does the job 🚀
> 
> ## How to reach me
> * Ping me on [Telegram](https://t.me/caoviethuy123) if you want me write tool for you

thanks. but
![Створити точковий рисунок](https://github.com/user-attachments/assets/80b2c859-a237-45ea-9202-bf7d85a92f9b)
The host www.binance.com rejected the connection request.

**Comment by slavon141** [comment]
> It works well for me.

What country are you from? I'll try using a vpn, because this method doesn't work for me either.

**Comment by slavon141** [comment]
@kics223w1 
![Створити точковий рисунок](https://github.com/user-attachments/assets/6dfefe86-1de3-4feb-a52a-3fcfab2a26d4)
The host www.binance.com rejected the connection request.

**Comment by slavon141** [comment]
[Theslandybrain](https://github.com/Theslandybrain) How did you fix the browser launch?

**Comment by slavon141** [comment]
[Theslandybrain](https://github.com/Theslandybrain) ,  I found a solution. https://github.com/0x-John/Android-for-Web-Telegram

**Comment by slavon141** [comment]
> ![image](https://private-user-images.githubusercontent.com/182003504/369643407-fbf1e9fa-73aa-4440-aa63-4396ba585e6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyNjg5NjEsIm5iZiI6MTcyNzI2ODY2MSwicGF0aCI6Ii8xODIwMDM1MDQvMzY5NjQzNDA3LWZiZjFlOWZhLTczYWEtNDQ0MC1hYTYzLTQzOTZiYTU4NWU2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQxMjUxMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTk0OTFiYzdiMDU4MjllNjcwYmMyNGRiZTEyMzRiYjNkZjliMzFjYTY3MDZmZDg3N2QyMzJkYzgwYmZhN2E0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pM9CVNuCzjskeoejOX1bjH3iSWxcmtzXkHl6Z-7GQf8) I fixed the launch via browser, but the script just doesn't work

How did you fix the browser launch?

**Comment by slavon141** [comment]
> Open game, paste the code to the inspect view then click Enter. That's it. It works well for me. <img alt="ảnh" width="1731" src="https://private-user-images.githubusercontent.com/77295189/369640874-209d83cd-1f0d-4e56-8c05-7b7acb2fe5c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyODA4MDcsIm5iZiI6MTcyNzI4MDUwNywicGF0aCI6Ii83NzI5NTE4OS8zNjk2NDA4NzQtMjA5ZDgzY2QtMWYwZC00ZTU2LThjMDUtN2I3YWNiMmZlNWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI1VDE2MDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzMTBjMjVhYjIzYzQzMDVkMmU1NjVhMjllZTliZmIyYzU5YzA5YmQ0OWE1NTBhMDliNzYwOWEwYjZhNGY1ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.m-XxC5K3iBDdn4HJSlN--Ijqx6xtjoalZy8suKgcn2A">

How did you open moonbix in a browser?

**Comment by kics223w1** [comment]
Just read my previous responses. 
I open it from telegram desktop

**Comment by lacvietanh** [comment]
need a way to open moonbix on browser. 
about 3 days ago, it (binance) fixed

**Comment by vanhbakaa** [comment]
Open in telegram

> need a way to open moonbix on browser. about 3 days ago, it (binance) fixed
