### ISSUE TITLE
error

### ISSUE THREAD

**Issue by seregafullman** [shamhi/HamsterKombatBot#244]
Microsoft Windows [Version 10.0.22631.3593]
(c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.

D:\HamsterKombat\HamsterKombatBot>D:\HamsterKombat\HamsterKombatBot\INSTALL.bat
Creating virtual environment...
"python" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
Activating virtual environment...
Системе не удается найти указанный путь.
Installing dependencies...
Defaulting to user installation because normal site-packages is not writeable
Collecting aiohttp==3.9.3 (from -r requirements.txt (line 1))
  Using cached aiohttp-3.9.3-cp312-cp312-win_amd64.whl.metadata (7.6 kB)
Collecting aiohttp-proxy==0.1.2 (from -r requirements.txt (line 2))
  Using cached aiohttp_proxy-0.1.2-py3-none-any.whl.metadata (2.7 kB)
Collecting aiosignal==1.3.1 (from -r requirements.txt (line 3))
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting annotated-types==0.6.0 (from -r requirements.txt (line 4))
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting async-timeout==4.0.3 (from -r requirements.txt (line 5))
  Using cached async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB)
Collecting attrs==23.2.0 (from -r requirements.txt (line 6))
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting better-proxy==1.1.5 (from -r requirements.txt (line 7))
  Using cached better_proxy-1.1.5-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: colorama==0.4.6 in c:\users\katan\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 8)) (0.4.6)
Collecting frozenlist==1.4.1 (from -r requirements.txt (line 9))
  Using cached frozenlist-1.4.1-cp312-cp312-win_amd64.whl.metadata (12 kB)
Collecting idna==3.6 (from -r requirements.txt (line 10))
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting loguru==0.7.2 (from -r requirements.txt (line 11))
  Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB)
Collecting multidict==6.0.5 (from -r requirements.txt (line 12))
  Using cached multidict-6.0.5-cp312-cp312-win_amd64.whl.metadata (4.3 kB)
Requirement already satisfied: pyaes==1.6.1 in c:\users\katan\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 13)) (1.6.1)
Collecting pydantic==2.6.4 (from -r requirements.txt (line 14))
  Using cached pydantic-2.6.4-py3-none-any.whl.metadata (85 kB)
Collecting pydantic-settings==2.2.1 (from -r requirements.txt (line 15))
  Using cached pydantic_settings-2.2.1-py3-none-any.whl.metadata (3.1 kB)
Collecting pydantic_core==2.16.3 (from -r requirements.txt (line 16))
  Using cached pydantic_core-2.16.3-cp312-none-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: Pyrogram==2.0.106 in c:\users\katan\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 17)) (2.0.106)
Requirement already satisfied: PySocks==1.7.1 in c:\users\katan\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 18)) (1.7.1)
Requirement already satisfied: python-dotenv==1.0.1 in c:\users\katan\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 19)) (1.0.1)
Collecting TgCrypto==1.2.5 (from -r requirements.txt (line 20))
  Using cached TgCrypto-1.2.5.tar.gz (37 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting typing_extensions==4.11.0 (from -r requirements.txt (line 21))
  Using cached typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: win32-setctime==1.1.0 in c:\users\katan\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 22)) (1.1.0)
Collecting yarl==1.9.4 (from -r requirements.txt (line 23))
  Using cached yarl-1.9.4-cp312-cp312-win_amd64.whl.metadata (32 kB)
Using cached aiohttp-3.9.3-cp312-cp312-win_amd64.whl (363 kB)
Using cached aiohttp_proxy-0.1.2-py3-none-any.whl (12 kB)
Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Using cached better_proxy-1.1.5-py3-none-any.whl (3.2 kB)
Using cached frozenlist-1.4.1-cp312-cp312-win_amd64.whl (50 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached loguru-0.7.2-py3-none-any.whl (62 kB)
Using cached multidict-6.0.5-cp312-cp312-win_amd64.whl (27 kB)
Using cached pydantic-2.6.4-py3-none-any.whl (394 kB)
Using cached pydantic_settings-2.2.1-py3-none-any.whl (13 kB)
Using cached pydantic_core-2.16.3-cp312-none-win_amd64.whl (1.9 MB)
Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Using cached yarl-1.9.4-cp312-cp312-win_amd64.whl (76 kB)
Building wheels for collected packages: TgCrypto
  Building wheel for TgCrypto (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for TgCrypto (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-312
      creating build\lib.win-amd64-cpython-312\tests
      copying tests\__init__.py -> build\lib.win-amd64-cpython-312\tests
      creating build\lib.win-amd64-cpython-312\tests\cbc
      copying tests\cbc\test_cbc.py -> build\lib.win-amd64-cpython-312\tests\cbc
      copying tests\cbc\__init__.py -> build\lib.win-amd64-cpython-312\tests\cbc
      creating build\lib.win-amd64-cpython-312\tests\ctr
      copying tests\ctr\test_ctr.py -> build\lib.win-amd64-cpython-312\tests\ctr
      copying tests\ctr\__init__.py -> build\lib.win-amd64-cpython-312\tests\ctr
      creating build\lib.win-amd64-cpython-312\tests\ige
      copying tests\ige\test_ige.py -> build\lib.win-amd64-cpython-312\tests\ige
      copying tests\ige\__init__.py -> build\lib.win-amd64-cpython-312\tests\ige
      running build_ext
      building 'tgcrypto' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for TgCrypto
Failed to build TgCrypto
ERROR: Could not build wheels for TgCrypto, which is required to install pyproject.toml-based projects
Copying .env-example to .env...
Скопировано файлов:         1.
Please edit the .env file to add your API_ID and API_HASH.
Для продолжения нажмите любую клавишу . . .

**Comment by XPacL** [comment]
Установи python 3.10 или 3.11

**Comment by seregafullman** [comment]
> Microsoft Windows [Version 10.0.22631.3593] (c) Корпорация Майкрософт (Microsoft Corporation). Все права защищены.
> 
> D:\HamsterKombat\HamsterKombatBot>D:\HamsterKombat\HamsterKombatBot\INSTALL.bat Creating virtual environment... "python" не является внутренней или внешней командой, исполняемой программой или пакетным файлом. Activating virtual environment... Системе не удается найти указанный путь. Installing dependencies... Defaulting to user installation because normal site-packages is not writeable Collecting aiohttp==3.9.3 (from -r requirements.txt (line 1)) Using cached aiohttp-3.9.3-cp312-cp312-win_amd64.whl.metadata (7.6 kB) Collecting aiohttp-proxy==0.1.2 (from -r requirements.txt (line 2)) Using cached aiohttp_proxy-0.1.2-py3-none-any.whl.metadata (2.7 kB) Collecting aiosignal==1.3.1 (from -r requirements.txt (line 3)) Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB) Collecting annotated-types==0.6.0 (from -r requirements.txt (line 4)) Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB) Collecting async-timeout==4.0.3 (from -r requirements.txt (line 5)) Using cached async_timeout-4.0.3-py3-none-any.whl.metadata (4.2 kB) Collecting attrs==23.2.0 (from -r requirements.txt (line 6)) Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB) Collecting better-proxy==1.1.5 (from -r requirements.txt (line 7)) Using cached better_proxy-1.1.5-py3-none-any.whl.metadata (2.6 kB) Requirement already satisfied: colorama==0.4.6 in c:\users\katan\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 8)) (0.4.6) Collecting frozenlist==1.4.1 (from -r requirements.txt (line 9)) Using cached frozenlist-1.4.1-cp312-cp312-win_amd64.whl.metadata (12 kB) Collecting idna==3.6 (from -r requirements.txt (line 10)) Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB) Collecting loguru==0.7.2 (from -r requirements.txt (line 11)) Using cached loguru-0.7.2-py3-none-any.whl.metadata (23 kB) Collecting multidict==6.0.5 (from -r requirements.txt (line 12)) Using cached multidict-6.0.5-cp312-cp312-win_amd64.whl.metadata (4.3 kB) Requirement already satisfied: pyaes==1.6.1 in c:\users\katan\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 13)) (1.6.1) Collecting pydantic==2.6.4 (from -r requirements.txt (line 14)) Using cached pydantic-2.6.4-py3-none-any.whl.metadata (85 kB) Collecting pydantic-settings==2.2.1 (from -r requirements.txt (line 15)) Using cached pydantic_settings-2.2.1-py3-none-any.whl.metadata (3.1 kB) Collecting pydantic_core==2.16.3 (from -r requirements.txt (line 16)) Using cached pydantic_core-2.16.3-cp312-none-win_amd64.whl.metadata (6.6 kB) Requirement already satisfied: Pyrogram==2.0.106 in c:\users\katan\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 17)) (2.0.106) Requirement already satisfied: PySocks==1.7.1 in c:\users\katan\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 18)) (1.7.1) Requirement already satisfied: python-dotenv==1.0.1 in c:\users\katan\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 19)) (1.0.1) Collecting TgCrypto==1.2.5 (from -r requirements.txt (line 20)) Using cached TgCrypto-1.2.5.tar.gz (37 kB) Installing build dependencies ... done Getting requirements to build wheel ... done Preparing metadata (pyproject.toml) ... done Collecting typing_extensions==4.11.0 (from -r requirements.txt (line 21)) Using cached typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB) Requirement already satisfied: win32-setctime==1.1.0 in c:\users\katan\appdata\roaming\python\python312\site-packages (from -r requirements.txt (line 22)) (1.1.0) Collecting yarl==1.9.4 (from -r requirements.txt (line 23)) Using cached yarl-1.9.4-cp312-cp312-win_amd64.whl.metadata (32 kB) Using cached aiohttp-3.9.3-cp312-cp312-win_amd64.whl (363 kB) Using cached aiohttp_proxy-0.1.2-py3-none-any.whl (12 kB) Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB) Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB) Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB) Using cached attrs-23.2.0-py3-none-any.whl (60 kB) Using cached better_proxy-1.1.5-py3-none-any.whl (3.2 kB) Using cached frozenlist-1.4.1-cp312-cp312-win_amd64.whl (50 kB) Using cached idna-3.6-py3-none-any.whl (61 kB) Using cached loguru-0.7.2-py3-none-any.whl (62 kB) Using cached multidict-6.0.5-cp312-cp312-win_amd64.whl (27 kB) Using cached pydantic-2.6.4-py3-none-any.whl (394 kB) Using cached pydantic_settings-2.2.1-py3-none-any.whl (13 kB) Using cached pydantic_core-2.16.3-cp312-none-win_amd64.whl (1.9 MB) Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB) Using cached yarl-1.9.4-cp312-cp312-win_amd64.whl (76 kB) Building wheels for collected packages: TgCrypto Building wheel for TgCrypto (pyproject.toml) ... error error: subprocess-exited-with-error
> 
> × Building wheel for TgCrypto (pyproject.toml) did not run successfully. │ exit code: 1 ╰─> [19 lines of output] running bdist_wheel running build running build_py creating build creating build\lib.win-amd64-cpython-312 creating build\lib.win-amd64-cpython-312\tests copying tests__init__.py -> build\lib.win-amd64-cpython-312\tests creating build\lib.win-amd64-cpython-312\tests\cbc copying tests\cbc\test_cbc.py -> build\lib.win-amd64-cpython-312\tests\cbc copying tests\cbc__init__.py -> build\lib.win-amd64-cpython-312\tests\cbc creating build\lib.win-amd64-cpython-312\tests\ctr copying tests\ctr\test_ctr.py -> build\lib.win-amd64-cpython-312\tests\ctr copying tests\ctr__init__.py -> build\lib.win-amd64-cpython-312\tests\ctr creating build\lib.win-amd64-cpython-312\tests\ige copying tests\ige\test_ige.py -> build\lib.win-amd64-cpython-312\tests\ige copying tests\ige__init__.py -> build\lib.win-amd64-cpython-312\tests\ige running build_ext building 'tgcrypto' extension error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/ [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. ERROR: Failed building wheel for TgCrypto Failed to build TgCrypto ERROR: Could not build wheels for TgCrypto, which is required to install pyproject.toml-based projects Copying .env-example to .env... Скопировано файлов: 1. Please edit the .env file to add your API_ID and API_HASH. Для продолжения нажмите любую клавишу . . .
