### ISSUE TITLE
hamster_kombat is a big liar

### ISSUE THREAD

**Issue by cr4zyfish** [shamhi/HamsterKombatBot#2444]
![ggg](https://github.com/user-attachments/assets/2a0a27d2-b193-4d15-a04a-a2b9619b2505)
In this tweet they claimed that players "tapping the same exact pixel"  is this even possible? you know how hamster works and it is not sending any data about tapped pixel to servers! looks like they are a bunch of scammers and liars.

**Comment by EnterBrain** [comment]
Have you tracked all the requests for Google analytics to confirm this? I watched a lot of things they transmit there, including the size of the device screen, etc. I wouldn't be surprised if data analysts tracked bot patterns based on this data.

**Comment by lolyinseo** [comment]
> Have you tracked all the requests for Google analytics to confirm this? I watched a lot of things they transmit there, including the size of the device screen, etc. I wouldn't be surprised if data analysts tracked bot patterns based on this data.

I do. they are lying

**Comment by AlexanderQueen** [comment]
> Have you tracked all the requests for Google analytics to confirm this? I watched a lot of things they transmit there, including the size of the device screen, etc. I wouldn't be surprised if data analysts tracked bot patterns based on this data.

They banned a guy that applied manually original key from game into hamster. What you're talking about?


https://github.com/user-attachments/assets/1102c376-aae5-4f59-9648-d50205471623

Pls, say that this is analytics too....

**Comment by XPacL** [comment]
Они просто рандомно раздали баны вот и вся математика. Про тапы в один пиксель на телефоне это вообще пиздятина, доказывающая что они держат своё комьюнити за глупое стадо.

**Comment by WeendVidente777** [comment]
> они держат своё комьюнити за глупое стадо.

поправочка, за стадо хомяков) И в общем то не скрывают этого.
