### ISSUE TITLE
82 - Unknown error while getting access token: Cannot connect to host (SSL: CERTIFICATE_VERIFY_FAILED) 

### ISSUE THREAD

**Issue by glorySyntax** [shamhi/HamsterKombatBot#25]
![image](https://github.com/shamhi/HamsterKombatBot/assets/128384088/fe1ba863-6795-4f50-862a-78017c382e4e)
Запускаю на своем компе - всё шикарно работает для 3-ёх аккаунтов, запускаю на дедике - вот такая ошибка

**Comment by flexxiki** [comment]
такая же хуйня, пробовал с прокси - все равно не ворк :( 
если решил проблему, подскажи пожалуйста!

**Comment by mspet23** [comment]
еба тоже самое, и всегда на дедике такая хуйня

**Comment by maplexx14** [comment]
Похоже что на ваших дедиках закрыт доступ к запросам на другие IP

**Comment by ButCheR-PRO** [comment]
Дубликат: https://github.com/shamhi/HamsterKombatBot/issues/143
