### ISSUE TITLE
Для чего нужен файл profile.json ?

### ISSUE THREAD

**Issue by bd100b** [shamhi/HamsterKombatBot#252]

**Comment by dinrise** [comment]
Получает заголовки с помощью него, в коде же все понятно

**Comment by bd100b** [comment]
заголовки и отпечаток для каждой сессии уникальный генерится?

**Comment by dinrise** [comment]
да

**Comment by shamhi** [comment]
работает по такому принципу

```json
{
  "session1": {
      "headers": {...},
      "fingerprint": {...}
  },
  "session2": {
      "headers": {...},
      "fingerprint": {...}
  },
  ...
}
```

`session1` и `session2` - названия сессий в папке `sessions/session1.session` и `sessions/session2.session`
