### ISSUE TITLE
Запуск бота сразу в выбранном режиме: Создание сессии/Кликер

### ISSUE THREAD

**Issue by VintaGist** [shamhi/HamsterKombatBot#258]
https://github.com/shamhi/HamsterKombatBot/blob/0ca5159d1689e5a2debf2354d9a8f776bcf2a8d1/START.bat#L5

Прошу заменить указанную строку на 
```
python main.py %*
````

Это даст возможность пробрасывать параметры запуска в main.py и запускать сразу необходимый режим:
`.\START.bat -a 1` - Create session
`.\START.bat -a 2` - Run clicker

**Comment by ButCheR-PRO** [comment]
А я сеье создал START2_clicker.bat
```
@echo off
echo Activating virtual environment...
call venv\Scripts\activate
echo Starting the bot...
python main.py --action 2
pause

```
