### ISSUE TITLE
[Вопрос] Работает ли бот с прокси ipv6?

### ISSUE THREAD

**Issue by dlgv24** [shamhi/HamsterKombatBot#259]
Купил несколько прокси для теста. Приложение телеграм с ними работает, все норм, а вот бот не хочет. Нужно брать ipv4 прокси или возможно как нибудь допилить бота?

**Comment by tancyit3** [comment]
IPv4 надо, можешь купить на сайте - https://proxy6.net/
Возьми IPv4 Shared на троих которые, дешевле стоит, а разницы нет. тип SOCKS5
IPv4 Shared 1 месяц - 33р, копейки

**Comment by KOTBCTAKAHE** [comment]
### Только IPv4.
