### ISSUE TITLE
Словил бан аккаунта

### ISSUE THREAD

**Issue by dmitry-js** [shamhi/HamsterKombatBot#261]
Делал все по инструкции, скрипт был запущен где-то 2 часа, после чего аккаунт был заблокирован. 
Хорошо использовался виртуальный номер (был куплен несколько дней назад и до этого нормально работал), а не реальный, иначе потерял бы основной аккаунт. 

Были ли еще у кого-то баны, кто каких рекомендаций придерживается при работе с подобными ботами и как свести риски блокировки к минимуму?
![photo_2024-06-10_15-04-02](https://github.com/shamhi/HamsterKombatBot/assets/118116492/aa060856-facf-44e4-904a-f146c1ef58c2)

**Comment by ig55555or** [comment]
тебя просто забанили в тг, используй реальные номера и будет все нормально

**Comment by ButCheR-PRO** [comment]
> Были ли еще у кого-то баны, кто каких рекомендаций придерживается при работе с подобными ботами и как свести риски блокировки к минимуму?

Покупай реальные сим-карты и создавай на них аккаунт в Телеграм. 

Тема 1 https://github.com/shamhi/HamsterKombatBot/issues/121
Тема 2 https://github.com/shamhi/HamsterKombatBot/issues/197
Тема 3 https://github.com/shamhi/HamsterKombatBot/issues/202
Тема 4 https://github.com/shamhi/HamsterKombatBot/issues/237
