### ISSUE TITLE
После запуска бота не даёт зайти в аккаунт вручную

### ISSUE THREAD

**Issue by Vuduist** [shamhi/HamsterKombatBot#262]
Запустил бота, после отключения бота и удаления сессии из списка устройств телеграм, не даёт авторизоваться в игре. Что в таком случае делать? Ожидание и перезагрузка устройства не помогает.
![image](https://github.com/shamhi/HamsterKombatBot/assets/66877692/9be8b7f0-3835-4501-8f85-9382fd54829a)

**Comment by slayer326** [comment]
> Запустил бота, после отключения бота и удаления сессии из списка устройств телеграм, не даёт авторизоваться в игре. Что в таком случае делать? Ожидание и перезагрузка устройства не помогает. ![image](https://private-user-images.githubusercontent.com/66877692/338195926-9be8b7f0-3835-4501-8f85-9382fd54829a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMjc0MjgsIm5iZiI6MTcxODAyNzEyOCwicGF0aCI6Ii82Njg3NzY5Mi8zMzgxOTU5MjYtOWJlOGI3ZjAtMzgzNS00NTAxLThmODUtOTM4MmZkNTQ4MjlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDEzNDUyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZDFkNzE0OTQzZTRlZjExZjQ2ZTkxNTE5YWY4NWY0YWNhMzYxODM0ODljMWQ4ZTI0NTlkODY3OWE3N2JjNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nYf22AcuCwOfGhGeZSbHfE-j7BXZrPsulkJtHjgaTvc)

Подождать пару часов, всё будет работать, проходили)

**Comment by doctormors** [comment]
30 минут надо подождать примерно, в коде сессия длиться 3600сек

**Comment by ButCheR-PRO** [comment]
> 30 минут надо подождать примерно, в коде сессия длиться 3600сек

3600 секунд = 60 минут. 
А вообще это дубликат темы: https://github.com/shamhi/HamsterKombatBot/issues/128
