### ISSUE TITLE
 Unknown error during Authorization: Telegram says: [406 CHANNEL_PRIVATE] - The channel/supergroup is not accessible (caused by "channels.GetMessages")

### ISSUE THREAD

**Issue by RGiuseppeZ** [shamhi/HamsterKombatBot#265]
![image](https://github.com/shamhi/HamsterKombatBot/assets/93671014/134b43ff-d6c7-4053-9f17-5ee281bed36f)

**Comment by ButCheR-PRO** [comment]
Read this: 
1 https://github.com/shamhi/HamsterKombatBot/issues/38
2 https://github.com/shamhi/HamsterKombatBot/issues/58
3 https://github.com/shamhi/HamsterKombatBot/issues/86
4 https://github.com/shamhi/HamsterKombatBot/issues/137
5 https://github.com/shamhi/HamsterKombatBot/issues/263

**Comment by Dererontino** [comment]
![image](https://github.com/user-attachments/assets/1457cc29-cc21-4209-b470-5c0cbfa0118c)
Все что написано выше не работает
