### ISSUE TITLE
Бот не покупает некоторые карточки

### ISSUE THREAD

**Issue by EddieBrock69** [shamhi/HamsterKombatBot#267]
Проблема в том, что бот почему-то просто не покупает некоторые карточки, хотя они явно выгоднее остальных, баланса точно хватает. Вот некоторые из них: "Consensus Piranha Pass", "Bitcoin Pizza day", "Top 10 Global Ranking", "Special Hamster Conference".

**Comment by gg-script** [comment]
Вроде как дубликат и об этом известно

**Comment by ButCheR-PRO** [comment]
Обнови бота до последней версии
