### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by carapa44** [shamhi/HamsterKombatBot#269]
![image](https://github.com/shamhi/HamsterKombatBot/assets/44908509/868c3daf-04b4-47d2-ae4c-b63a3df60380)
install.bat не помог, вручную в питоне не шарю на столько, чтоб прилепить loguru к текущей системе.

**Comment by gg-script** [comment]
pip install loguru

**Comment by ButCheR-PRO** [comment]
Дубликат:
https://github.com/shamhi/HamsterKombatBot/issues/150

**Comment by carapa44** [comment]
> Дубликат: #150

> pip install loguru

Не помогло, потому и поднял новый тред
