### ISSUE TITLE
Как пользоваться USE_RANDOM_USERAGENT?

### ISSUE THREAD

**Issue by bd100b** [shamhi/HamsterKombatBot#270]

**Comment by tancyit3** [comment]
в .env ставишь - USE_RANDOM_USERAGENT=True и пошло поехало)

**Comment by bd100b** [comment]
получается всех кто пользовался ботом до обновления могут побрить так как у всех стоял один и тот же юзерагент на все сессии))

**Comment by RelaxNewLife** [comment]
yes dosn't work URA also after last update
