### ISSUE TITLE
Зависает бот после апгрейда.

### ISSUE THREAD

**Issue by kaospwnz** [shamhi/HamsterKombatBot#271]
После апгрейда бот зависает, при нажатии любой клавиши- продолжает работу.
![image](https://github.com/shamhi/HamsterKombatBot/assets/136068263/9592dfeb-c10d-44bd-8f71-ebebd29b9cb2)

В 2:16:39 был нажат пробел

Win10
Py 3.11.2

Конфиг:
MIN_AVAILABLE_ENERGY=100
SLEEP_BY_MIN_ENERGY=[1800,2400]
ADD_TAPS_ON_TURBO=2500
AUTO_UPGRADE=True
MAX_LEVEL=20
BALANCE_TO_SAVE=51000
UPGRADES_COUNT=10
APPLY_DAILY_ENERGY=True
APPLY_DAILY_TURBO=True
RANDOM_TAPS_COUNT=[50,200]
SLEEP_BETWEEN_TAP=[10,25]
USE_PROXY_FROM_FILE=False

**Comment by kaospwnz** [comment]
Так же вот, заснул на 1947 секунд, по итоге прошло больше, разбудил нажатием клавиши
![image](https://github.com/shamhi/HamsterKombatBot/assets/136068263/c107af00-2835-4bbd-96d4-73153d660fc5)

**Comment by KOTBCTAKAHE** [comment]
Такое может происходить. Проблема может быть связана с буферизацией вывода логгера. По умолчанию стандартный вывод (stdout) буферизируется, и это может привести к задержке отображения сообщений. Когда вы нажимаете любую клавишу, это может приводить к сбросу буфера и отображению накопленных сообщений

**Comment by kaospwnz** [comment]
То есть фактически бот не зависает, просто не отдает в терминал stdout?

**Comment by KOTBCTAKAHE** [comment]
> То есть фактически бот не зависает, просто не отдает в терминал stdout?

Да, все верно. Если я конечно, не ошибаюсь.

**Comment by kaospwnz** [comment]
Встроенного логгирования нет? Надо либо самому дописать, либо отладить через IDE? 
Можно небольшое напутствие получить, а то я только автотесты умею писать :D

**Comment by ButCheR-PRO** [comment]
1. https://github.com/shamhi/HamsterKombatBot/issues/209
