### ISSUE TITLE
[Предложение] Подключение рефералов к аккаунту | Add referrals (refferal referal реферал)

### ISSUE THREAD

**Issue by Inatril** [shamhi/HamsterKombatBot#273]
Возможно ли сделать режим для подключения рефералов к аккаунту.
Примерный принцип работы выглядит просто:
в конфиге указывается ссылка либо же прямо в консоли,
и все сессии подключаются по этой ссылке и нажимают кнопку клайма приза за рефералку.

**Comment by ButCheR-PRO** [comment]
1. https://github.com/shamhi/HamsterKombatBot/issues/224
