### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type' в чем может быть проблема?

### ISSUE THREAD

**Issue by LorenaDeff** [shamhi/HamsterKombatBot#274]
На винде, запустил install, далее start, выходит ошибка( что не так?)
![image](https://github.com/shamhi/HamsterKombatBot/assets/153757233/4d9ef75b-0ba0-4eb7-837f-67ad4d4355ea)

**Comment by euphoria360** [comment]
python version is old. use debian 12.

**Comment by shamhi** [comment]
use python 3.11

**Comment by ButCheR-PRO** [comment]
# Получение API ключей:
1. Перейдите на сайт [my.telegram.org](https://my.telegram.org) и войдите в систему, используя свой номер телефона.
2. Выберите "API development tools" и заполните форму для регистрации нового приложения.
3. Запишите API_ID и API_HASH в файле .env, предоставленные после регистрации вашего приложения.

# Установка:
Скачай и установи: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Затем синхронизируйте на компьютере системное время.
Скачай последнюю версию бота [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) и распакуй.
Потом запусти INSTALL.bat. 
Затем нужно настроить конфиг .env согласно документации в README.md
После этого нужно создать сессию через START.bat выбрав пункт 1. 
И только потом запускать настроенный кликер через START.bat выбрав пункт 2.
