### ISSUE TITLE
Не будет ли палевно что после каждого перезапуска бота присваивается новый юзерагент? )

### ISSUE THREAD

**Issue by bd100b** [shamhi/HamsterKombatBot#277]

**Comment by shamhi** [comment]
твой выбор, можешь поставить статичные хэдеры и фингерпринты для каждой сессии в файле `profiles.json` а можешь использовать рандомный юзерагент

**Comment by bd100b** [comment]
> твой выбор, можешь поставить статичные хэдеры и фингерпринты для каждой сессии в файле `profiles.json` , а можешь использовать рандомный юзерагент

типа, пересоздать сессии и под каждую сессию менять файл profiles.json и оно те данные сохранит в файл session?

**Comment by Kit0077** [comment]
> твой выбор, можешь поставить статичные хэдеры и фингерпринты для каждой сессии в файле `profiles.json` , а можешь использовать рандомный юзерагент

Можно как то посмотреть в каком формате указывать юзеры для каждой сессии?
