### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by ffipper** [shamhi/HamsterKombatBot#28]
Какого вида должен быть API_ID / API_HASH, я уже по разному перепробовал вставлять, выплывает ошибка.
![photo_2024-05-19_15-05-58](https://github.com/shamhi/HamsterKombatBot/assets/71987966/75c8ffe0-80d8-44da-bea2-4c60b47c24d2)

**Comment by ggaammeerr** [comment]
Открой файл .env и там впиши
