### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by shekelx** [shamhi/HamsterKombatBot#282]
Кто знает как пофиксить?
![mlN5wxg](https://github.com/shamhi/HamsterKombatBot/assets/155970596/0d18682d-320d-4675-a43a-e423d4019349)

**Comment by KOTBCTAKAHE** [comment]
в .env у вас неправильное значение в MAX_LEVEL.

**Comment by ButCheR-PRO** [comment]
В .env установи:
`MAX_LEVEL=20`
