### ISSUE TITLE
При запуске бота возникает ошибка TypeError: nt._path_exists() takes no keyword arguments

### ISSUE THREAD

**Issue by kexc** [shamhi/HamsterKombatBot#283]
После установки и запуска бота "с нуля" на Windows, возникает следующая ошибка (актуально для бранчей dev и main).

Activating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "C:\bots\HamsterKombatBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\bots\HamsterKombatBot\bot\utils\__init__.py", line 8, in <module>
    if not os.path.exists(path='sessions'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments

**Comment by KOTBCTAKAHE** [comment]
Ошибка указывает на то, что функция `os.path.exists` не принимает именованные аргументы, что вызывает исключение `TypeError`. Проблема возникает из-за использования именованного аргумента `path`, тогда как функция `os.path.exists` принимает путь как позиционный аргумент.

Чтобы исправить эту ошибку, нужно изменить вызов `os.path.exists` в файле `C:\bots\HamsterKombatBot\bot\utils\__init__.py`.

Вместо:
```python
if not os.path.exists(path='sessions'):
```

должно быть:
```python
if not os.path.exists('sessions'):
```
Не знаю, исправит ли это ситуацию.

**Comment by kexc** [comment]
> Ошибка указывает на то, что функция `os.path.exists` не принимает именованные аргументы, что вызывает исключение `TypeError`. Проблема возникает из-за использования именованного аргумента `path`, тогда как функция `os.path.exists` принимает путь как позиционный аргумент.
> 
> Чтобы исправить эту ошибку, нужно изменить вызов `os.path.exists` в файле `C:\bots\HamsterKombatBot\bot\utils\__init__.py`.
> 
> Вместо:
> 
> ```python
> if not os.path.exists(path='sessions'):
> ```
> 
> должно быть:
> 
> ```python
> if not os.path.exists('sessions'):
> ```
> 
> Не знаю, исправит ли это ситуацию.

Да, данная правка исправляет эту проблему.

**Comment by kexc** [comment]
> Не знаю, исправит ли это ситуацию.

Да, данное изменения исправляет эту ошибку
