### ISSUE TITLE
for buy combo cards

### ISSUE THREAD

**Issue by repon06** [shamhi/HamsterKombatBot#284]
`if common_price < bonus and balance > common_price and is_combo_accessible:`
to
`if common_price < bonus and balance > common_price and not is_combo_accessible:`

**Comment by VintaGist** [comment]
> to

Поясни свою мысль.

**Comment by Hoochizoid** [comment]
> 2024-06-13 23:03:25 | INFO     | 107 - Home | Last passive earn: +____________ | Earn every hour: 1_____________
> 2024-06-13 23:03:27 | INFO     | 156 - Home | Daily combo is not applicable, you can only purchase 2 of 3 cards
> 2024-06-13 23:03:33 | SUCCESS  | 285 - Home | Successful tapped! | Balance: 8_______________ (+5________) | Total: 2___________
> 2024-06-13 23:03:33 | INFO     | 442 - Sleep 18s

При этом комбо уже было собрано днем (в ручную)... Я думал бот проверяет, собрано ли комбо, а потом его выполняет...

**Comment by ButCheR-PRO** [comment]
https://github.com/shamhi/HamsterKombatBot/issues/251#issuecomment-2175933781
