### ISSUE TITLE
UnicodeEncodeError 'charmap' codec can't encode characters in position 4-5 character maps to undefined - Ошибка кодировки?

### ISSUE THREAD

**Issue by DIMITREOS** [shamhi/HamsterKombatBot#287]
![image](https://github.com/shamhi/HamsterKombatBot/assets/116508458/bf6698ec-9917-40a8-a815-332339517e20)

**Comment by KOTBCTAKAHE** [comment]
Ошибка UnicodeEncodeError указывает на то, что Python пытается вывести символы, которые не могут быть закодированы в текущей кодировке консоли (в данном случае cp1251).
Попробуйте ввести следующую комманду: 
   ```sh
   chcp 65001
   ```

**Comment by ButCheR-PRO** [comment]
Ещё попробуй скачай и установи: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
