### ISSUE TITLE
[Опрос] Как часто банят в игре?

### ISSUE THREAD

**Issue by PrograMistV1** [shamhi/HamsterKombatBot#288]
Я изучаю работу хомяка и сейчас рассматриваю авторизацию в игре. Так как не хочется потерять игровой аккаунт, я начал искать все возможные причины блокировок, но, пересмотрев практически все вопросы, связанные с этой темой, я понял, что банят только сами аккаунты в Telegram, а не игровые аккаунты. Есть ли здесь люди, которых банили в самой игре за использование ботов?

**Comment by ButCheR-PRO** [comment]
После листинга узнаем :)

**Comment by PrograMistV1** [comment]
Почему после листинга?

**Comment by Kit0077** [comment]
> Почему после листинга?

Потому что ботоводы создают активность и движ в системе, что очень на руку создателям таких проектов как хомяк. Во время листинга, как это было с НотКоином, спалившихся ботов просто побреют)) их монеты раздадут либо в бонус другим пользователям, либо отправят для ликвидности на биржу.

**Comment by PrograMistV1** [comment]
> Потому что ботоводы создают активность и движ в системе

Штош, это объясняет почему я не смог найти ни единого забаненного человека. Остаётся лишь надеяться что после листинга не прилетит бан.

**Comment by XPacL** [comment]
Всех поброют при раздаче, проходили уже

**Comment by yoyoallf** [comment]
> > Потому что ботоводы создают активность и движ в системе
> 
> Штош, это объясняет почему я не смог найти ни единого забаненного человека. Остаётся лишь надеяться что после листинга не прилетит бан.

нот коин именно на листинге побрил многих фермеров

**Comment by ButCheR-PRO** [comment]
> А палят не по айпи, не по юзерагентам, а по тапанью в одну точку, человек так не сможет при всем желании

Для надёжности лучше заходить иногда в игру самому и тапать хоть немного и покупать что-то вручную. Ну и задания выполнять

**Comment by treyne** [comment]
> > > Потому что ботоводы создают активность и движ в системе
> > > Штош, это объясняет почему я не смог найти ни единого забаненного человека. Остаётся лишь надеяться что после листинга не прилетит бан.
> 
> нот коин именно на листинге побрил многих фермеров
> 
> А палят не по айпи, не по юзерагентам, а по тапанью в одну точку, человек так не сможет при всем желании

Вообще при тапе на сервер не посылается информация о координатах нажатия. Даже несколько тапов просто по итогу объединяются в один
![IMG_20240707_092258_148](https://github.com/shamhi/HamsterKombatBot/assets/8302610/e1457e62-9fca-4d0b-9a33-32f49950be22)
![IMG_20240707_092258_441](https://github.com/shamhi/HamsterKombatBot/assets/8302610/4658186d-7cef-49c5-a6fb-a0120dbb9709)
![IMG_20240707_092258_991](https://github.com/shamhi/HamsterKombatBot/assets/8302610/2b4a6a45-5be6-4c0a-9dfd-70a89e79e3fa)
![IMG_20240707_092258_271](https://github.com/shamhi/HamsterKombatBot/assets/8302610/07d2b938-be0f-4c34-8d5f-9bbed4c3f7dd)
![IMG_20240707_092258_903](https://github.com/shamhi/HamsterKombatBot/assets/8302610/396fe455-4525-4a80-b9b9-48761b6aba13)
ин запрос.

**Comment by PrograMistV1** [comment]
> Ещё я выяснил что слово дня хранится непосредственно в коде станицы.

Морзе передается в `https://api.hamsterkombat.io/clicker/config` в виде base64 строки +1 лишний символ. Удаляешь 4 символ и преобразуешь base64 в utf8.

**Comment by treyne** [comment]
> едается в `https://`

Спасибо огромное! Я сам бы очень долго искал

**Comment by MsaMadman** [comment]
> я понял, что банят только сами аккаунты в Telegram

уже начинаю переживать 😱. Банят навсегда?

**Comment by hardim26** [comment]
> > я понял, что банят только сами аккаунты в Telegram
> 
> уже начинаю переживать 😱. Банят навсегда?

Банят за паразитивную нагрузку. Нпример если тапер запускется раз в 5 минут.

**Comment by MsaMadman** [comment]
я использую бот где нет отправки данных в гугл аналитику https://github.com/jawikas/hamsterkombat


> > > я понял, что банят только сами аккаунты в Telegram
> > 
> > 
> > уже начинаю переживать 😱. Банят навсегда?
> 
> Банят за паразитивную нагрузку. Нпример если тапер запускется раз в 5 минут.

я использую бот где нет отправки данных в гугл аналитику https://github.com/jawikas/hamsterkombat

в таком случае тоже бан?
