### ISSUE TITLE
[Предложение] Уведомления в telegram

### ISSUE THREAD

**Issue by Hoochizoid** [shamhi/HamsterKombatBot#289]
Уважаемые разработчики, можно добавить возможностью направления уведомлений о работе бота в телеграмм (например, ошибки и сводную статистику о работе бота за последний чат), а также возможность остановки (паузы) и возобновления работы бота?

**Comment by Kit0077** [comment]
> Уважаемые разработчики, можно добавить возможностью направления уведомлений о работе бота в телеграмм (например, ошибки и сводную статистику о работе бота за последний чат), а также возможность остановки (паузы) и возобновления работы бота?

Мне кажется это уже борщ😁можно сразу тогда Дурову отправлять свои достижения или в поддержку хомяка

**Comment by 4erdenko** [comment]
> Уважаемые разработчики, можно добавить возможностью направления уведомлений о работе бота в телеграмм (например, ошибки и сводную статистику о работе бота за последний чат), а также возможность остановки (паузы) и возобновления работы бота?

Не знаю, как у остальных, а у меня есть такие планы.

**Comment by bd100b** [comment]
> > Уважаемые разработчики, можно добавить возможностью направления уведомлений о работе бота в телеграмм (например, ошибки и сводную статистику о работе бота за последний чат), а также возможность остановки (паузы) и возобновления работы бота?
> 
> Не знаю, как у остальных, а у меня есть такие планы.

а смысл если скоро листинг? 
разве что как шаблон для будущих проектов

**Comment by yoyoallf** [comment]
> > > Уважаемые разработчики, можно добавить возможностью направления уведомлений о работе бота в телеграмм (например, ошибки и сводную статистику о работе бота за последний чат), а также возможность остановки (паузы) и возобновления работы бота?
> > 
> > 
> > Не знаю, как у остальных, а у меня есть такие планы.
> 
> а смысл если скоро листинг? разве что как шаблон для будущих проектов

Смысл в том, что разрабы говорят, что майнить монету можно будет и после листинга. Если она что-то будет стоить, то забивать на хомяка не будут

**Comment by KOTBCTAKAHE** [comment]
раз уж многие этого хотят, то как можно будет реализовать уведомление. тг бот это должен уведомлять?

**Comment by mlt-melt** [comment]
> раз уж многие этого хотят, то как можно будет реализовать уведомление. тг бот это должен уведомлять? в избранное вряд-ли это можно, уведы тупо не будут приходить

Можно реализовать наиболее простым способом. Регаем бота в BotFather, получаем токен
Отправляем http запрос на урл:
`https://api.telegram.org/*bot token*/sendMessage?chat_id=*tg id*&text=Уведомление`

Это подойдет для уведомлений. Но чтобы например остановить фарм через бота, нужно скорее всего запускать полноценный инстанс, например через aiogram. Это уже работа посерьезней
