### ISSUE TITLE
Пример файла конфигураций .env | Example configuration file .env

### ISSUE THREAD

**Issue by Human4ik1** [shamhi/HamsterKombatBot#290]
знаю, глупый вопрос. но я ни как не могу понять, как правильно заполнить файл конфигураций.
разные варианты пробовал, но все время получаю ошибку о том что настройки не верные.
пожалуйста, приведите полностью заполненный файл конфигураций

**Comment by VintaGist** [comment]
> знаю, глупый вопрос. но я ни как не могу понять, как правильно заполнить файл конфигураций.
> разные варианты пробовал, но все время получаю ошибку о том что настройки не верные.
> пожалуйста, приведите полностью заполненный файл конфигураций

Если файл `.env` заполнен не полностью, значения берутся по умолчанию из обработчика конфига:

https://github.com/shamhi/HamsterKombatBot/blob/main/bot/config/config.py#L6C1-L31C1

`API_ID` и `API_HASH` заполнять обязательно. Без этого никак.

**Comment by ButCheR-PRO** [comment]
Вот пример файла .env:
```
API_ID=11111111
API_HASH=9999999xxxxxxxxxxx99999999999999

MIN_AVAILABLE_ENERGY=100
SLEEP_BY_MIN_ENERGY=[1800,2400]

ADD_TAPS_ON_TURBO=2500

AUTO_UPGRADE=True
MAX_LEVEL=20
BALANCE_TO_SAVE=1000000
UPGRADES_COUNT=10

APPLY_DAILY_ENERGY=True
APPLY_DAILY_TURBO=True

RANDOM_TAPS_COUNT=[50,200]
SLEEP_BETWEEN_TAP=[10,25]

USE_RANDOM_USERAGENT=True
USE_PROXY_FROM_FILE=False
```

**Comment by Human4ik1** [comment]
спасибо, в тот же вечер смог правильно заполнить все поля и успешно запустить бота)
но как шпору думаю этот вопрос оставить можно)

**Comment by KOTBCTAKAHE** [comment]
> спасибо, в тот же вечер смог правильно заполнить все поля и успешно запустить бота) но как шпору думаю этот вопрос оставить можно)

Окей.
