### ISSUE TITLE
Unable to sync

### ISSUE THREAD

**Issue by angelnofly74** [shamhi/HamsterKombatBot#293]
После запуска бота, и успешного выполнения заданий решил зайти и проверить в аккаунтах на как прошли обновления и столкнулся с тем что на всех аккаунтах одинаково 
Request error Unable to sync
![Screenshot_3](https://github.com/shamhi/HamsterKombatBot/assets/172526176/5cd98a16-d18d-4109-9ff7-f01a424aee4f)
при этом запуская скрипт снова он успешно работает тапает и прокачивает, ну в общем все работает
я видимо ошибся в том что не сделал true для рандом юзер агент

получается забани все аки? 40 аков 

upd. 15 минут спустя (примерно) проверял по 10 штук - все аки заработали
что в итоге произошло не понял

**Comment by Pawansingh333** [comment]
This Is Hamster Server Issue

**Comment by Sanek63** [comment]
я как понял это обычная ошибка синхронизации, когда параллельно бот фармит монетку и ты пытаешься запустить приложуху. У меня такое решалось тем, что я останавливал бота, ждал порядка 10-15 минут (сразу не срабатывало) и далее заходило в приложение

**Comment by angelnofly74** [comment]
![Screenshot_3](https://github.com/shamhi/HamsterKombatBot/assets/172526176/c691210d-7cf7-445a-8b50-c8ce2eccb8a4)
Ну в обще последствия одинаковых юзер агентов на 40 аках стразу видны спустя 12 часов телега отреагировала акаунты в бане (судя по  логам в боте)

**Comment by Sanek63** [comment]
а покажи лог, где у тебя пишет то, что акки в бане

**Comment by angelnofly74** [comment]
> а покажи лог, где у тебя пишет то, что акки в бане

![photo_2024-07-04_11-44-43](https://github.com/shamhi/HamsterKombatBot/assets/172526176/d7fae013-824e-49e9-bd15-b9266556554d)

**Comment by angelnofly74** [comment]
> а ты прокси хотя бы юзал? Или все с одного ip херачил

да 1 прокси - 1 акаунт
