### ISSUE TITLE
ERROR: Invalid interpolation format for "command" option in service "bot": "${ARGUMENT:2}"

### ISSUE THREAD

**Issue by mrdarkerr** [shamhi/HamsterKombatBot#294]
$ docker-compose up
ERROR: Invalid interpolation format for "command" option in service "bot": "${ARGUMENT:2}"

**Comment by 4erdenko** [comment]
https://github.com/shamhi/HamsterKombatBot/commit/736c03bc0fb2bc4ce80e92e668f8edd637b070c3
