### ISSUE TITLE
последствия одинаковых юзер агентов на 40 аках одновременно (моя ошибка в настройках)

### ISSUE THREAD

**Issue by angelnofly74** [shamhi/HamsterKombatBot#295]
![Screenshot_4](https://github.com/shamhi/HamsterKombatBot/assets/172526176/bfe6451b-b884-4035-8928-ad2eeea31db1)
аки стояли неделю или больше, регал все руками разные прокси на каждом все было ок вчера поставил бота протестировал на 1 аке все работало и не поменял в конфиге на рандомные юзер агенты (возможно в этом причина) больше вроде нигде не косячил 
какие есть кого мысли почему 23 ака улетели в бан разом?
спасибо

**Comment by WLASIX** [comment]
Потому что твои аккаунты недостаточно долго лежали. Моим в районе 3-4 лет - всё ок. 
Прокси не использую, юзерагенты не трогаю

**Comment by StearD2k** [comment]
Ты вручную во всех фармилках награды собираешь, или есть какая-то тактика. И можешь еще пожалуйста сказать свои настройки лдплеера, у меня i7 14700kf и после 20 окон лагать начинает.

**Comment by bd100b** [comment]
А что за софт на котором запускаешь ботов?

**Comment by E1r0y** [comment]
> Прокси не использую

Последствиями не чревато? А то хочу поставить, но вот на счёт прокси не знаю

**Comment by WLASIX** [comment]
> > Прокси не использую
> 
> Последствиями не чревато? А то хочу поставить, но вот на счёт прокси не знаю

Ну, хомяк может из-за этого не дропнуть токены, т.к. палишься по айпи. А касаемо тг, то все нормально будет, не забанят.

**Comment by Kit0077** [comment]
> ![Screenshot_4](https://private-user-images.githubusercontent.com/172526176/339278602-bfe6451b-b884-4035-8928-ad2eeea31db1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMTAwNjEsIm5iZiI6MTcxODMwOTc2MSwicGF0aCI6Ii8xNzI1MjYxNzYvMzM5Mjc4NjAyLWJmZTY0NTFiLWI4ODQtNDAzNS04OTI4LWFkMmVlZWEzMWRiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QyMDE2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzZmODE5NTgwNTRjNjYxMmFhZDNjZDhlZjRhMDQ1NzgzNWNhOWEwNzIyZmQxNGJlMjc1Yzc3ZTYwZWU3M2I5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XBg-BfKjijM-n_5SRb39UcH2sLZYS6NYRPabIs0OmZw) аки стояли неделю или больше, регал все руками разные прокси на каждом все было ок вчера поставил бота протестировал на 1 аке все работало и не поменял в конфиге на рандомные юзер агенты (возможно в этом причина) больше вроде нигде не косячил какие есть кого мысли почему 23 ака улетели в бан разом? спасибо

Бро, реально, подскажи, что за софт такой, который позволяет юзать столько окон для ТГ?

**Comment by bd100b** [comment]
> > ![Screenshot_4](https://private-user-images.githubusercontent.com/172526176/339278602-bfe6451b-b884-4035-8928-ad2eeea31db1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzMTAwNjEsIm5iZiI6MTcxODMwOTc2MSwicGF0aCI6Ii8xNzI1MjYxNzYvMzM5Mjc4NjAyLWJmZTY0NTFiLWI4ODQtNDAzNS04OTI4LWFkMmVlZWEzMWRiMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QyMDE2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NzZmODE5NTgwNTRjNjYxMmFhZDNjZDhlZjRhMDQ1NzgzNWNhOWEwNzIyZmQxNGJlMjc1Yzc3ZTYwZWU3M2I5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XBg-BfKjijM-n_5SRb39UcH2sLZYS6NYRPabIs0OmZw) аки стояли неделю или больше, регал все руками разные прокси на каждом все было ок вчера поставил бота протестировал на 1 аке все работало и не поменял в конфиге на рандомные юзер агенты (возможно в этом причина) больше вроде нигде не косячил какие есть кого мысли почему 23 ака улетели в бан разом? спасибо
> 
> Бро, реально, подскажи, что за софт такой, который позволяет юзать столько окон для ТГ?

я думаю там оперативки надо под 32 GB шоб столько окрывать)

**Comment by ButCheR-PRO** [comment]
> т.к. палишься по айпи

Если в квартире стоит роутер, раздаёт WiFi, и этим роутером пользуется сесья из 10 человек, и все играют в хомяка в квартире, естественно у всех будет одинаковый IP, за это банить не должны. user-agent желательно разный использовать но не критично, на старых версиях бота все под одним играли :) Кстати в Nox App Player через режим Multi-Drive можно много аккаунтов одновременно запускать.

**Comment by angelnofly74** [comment]
1 По поводу софта тут писали - это LDPlayer9 скачивал с оф сайта бесплатно
2 настройки базовые для всех аков это 2 ядра и оставновился на 1,5 Гб оперативы (пробова 2Гб - смысла нет работает так же своей хавает больше) на 1Гб аки иногда лагают)
3 у меня 128 оперативки есть нагрузка конечно но все стабильно работает

насчет отлежки понял просто не буду несколько ботов грузить значит, спасибо

**Comment by StearD2k** [comment]
Какой проц у тебя? И чистишь тапалки ручками или кликером?

**Comment by VintaGist** [comment]
> какие есть кого мысли почему 23 ака улетели в бан разом?


Тг лочит акки-автореги с неофиц. клиентов. А в софте именно неофициальный клиент

**Comment by angelnofly74** [comment]
я регал через эмуляторы  андроида через апк файл скачаный с оф сайта
и регал все через покупку номеров руками с разных апйпи вот странно

**Comment by Artazar13** [comment]
Какую прогу юзаешь в эмуляторе, чтобы под прокси тг запускалось?
Не может быть такого, что просто забыл включить ее перед массовым запуском ТГ?

**Comment by StearD2k** [comment]
Используй запись операций(ф10) в эмуле, чтобы записать, как ты с главного экрана заходишь и включаешь прокси, потом в настройках операции включи, чтобы она запускалась при запуске эмулятора.

**Comment by angelnofly74** [comment]
> Какую прогу юзаешь в эмуляторе, чтобы под прокси тг запускалось? Не может быть такого, что просто забыл включить ее перед массовым запуском ТГ?

я прокси ставлю в настройках телеграмм, когда регаю акаунты чтобы не возникла такая ситуация априори, если прокся сдохнет телега просто незагрузится и так я не забуду

**Comment by Artazar13** [comment]
> Используй запись операций(ф10) в эмуле, чтобы записать, как ты с главного экрана заходишь и включаешь прокси, потом в настройках операции включи, чтобы она запускалась при запуске эмулятора.

Спасибо огромное, дружище, не знал о такой функции, ты мне очень помог своим советом, очень полезная вещь. Правда функция запускается чуть раньше, чем полностью загружается эмулятор, решил это уменьшением скорости выполнения функции. Если есть более оптимальный вариант, буду благодарен за подсказку

**Comment by prognt** [comment]
> Какую прогу юзаешь в эмуляторе, чтобы под прокси тг запускалось? Не может быть такого, что просто забыл включить ее перед массовым запуском ТГ?

SuperProxy, постоянное подключение + блокировать если отключен прокси. Само запускается при старте.
