### ISSUE TITLE
Unknown error while getting Access Token: 422, message='Unprocessable Entity'

### ISSUE THREAD

**Issue by rezafebran** [shamhi/HamsterKombatBot#297]
![error](https://github.com/shamhi/HamsterKombatBot/assets/73734858/3d8346ec-f473-4074-9c36-4d29622e8c1a)

i thing i'am already correct with all env

**Comment by KOTBCTAKAHE** [comment]
i think, the session is incorrect. try to re-create session.

**Comment by rezafebran** [comment]
Already create but it’s the same i cant connect

**Comment by ButCheR-PRO** [comment]
Dupe:
1 https://github.com/shamhi/HamsterKombatBot/issues/38
2 https://github.com/shamhi/HamsterKombatBot/issues/58
3 https://github.com/shamhi/HamsterKombatBot/issues/86
4 https://github.com/shamhi/HamsterKombatBot/issues/137
5 https://github.com/shamhi/HamsterKombatBot/issues/263

**Comment by KOTBCTAKAHE** [comment]
> Already create but it’s the same i cant connect
The problem is with your proxy, have you tried without?

**Comment by ButCheR-PRO** [comment]
See this:
1. https://github.com/shamhi/HamsterKombatBot/issues/309
2. https://github.com/shamhi/HamsterKombatBot/issues/38
3. https://github.com/shamhi/HamsterKombatBot/issues/58
4. https://github.com/shamhi/HamsterKombatBot/issues/86
5. https://github.com/shamhi/HamsterKombatBot/issues/137
6. https://github.com/shamhi/HamsterKombatBot/issues/263
