### ISSUE TITLE
[Консультация] Не украдут мой аккаунт, если использовать вашу программу?

### ISSUE THREAD

**Issue by mironov1338** [shamhi/HamsterKombatBot#298]
У меня вопрос, как бот узнаёт какие карточки нужно для получения 5 миллионов?
Не украдут мой аккаунт, если использовать вашу программу?

My question is, how does the bot find out which cards are needed to get 5 million?
Will they steal my account if I use your program?

**Comment by bd100b** [comment]
Если скажут что не украдут ваш аккаунт, вы поверите в это?

**Comment by mironov1338** [comment]
Да мне интересно как работает само ПО, есть ли связь с сервером и какие данные берут они, а так я не боюсь)) максимум что могут угнать это монеты когда будет листинг)))

**Comment by Hoochizoid** [comment]
```
async def get_combo_cards(http_client: aiohttp.ClientSession) -> dict:
    return await make_post_request(
        http_client,
        'https://api21.datavibe.top/api/GetCombo',
        {},
        'getting Combo Cards',
    )
```

Данные о комбо запрашиваются данной функцией с сайта https://api21.datavibe.top/api/GetCombo, в ответ получаем: {"combo":["it_team","hamster_youtube_gold_button","product_team"],"date":"13-06-24"}

**Comment by GriGriGG** [comment]
@mironov1338 Чел, может и украдут, может и обнулят твою телегу, всё может быть, может придёт самый большой хомяк и будет стричь уже тебя
Читай лицензию. Тут никто не даст тебе гарантий: ответственность за использование этого репозитория лежит только на тебе

p.s. Просмотри код, есть ли там строчки на передачу информации третьей стороне? Сделай выводы

**Comment by XPacL** [comment]
Консультация по HamsterBOT платная

**Comment by ButCheR-PRO** [comment]
> Не украдут мой аккаунт, если использовать вашу программу?

Твой аккаунт могут украсть даже если ты никогда не будешь пользоваться подобными программами :) 
На гитхабе весь код программы открытый, его все давно изучили, и помогают дописывать и проверять, улучшать. Здесь нет вредоносного кода который уводить чужие аккаунты.

**Comment by mironov1338** [comment]
Спасибо за подколы, но я просто спросил. Я всех прочел и всё понял, спасибо буду знать, есть кого забанили в тг?
Если дают бан то уже со сто процентной вероятностью можно забыть про акк?

**Comment by GravelFire** [comment]
Как с такой шизой можно было вообще наткнуться на данный репозиторий, ведь даже если откроешь телеграмм тебе акк снесут.

**Comment by GriGriGG** [comment]
@GravelFire Можно не заводить телеграм аккаунт. Тебе не снесут того чего нет. think about it 
@mironov1338 Я бы воздержался от привязки основного акка. Ну мало ли что, всё таки основа дорога как память (контакты, файлы и проч.)

**Comment by XPacL** [comment]
> @GravelFire Можно не заводить телеграм аккаунт. Тебе не снесут того чего нет. think about it @mironov1338 Я бы воздержался от привязки основного акка. Ну мало ли что, всё таки основа дорога как память (контакты, файлы и проч.)

Да никто твой основной аккаунт не забанит из-за скрипта. Максимум что грозит, так это бритьё на раздаче.

**Comment by vital1** [comment]
Возвращаясь к исходному вопросу, хотелось бы заметить, что в коде вызов `get_combo_cards()` происходит с тем же http_client-ом, что и для функций хомяка. В частности, с теми же хедерами, в которых передаётся, например, access_token. А что это за сайт такой [https://api21.datavibe.top/api/GetCombo](url) и что они делают с этим access_token - неизвестно, так что теоретически возможно, что могут и угнать аккаунт хомяка.
