### ISSUE TITLE
[Request] More bots | Нужно больше ботов

### ISSUE THREAD

**Issue by MGTV01** [shamhi/HamsterKombatBot#300]
It is great. For other Telegram bots such as **dotcoin**, **wcoin**, topcoin**, **CyberFinanceBot**, **Simple Coin** and **monorix**, **bunnybot**, Make scripts for Clicker Mafia and the rest of the robots. Your scripts are wonderful and high-performance. Tanx

**Comment by ButCheR-PRO** [comment]
I wish I could make a bot on [GEMZ] (https://t.me/gemzcoin_bOt/tap?startapp=LRiEA-UFZlW6w1XPW4jTODI)

**Comment by bd100b** [comment]
> I wish I could make a bot on [GEMZ](https://t.me/gemzcoin_bOt/tap?startapp=LRiEA-UFZlW6w1XPW4jTODI)

так это ж мусор

**Comment by ButCheR-PRO** [comment]
> так это ж мусор

Так же и про NOT Coin Говорили и про Hamster Kombat. Но у GEMZ уже комьюнити 1 200 000, хотя она только недавно появилась. Так что сейчас есть все шансы занять первые места в этой игре, пока она не достигла пика популярности как и Hamster Kombat.
