### ISSUE TITLE
ModuleNotFoundError: No module named loguru

### ISSUE THREAD

**Issue by carapa44** [shamhi/HamsterKombatBot#301]
#269 
Using "pip install loguru" не помогло, как и обновление Pip до 24.0.0
![image](https://github.com/shamhi/HamsterKombatBot/assets/44908509/f8da446d-47a6-4cff-9dae-cab7019cc7ae)
Install.bat начал находить к.ошибку, start.bat продолжает не видеть loguru

**Comment by ButCheR-PRO** [comment]
Неужели все эти решения не помогли? https://github.com/shamhi/HamsterKombatBot/issues/269
Какая версия Python? Пробовал удалить бота, заново скачать и распаковать бота и запустить INSTALL.bat?

**Comment by yoyoallf** [comment]
Привет, проблема с этой ошибкой в переменных на винде. Смотри, вбей в поиске винды "изменение системных переменных среды", далее заходишь "переменные среды" - там в списке выбираешь "Path" и добавляешь пути до папки с питоном и до папки со скриптами питона. 

Тогда pip заработает, а до этого винда просто не распознает эту команду. Возможно, тебе придется все модули так установить через командную строку винды. Нажимаешь старт.бат и там будет писать чего не хватает, просто копируешь название модуля на который ругается и так же в кмд вводишь pip install ****
![123](https://github.com/shamhi/HamsterKombatBot/assets/172905253/490aa7dd-e262-4174-b66c-b959ee06f573)

**Comment by carapa44** [comment]
> Привет, нужно просто установить модуль. Но кмд винды может не реагировать на команду pip. Проблема с этой ошибкой в переменных на винде. Смотри, вбей в поиске винды "изменение системных переменных среды", далее заходишь "переменные среды" - там в списке выбираешь "Path" и добавляешь пути до папки с питоном и до папки со скриптами питона.
> 
> Тогда pip заработает, а до этого винда просто не распознает эту команду. Возможно, тебе придется все модули так установить через командную строку винды. Нажимаешь старт.бат и там будет писать чего не хватает, просто копируешь название модуля на который ругается и так же в кмд вводишь pip install **** ![123](https://private-user-images.githubusercontent.com/172905253/339985222-490aa7dd-e262-4174-b66c-b959ee06f573.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzM0ODUsIm5iZiI6MTcxODYzMzE4NSwicGF0aCI6Ii8xNzI5MDUyNTMvMzM5OTg1MjIyLTQ5MGFhN2RkLWUyNjItNDE3NC1iNjZjLWI5NTllZTA2ZjU3My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxNDA2MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2IwNzEwMGNlMTI3YTU0MGI1MDZlZjQ3MzJhNzAxNzBlOTlmNDY1OWQwNmVjMjI1MWEwNTgyMzA4ZDcxZDRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.60TWIrvkYC0BcC_p_p7RqVfEfIBF6vxofWPOzSqUNlQ)

В том и проблема, что винда распознает pip и даже установила loguru, но по какой-то причине его не видит именно софт...
