### ISSUE TITLE
ATP▷【公式放送】大坂なおみvsアンドレースク ライブ放送.生放送.ライブ配信.テレビ放送 2024年6月14日

### ISSUE THREAD

**Issue by x10sion** [shamhi/HamsterKombatBot#306]
01分前-大坂なおみ戦へ「私たちは似たようなキャリア」 元世界4位アンドレースク8強入り＜女子テニス＞ 2024年6月14日

**[🔴生中継▶ 大坂なおみvsアンドレースク ライブ](https://x-stream247.blogspot.com/2021/10/tennis.html)**

**[🔴生中継▶ 大坂なおみvsアンドレースク ライブ](https://x-stream247.blogspot.com/2021/10/tennis.html)**

女子テニスのリベマ・オープン（オランダ/スヘルトーヘンボス、芝、WTA250）は12日にシングルス2回戦が行われ、ワイルドカード（主催者推薦）で出場している世界ランク228位のB・アンドレースク（カナダ）が第6シードのユアン・ユエ（中国）を6-4, 6-4のストレートで破りベスト8進出を果たした。アンドレースクは準々決勝で同125位の大坂なおみと対戦する。

【大坂なおみvsアンドレースク 1ポイント速報】 23歳で元世界ランク4位のアンドレースクは負傷でツアーから離脱していたものの、前週の全仏オープン（フランス/パリ、レッドクレー、グランドスラム）で約10ヵ月ぶりに復帰。同大会では2試合に勝利し3回戦に進出した。

サーフェスを芝に移し復帰2大会目としてリベマ・オープンに出場。1回戦では予選勝者で世界ランク392位のE・ヴェダー（オランダ）を下し2回戦に駒を進めた。

世界ランク38位のユアンと顔を合わせた2回戦、アンドレースクはサービス時に69パーセントの確率でポイントを獲得し相手のブレークを1度に抑えると、リターンゲームでは3度のブレークを果たし、1時間21分で8強入りを決めた。

勝利したアンドレースクは準々決勝で同じくワイルドカードで出場している大坂と対戦する。大坂は2回戦で同140位のS・ラメンス（オランダ）を下しての勝ち上がり。

両者は過去に2019年10月のチャイナ・オープン（中国/北京、ハード、当時WTAプレミアマンダトリー）準々決勝で1度対戦しており、この時は大坂が5-7, 6-3, 6-4の逆転で勝利した。

大坂は2018年と2020年の全米オープン（アメリカ/ニューヨーク、ハード、グランドスラム）女王で、アンドレースクは2019年の全米オープン女王。準々決勝は元全米オープン女王対決となる。

女子テニス協会のWTAは公式サイトにアンドレースクの大坂戦に向けてのコメントを掲載した。

「ある意味、私たちは似たようなキャリアを歩んできた。同じではないけれど、私たちはとても若い頃に優勝して、その後何度も休んできた。彼女と一緒にコートに戻ってきたことは、テニス界にとって素晴らしいことだと思う。私たちはイガ（シフィオンテク）のような直線的なキャリアを歩んでいないので、ロールモデルでもある」

「これが他の人のモチベーションや刺激になってほしい。勝てなくても幸せだということを示せる。テニスはテニスに過ぎない。それ以外の人生も発見できる。私たちは二人ともそのレベルに達していると思うし、これをみるのは素晴らしいことよ」

女子テニスのリベマ・オープン（オランダ/スヘルトーヘンボス、芝、WTA250）は１４日、ワイルドカード（主催者推薦）で出場する世界ランク１２５位の大坂なおみと同じくワイルドカードで参戦する同２２８位のＢ・アンドレースク（カナダ）のシングルス準々決勝がセンターコートの第３試合に組まれた。試合は日本時間１４日の２２時（現地１４日の１５時）以降に開始予定。

両者は２度目の顔合わせであり、大坂の１勝。唯一の対戦は２０１９年１０月のチャイナ・オープン（中国/北京、ハード、当時WTAプレミアマンダトリー）準々決勝であり、この時は大坂が5-7, 6-3, 6-4の逆転で勝利した。

なお、大坂は２０１８年と２０２０年の全米オープン（アメリカ/ニューヨーク、ハード、グランドスラム）女王で、アンドレースクは２０１９年の全米オープン女王。準々決勝は元全米オープン女王対決となる。

７月１日に開幕するウィンブルドン（イギリス/ロンドン、芝、グランドスラム）に照準を合わせている大坂は今大会が芝コートシーズン１大会目。１回戦で第４シードのＥ・メルテンス（ベルギー）、２回戦で世界ランク１４０位のＳ・ラメンス（オランダ）を下し、芝コートのツアー大会では２０１８年６月のネイチャー・バレー・オープン（イギリス/ノッティンガム、芝、WTA250）以来 約６年ぶりの８強入りを決めた。

一方、元世界ランク４位のアンドレースクは１回戦で予選勝者で世界ランク３９２位のＥ・ヴェダー（オランダ）、２回戦で第６シードのユアン・ユエ（中国）を下しベスト８に駒を進めた。

なお、この試合の勝者は準決勝で予選勝者で世界ランク１３８位のＤ・ガルフィ（ハンガリー）と同４００位のA・クルニッツ（セルビア）のどちらかと対戦する。

**Comment by ButCheR-PRO** [comment]
spam
