### ISSUE TITLE
[Предложение] Покупать комбо даже если в минус

### ISSUE THREAD

**Issue by Kit0077** [shamhi/HamsterKombatBot#310]
Подскажите пожалуйста, почему скрипт не покупает комбо, если нет никаких ограничений. Вручную я спокойно захожу и покупаю. Почти сутки прошли, комбо не было куплено.

![photo_2_2024-06-15_12-45-58](https://github.com/shamhi/HamsterKombatBot/assets/57114371/e2c9ace3-b239-4c77-9a24-6ec30ac6305f)
![photo_1_2024-06-15_12-45-58](https://github.com/shamhi/HamsterKombatBot/assets/57114371/da32c84e-f5f0-41b0-9883-564560fb56f5)
![image](https://github.com/shamhi/HamsterKombatBot/assets/57114371/4d11afcb-1f0d-40bc-a174-e0fa23a4dae8)

**Comment by Kit0077** [comment]
Возможно я нашел причину, может ли это быть связано со значением "UPGRADES_COUNT", если для покупки в комбо, карта должна преодолеть значение указанное в "UPGRADES_COUNT"?

**Comment by gg-script** [comment]
Ты купил его в минус

**Comment by Kit0077** [comment]
> Ты купил его в минус

Конечно, а как по другому. При таком уровне дохода. И если я правильно понимаю скрипт, то он должен совершать покупку комбо даже в минус

**Comment by gg-script** [comment]
как раз таки не должен, в чем смысл покупать комбо в минус

**Comment by Kit0077** [comment]
> как раз таки не должен, в чем смысл покупать комбо в минус

Вот это да! Я почему то думал по другому. Это можно как исправить. @shamhi привет, бро, еще раз выражаю тебе благодарность за скрипт. Подскажи пожалуйста, разве покупка комбо, не является одной из приоритетных задач, хоть и у минус, исходя из логики других проектов, некоторые из нас знают, что за выполнение заданий, на листинге дают больше плюх. Как ты считаешь, стоит ли изменить логику для покупки комбо в минус?

**Comment by gg-script** [comment]
Привет! Там неизвестно, дадут ли даже ачивку за это, а ты уже про плюхи спрашиваешь.

**Comment by Kit0077** [comment]
> Привет! Там неизвестно, дадут ли даже ачивку за это, а ты уже про плюхи спрашиваешь.

Ращрабы говорили, что те кто не пропустил ни одного комбо будут отдельно вознаграждены. Можно предположить, что за кол-во собранных комбо тоже будет бонус, это же некое проявление активности

**Comment by ButCheR-PRO** [comment]
В bot/core/tapper.py на 164 строке прописана такая логика:
`if common_price < bonus and balance > common_price and is_combo_accessible:`
То есть, если затраты на покупку комбо меньше чем бонус комбо (5кк) И ваш баланс больше чекм затраты на покупку комбо И комбо доступно, то начать процесс покупки. 
Но эту логику можно изменить, убрав условие `if common_price < bonus`.
В итоге строчка будет выглядеть так: 
`if balance > common_price and is_combo_accessible:`

**Comment by ButCheR-PRO** [comment]
Но эту дискуссию мы ведём в этой теме: https://github.com/shamhi/HamsterKombatBot/issues/251
