### ISSUE TITLE
Sleep every 20 minutes. Why?

### ISSUE THREAD

**Issue by rezafebran** [shamhi/HamsterKombatBot#312]
![image](https://github.com/shamhi/HamsterKombatBot/assets/73734858/c618ecca-01b9-4018-a33c-a255e66b065e)
Am run on ubuntu vps, why every 20 mnt i got stuck

**Comment by eliafino** [comment]
Sleep 2121 seconds, last line. SLEEP_BY_MIN_ENERGY

**Comment by ButCheR-PRO** [comment]
.env:
`SLEEP_BY_MIN_ENERGY=[1800,2400]`
Delay when reaching minimum energy in seconds                   |
