### ISSUE TITLE
ssl

### ISSUE THREAD

**Issue by KotainFN** [shamhi/HamsterKombatBot#313]
| ERROR    | 30 - Unknown error while getting Access Token: Cannot connect to host api.hamsterkombat.io:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:992)')] | Response text: ...
чо делать

**Comment by KOTBCTAKAHE** [comment]
#143 Почитайте.

**Comment by KotainFN** [comment]
> #143 Почитайте.

не помогло
точнее не могу найти строку которую менять

**Comment by KOTBCTAKAHE** [comment]
> не помогло точнее не могу найти строку которую менять

Вы сертификат установили?
