### ISSUE TITLE
Вписываю в .env все данные, запускаю INSTALL, и мне пишет, что я не указал api id и api hash. Почему такая проблема возникает?

### ISSUE THREAD

**Issue by quizzx** [shamhi/HamsterKombatBot#314]

**Comment by gg-script** [comment]
наверное сначала инсталл, потом редачишь .енв, а потом старт.бат

**Comment by quizzx** [comment]
> наверное сначала инсталл, потом редачишь .енв, а потом старт.бат

я какими только способами не пробовал, все равно просит апи айди и хэш, хотя я их уже указал

**Comment by quizzx** [comment]
все, отмена, у меня получилось
ура
