### ISSUE TITLE
Один и тот же кошелек на несколько акков

### ISSUE THREAD

**Issue by XPacL** [shamhi/HamsterKombatBot#315]
Как вы привязываете кошельки? Один на несколько аккаунтов или к каждому аккаунту отдельный кошелёк? У меня 5 аккаунтов, думаю не будет ли бритья при раздаче, если я привяжу один кошель на все свои акки. Аккаунты реальные моей семьи.

**Comment by bd100b** [comment]
> Как вы привязываете кошельки? Один на несколько аккаунтов или к каждому аккаунту отдельный кошелёк? У меня 5 аккаунтов, думаю не будет ли бритья при раздаче, если я привяжу один кошель на все свои акки. Аккаунты реальные моей семьи.

будут

**Comment by ButCheR-PRO** [comment]
На каждом телеграм аккаунте создаём новый кошелек t.me/@wallet
И привязываем. Потом деньги оттуда можно будет передать на свой основной кошелек.
