### ISSUE TITLE
Глупый вопрос, наверное

### ISSUE THREAD

**Issue by yoyoallf** [shamhi/HamsterKombatBot#317]
Привет, повторюсь, наверное, глупый вопрос, но можно ли заходить в игру с телеграмма, когда бот активен? или бота выбьет?

**Comment by gg-script** [comment]
привет! вряд ли сможешь зайти, нельзя более одной сессии активной

**Comment by mironov1338** [comment]
> Привет, повторюсь, наверное, глупый вопрос, но можно ли заходить в игру с телеграмма, когда бот активен? или бота выбьет?

Я с тел заходил, и прям сейчас в эмуляторе запущен акк

**Comment by ButCheR-PRO** [comment]
Сможешь так заходить несколько дней, но потом даже когда выключишь бота, не сможешь войти в игру с телефона еще около 1 часа, будет писать ошибку Unable to sync. https://github.com/shamhi/HamsterKombatBot/issues/128
