### ISSUE TITLE
Nothing append

### ISSUE THREAD

**Issue by August7337** [shamhi/HamsterKombatBot#318]
Hello did you know why nothing append ???

![image](https://github.com/shamhi/HamsterKombatBot/assets/78742326/d02d9728-93ff-4d6c-89b8-ae4488eca562)

**Comment by Freddywhest** [comment]
Wait or check your internet connection

**Comment by August7337** [comment]
> Wait or check your internet connection
my connection is good and I waited one night, and nothing happens

**Comment by Freddywhest** [comment]
Have you created a session?
