### ISSUE TITLE
Unknown error 'NoneType' object has no attribute 'replace', Cannot connect to host

### ISSUE THREAD

**Issue by Danielz1452** [shamhi/HamsterKombatBot#322]
![2024-06-16_18-28-13](https://github.com/shamhi/HamsterKombatBot/assets/172988800/b2516511-aa8b-498a-bbd3-cb43439cd680)

**Comment by Freddywhest** [comment]
Remove proxy and try if you get the error

**Comment by Danielz1452** [comment]
> Remove proxy and try if you get the error

I ran it with a proxy on the emulator, everything worked.
