### ISSUE TITLE
How can I fix this error?

### ISSUE THREAD

**Issue by RoniherVilchez** [shamhi/HamsterKombatBot#323]
File "HamsterKombatBot\venv\Lib\site-packages\pydantic_settings\main.py", line 84, in __init__
    super().__init__(
  File "HamsterKombatBot\venv\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 3 validation errors for Settings
SLEEP_BY_MIN_ENERGY
  Input should be a valid list [type=list_type, input_value=1800, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/list_type
RANDOM_TAPS_COUNT
  Input should be a valid list [type=list_type, input_value=50, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/list_type
SLEEP_BETWEEN_TAP
  Input should be a valid list [type=list_type, input_value=25, input_type=int]
    For further information visit https://errors.pydantic.dev/2.6/v/list_type

**Comment by Freddywhest** [comment]
Refer to the docs on how to set **SLEEP_BY_MIN_ENERGY**, **RANDOM_TAPS_COUNT** and **SLEEP_BETWEEN_TAP**. I'm sure you are getting this error because you set it wrongly

**Comment by RoniherVilchez** [comment]
> Refer to the docs on how to set **SLEEP_BY_MIN_ENERGY**, **RANDOM_TAPS_COUNT** and **SLEEP_BETWEEN_TAP**. I'm sure you are getting this error because you set it wrongly

But it is a simple numerical value xD how can it be wrong to assign a numerical value within the range shown in the readme file to an ENV. <3

**Comment by ikbarl123** [comment]
you might have whitespace/invisible char on your .env, python are sensitive to whitespace

**Comment by ButCheR-PRO** [comment]
https://github.com/shamhi/HamsterKombatBot/issues/290
