### ISSUE TITLE
PLS HELP MEEEEEEE PLSSSSS

### ISSUE THREAD

**Issue by susubobo** [shamhi/HamsterKombatBot#324]
ctivating virtual environment...
Starting the bot...
Traceback (most recent call last):
  File "F:\HamsterKombatBot\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "F:\HamsterKombatBot\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "F:\HamsterKombatBot\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "F:\HamsterKombatBot\bot\core\tapper.py", line 11, in <module>
    from bot.api.combo import claim_daily_combo, get_combo_cards
  File "F:\HamsterKombatBot\bot\api\combo.py", line 2, in <module>
    from bot.api.http import make_post_request
  File "F:\HamsterKombatBot\bot\api\http.py", line 6, in <module>
    from bot.utils.scripts import escape_html
  File "F:\HamsterKombatBot\bot\utils\scripts.py", line 7, in <module>
    from fake_useragent import UserAgent
ModuleNotFoundError: No module named 'fake_useragent'
Press any key to continue . . .

PLS HELP MEEEEEEE

**Comment by Freddywhest** [comment]
Open **INSTALL.bat** before opening **START.bat**

**Comment by yoyoallf** [comment]
> Open **INSTALL.bat** before opening **START.bat**

or use cmd-> pip install fake_useragent

**Comment by ButCheR-PRO** [comment]
# Installation:
Download and install: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Then synchronize the system time on your computer.
Download the latest version of the bot [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) and unpack it.
Then run INSTALL.bat.

# Obtaining API keys:
1. Go to the website [my.telegram.org](https://my.telegram.org) and log in using your phone number.
2. Select "API development tools" and fill out the form to register a new application.
3. Record the API_ID and API_HASH in the .env file provided after registering your application.


# Setting up the config and launching:
Then you need to configure the .env config according to the documentation in README.md.
After this, you need to create a session through START.bat by selecting option 1. Enter your phone number in international format, Telegram will receive a code that you need to enter in the bot window.
And only then launch the configured clicker through START.bat by selecting point 2.
