### ISSUE TITLE
При запуске ничего не происходит

### ISSUE THREAD

**Issue by ridiculonius** [shamhi/HamsterKombatBot#327]
Вроде все сделал, все токены и API написал в конфиге, и такая фигня:
![image](https://github.com/shamhi/HamsterKombatBot/assets/125882040/6cded6dd-5c9f-487d-80a6-7da2588fa6d8)

Не подскажете, как это решить?

**Comment by Kit0077** [comment]
> Вроде все сделал, все токены и API написал в конфиге, и такая фигня: ![image](https://private-user-images.githubusercontent.com/125882040/340277391-6cded6dd-5c9f-487d-80a6-7da2588fa6d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NDk4MDUsIm5iZiI6MTcxODY0OTUwNSwicGF0aCI6Ii8xMjU4ODIwNDAvMzQwMjc3MzkxLTZjZGVkNmRkLTVjOWYtNDg3ZC04MGE2LTdkYTI1ODhmYTZkOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxN1QxODM4MjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNGFlODNhNmEwNGNlZjY4MTA3OThiNDJhZjQ0ODlmNDZmMjlmNjFjNGZjMTVkN2UwMzgyYjMxNjMzZDFkNWUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.de09b9uiWpAM3hDccEBGVMVQ-YHCBTtPa1qwNWWT-CA)
> 
> Не подскажете, как это решить?

А что не так?

**Comment by shamhi** [comment]
synchronize system time

**Comment by ButCheR-PRO** [comment]
синхронизируйте на компьютере системное время.

**Comment by ridiculonius** [comment]
решено, закрываю
