### ISSUE TITLE
Системе не удается найти указанный путь. Не запускается бот

### ISSUE THREAD

**Issue by F0XYGAMER** [shamhi/HamsterKombatBot#328]
![Снимок экрана 2024-06-18 104013](https://github.com/shamhi/HamsterKombatBot/assets/66869700/bffcf492-6753-450b-9730-d805538af5e4)

**Comment by ButCheR-PRO** [comment]
# Установка:
Скачай и установи: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Затем синхронизируйте на компьютере системное время.
Скачай последнюю версию бота [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) и распакуй.
Потом запусти INSTALL.bat. 

# Получение API ключей:
1. Перейдите на сайт [my.telegram.org](https://my.telegram.org) и войдите в систему, используя свой номер телефона.
2. Выберите "API development tools" и заполните форму для регистрации нового приложения.
3. Запишите API_ID и API_HASH в файле .env, предоставленные после регистрации вашего приложения.


# Настройка конфига и запуск:
Затем нужно настроить конфиг .env согласно документации в README.md.
После этого нужно создать сессию через START.bat выбрав пункт 1.  Вводим свой номер телефона в международном формате, в телеграм придёт код, который нужно ввести в окне бота.
И только потом запускать настроенный кликер через START.bat выбрав пункт 2.

**Comment by F0XYGAMER** [comment]
![Снимок экрана 2024-06-18 173346](https://github.com/shamhi/HamsterKombatBot/assets/66869700/dd2dbe2f-8415-41f5-a509-4e5725d8be95)
Все тоже самое

**Comment by F0XYGAMER** [comment]
Все, починил. Запустил сетапник, нажал 'Modify', потом 'Next' и поставил галочку тут. Все сделал, бот работает
![image](https://github.com/shamhi/HamsterKombatBot/assets/66869700/8072e9ac-edd8-4f47-a0b1-46c1a379866f)

**Comment by F0XYGAMER** [comment]
Все, починил. Запустил сетапник, нажал 'Modify', потом 'Next' и поставил галочку тут. Все сделал, бот работает
![image](https://github.com/shamhi/HamsterKombatBot/assets/66869700/9df0a4d9-7d6f-4f25-99a9-ef929d00262d)
