### ISSUE TITLE
from bot.api.combo import claim_daily_combo, get_combo_cards, SyntaxError: invalid character '·' (U+00B7)

### ISSUE THREAD

**Issue by Milicioner** [shamhi/HamsterKombatBot#330]
(venv) PS C:\hamsterur> python main.py
Traceback (most recent call last):
  File "C:\hamsterur\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "C:\hamsterur\bot\utils\__init__.py", line 2, in <module>
    from . import launcher
  File "C:\hamsterur\bot\utils\launcher.py", line 12, in <module>
    from bot.core.tapper import run_tapper
  File "C:\hamsterur\bot\core\tapper.py", line 11, in <module>
    from bot.api.combo import claim_daily_combo, get_combo_cards
  File "C:\hamsterur\bot\api\combo.py", line 108
    <title>HamsterKombatBot/bot/api/combo.py at main · shamhi/HamsterKombatBot</title>
                                                     ^
SyntaxError: invalid character '·' (U+00B7)

**Comment by ButCheR-PRO** [comment]
# Установка:
Скачай и установи: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Затем синхронизируйте на компьютере системное время.
Скачай последнюю версию бота [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) и распакуй.
Потом запусти INSTALL.bat. 

# Получение API ключей:
1. Перейдите на сайт [my.telegram.org](https://my.telegram.org) и войдите в систему, используя свой номер телефона.
2. Выберите "API development tools" и заполните форму для регистрации нового приложения.
3. Запишите API_ID и API_HASH в файле .env, предоставленные после регистрации вашего приложения.


# Настройка конфига и запуск:
Затем нужно настроить конфиг .env согласно документации в README.md.
После этого нужно создать сессию через START.bat выбрав пункт 1.  Вводим свой номер телефона в международном формате, в телеграм придёт код, который нужно ввести в окне бота.
И только потом запускать настроенный кликер через START.bat выбрав пункт 2.

**Comment by Milicioner** [comment]
Спасибо.
