### ISSUE TITLE
error, i cant fix it

### ISSUE THREAD

**Issue by rezafebran** [shamhi/HamsterKombatBot#334]
![image](https://github.com/shamhi/HamsterKombatBot/assets/73734858/8c299d66-28a1-4cda-8544-775cfb782f09)

**Comment by XPacL** [comment]
Ну так ты возьми и прочитай последнюю строчку, там же всё написано достаточно доходчиво. Это должно натолкнуть тебя на правильную мысль.

**Comment by ButCheR-PRO** [comment]
Синхронизируйте системное время на компьютере
