### ISSUE TITLE
Unknown error: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by joden95** [shamhi/HamsterKombatBot#335]
Can ypu help me fix this erorr?

![Screenshot_2](https://github.com/shamhi/HamsterKombatBot/assets/159123995/0c55989a-219b-4501-83f1-2a5e48187ceb)

**Comment by ButCheR-PRO** [comment]
Dupe
1. https://github.com/shamhi/HamsterKombatBot/issues/322
