### ISSUE TITLE
Unknown error while getting Nuxt Builds

### ISSUE THREAD

**Issue by pasha140395** [shamhi/HamsterKombatBot#336]
Unknown error while getting Nuxt Builds: 403, message='Forbidden', url=URL('https://hamsterkombat.io/_nuxt/builds/meta/32ddd2fc-00f7-4814-bc32-8f160963692c.json') | Response text: \<!DOCTYPE html\>\<html lang="en-US"\><head\><title\>Just a moment...</title\>\<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"\>\<meta http-equiv="X-UA-Compatible" content="IE=Edge"\>\<meta name="robots" content="noindex,nofollow"\>\<...

**Comment by rippomane** [comment]
same
