### ISSUE TITLE
Апгрейд пассивного дохода

### ISSUE THREAD

**Issue by denis-akazuki** [shamhi/HamsterKombatBot#337]
Приветствую всех. Обновил бота из репозитория до последнего коммита, и бот перестал вкачивать пассивный доход. Возможно что-то нужно указать в конфиге для вкачивания? Сейчас только вкачивает баланс, и всё

**Comment by yoyoallf** [comment]
в файле env
AUTO_UPGRADE=

должно стоять True

**Comment by denis-akazuki** [comment]
В коммите 0296a4eda440c42d517c54eccff0b066892edc4f появилась 445-я строчка в файле `tapper.py`. Данная проверка на высоких уровнях прокачки просто блокирует любой апгрейд карточки. У меня сложилась такая ситуация, что апгрейд любой карточки стоит гораздо больше, чем значение в переменной `max_price_limit`.

**Comment by yoyoallf** [comment]
А попробуй добавить в env переменную

MAX_PRICE_LIMIT=
и поставить значение больше чем стоимость карточек

**Comment by Ultraz46** [comment]
Интересно, а по каким критериям вообще идет прокачка пассивного дохода? Просто все подряд покупает или по наилучшему сочетанию профита к цене карточки!?

**Comment by ButCheR-PRO** [comment]
Логику покупки карточек обсуждаем тут:
1. https://github.com/shamhi/HamsterKombatBot/issues/142
Логику покупки комбо, обсуждаем тут:
2. https://github.com/shamhi/HamsterKombatBot/issues/251
Пример файла конфигураций .env:
3. https://github.com/shamhi/HamsterKombatBot/issues/290
