### ISSUE TITLE
2 repeated errors

### ISSUE THREAD

**Issue by rippomane** [shamhi/HamsterKombatBot#338]
Unknown error while getting Nuxt Builds: 403, message='Forbidden', url=URL('https://hamsterkombat.io/_nuxt/builds/meta/32ddd2fc-00f7-4814-bc32-8f160963692c.json') | Response text: \<!DOCTYPE html\>\<html lang="en-US"\><head\><title\>Just a moment...</title\>\<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"\>\<meta http-equiv="X-UA-Compatible" content="IE=Edge"\>\<meta name="robots" content="noindex,nofollow"\>\<...

Unknown error while getting Access Token: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/auth/auth-by-telegram-webapp') | Response text: {"type":"validation","on":"body","found":{"initDataRaw":null,"fingerprint":{"visitorId":"9827281de14d242eaa1c1cb60011b339"}}}..

what do these errors mean?

**Comment by idimo** [comment]
same

**Comment by ShelyGanz** [comment]
2024-06-19 18:08:20 | ERROR    | 30 - Unknown error while getting Access Token: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/auth/auth-by-telegram-webapp') | Response text: Couchbase error! Method=query(q=
      select auth_user.* from auth_user
      where telegramUserId = $telegramUserId
      limit 1
      , options={"adhoc":false,"parameters":{"telegramUserId":412465382}}) Collection=hamster.auth.auth_user Error=InternalS...

**Comment by socloseeee** [comment]
> 2024-06-19 18:08:20 | ERROR    | 30 - Unknown error while getting Access Token: 500, message='Internal Server Error', url=URL('https://api.hamsterkombat.io/auth/auth-by-telegram-webapp') | Response text: Couchbase error! Method=query(q=
> 
>       select auth_user.* from auth_user
> 
>       where telegramUserId = $telegramUserId
> 
>       limit 1
> 
>       , options={"adhoc":false,"parameters":{"telegramUserId":412465382}}) Collection=hamster.auth.auth_user Error=InternalS...

Same error...

**Comment by xshayank** [comment]
I am getting the same error

**Comment by provincialcxz** [comment]
Я тоже получил эту ошибку, возможно разрабы хомяка немного поменяли свое приложение

**Comment by xshayank** [comment]
> Я тоже получил эту ошибку, возможно разрабы хомяка немного поменяли свое приложение

Yes I think you are right
This started to happen right after they updated and added a new card

**Comment by provincialcxz** [comment]
> > Я тоже получил эту ошибку, возможно, разрабы хомяка немного поменяли свое приложение
> 
> Да, я думаю, вы правы. Это начало происходить сразу после того, как они обновили и добавили новую карту.

Я не особо разбираюсь в том как устроены приложения в телеграмме, как можно посмотреть какие запросы отправляются?

**Comment by xshayank** [comment]
> > > Я тоже получил эту ошибку, возможно, разрабы хомяка немного поменяли свое приложение
> 
> > 
> 
> > Да, я думаю, вы правы. Это начало происходить сразу после того, как они обновили и добавили новую карту.
> 
> 
> 
> Я не особо разбираюсь в том как устроены приложения в телеграмме, как можно посмотреть какие запросы отправляются?

If I am correct you have to use a network scanner that scans everything that goes out of your phone
That way you can get the packets that the application is sending

**Comment by MaxZhelt** [comment]
I really hope that this will be fixed...

**Comment by xshayank** [comment]
So here is the packets 
I am sleepy so I am just sending them here
If anyone found the fix let us know!
![image](https://github.com/shamhi/HamsterKombatBot/assets/133507234/577bb1f3-22fc-4638-95db-86ecf32a1022)

![image](https://github.com/shamhi/HamsterKombatBot/assets/133507234/1ea4654a-52fd-4f67-b36d-59f2858989c8)


![image](https://github.com/shamhi/HamsterKombatBot/assets/133507234/3acaa543-d5dd-425c-9543-405f55534595)

**Comment by GravelFire** [comment]
**`Ошибки больше не наблюдается`**

**Comment by xshayank** [comment]
Yea the hamster servers are the issue

**Comment by ButCheR-PRO** [comment]
The errors were on the server side. You just need to wait and the errors will correct themselves.
