### ISSUE TITLE
Обновление / Покупка нужных карт

### ISSUE THREAD

**Issue by Malg1nov** [shamhi/HamsterKombatBot#341]
Уважаемые, подскажите пожалуйста пошагово , как обновить бота ? 

прописываю данные команды, выдает ошибку.
[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

и какой файл нужно отредактировать, чтоб бот прокачивал только нужные мне карты и после таймера еще раз их покупал ,а не все подряд.

**Comment by ButCheR-PRO** [comment]
# Установка:
Скачай и установи: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Затем синхронизируйте на компьютере системное время.
Скачай последнюю версию бота [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) и распакуй.
Потом запусти INSTALL.bat. 

# Получение API ключей:
1. Перейдите на сайт [my.telegram.org](https://my.telegram.org) и войдите в систему, используя свой номер телефона.
2. Выберите "API development tools" и заполните форму для регистрации нового приложения.
3. Запишите API_ID и API_HASH в файле .env, предоставленные после регистрации вашего приложения.


# Настройка конфига и запуск:
Затем нужно настроить конфиг .env согласно документации в README.md.
После этого нужно создать сессию через START.bat выбрав пункт 1.  Вводим свой номер телефона в международном формате, в телеграм придёт код, который нужно ввести в окне бота.
И только потом запускать настроенный кликер через START.bat выбрав пункт 2.

**Comment by Malg1nov** [comment]
> # Установка:
> Скачай и установи: [Python 3.10.9](https://www.python.org/downloads/release/python-3109/) Затем синхронизируйте на компьютере системное время. Скачай последнюю версию бота [HamsterKombatBot](https://github.com/shamhi/HamsterKombatBot) и распакуй. Потом запусти INSTALL.bat.
> 
> # Получение API ключей:
> 1. Перейдите на сайт [my.telegram.org](https://my.telegram.org) и войдите в систему, используя свой номер телефона.
> 2. Выберите "API development tools" и заполните форму для регистрации нового приложения.
> 3. Запишите API_ID и API_HASH в файле .env, предоставленные после регистрации вашего приложения.
> 
> # Настройка конфига и запуск:
> Затем нужно настроить конфиг .env согласно документации в README.md. После этого нужно создать сессию через START.bat выбрав пункт 1. Вводим свой номер телефона в международном формате, в телеграм придёт код, который нужно ввести в окне бота. И только потом запускать настроенный кликер через START.bat выбрав пункт 2.


но у меня же уже он установлен, просит обновить версию с  new release of pip available: 22.2.1 -> 24.0
я скачивал архив снова , запускается не обновленный
