### ISSUE TITLE
[Предложение] Сбор дейли Азбуки Морзе

### ISSUE THREAD

**Issue by ShelyGanz** [shamhi/HamsterKombatBot#344]
Возможно ли добавить сбор Daily Morze game 

Код: FARM
F • • — •
A • — 
R • — •
M — —

3 раза тыкаем на «прибыль за тап» в левом верхнем углу
Переходим на красного хомяка, далее вводим код.

Точка - короткий тап
Тире - длинный тап.

**Comment by ImMagnat** [comment]
> Возможно ли добавить сборку игры Daily Morze
> 
> Код: FARM F • • — • A • — R • — • M — —
> 
> 3 раза тыкаем на «прибыль за краном» в нижнем верхнем углу, переходим на красный хомяка, далее вводим код.
> 
> Точка – короткий кран. Тире – длинный кран.

Морзе и так собирается, + механика сейчас в игре другая (сейчас 3 раза тапать нет необходимости)

**Comment by yoyoallf** [comment]
Это давно уже есть))
