### ISSUE TITLE
Hello  I have  API_ID and API_HASH  ，report errors

### ISSUE THREAD

**Issue by xpgu66** [shamhi/HamsterKombatBot#372]
When I started   INSTALL.bat    It will give an error message. 

 Copying .env-example to .env...
已复制         1 个文件。
Please edit the .env file to add your API_ID and API_HASH.

My.env-example is related to.env
API_ID and API_HASH.

May I ask you how to solve this problem

![image](https://github.com/shamhi/HamsterKombatBot/assets/111165445/83d1631f-09a6-4c61-b219-c6b1b5f5ca99)

**Comment by xpgu66** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/111165445/90af82bb-5320-4307-a21e-fa2638e31260)
the is   .env-example

**Comment by vegasline** [comment]
1. INSTALL.bat
2. .env edit
3. START.bat
ok?

**Comment by xpgu66** [comment]
谢谢你的解答，我按照您的要求，首先启动了 INSTALL.bat 
然后在去 .env edit  添加ID

**Comment by xpgu66** [comment]
Thank you for the tutorial.
I started INSTALL.bat according to your requirement
Then I updated the.env edit and saved it
After starting START.bat
But it still reported an error,
Looks like a grammatical error.
Thanks again for your answer

![Uploading image.png…]()
1

**Comment by xpgu66** [comment]
![Uploading image.png…]()

**Comment by xpgu66** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/111165445/d7f56d3f-c75a-478a-bdfa-4b5d94bcee81)   
![image](https://github.com/shamhi/HamsterKombatBot/assets/111165445/6946fbe8-b084-46fb-a6c8-552b5b8cbf13)
![image](https://github.com/shamhi/HamsterKombatBot/assets/111165445/d9e3365b-e480-4cef-abc9-13f838aa8793)
![image](https://github.com/shamhi/HamsterKombatBot/assets/111165445/5aa8c658-0edd-4493-b306-1ea28051891b)

**Comment by xpgu66** [comment]
Starting the bot...
Traceback (most recent call last):
  File "E:\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "E:\HamsterKombatBot-main\bot\utils\__init__.py", line 8, in <module>
    if not os.path.exists(path='sessions'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments
请按任意键继续. . .

**Comment by xpgu66** [comment]
Error message

Starting the bot...
Traceback (most recent call last):
  File "E:\HamsterKombatBot-main\main.py", line 4, in <module>
    from bot.utils.launcher import process
  File "E:\HamsterKombatBot-main\bot\utils\__init__.py", line 8, in <module>
    if not os.path.exists(path='sessions'):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: nt._path_exists() takes no keyword arguments
请按任意键继续. . .

**Comment by xpgu66** [comment]
After I referenced someone else's configuration file, I did not report errors, thank you again

https://github.com/shamhi/HamsterKombatBot/issues/290#issuecomment-2162692634

**Comment by ButCheR-PRO** [comment]
1. https://github.com/shamhi/HamsterKombatBot/issues/290
