### ISSUE TITLE
flood wait

### ISSUE THREAD

**Issue by rezafebran** [shamhi/HamsterKombatBot#374]
![image](https://github.com/shamhi/HamsterKombatBot/assets/73734858/31712916-96c6-4146-bd39-51eb6fe67586)
what is this? i cant run my bots

**Comment by 4D4N-P** [comment]
Before starting the script, maybe u need run telegram bot: @hamster_kombat_bot

**Comment by ButCheR-PRO** [comment]
1. https://github.com/shamhi/HamsterKombatBot/issues/77
