### ISSUE TITLE
Daily combo is not applicable, you can only purchase 1 of 3 cards

### ISSUE THREAD

**Issue by sonnguyenHT** [shamhi/HamsterKombatBot#379]
![image](https://github.com/shamhi/HamsterKombatBot/assets/73238807/32e4889f-4171-4f4b-b4ed-f6e27e100bea)
Did any environment variable I need to make this action happend

**Comment by sonnguyenHT** [comment]
And can I ask for how long after I stop the session on the docker-compose, I can access it on telegram application on phone, It now showing "Request error Unable to sync"

https://github.com/shamhi/HamsterKombatBot/assets/73238807/7b2761e9-05f5-4afc-97dd-9354c7bb6338

**Comment by gg-script** [comment]
> And can I ask for how long after I stop the session on the docker-compose, I can access it on telegram application on phone, It now showing "Request error Unable to sync"
> 
>  hamter_kombat.mp4

Hi! It is not known for certain, it seems like 30-60 minutes later

**Comment by sonnguyenHT** [comment]
Happy to know that @gg-script, it seem working like you say

**Comment by ButCheR-PRO** [comment]
1. https://github.com/shamhi/HamsterKombatBot/issues/128
