### ISSUE TITLE
ModuleNotFoundError: No module named 'loguru'

### ISSUE THREAD

**Issue by linquit** [shamhi/HamsterKombatBot#380]
![image](https://github.com/shamhi/HamsterKombatBot/assets/66126661/1b2de820-648b-42c7-98c1-a1e5b6aaea4a)
чо делать? пробовал импортировать этот модуль всё равно ошибку выдает

**Comment by K1ckMan** [comment]
rename your .env-example file to .env

**Comment by yoyoallf** [comment]
> I've already fixed this, I didn't have enough "" in the file, now I can't log in from my phone ![image](https://private-user-images.githubusercontent.com/66126661/343156717-e762bb01-4382-4056-96d8-05a85c2bb3d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDY3OTksIm5iZiI6MTcxOTQwNjQ5OSwicGF0aCI6Ii82NjEyNjY2MS8zNDMxNTY3MTctZTc2MmJiMDEtNDM4Mi00MDU2LTk2ZDgtMDVhODVjMmJiM2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDEyNTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmNDk0ZDRhNjViZGQwNTNmNjJjYzllNjI3MDViMWVlNTg4ZjY2ODg1NTM0ZTRhNzU3NjRjODMyNjBlNTJhMGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ha0NZ0SSObq90V_QVbI2ru_9VYJ7XU-5fe9vHb_hNOs)

When the bot is running, you won't be able to log in. When you disable the bot, you will be able to log in via your phone in about an hour

**Comment by ButCheR-PRO** [comment]
1. https://github.com/shamhi/HamsterKombatBot/issues/150
2. https://github.com/shamhi/HamsterKombatBot/issues/128
