### ISSUE TITLE
Cant launch bot

### ISSUE THREAD

**Issue by laggedv1** [shamhi/HamsterKombatBot#389]
![a8e5b455f545ca0ac6172f6bb23db9b4](https://github.com/shamhi/HamsterKombatBot/assets/174215942/14d2efe0-f184-4f99-9002-4f7d6c6b33d2)

Can someone help ? HAVE  USE_Proxy_FROM_FILE = false

**Comment by TemoSulava** [comment]
you have inputed wrong value in env files

**Comment by laggedv1** [comment]
> you have inputed wrong value in env files

![ac381243023aecd1ee0e15b2d04178ae](https://github.com/shamhi/HamsterKombatBot/assets/174215942/42dc4a06-241e-437d-9bc6-09d541b078e6)
api hash & id is ok , where did i miss something?
