### ISSUE TITLE
I use the script to run the program for 3 days, today I want to see how in telegram, found that it can not go, said that the data can not be synchronized, how to solve this

### ISSUE THREAD

**Issue by hardwin1014** [shamhi/HamsterKombatBot#392]

**Comment by hardwin1014** [comment]
![Uploading IMG_1659.png…]()

**Comment by hardwin1014** [comment]
![Uploading IMG_1659.png…]()

**Comment by wannaD1E** [comment]
Не один твой скриншот не видно, но если тебе пишет ошибку синхронизации, то выключи бота, возьми кружку кофе, скачай фильм и посмотри его. Через 1 или 2 часа попробуй зайти снова.
Бот открывает сессию на 1 час, пока она не закончится с мобильных устройств зайти не получится.

**Comment by hardwin1014** [comment]
> Не один твой скриншот не видно, но если тебе пишет ошибку синхронизации, то выключи бота, возьми кружку кофе, скачай фильм и посмотри его. Через 1 или 2 часа попробуй зайти снова. Бот открывает сессию на 1 час, пока она не закончится с мобильных устройств зайти не получится.

You're right. Thank you
