### ISSUE TITLE
После ввода названия сессии ничего не происходит. Невозможно авторизоваться в аккаунт Telegram.

### ISSUE THREAD

**Issue by Ozzy4t** [shamhi/HamsterKombatBot#394]
После ввода названия сессии ничего не происходит. Невозможно авторизоваться в аккаунт Telegram. Что мне делать? Это не проблема в данном скрипте, у меня так везде с подобными скриптами, хотя ранее всё работало отлично, я менял уже на другой аккаунт api, но ничего не изменилось.
![image](https://github.com/shamhi/HamsterKombatBot/assets/172856987/6b40f3e4-1fd3-44dd-849b-072cbfb616e1)

**Comment by hardim26** [comment]
В файле .env прописал все?

**Comment by Ozzy4t** [comment]
> В файле .env прописал все?

Да, если бы не прописал, оно выдало бы ошибку.

**Comment by hardim26** [comment]
А питон какой?

**Comment by hardim26** [comment]
И еще, какое название папки. Я в коде еще не успел все изучить, по похоже где то используется относительный путь с названием родной папки как в архиве

**Comment by Ozzy4t** [comment]
> И еще, какое название папки. Я в коде еще не успел все изучить, по похоже где то используется относительный путь с названием родной папки как в архиве

питона разные  версии поставил 3.9 3.10 3.11 3.12., название папки "HamsterKombatBot-main" как в архиве

**Comment by Ozzy4t** [comment]
> попробуй прожать синхронизацию времени в винде мне помогло ![изображение](https://private-user-images.githubusercontent.com/174643742/345561823-0e53cbb1-c7eb-4ad4-aef6-f008a137d565.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNDY3NDUsIm5iZiI6MTcyMDA0NjQ0NSwicGF0aCI6Ii8xNzQ2NDM3NDIvMzQ1NTYxODIzLTBlNTNjYmIxLWM3ZWItNGFkNC1hZWY2LWYwMDhhMTM3ZDU2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwM1QyMjQwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDY0ODljNWY1MjdhODMyN2E2ZDY0NWQ0YTJhMTdiZmZlODNlNTAwYzc2YTAyOWZjNTkxOWUxMDMzNmUyZjg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HfzZ7mvX4E61uG396CaxpXxovbZ4giedZnJRjJcZDJg)

просто лучший, спасибо!!!
