### ISSUE TITLE
Запуск бота

### ISSUE THREAD

**Issue by dezdemxn** [shamhi/HamsterKombatBot#4]
Когда скачиваешь бота, все делаешь по гайду, бот запускается на какое то время, после уже выдает ошибку Unknown error when Tapping: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/clicker/tap') . После запускаешь снова бота, и он уже пишет это
![image](https://github.com/shamhi/HamsterKombatBot/assets/165968275/8ccb99bd-17da-4117-9294-e6169c43a038)
Фикситься это конечно если заново писать команды по гайду, но можно ли как то без этого?

**Comment by liluglymane666** [comment]
мне помогло синхронизация времени в винде

**Comment by avtosubaru25** [comment]
дополнение у кого выскакивает куча ошибок и прокси гуано 
вот небольшой фикс  а то видимо сервак думает что его дудосят ))))
                try:
                    if time() - access_token_created_time >= 3600:
                        await asyncio.sleep(randint(2, 10))
                        tg_web_data = await self.get_tg_web_data(proxy=proxy)
                        access_token = await self.login(http_client=http_client, tg_web_data=tg_web_data)

**Comment by avtosubaru25** [comment]
Алекс подскажите  где вы прокси берете , у меня заводиться только с https  естественно фри прокси   . Нашол проект он собирает бесплатные 30т.т. проксей но другой проект по чеку проксей отказываеться работать и поэтому уже задумалься купить может проше ? и сокс туда не идут верно ?

**Comment by avtosubaru25** [comment]
А вообще вы красавачик такие злостные проекты пилить за короткое время

**Comment by shamhi** [comment]
> Алекс подскажите где вы прокси берете

proxy6.net
30р на месяц годно

**Comment by zerg211** [comment]
просто монстр

**Comment by ButCheR-PRO** [comment]
Решения проблем:
1) Зайдите в этот аккаунт телеграмм с любого устройства;
2) Закройте все сессии с заголовком Pyrogram
3) Пересоздайте сессию внутри вашего бота (вместо токена используйте номер телефона в международном формате)
4) Отключите прокси или используйте SOCKS5 вместо HTTP
5) Синхронизируйте системное время на компьютере
