### ISSUE TITLE
Upgrading bug

### ISSUE THREAD

**Issue by qu1zzlyzz** [shamhi/HamsterKombatBot#41]
![image](https://github.com/shamhi/HamsterKombatBot/assets/154055867/47cfb68c-bb61-4a4e-a8b2-f2afe4336dba)
Бот не может ничего купить.

**Comment by TkikT1** [comment]
> ![image](https://private-user-images.githubusercontent.com/154055867/332760925-47cfb68c-bb61-4a4e-a8b2-f2afe4336dba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MDk3MjgsIm5iZiI6MTcxNjQwOTQyOCwicGF0aCI6Ii8xNTQwNTU4NjcvMzMyNzYwOTI1LTQ3Y2ZiNjhjLWJiNjEtNGE0ZS1hOGIyLWYyYWZlNDMzNmRiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQyMDIzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNGM0ODgwMjMwYjExYTg3YzU0MzY3M2JhMDU2NDY3NzJmNDRlODAyMjRmMTYzNzViYzgzYmE2NmI2M2QwNGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xaBricgxBO8SWfQPesyL5O_fXxbJofXQLmJ-Fq5X2aw) Бот не может ничего купить.

помогло?
