### ISSUE TITLE
Bad code

### ISSUE THREAD

**Issue by sheldygg** [shamhi/HamsterKombatBot#42]
You are wrong user response.raise_for_status in your functions.
Hamster API can return information with 4xx code.
For example in your function `buy_upgrade` api can return `SUBSCRIPTION_TELEGRAM_CHANNEL_IS_REQUIRED` or `INSUFFICIENT_FUNDS` but you just raise exceptions.

And error with `get_profile_data` api can return profile data in response["found"]["clickerUser"]

Fix this erros please.

**Comment by shamhi** [comment]
update repo
