### ISSUE TITLE
Запрос на получение API ключа и хеша для Telegram бота

### ISSUE THREAD

**Issue by binahmad362** [shamhi/HamsterKombatBot#43]
Здравствуйте,

Я нашел вашего бота в репозитории Python для Telegram, и мне очень интересно его использовать. Однако, я столкнулся с проблемой: в коде есть поля для API ключа и хеша, и я не уверен, как их получить. Вы могли бы подсказать, как мне это сделать? Это будет очень полезно для меня.

Спасибо за вашу помощь!

**Comment by Crazed981** [comment]
https://my.telegram.org/auth?to=apps
