### ISSUE TITLE
363 - Unknown error: cannot access local variable 'available_energy' where it is not associated with value

### ISSUE THREAD

**Issue by wxsqseen** [shamhi/HamsterKombatBot#46]
![изображение_2024-05-22_234253766](https://github.com/shamhi/HamsterKombatBot/assets/170565347/ce59ff9b-1538-47b4-abd7-be880ba8ee30)

**Comment by tancyit3** [comment]
на счет первой ошибки - https://core.telegram.org/api/errors#420-flood
попробуй подождать сколько секунд там пишет
