### ISSUE TITLE
Unknown error: cannot access local variable 'available_energy' where it is not associated with a value

### ISSUE THREAD

**Issue by atess2** [shamhi/HamsterKombatBot#47]
![Без имени](https://github.com/shamhi/HamsterKombatBot/assets/110168140/87aca52e-f936-4b3b-a690-ca68159fb680)
что делать.

**Comment by atess2** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/110168140/f5b47f79-f0e6-4c18-a277-29ce4b458730)

**Comment by ButCheR-PRO** [comment]
Советую установить [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Затем синхронизировать на компьютере системное время.
Потом запустить INSTALL.bat. 
Затем настроить конфиг .env согласно документации в README.md
После этого создать сессию через START.bat выбрав пункт 1. 
И только потом запускать настроенный кликер через START.bat выбрав пункт 2.
