### ISSUE TITLE
 Unknown error while buying Upgrade: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/clicker/buy-upgrade')

### ISSUE THREAD

**Issue by atess2** [shamhi/HamsterKombatBot#48]
![image](https://github.com/shamhi/HamsterKombatBot/assets/110168140/1ac9adfe-4a9d-4226-9728-9099612f6c75)
 Unknown error while buying Upgrade: 422, message='Unprocessable Entity', url=URL('https://api.hamsterkombat.io/clicker/buy-upgrade')
 что за ошибка?

**Comment by ButCheR-PRO** [comment]
Дубликат https://github.com/shamhi/HamsterKombatBot/issues/4
