### ISSUE TITLE
205 - Unknown error while tapping: 422 Unprocessable Entity. farm all taps in one time 

### ISSUE THREAD

**Issue by yacody** [shamhi/HamsterKombatBot#53]
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/70fb3d34-5709-45b2-b48c-59634fd47f8f)

**Comment by yacody** [comment]
1 normal tap, then 5 errors and all other taps in 1 sec

**Comment by shamhi** [comment]
their servers are full
