### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by darhanger** [shamhi/HamsterKombatBot#54]
![image](https://github.com/shamhi/HamsterKombatBot/assets/22445395/fe7b5799-8a23-4421-888e-57a286914c96)

Уже час где-то лутаю эту ошибку.

**Comment by izhbec** [comment]
сэйм

**Comment by darhanger** [comment]
Продуплилось на 2 минуты и посыпалось это https://github.com/shamhi/HamsterKombatBot/issues/49

**Comment by izhbec** [comment]
да-да, тож самое

**Comment by shamhi** [comment]
ждите обнову через 10 мин, пока тестирую в ветке `dev`

**Comment by shamhi** [comment]
обнови, попробуй еще раз

**Comment by darhanger** [comment]
> обнови, попробуй еще раз
> 
> со вчерашнего дня что-то странно начало у всех выдавать флуд вейты

Я думаю можно закрывать. Лично у меня все пошло нормально уже. Думаю можешь пушить апдейт
![image](https://github.com/shamhi/HamsterKombatBot/assets/22445395/7eee49e6-70c3-4aca-8ab7-5ad5bcf79145)

**Comment by darhanger** [comment]
Хотя стоп. Переписал батник с --action 2, запустил и опять посыпалось 
![image](https://github.com/shamhi/HamsterKombatBot/assets/22445395/aa8747a4-a820-44d4-a56a-a6fc601f0197)

**Comment by avtosubaru25** [comment]
да и странно только на хамстере флуд сыпет остальные боты нормально

**Comment by shamhi** [comment]
у меня все работает

**Comment by Qssa** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/38109920/d86fdc9b-128f-40d6-af58-6ce1b601c400)
Тоже самое

**Comment by VasNick8064** [comment]
> ![image](https://private-user-images.githubusercontent.com/38109920/333128522-d86fdc9b-128f-40d6-af58-6ce1b601c400.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTcyMTAsIm5iZiI6MTcxNjQ1NjkxMCwicGF0aCI6Ii8zODEwOTkyMC8zMzMxMjg1MjItZDg2ZmRjOWItMTI4Zi00MGQ2LWFmNTgtNmNlMWI2MDFjNDAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA5MzUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYTBjMDg3ZmE5ZDBmMGYwZTg5MDE3MmZkNGNhMjY0ODUwMDQ4ZmE4NjIyYmNkZDhkNTAyZTY0ZjZhN2M3MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vD64cooKCNWAj83zK-sfVvPp78G_mlzqQ9C9SXhVdBo) Тоже самое

`git reset --hard`

`git pull`

**Comment by VasNick8064** [comment]
Все работает, можно закрывать.
![image](https://github.com/shamhi/HamsterKombatBot/assets/162046111/6a40df62-1563-4137-8949-7153c2c3ae66)

**Comment by yacody** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/c5501792-18b3-44b2-a067-3a62cacbea58)
не работает

**Comment by darhanger** [comment]
> ![image](https://private-user-images.githubusercontent.com/146646846/333132475-c5501792-18b3-44b2-a067-3a62cacbea58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTc4NjcsIm5iZiI6MTcxNjQ1NzU2NywicGF0aCI6Ii8xNDY2NDY4NDYvMzMzMTMyNDc1LWM1NTAxNzkyLTE4YjMtNDRiMi1hMDY3LTNhNjJjYWNiZWE1OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QwOTQ2MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kODFmZDIyOWQ1Y2NkYmI0MTlkMTM3NTQxZDU3NjNiZTQ1YTUzOTg5ODNhNDliODNhMTYxZjI4MTY2NGE4YjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.zNhIVhHM3kyM1nfecb5ljow1GnaN9xf83qFbSPw36z0) не работает

Такая же херня

**Comment by shamhi** [comment]
у вас запущены другие боты?

**Comment by VasNick8064** [comment]
> у вас запущены другие боты?

Да,  снова посыпались ошибки

**Comment by yacody** [comment]
> у вас запущены другие боты?
> 
> если да, то остановите их пока я не обновлю, везде нужно пересмотреть логику авторизации
> 
> они удлиняют флудвейт

мемефи стоит ещё, попробую без него

**Comment by liluglymane666** [comment]
![444](https://github.com/shamhi/HamsterKombatBot/assets/57453873/cece7b69-9c47-4791-9f05-fae4e0711327)
у меня вообще все ошибки в перемешку

**Comment by darhanger** [comment]
> у вас запущены другие боты?
> 
> если да, то остановите их пока я не обновлю, везде нужно пересмотреть логику авторизации
> 
> они удлиняют флудвейт

Питон у меня версии 3.11, допом крутиться еще https://github.com/NightStrang6r/FunPayVertex

**Comment by avtosubaru25** [comment]
да я тоже непойму штук пять разных потов на на одном акке крутиться а только хамстер ругаеться  может на него запросов много сыпеться и телега его немного ограничила по групам смотрел много кто начал писать для него ботов

> у вас запущены другие боты?
> 
> если да, то остановите их пока я не обновлю, везде нужно пересмотреть логику авторизации
> 
> они удлиняют флудвейт

**Comment by darhanger** [comment]
> да я тоже непойму штук пять разных потов на на одном акке крутиться а только хамстер ругаеться может на него запросов много сыпеться и телега его немного ограничила по групам смотрел много кто начал писать для него ботов
> 
> > у вас запущены другие боты?
> > если да, то остановите их пока я не обновлю, везде нужно пересмотреть логику авторизации
> > они удлиняют флудвейт

Это все да, но обычный заход через прилогу ведь работает? И так же быстро грузиться. Если была бы проблема со стороны прилоги, то бы и она скорее всего глючила.

**Comment by Qssa** [comment]
У меня прилога уже пару дней глючит иногда, ошибку кидает

**Comment by avtosubaru25** [comment]
какую

**Comment by darhanger** [comment]
> ну телега то видит что ты по апи тыкаешь а не с тела )))))) , короче смысл что такая ебля именно с хамстером

Ну тык по кнопке всеравно делает запрос к апи, не просто же так ты тыкаешь и у тебя работает)

**Comment by yacody** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/427007fd-1691-48f6-9317-84dccc0b2bfe)
вот такой прикол теперь ещё, если сначала зеленый свет дает))

**Comment by avtosubaru25** [comment]
> > ну телега то видит что ты по апи тыкаешь а не с тела )))))) , короче смысл что такая ебля именно с хамстером
> 
> Ну тык по кнопке всеравно делает запрос к апи, не просто же так ты тыкаешь и у тебя работает)

а ты случаем не пробовал запустить бота с др апи хеш?

**Comment by QuantumLeap-us** [comment]
Why not try rm -rf __pycache__/ after the update?

**Comment by darhanger** [comment]
> Why not try rm -rf **pycache**/ after the update?

I think need modify start.bat to clear cache after every launch.

**Comment by QuantumLeap-us** [comment]
Not everyone uses windows.

**Comment by avtosubaru25** [comment]
> > Why not try rm -rf **pycache**/ after the update?
> 
> I think need modify start.bat to clear cache after every launch.
> 
> ```
> @echo off
> 
> echo Clearing __pycache__ directories...
> for /r %%i in (__pycache__) do if exist "%%i" rd /s /q "%%i"
> 
> echo Activating virtual environment...
> call venv\Scripts\activate
> 
> echo Starting the bot...
> python main.py
> 
> pause
> ```
и чо помогло тебе ?

**Comment by yacody** [comment]
c 3 раза запустилось, но за 1 клик  выфармливает все коины. Также было и вчера. 
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/eb8bee39-d606-4c76-aa93-78b56317a448)
сомнительно, думаю могут бан выдать за такое(конфиг настроен иначе)

**Comment by darhanger** [comment]
> > > Why not try rm -rf **pycache**/ after the update?
> > 
> > 
> > I think need modify start.bat to clear cache after every launch.
> > ```
> > @echo off
> > 
> > echo Clearing __pycache__ directories...
> > for /r %%i in (__pycache__) do if exist "%%i" rd /s /q "%%i"
> > 
> > echo Activating virtual environment...
> > call venv\Scripts\activate
> > 
> > echo Starting the bot...
> > python main.py
> > 
> > pause
> > ```
> 
> и чо помогло тебе ?

Угу, заработал после того как кэш вычистил. На счет того кода который выше не уверен, я не силен в таких делах. Но вроде как должен работать.

**Comment by avtosubaru25** [comment]
> > > > Why not try rm -rf **pycache**/ after the update?
> > > 
> > > 
> > > I think need modify start.bat to clear cache after every launch.
> > > ```
> > > @echo off
> > > 
> > > echo Clearing __pycache__ directories...
> > > for /r %%i in (__pycache__) do if exist "%%i" rd /s /q "%%i"
> > > 
> > > echo Activating virtual environment...
> > > call venv\Scripts\activate
> > > 
> > > echo Starting the bot...
> > > python main.py
> > > 
> > > pause
> > > ```
> > 
> > 
> > и чо помогло тебе ?
> 
> Угу, заработал после того как кэш вычистил. На счет того кода который выше не уверен, я не силен в таких делах. Но вроде как должен работать.

в инете нашол или ГПТ ?

**Comment by darhanger** [comment]
Ручками написал.

**Comment by darhanger** [comment]
> > Why not try rm -rf **pycache**/ after the update?
> 
> I think need modify start.bat to clear cache after every launch.
> 
> ```
> @echo off
> 
> echo Clearing __pycache__ directories...
> for /r %%i in (__pycache__) do if exist "%%i" rd /s /q "%%i"
> 
> echo Activating virtual environment...
> call venv\Scripts\activate
> 
> echo Starting the bot...
> python main.py
> 
> pause
> ```

@shamhi что скажешь за код? Стоит очистку добавлять или?

**Comment by avtosubaru25** [comment]
> Ручками написал.

у меня неа непомогло  
 2024-05-23 15:34:44 | ERROR    | 69 - Lesnik | Unknown error during Authorization: Telegram says: [420 FLOOD_WAIT_X] - A wait of 443 seconds is required (caused by "contacts.ResolveUsername")
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002A7E805B6D0>
Unclosed client session

**Comment by avtosubaru25** [comment]
> Ручками написал.

смотри
https://github-com.translate.goog/aahnik/tgcf/issues/30?_x_tr_sl=auto&_x_tr_tl=ru&_x_tr_hl=ru

**Comment by VasNick8064** [comment]
```
WARNING  | 54 - tesssst | FloodWait Telegram says: [420 FLOOD_WAIT_X] - A wait of 231 seconds is required (caused by "contacts.ResolveUsername")
 | INFO     | 55 - tesssst | Sleep 231s
```

**Comment by shamhi** [comment]
> > > Why not try rm -rf **pycache**/ after the update?
> > 
> > 
> > I think need modify start.bat to clear cache after every launch.
> > ```
> > @echo off
> > 
> > echo Clearing __pycache__ directories...
> > for /r %%i in (__pycache__) do if exist "%%i" rd /s /q "%%i"
> > 
> > echo Activating virtual environment...
> > call venv\Scripts\activate
> > 
> > echo Starting the bot...
> > python main.py
> > 
> > pause
> > ```
> 
> @shamhi что скажешь за код? Стоит очистку добавлять или?

можно вообще не заморачиваться на этот счет и запускать скрипт вот так: `python main.py -a 2 -B`

**Comment by izhbec** [comment]
@shamhi мб сделаешь где нибудь список доступных ботов вообще?
