### ISSUE TITLE
202 - Unknown error while buying Upgrade: 400 Bad Request. пытается улучшить когда нет монеток

### ISSUE THREAD

**Issue by xKumorio** [shamhi/HamsterKombatBot#57]
![image](https://github.com/shamhi/HamsterKombatBot/assets/78680226/f80a8a74-68f7-4c92-b8e3-ee3620c8e221)

пытается улучшить когда нет монеток

**Comment by darhanger** [comment]
> ![image](https://private-user-images.githubusercontent.com/78680226/333138420-f80a8a74-68f7-4c92-b8e3-ee3620c8e221.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0NTg5MzksIm5iZiI6MTcxNjQ1ODYzOSwicGF0aCI6Ii83ODY4MDIyNi8zMzMxMzg0MjAtZjgwYThhNzQtNjhmNy00YzkyLWI4ZTMtZWUzNjIwYzhlMjIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDEwMDM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NjEzYjRhMWEyYTUyMTZhYWRkMTQ2YmI5MWY1MGE5NTA3OWNhMzljZDBiMjQ5MjJhN2I0NDkxYTM4YjA0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.taeN22jSpLRgEeharEE9vmW2ZUzwRq8E6IaoEZxogaQ)
> 
> пытается улучшить когда нет монеток

У меня сначала тоже это было, а потом спустя минуты две прилетело это https://github.com/shamhi/HamsterKombatBot/issues/54
