### ISSUE TITLE
Проблема при запуске 

### ISSUE THREAD

**Issue by azariallev** [shamhi/HamsterKombatBot#6]
Добрый день, возникают такие ошибки. Версия python последняя, при тех же настройках PocketFI от вас идеально работает. Такая проблема возникает во всех остальных скриптах ((
помогите разобраться

![Снимок экрана 2024-04-16 190352](https://github.com/shamhi/HamsterKombatBot/assets/166390485/9b4355e3-e0f3-4efd-bf79-fda6b64d01d8)

**Comment by avtosubaru25** [comment]
у вас скорее всего глобал пит пайтон а не с венма , сделайте как в инструкции
