### ISSUE TITLE
выдает ошибку при старте

### ISSUE THREAD

**Issue by sh1guchi** [shamhi/HamsterKombatBot#60]
![Снимок экрана 2024-05-23 164903](https://github.com/shamhi/HamsterKombatBot/assets/170630655/3e1506d8-b277-4232-a318-990439f08bc0)
здравствуйте, при попытке запуска выдает такую ошибку, подскажите что делать

**Comment by ilyaking** [comment]
README читай
делай по инструкции

**Comment by sh1guchi** [comment]
> README читай делай по инструкции

илья ты сам то помочь не смог, давай мне кто нибудь другой поможет

**Comment by ilyaking** [comment]
я и не пытался помочь) мне лень было
