### ISSUE TITLE
патч не помог

### ISSUE THREAD

**Issue by yacody** [shamhi/HamsterKombatBot#62]
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/81863b04-6782-437c-a9ca-bfea6cbf5313)

**Comment by Qssa** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/38109920/9c8d95a7-66fe-450e-b895-6b987f64100f)
Плюсую
Не выходит

**Comment by PSHacks** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/5302606/b8342136-33c4-49c2-ac7b-b1bf90dd5a26)
+1 :(

**Comment by xKumorio** [comment]
+

**Comment by AlexKrutoy** [comment]
![изображение](https://github.com/shamhi/HamsterKombatBot/assets/65369825/822fc434-77bd-4e90-9c33-1cc54f1e13c7)
+

**Comment by shamhi** [comment]
я ничего не могу поделать с этим, подождите пару часов, может отпадет

после первого запуска ваши токены сохранятся в файле auth_keys.json , и больше флудвейтов не будет!

**Comment by PSHacks** [comment]
> я ничего не могу поделать с этим, подождите пару часов, может отпадет
> 
> после первого запуска ваши токены сохранятся в файле auth_keys.json , и больше флудвейтов не будет!

Через 800 секунд попробую и отпишусь, бота переустановил только что, зашел получил 800 сек

**Comment by meistermode** [comment]
> после первого запуска ваши токены сохранятся в файле auth_keys.json , и больше флудвейтов не будет!

ранее такой файл у меня создавался, щас решил специально переустановить и накатить новую сессию, ничего не засейвилось -> здравствуй, флудвейт

**Comment by tancyit3** [comment]
> я ничего не могу поделать с этим, подождите пару часов, может отпадет
> 
> после первого запуска ваши токены сохранятся в файле auth_keys.json , и больше флудвейтов не будет!

у меня не создается файл auth_keys.json. просто по кд. подождем значит
![изображение](https://github.com/shamhi/HamsterKombatBot/assets/136000100/0f92f53d-fd5e-4e22-aed0-abed7eec308b)

**Comment by darhanger** [comment]
У меня такая же фигня. Один акк крутиться нормально, на другом по кд ошибку сыпит.

**Comment by tancyit3** [comment]
> У меня такая же фигня. Один акк крутиться нормально, на другом по кд ошибку сыпит.

У тебя то есть один акк стабильно работает? У меня просто 3 аккаунтам флуд дает

**Comment by darhanger** [comment]
> > У меня такая же фигня. Один акк крутиться нормально, на другом по кд ошибку сыпит.
> 
> У тебя то есть один акк стабильно работает? У меня просто 3 аккаунтам флуд дает

на разных машинах.

**Comment by shamhi** [comment]
вышла обнова!

**Comment by Qssa** [comment]
> вышла обнова!

Работает, от души

**Comment by tancyit3** [comment]
> вышла обнова!

ворк, можно закрывать

**Comment by liluglymane666** [comment]
вроде работает,но с ошибками

![555jpg](https://github.com/shamhi/HamsterKombatBot/assets/57453873/e39530c7-19e7-43dc-818a-5a95af172b37)

**Comment by yacody** [comment]
> > вышла обнова!
> 
> ворк, можно закрывать

![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/7b2bb78b-b8c0-4169-98c2-711a60400b68)
так себе ворк

**Comment by shamhi** [comment]
> вроде работает,но с ошибками
> 
> ![555jpg](https://private-user-images.githubusercontent.com/57453873/333306078-e39530c7-19e7-43dc-818a-5a95af172b37.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTA1NzYsIm5iZiI6MTcxNjQ5MDI3NiwicGF0aCI6Ii81NzQ1Mzg3My8zMzMzMDYwNzgtZTM5NTMwYzctMTllNy00M2RjLTgxOGEtNWE5NWFmMTcyYjM3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE4NTExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3N2QyNmJkODdhYzJlZTMyNjI0OTY1ZGFjNDA5NWU2MTZiYjFjZmZmOTBjY2Y5OGZjYjA0ODhhMmYwOTUyMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zjuLAuSKJHKBtZFKS4cLdXvuXxTOczR_AkG3m5iuSGs)

сейчас запушу фикс

**Comment by yacody** [comment]
оно работает, но после пары нормальных тапов тратит всю энергию делая кучу кликов в одну секунду. как бы норм, но думаю за такое и забанить может

**Comment by shamhi** [comment]
обновляйте

**Comment by shamhi** [comment]
> оно работает, но после пары нормальных тапов тратит всю энергию делая кучу кликов в одну секунду. как бы норм, но думаю за такое и забанить может

поставь в `.env` свои значения

**Comment by liluglymane666** [comment]
готово.все работает.Спасибо!!!

**Comment by Qssa** [comment]
> > оно работает, но после пары нормальных тапов тратит всю энергию делая кучу кликов в одну секунду. как бы норм, но думаю за такое и забанить может
> 
> поставь в `.env` свои значения

Если у меня не одна сессия, как эти значения ставить?

**Comment by shamhi** [comment]
> > > оно работает, но после пары нормальных тапов тратит всю энергию делая кучу кликов в одну секунду. как бы норм, но думаю за такое и забанить может
> > 
> > 
> > поставь в `.env` свои значения
> 
> Если у меня не одна сессия, как эти значения ставить? Api и т.д 400 ошибка у меня

одних api_id и api_hash хватит на много аккаунтов

**Comment by shamhi** [comment]
все, последнее обновление
