### ISSUE TITLE
Just now, I lost half of my accounts, about 10 or so. Total ban

### ISSUE THREAD

**Issue by hardwin1014** [shamhi/HamsterKombatBot#658]

**Comment by nartyjezusa** [comment]
did you used proxy?

**Comment by hardwin1014** [comment]
Yes, I used the purchased IP, with a unique IP for each account. The banned account is the account I purchased. Is it because it's a new account?

------------------ Original ------------------
From: nartyjezusa ***@***.***&gt;
Date: Mon,Jul 8,2024 3:07 AM
To: shamhi/HamsterKombatBot ***@***.***&gt;
Cc: 苍南 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [shamhi/HamsterKombatBot] Just now, I lost half of my accounts,about 10 or so. Total ban (Issue #658)





 
did you used proxy?

**Comment by AutumnQR** [comment]
https://github.com/shamhi/HamsterKombatBot/issues/121#issuecomment-2135764249

**Comment by KOTBCTAKAHE** [comment]
false alarm of the antispam system, sorry
