### ISSUE TITLE
Unknown error while buying Upgrade: 400, message='Bad Request' error_code:"INSUFFICIENT_FUNDS"

### ISSUE THREAD

**Issue by meistermode** [shamhi/HamsterKombatBot#66]
Unknown error while buying Upgrade: 400, message='Bad Request', url=URL('https://api.hamsterkombat.io/clicker/buy-upgrade') | Response text: {"error_code":"INSUFFICIENT_FUNDS","error_message":"Insufficient funds: your balanceCoins 3584.440045838574, required: 6418"}
над проверку баланса перед апгрейдом

**Comment by ButCheR-PRO** [comment]
Советую установить [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Затем синхронизировать на компьютере системное время.
Скачать последнюю версию бота
Потом запустить INSTALL.bat. 
Затем настроить конфиг .env согласно документации в README.md
После этого создать сессию через START.bat выбрав пункт 1. 
И только потом запускать настроенный кликер через START.bat выбрав пункт 2.
