### ISSUE TITLE
 cannot access local variable 'available_energy'

### ISSUE THREAD

**Issue by liluglymane666** [shamhi/HamsterKombatBot#7]
собственно вот.энергии достаточно,проверял.Конфиг менял,работаю с прокси
![image](https://github.com/shamhi/HamsterKombatBot/assets/57453873/b7dd017a-181c-478f-8ac0-cc40852bca37)

**Comment by huukhoa1412** [comment]
me too

**Comment by lbiskupi** [comment]
i have similar issue but only on 1 of the 10 acc, i think it may be a ban or something similar

**Comment by huukhoa1412** [comment]
> i have similar issue but only on 1 of the 10 acc, i think it may be a ban or something similar

I only run 1 acc ,many error

**Comment by liluglymane666** [comment]
опять проблема актуальна

**Comment by shamhi** [comment]
fixed
