### ISSUE TITLE
Добавить проверку на баланс

### ISSUE THREAD

**Issue by AlexKrutoy** [shamhi/HamsterKombatBot#73]
Из-за того, что нет проверки на баланс, то при попытке апгрейда выдает ошибку на всю консоль:
![изображение](https://github.com/shamhi/HamsterKombatBot/assets/65369825/3dbcb421-5bed-47c3-b76a-ec080942774d)

**Comment by liluglymane666** [comment]
same shit

**Comment by tancyit3** [comment]
На счёт всего не знаю, но если хочешь убрать этот json текст, то убери  - **f"Response text: {response_text}") в tapper.py**

**Comment by AlexKrutoy** [comment]
![изображение](https://github.com/shamhi/HamsterKombatBot/assets/65369825/4a5a9d7f-5283-44d7-b44b-89af1c3b4ecd)
Ну а ещё такая фишка бывает, после того как закрою консоль

**Comment by AlexKrutoy** [comment]
С телефона бот тогда выдает "Request error, unable to sync"

**Comment by AlexKrutoy** [comment]
Упс, с телефона кстати при ошибке выдает "Request Error - unable to sync", ну тут уже видимо проблема не в коде бота для хомяка, а в боте хомяке

**Comment by tancyit3** [comment]
> Упс, с телефона кстати при ошибке выдает "Request Error - unable to sync", ну тут уже видимо проблема не в коде бота для хомяка, а в боте хомяке


Если запущен код, то он тебе не даст зайти с телефона

**Comment by AlexKrutoy** [comment]
> > Упс, с телефона кстати при ошибке выдает "Request Error - unable to sync", ну тут уже видимо проблема не в коде бота для хомяка, а в боте хомяке
> 
> Если запущен код, то он тебе не даст зайти с телефона

После закрытия cmd с ботом и повторном открытии и запуска авто-бота появляется данная ошибка, а потом уже при закрытии во второй раз с данной ошибкой и попыткой зайти с телефона - тг бот выдает "unable to sync"

**Comment by shamhi** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/65369825/333309497-4a5a9d7f-5283-44d7-b44b-89af1c3b4ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTE0MDIsIm5iZiI6MTcxNjQ5MTEwMiwicGF0aCI6Ii82NTM2OTgyNS8zMzMzMDk0OTctNGE1YTlkN2YtNTI4My00NGQ3LWI0NGItODlhZjFjM2I0ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE5MDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjM3MTliOWQyOTEwMTkzYzlhYWQ1N2FiOTYxM2UxYzFiM2JmNDZjNTZjZTFkYjU3MjQ1ZDlhMDVjZmJmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Pf4NghpZKbhJxWR5IPrFdbHgQV7DCvWrTZeUjEvMw0) Ну а ещё такая фишка бывает, после того как закрою консоль

я это добавил для борьбы с флудвейтом, но нашлось другое решение, поэтому я удалил эту логику auth_keys с бота
обнови

**Comment by AlexKrutoy** [comment]
> > ![изображение](https://private-user-images.githubusercontent.com/65369825/333309497-4a5a9d7f-5283-44d7-b44b-89af1c3b4ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTE0MDIsIm5iZiI6MTcxNjQ5MTEwMiwicGF0aCI6Ii82NTM2OTgyNS8zMzMzMDk0OTctNGE1YTlkN2YtNTI4My00NGQ3LWI0NGItODlhZjFjM2I0ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE5MDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjM3MTliOWQyOTEwMTkzYzlhYWQ1N2FiOTYxM2UxYzFiM2JmNDZjNTZjZTFkYjU3MjQ1ZDlhMDVjZmJmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Pf4NghpZKbhJxWR5IPrFdbHgQV7DCvWrTZeUjEvMw0) Ну а ещё такая фишка бывает, после того как закрою консоль
> 
> я это добавил для борьбы с флудвейтом, но нашлось другое решение, поэтому я удалил эту логику auth_keys с бота обнови

обновлен, стоит 1.6 версия, последний коммит который

**Comment by AlexKrutoy** [comment]
А, понял, уже +4 коммита, щас обновлю

**Comment by AlexKrutoy** [comment]
> > ![изображение](https://private-user-images.githubusercontent.com/65369825/333309497-4a5a9d7f-5283-44d7-b44b-89af1c3b4ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTE0MDIsIm5iZiI6MTcxNjQ5MTEwMiwicGF0aCI6Ii82NTM2OTgyNS8zMzMzMDk0OTctNGE1YTlkN2YtNTI4My00NGQ3LWI0NGItODlhZjFjM2I0ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE5MDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjM3MTliOWQyOTEwMTkzYzlhYWQ1N2FiOTYxM2UxYzFiM2JmNDZjNTZjZTFkYjU3MjQ1ZDlhMDVjZmJmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Pf4NghpZKbhJxWR5IPrFdbHgQV7DCvWrTZeUjEvMw0) Ну а ещё такая фишка бывает, после того как закрою консоль
> 
> я это добавил для борьбы с флудвейтом, но нашлось другое решение, поэтому я удалил эту логику auth_keys с бота обнови

+, пофикшено, осталось добавить проверку на баланс)

**Comment by GekK9** [comment]
> > > ![изображение](https://private-user-images.githubusercontent.com/65369825/333309497-4a5a9d7f-5283-44d7-b44b-89af1c3b4ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTE0MDIsIm5iZiI6MTcxNjQ5MTEwMiwicGF0aCI6Ii82NTM2OTgyNS8zMzMzMDk0OTctNGE1YTlkN2YtNTI4My00NGQ3LWI0NGItODlhZjFjM2I0ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE5MDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjM3MTliOWQyOTEwMTkzYzlhYWQ1N2FiOTYxM2UxYzFiM2JmNDZjNTZjZTFkYjU3MjQ1ZDlhMDVjZmJmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Pf4NghpZKbhJxWR5IPrFdbHgQV7DCvWrTZeUjEvMw0) Ну а ещё такая фишка бывает, после того как закрою консоль
> > 
> > 
> > я это добавил для борьбы с флудвейтом, но нашлось другое решение, поэтому я удалил эту логику auth_keys с бота обнови
> 
> обновлен, стоит 1.6 версия, последний коммит который

![image](https://github.com/shamhi/HamsterKombatBot/assets/110110744/e2b6bf8c-668c-46e3-b2f4-8e4abaef6e22)

Как-то ошибку выбивает, мб связано с достпуностью к покупке или прайсом

**Comment by shamhi** [comment]
> > > > ![изображение](https://private-user-images.githubusercontent.com/65369825/333309497-4a5a9d7f-5283-44d7-b44b-89af1c3b4ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTE0MDIsIm5iZiI6MTcxNjQ5MTEwMiwicGF0aCI6Ii82NTM2OTgyNS8zMzMzMDk0OTctNGE1YTlkN2YtNTI4My00NGQ3LWI0NGItODlhZjFjM2I0ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE5MDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjM3MTliOWQyOTEwMTkzYzlhYWQ1N2FiOTYxM2UxYzFiM2JmNDZjNTZjZTFkYjU3MjQ1ZDlhMDVjZmJmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Pf4NghpZKbhJxWR5IPrFdbHgQV7DCvWrTZeUjEvMw0) Ну а ещё такая фишка бывает, после того как закрою консоль
> > > 
> > > 
> > > я это добавил для борьбы с флудвейтом, но нашлось другое решение, поэтому я удалил эту логику auth_keys с бота обнови
> > 
> > 
> > обновлен, стоит 1.6 версия, последний коммит который
> 
> ![image](https://private-user-images.githubusercontent.com/110110744/333310845-e2b6bf8c-668c-46e3-b2f4-8e4abaef6e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTE3ODYsIm5iZiI6MTcxNjQ5MTQ4NiwicGF0aCI6Ii8xMTAxMTA3NDQvMzMzMzEwODQ1LWUyYjZiZjhjLTY2OGMtNDZlMy1iMmY0LThlNGFiYWVmNmUyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxOTExMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzJmYzI0ZWU0Mjk2Y2Q4OWRlMTRiMTY2ODJmMDk4NDM5ODg5MDVmYmY1OWJiZDg1MTY4M2Y1MzI3NjRkNjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wAGlWG5hgHw7g0mH6hhmXnxdL6j8co-VaHF2CEnweWQ)
> 
> Как-то ошибку выбивает, мб связано с достпуностью к покупке или прайсом

кстати, посмотри, после 422 оно улучшилось?

**Comment by GekK9** [comment]
> > > > > ![изображение](https://private-user-images.githubusercontent.com/65369825/333309497-4a5a9d7f-5283-44d7-b44b-89af1c3b4ecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTE0MDIsIm5iZiI6MTcxNjQ5MTEwMiwicGF0aCI6Ii82NTM2OTgyNS8zMzMzMDk0OTctNGE1YTlkN2YtNTI4My00NGQ3LWI0NGItODlhZjFjM2I0ZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE5MDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjM3MTliOWQyOTEwMTkzYzlhYWQ1N2FiOTYxM2UxYzFiM2JmNDZjNTZjZTFkYjU3MjQ1ZDlhMDVjZmJmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Pf4NghpZKbhJxWR5IPrFdbHgQV7DCvWrTZeUjEvMw0) Ну а ещё такая фишка бывает, после того как закрою консоль
> > > > 
> > > > 
> > > > я это добавил для борьбы с флудвейтом, но нашлось другое решение, поэтому я удалил эту логику auth_keys с бота обнови
> > > 
> > > 
> > > обновлен, стоит 1.6 версия, последний коммит который
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/110110744/333310845-e2b6bf8c-668c-46e3-b2f4-8e4abaef6e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0OTE3ODYsIm5iZiI6MTcxNjQ5MTQ4NiwicGF0aCI6Ii8xMTAxMTA3NDQvMzMzMzEwODQ1LWUyYjZiZjhjLTY2OGMtNDZlMy1iMmY0LThlNGFiYWVmNmUyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyM1QxOTExMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzJmYzI0ZWU0Mjk2Y2Q4OWRlMTRiMTY2ODJmMDk4NDM5ODg5MDVmYmY1OWJiZDg1MTY4M2Y1MzI3NjRkNjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wAGlWG5hgHw7g0mH6hhmXnxdL6j8co-VaHF2CEnweWQ)
> > Как-то ошибку выбивает, мб связано с достпуностью к покупке или прайсом
> 
> кстати, посмотри, после 422 оно улучшилось?

Сори за долгий ответ, вроде как да

**Comment by shamhi** [comment]
значит 422 это успешный ответ

**Comment by GekK9** [comment]
По логике да, но сервер чего-то ругается судя по ответу

**Comment by AlexKrutoy** [comment]
@shamhi Привет еще раз, думаю неплохо было бы создать дискорд сервер с ру и en чатами, багами и вопросами к разработчикам)

**Comment by GekK9** [comment]
@shamhi последний коммит = фикс, все теперь идеально. Как предложение: для каждой сессии организовать свой конфиг (как минимум для прав апгрейда карточек), чтобы не создавать для каждой сессии свой реп

**Comment by avtosubaru25** [comment]
> значит 422 это успешный ответ

Саша красавчик все работает , как нашол ответ  ?

**Comment by GekK9** [comment]
@shamhi Со временем обнародовалась еще одно. Проверка на кд апгрейда карточки

![image](https://github.com/shamhi/HamsterKombatBot/assets/110110744/b5b01f35-97bb-4966-b897-5da96265bc76)

**Comment by krava77** [comment]
Здравствуйте!
подскажите пожалуйста, работают ли боты с Ipv6 прокси или только Ipv4 ?

**Comment by avtosubaru25** [comment]
> Здравствуйте! подскажите пожалуйста, работают ли боты с Ipv6 прокси или только Ipv4 ?
Ipv4

**Comment by vaniademianov** [comment]
> @shamhi Со временем обнародовалась еще одно. Проверка на кд апгрейда карточки
> 
> ![image](https://private-user-images.githubusercontent.com/110110744/333345785-b5b01f35-97bb-4966-b897-5da96265bc76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzUzMjMsIm5iZiI6MTcxNjUzNTAyMywicGF0aCI6Ii8xMTAxMTA3NDQvMzMzMzQ1Nzg1LWI1YjAxZjM1LTk3YmItNDk2Ni1iODk3LTVkYTk2MjY1YmM3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQwNzE3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjUxODA3ZTY2YjYwYWNmMzUzNGMyOTk0MmQyMGJmMTlmZTU3MDdlNTUxMGJkODY4NDQ2YTMxYjJkOTYyMDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q48YBtkqYCNA_hNddSx7r3107kuIg1VdVd_bLFMukqQ)

https://github.com/shamhi/HamsterKombatBot/pull/72

**Comment by AlexKrutoy** [comment]
fixed
