### ISSUE TITLE
411 - Unknown error: cannot access local variable 'response_text' where it is not associated with a value

### ISSUE THREAD

**Issue by KotainFN** [shamhi/HamsterKombatBot#74]
411 error😭

**Comment by KotainFN** [comment]
Unknown error: cannot access local variable 'response_text' where it is not associated with a value

**Comment by RoninReilly** [comment]
+ same

**Comment by RoninReilly** [comment]
Change tapper.py with my update. I just remove ssl verif and add right var init. Check it https://codefile.io/f/Ik60qxp9Wb

**Comment by ButCheR-PRO** [comment]
I advise you to install [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Then synchronize the system time on your computer.
Then run INSTALL.bat.
Then set up the .env config according to the documentation in README.md.
After this, create a session via START.bat by selecting option 1.
And only then launch the configured clicker through START.bat by selecting point 2.
