### ISSUE TITLE
411 - Unknown error: cannot access local variable 'response_text' where it is not associated with a value

### ISSUE THREAD

**Issue by vedma1337** [shamhi/HamsterKombatBot#75]
![image](https://github.com/shamhi/HamsterKombatBot/assets/157295406/f90dfcc6-17b2-4e75-8465-9a5550fb487a)

**Comment by babasuck** [comment]
start cmd as administrator

**Comment by vedma1337** [comment]
> start cmd as administrator
> 
> upd. oh I see C:\Window\system32\cmd.exe label so you as adm already. Try to replace bot directory to "Documents"

![image](https://github.com/shamhi/HamsterKombatBot/assets/157295406/1dbda3db-b343-4dbf-a9e2-ccbbd4e03dd4)
same

**Comment by shamhi** [comment]
you need 3.11 or 3.10 python version

**Comment by vedma1337** [comment]
> you need 3.11 or 3.10 python version

![image](https://github.com/shamhi/HamsterKombatBot/assets/157295406/1a4dfc4c-e991-4870-90a2-79fe3ad1d9b9)

**Comment by shamhi** [comment]
wait fix

**Comment by vedma1337** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/157295406/2cdb43c9-61a6-445b-84cf-1e64573be06b)

**Comment by shamhi** [comment]
это уже твои сетевые проблемы

**Comment by Kanorto** [comment]
у него на первом скрине tgcrypto не стоял, пускай попробует переустановить зависимости.

**Comment by vedma1337** [comment]
> у него на первом скрине tgcrypto не стоял, пускай попробует переустановить зависимости.

да не, не в нем прикол

**Comment by ButCheR-PRO** [comment]
Советую установить [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
Затем синхронизировать на компьютере системное время.
Потом запустить INSTALL.bat. 
Затем настроить конфиг .env согласно документации в README.md
После этого создать сессию через START.bat выбрав пункт 1. 
И только потом запускать настроенный кликер через START.bat выбрав пункт 2.
