### ISSUE TITLE
407 - Unknown error: local variable 'avaliable_energy' referenced before assignment

### ISSUE THREAD

**Issue by Zoro752** [shamhi/HamsterKombatBot#76]
Что делать?
![Безымянный](https://github.com/shamhi/HamsterKombatBot/assets/170701597/8426c6eb-6feb-487a-b654-ee980b560408)

**Comment by vaniademianov** [comment]
можешь плз заскриншотить логи с начала?

**Comment by Kanorto** [comment]
Использовали полный установщик, ошибок во время установки зависимостей не было? Версия python та?

**Comment by ButCheR-PRO** [comment]
Советую установить [Python 3.10.9](https://www.python.org/downloads/release/python-3109/)
И запустить INSTALL.bat. После этого создать сессию через START.bat выбрав пункт 1.
