### ISSUE TITLE
420 FLOOD_WAIT_X

### ISSUE THREAD

**Issue by mrranger** [shamhi/HamsterKombatBot#77]
FloodWait Telegram says: [420 FLOOD_WAIT_X] - A wait of 475 seconds is required (caused by "contacts.ResolveUsername")

**Comment by AlexKrutoy** [comment]
обнови бота, перекачай зип

**Comment by vaniademianov** [comment]
https://github.com/shamhi/HamsterKombatBot/pull/72

**Comment by mrranger** [comment]
> обнови бота, перекачай зип

Не помогает)

**Comment by Fairmont77** [comment]
[https://t.me/hamster_kombat/182](url) - just wait)
