### ISSUE TITLE
карточка не имеет апгрейдов, но бот её постоянно пытается улучшить

### ISSUE THREAD

**Issue by yacody** [shamhi/HamsterKombatBot#79]
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/c651d1d0-3370-4e5d-b59b-06ea5622e95b)

**Comment by shamhi** [comment]
она помечена как доступная, поэтому бот пытается ее купить

**Comment by yacody** [comment]
> она помечена как доступная, поэтому бот пытается ее купить

ну так она куплена. Проблема в том, что он апгрейдитьь пытается

**Comment by photelega** [comment]
`{'id': 'joe_rogan_podcast', 'name': 'Joe Rogan Podcast', 'maxLevel': 1, 'price': 1102500, 'profitPerHour': 0, 'condition': None, 'section': 'Specials', 'level': 2, 'currentProfitPerHour': 0, 'profitPerHourDelta': 0, 'isAvailable': True, 'isExpired': False}`

Only one these upgrade has this behavior.
And it is the only one that has the "maxLevel" key in json, can  be added to exceptions (if by id). 
Or when selecting actual upgrades, make a check : 
`if data.get('maxLevel', data['level']) >= data['level']` 

in case there are more such upgrades or if this one's maxLevel increases

**Comment by yacody** [comment]
> `{'id': 'joe_rogan_podcast', 'name': 'Joe Rogan Podcast', 'maxLevel': 1, 'price': 1102500, 'profitPerHour': 0, 'condition': None, 'section': 'Specials', 'level': 2, 'currentProfitPerHour': 0, 'profitPerHourDelta': 0, 'isAvailable': True, 'isExpired': False}`
> 
> Only one these upgrade has this behavior. And it is the only one that has the "maxLevel" key in json, can be added to exceptions (if by id). Or when selecting actual upgrades, make a check : `if data.get('maxLevel', data['level']) >= data['level']`
> 
> in case there are more such upgrades or if this one's maxLevel increases

where i need to write this? tell me pls

**Comment by photelega** [comment]
> `{'id': 'joe_rogan_podcast', 'name': 'Joe Rogan Podcast', 'maxLevel': 1, 'price': 1102500, 'profitPerHour': 0, 'condition': None, 'section': 'Specials', 'level': 2, 'currentProfitPerHour': 0, 'profitPerHourDelta': 0, 'isAvailable': True, 'isExpired': False}`
> 
> Only one these upgrade has this behavior. And it is the only one that has the "maxLevel" key in json, can be added to exceptions (if by id). Or when selecting actual upgrades, make a check : `if data.get('maxLevel', data['level']) >= data['level']`
> 
> in case there are more such upgrades or if this one's maxLevel increases

Correction, this is a special upgrade - it becomes your own, maybe different users have different ones

**Comment by photelega** [comment]
> > `{'id': 'joe_rogan_podcast', 'name': 'Joe Rogan Podcast', 'maxLevel': 1, 'price': 1102500, 'profitPerHour': 0, 'condition': None, 'section': 'Specials', 'level': 2, 'currentProfitPerHour': 0, 'profitPerHourDelta': 0, 'isAvailable': True, 'isExpired': False}`
> > Only one these upgrade has this behavior. And it is the only one that has the "maxLevel" key in json, can be added to exceptions (if by id). Or when selecting actual upgrades, make a check : `if data.get('maxLevel', data['level']) >= data['level']`
> > in case there are more such upgrades or if this one's maxLevel increases
> 
> where i need to write this? tell me pls

#87 

https://github.com/shamhi/HamsterKombatBot/pull/87/files

**Comment by shamhi** [comment]
fixed
