### ISSUE TITLE
Как понять, работают ли прокси??

### ISSUE THREAD

**Issue by dezdemxn** [shamhi/HamsterKombatBot#8]
Как прокси правильно вводить?
![image psd](https://github.com/shamhi/HamsterKombatBot/assets/165968275/b751c57e-d946-4cd9-a8e5-b6474ac950b7)

![image](https://github.com/shamhi/HamsterKombatBot/assets/165968275/5306af13-84b3-40b9-9a2b-1eb6e3aae448)
![image](https://github.com/shamhi/HamsterKombatBot/assets/165968275/c16ccb35-a5a1-46ab-bdd8-8dcbd5c1e8b0)

**Comment by dezdemxn** [comment]
Как я понимаю, 1 строка прокси для первой сессии или не так?

**Comment by shamhi** [comment]
> Как понять, работают ли прокси??

1. При запуске ты видишь число проксей "| 3 proxies"
2. После запуска они проверяются на валидность: отправляется запрос на https://httpbin.org/ip для проверки IP адреса

> Как я понимаю, 1 строка прокси для первой сессии или не так работает?

Прокси ставится в том порядке, в каком лежат сессии в папке `sessions/`

**Comment by dezdemxn** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/165968275/fcd9abde-1f4b-494f-8e1f-06bfa822b35d)
Неправильно ввел прокси? не вижу число

**Comment by shamhi** [comment]
покажи начало запуска, вероятнее всего ты не установил USE_PROX_FROM_FILE=True

**Comment by dezdemxn** [comment]
![image](https://github.com/shamhi/HamsterKombatBot/assets/165968275/31888ab7-6085-4633-8a07-62582b502ecc)

**Comment by shamhi** [comment]
не TRUE а True
