### ISSUE TITLE
FloodWait

### ISSUE THREAD

**Issue by DamAlyuk** [shamhi/HamsterKombatBot#80]
??

**Comment by maplexx14** [comment]
too many requests

**Comment by DamAlyuk** [comment]
> too many requests

Да ну, а как решить, умник? Появляется из-за contacts.ResolveUsername

**Comment by maplexx14** [comment]
> > too many requests
> 
> Да ну, а как решить, умник? Появляется из-за contacts.ResolveUsername

А ты сразу нормально формулируй вопрос

**Comment by AlexKrutoy** [comment]
обновите до ласт коммита, скачайте зип

**Comment by DamAlyuk** [comment]
> > > too many requests
> > 
> > 
> > Да ну, а как решить, умник? Появляется из-за contacts.ResolveUsername
> 
> А ты сразу нормально формулируй вопрос

Ну ты же вроде не тупой, можешь догадаться о чем речь. Как будто я не могу зайти в тг доки и почитать что это означает...

**Comment by DamAlyuk** [comment]
> обновите до ласт коммита, скачайте зип

Кратко можете объяснить в чем решение заключается?

**Comment by AlexKrutoy** [comment]
> > обновите до ласт коммита, скачайте зип
> 
> Кратко можете объяснить в чем решение заключается?

Если скачивал через гит, то открываешь cmd в папке бота и пишешь git pull

Если скачивал через сайт гитхаба с помощью скачивания zip, то по такому же принципу качаешь еще один zip и разархивируешь в папку бота со всеми заменами
