### ISSUE TITLE
Через несколько часов бот крашится

### ISSUE THREAD

**Issue by AlexKrutoy** [shamhi/HamsterKombatBot#81]
https://pastebin.com/raw/XuQL0u1n
лог ошибки

**Comment by Vladislav875** [comment]
Используешь последнюю версию бота ?

**Comment by glofflive** [comment]
Аналогично

**Comment by AlexKrutoy** [comment]
> Используешь последнюю версию бота ?

+

**Comment by shamhi** [comment]
проверь после обновлений

**Comment by AlexKrutoy** [comment]
> проверь после обновлений

k
