### ISSUE TITLE
422 Unknown error while getting Access Token Unprocessable Entity, NoneType pbject has no attribute - Проблема с PROXY. 

### ISSUE THREAD

**Issue by ATAMAH161** [shamhi/HamsterKombatBot#86]
![IMG_1486](https://github.com/shamhi/HamsterKombatBot/assets/170763572/6aa28be2-5c60-4079-94f2-3189868af51d)

Вот такая ошибка при запуске, даже после обновлений уже около 3 дней. Хотя другие скрипты автора работают.

**Comment by AlexKrutoy** [comment]
1 - версия питона
2 - как создавал сессию
3 - как открывал бота, через батник или два раза лкм по main.py
4 - пробывал ли запуск без прокси
?

**Comment by ATAMAH161** [comment]
> 1 - версия питона 2 - как создавал сессию 3 - как открывал бота, через батник или два раза лкм по main.py 4 - пробывал ли запуск без прокси 5 - стоит ли последняя версия? (коммит) ?

1- стоит как 3.11 так и 3.12
2- сессию создавал через скрипт
3- открывал через путь в поисковой строке написал cmd
4- не пробовал
5- последняя версия чего?

**Comment by shamhi** [comment]
> ![IMG_1486](https://private-user-images.githubusercontent.com/170763572/333722434-6aa28be2-5c60-4079-94f2-3189868af51d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzUzMjUsIm5iZiI6MTcxNzEzNTAyNSwicGF0aCI6Ii8xNzA3NjM1NzIvMzMzNzIyNDM0LTZhYTI4YmUyLTVjNjAtNDA3OS05NGYyLTMxODk4NjhhZjUxZC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMDU1NzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWM3MGVkY2NjMDIwYzE4YzJmYWMzMmU3MzI3OTEzZDU4Mjg1ZTFlZGFiZTY5ZGM1NWU1MzI5OGU1ZjkxZWM3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0z1FkhOZVe-rdJbtrFNluqFxozFO8cVdVSkRYuCFq0c)
> 
> Вот такая ошибка при запуске, даже после обновлений уже около 3 дней. Хотя другие скрипты автора работают.

проблема в прокси, не может подключиться к сессии

**Comment by ATAMAH161** [comment]
А где есть проверенные прокси которые работают в этом скрипте?

**Comment by ATAMAH161** [comment]
> > ![IMG_1486](https://private-user-images.githubusercontent.com/170763572/333722434-6aa28be2-5c60-4079-94f2-3189868af51d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMzUzMjUsIm5iZiI6MTcxNzEzNTAyNSwicGF0aCI6Ii8xNzA3NjM1NzIvMzMzNzIyNDM0LTZhYTI4YmUyLTVjNjAtNDA3OS05NGYyLTMxODk4NjhhZjUxZC5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMDU1NzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWM3MGVkY2NjMDIwYzE4YzJmYWMzMmU3MzI3OTEzZDU4Mjg1ZTFlZGFiZTY5ZGM1NWU1MzI5OGU1ZjkxZWM3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0z1FkhOZVe-rdJbtrFNluqFxozFO8cVdVSkRYuCFq0c)
> > Вот такая ошибка при запуске, даже после обновлений уже около 3 дней. Хотя другие скрипты автора работают.
> 
> проблема в прокси, не может подключиться к сессии

Интересно то, что на этих прокси tapswap работает твой скрипт. А этот hamster никак)

**Comment by ATAMAH161** [comment]
> 1. Попробуй пересоздать сессию
> 2. Кажется у тебя не стоит последняя версия бота, обнови `git pull origin main`
> 3. Я беру тут - https://proxy6.net

Да действительно проблема в прокси. Без прокси всё работает. Используются же IPv4 и какой формат http или socks5?

**Comment by shamhi** [comment]
> > 1. Попробуй пересоздать сессию
> > 2. Кажется у тебя не стоит последняя версия бота, обнови `git pull origin main`
> > 3. Я беру тут - https://proxy6.net
> 
> Да действительно проблема в прокси. Без прокси всё работает. Используются же IPv4 и какой формат http или socks5?

желательно socks5

**Comment by ATAMAH161** [comment]
> > > 1. Попробуй пересоздать сессию
> > > 2. Кажется у тебя не стоит последняя версия бота, обнови `git pull origin main`
> > > 3. Я беру тут - https://proxy6.net
> > 
> > 
> > Да действительно проблема в прокси. Без прокси всё работает. Используются же IPv4 и какой формат http или socks5?
> 
> желательно socks5

socks5://и т.д.      Такой же формат если по socks, а то есть сомнения по этому поводу

**Comment by ATAMAH161** [comment]
> > > 1. Попробуй пересоздать сессию
> > > 2. Кажется у тебя не стоит последняя версия бота, обнови `git pull origin main`
> > > 3. Я беру тут - https://proxy6.net
> > 
> > 
> > Да действительно проблема в прокси. Без прокси всё работает. Используются же IPv4 и какой формат http или socks5?
> 
> желательно socks5

В общем долгие тесты привели к таким выводам. Проблема была в прокси, но нужно было поменять лишь их тип на socks5 и тогда всё работает. С типом прокси всегда запара одни говорят http нужны и никак иначе у других socks5. Как считаешь какой тип для фермы подходит лучше и почему?

**Comment by ButCheR-PRO** [comment]
Пока что решение такое. В .env: 
`USE_PROXY_FROM_FILE=False`
Если 
`USE_PROXY_FROM_FILE=True`
То в bot/config/proxies.txt все прокси должны быть в SOCKS5 а не HTTP.
