### ISSUE TITLE
Обновление улучшений

### ISSUE THREAD

**Issue by babasuck** [shamhi/HamsterKombatBot#89]
Предлагаю, чтобы после очередного улучшения карточки список улучшений обновлялся и сортировался снова. Может быть так, что после улучшения карточки она все еще остается самой оптимальной, текущий алгоритм этого не учитывает. Для себя я изменил код таким образом, предлагаю добавить опцию в боте чисто для улучшения, без кликов, кто боится, что будут банить.

**Comment by Kanorto** [comment]
крутая идея, +

**Comment by Lyapsus** [comment]
Так сделай pr

**Comment by ButCheR-PRO** [comment]
> Предлагаю, чтобы после очередного улучшения карточки список улучшений обновлялся и сортировался снова. Может быть так, что после улучшения карточки она все еще остается самой оптимальной, текущий алгоритм этого не учитывает. Для себя я изменил код таким образом, предлагаю добавить опцию в боте чисто для улучшения, без кликов, кто боится, что будут банить.

Так выложи переделанный код :)
