### ISSUE TITLE
Ошибочка SSL сертификата

### ISSUE THREAD

**Issue by l1v0n1** [shamhi/HamsterKombatBot#90]
<img width="1201" alt="Screenshot 2024-05-25 at 10 01 32 AM" src="https://github.com/shamhi/HamsterKombatBot/assets/70073044/7e131bb5-30fc-4212-a104-0db3782262f5">

**Comment by shamhi** [comment]
https://stackoverflow.com/questions/50236117/scraping-ssl-certificate-verify-failed-error-for-http-en-wikipedia-org
