### ISSUE TITLE
Не могу после софта зайти в hamster. Через софт фармит, все хорошо, а на телефоне unable to sycn. Кто знает как фиксить? 

### ISSUE THREAD

**Issue by Sanchozuy** [shamhi/HamsterKombatBot#91]

**Comment by Sanchozuy** [comment]
Sync*

**Comment by yacody** [comment]
> Sync*

чтобы зайти офаешь бота и ждешь минут 30. после этого дает зайти только

**Comment by Kanorto** [comment]
а, у меня такая же проблема была. Крч слишком много запросов со своего айпишника не делай сразу после выключения. Постарайся после отключения подождать минут 5, и только потом заходить. Также во время майнинга скриптом лучше не заходить в бота.

**Comment by Sanchozuy** [comment]
Понял, всем спасибо
