### ISSUE TITLE
какой-то баг с фармом

### ISSUE THREAD

**Issue by yacody** [shamhi/HamsterKombatBot#92]
После одного нормального круга с фармом идёт пауза 2015 секунд, затем за раз выфармливаются все доступные клики, снова пауза 2015 секунд и нормальный круг.
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/e17df750-e19a-45b0-ba5e-5022c1523834)
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/f94b3cdd-97b2-4fff-85ff-f896bbfe91aa)
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/bdbbbd43-4af8-4d88-af64-293e18de14c2)

**Comment by shamhi** [comment]
может потому что ты в `.env` поставил `SLEEP_BY_MIN_ENERGY=2015` ?

**Comment by yacody** [comment]
> может потому что ты в `.env` поставил `SLEEP_BY_MIN_ENERGY=2015` ?

ну поставил, а как это связано с тем, что после 2015 секунд он за 1 клик всё выфармливает?

там поочереденость:
нормальный фарм
всё за 1 клик
нормальный фарм
всё за 1 клик

**Comment by yacody** [comment]
вот сейчас у меня закончился цикл нормального фарма и через 2015 секунд он выфармит всё сразу
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/567caa10-2458-40a3-8270-9113f160fddf)

**Comment by shamhi** [comment]
за такой слип к тебе же накапливается еще и пассивный заработок, вот бот считает его за +клик

**Comment by yacody** [comment]
> за такой слип к тебе же накапливается еще и пассивный заработок, вот бот считает его за +клик

да, но после него энергия 0. Выходит, что там пассивный доход + 6000 энергии за 1 клик. 

и вот кстати всё выфармил
![image](https://github.com/shamhi/HamsterKombatBot/assets/146646846/4a951890-28d0-4716-ac04-7cedea69d4cd)

**Comment by yacody** [comment]
хотя че то я пересчитал и не сходится...
у меня фарм в час 343819, энергии 6000.
получается через 2015 секунд он даёт только пассивный фарм, ниче не кликал и снова уходит в слип восстановливать фулл энергию? Попробую время сна в два раза уменьшить, мб так сработает

**Comment by Kanorto** [comment]
оставь лучше на 3 часа задержку нежели на такое большое количество времени. у тебя будет автомайнер лучше добывать чем бот.

**Comment by yacody** [comment]
> оставь лучше на 3 часа задержку нежели на такое большое количество времени. у тебя будет автомайнер лучше добывать чем бот.

во первых 2015 секунд это меньше 30 минут всего, с чего вдруг они стали больше 3 часов? во вторых, автомайнер работает вместе с кликером. Друг другу они не мешают.

**Comment by Kanorto** [comment]
тогда лучше увеличить время сна. Про секунды затупил, думал там больше.
