### ISSUE TITLE
[Предложение] Добавить настройку реферальной ссылки | Add referral link (refferal referal реферал)

### ISSUE THREAD

**Issue by AlexKrutoy** [shamhi/HamsterKombatBot#93]
Добавить настройку реф ссылки и автополучение коинов за подписку на тг/Х
В тг канал входить, а Х просто кликать, тк там не проверяет подписку

**Comment by yacody** [comment]
там вручную это занимает меньше минуты, на кой черт это в бота добавлять?

**Comment by Kanorto** [comment]
@AlexKrutoy вы сами можете встроить реферальную ссылку в код, если у вас тг ферма.

**Comment by AlexKrutoy** [comment]
> @AlexKrutoy вы сами можете встроить реферальную ссылку в код, если у вас тг ферма.

как?

**Comment by Kanorto** [comment]
https://github.com/shamhi/HamsterKombatBot/blob/main/bot/core/tapper.py

**Comment by AlexKrutoy** [comment]
> https://github.com/shamhi/HamsterKombatBot/blob/main/bot/core/tapper.py

предлагаешь самому код дописать или как? Нету там даже переменной под рефку

**Comment by Kanorto** [comment]
ну так да -_-
в чем минусы

**Comment by AlexKrutoy** [comment]
@shamhi ку, пока листал код таппера увидел строчки с юрлом, диалогом и т.п вещами, webview крч и решил почитать документацию, там есть параметр start_param, может быть его добавить как реф ссылку или это не то?

**Comment by DENIS76T5** [comment]
> > @shamhi ку, пока листал код таппера увидел строчки с юрлом, диалогом и т.п вещами, webview крч и решил почитать документацию, там есть параметр start_param, может быть его добавить как реф ссылку или это не то?
> 
> нет, он нужен если заходишь с браузера для активации рефки отправляется определенный запрос

как?

**Comment by ButCheR-PRO** [comment]
Продолжение:
1. https://github.com/shamhi/HamsterKombatBot/issues/273
