### ISSUE TITLE
Посыпались ерорки после ласт апдейта

### ISSUE THREAD

**Issue by AlexKrutoy** [shamhi/HamsterKombatBot#94]
![изображение](https://github.com/shamhi/HamsterKombatBot/assets/65369825/027d199b-e5e0-4657-b112-928377c7ad29)

**Comment by AlexKrutoy** [comment]
Не покупает улучшения, хотя включено

**Comment by AlexKrutoy** [comment]
kommit otkatil

**Comment by shamhi** [comment]
обнови сейчас
