### ISSUE TITLE
Покупка улучшений / получение бустов

### ISSUE THREAD

**Issue by itskekoff** [shamhi/HamsterKombatBot#95]
Дает иногда Bad Gateway на get_boosts или на покупке апгрейда.
 Unknown error while buying Upgrade: 502, message='Bad Gateway', url=URL('https://api.hamsterkombat.io/clicker/buy-upgrade')
 
 Это причина высокой активности у бота или какая-та ошибка? Я пытался найти и исправить, вероятно это просто результат ддоса или чего-либо ещё.

**Comment by Kanorto** [comment]
Скорее всего слишком много людей сейчас играет. Да и вылезает редко. Я забил
