### ISSUE TITLE
Ошибка 500

### ISSUE THREAD

**Issue by XxHLeB** [shamhi/HamsterKombatBot#96]
![image](https://github.com/shamhi/HamsterKombatBot/assets/54667358/8b971366-c0ea-4324-965c-532b9e9bfee3) вот , там пару данных на всякий замазал, было окей, чисто остановил бота сделать комбо подождал пол часа, запустил и тут на тебе, запускаю через ssh на сервере и использую прокси 3 аккаунта на 1 прокси

**Comment by XxHLeB** [comment]
Дополню, качал два дня назад после фиксов багов версия не 1.8 а 1.7 только заметил что ты обновил его

**Comment by meistermode** [comment]
сэйм

**Comment by meistermode** [comment]
> сэйм

подождал минут 10 и пошло поехало

**Comment by XxHLeB** [comment]
> > сэйм
> 
> 
> 
> подождал минут 10 и пошло поехало

Возможно у них траблы были щас запущу, я пока перенес сесси на новую версию бота
