### ISSUE TITLE
ИДИОТ ПОЧИНИ ХУЙНЮ

### ISSUE THREAD

**Issue by IgorbLoh123** [shamhi/HamsterKombatBot#97]
я ослик

**Comment by Kanorto** [comment]
@IgorbLoh123 Дурак?
Написано python 10 or 11. у тебя 3.8. Иди гайды поищи нормальные на установку python? и закрой варежку. Человек бесплатно кодом поделился а ты недоволен.

**Comment by AlexKrutoy** [comment]
боже какой конч

**Comment by xKumorio** [comment]
lmao лови репорт

**Comment by Kanorto** [comment]
@IgorbLoh123 удалите или закройте этот issue пожалуйста.
пускай нормальные вопросы в топе будут.
